SELECT
	OWNSTORE.FD_FACILITY_ID "store_num",
	WLBSTORE.FD_FACILITY_ID "store_num_wlb",
	REGEXP_REPLACE(FWF.FWFS_RX_NUMBER, '[^0-9]+', '') "rx_num",
	FWF.FWFS_RX_NUMBER "rx_num_txt",
	FWF.FWFS_REFILL_NUM "refill_num",
	TO_NUMBER(NVL(FWF.PARTIAL_FILL_SEQ,'0')) "part_seq_num",
	PATIENT.PD_PATIENT_NUM "patient_num",
	FWF.FACILITY_ORDER_NUMBER "order_num",
	wfs.WFSD_STEP_DESCRIPTION "wfs_desc",
	TRUNC(FWF.FWFS_ORDER_DATE) "order_date",	
	
	NVL((SELECT Max(bpv.SKIP_PRE_VER_CODE)
	  FROM TREXONE_AUD_DATA.RX_FILL bpv
	 WHERE bpv.RX_RECORD_NUM = fwf.FWFS_RX_RECORD_NUM
	   AND bpv.RX_FILL_SEQ = fwf.FWFS_RX_FILL_SEQ
	   AND bpv.H_LEVEL IN (
		   SELECT MAX(H_LEVEL)
			 FROM TREXONE_AUD_DATA.RX_FILL
			WHERE RX_RECORD_NUM = fwf.FWFS_RX_RECORD_NUM
			  AND RX_FILL_SEQ = fwf.FWFS_RX_FILL_SEQ
			  AND CAST(FROM_TZ(CAST(DATESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/Eastern' AS DATE) <=  fwf.FWFS_DT_OUT
	       )
	),0) "bypasspv",

	TRUNC(FWF.FWFS_DT_IN) "date_entered_wfs",
	FWF.FWFS_DT_IN "datetime_entered_wfs",
	TRUNC(FWF.FWFS_DT_OUT) "date_exited_wfs",
	FWF.FWFS_DT_OUT "datetime_exited_wfs",

	ROUND(((FWF.FWFS_DT_OUT - FWF.FWFS_DT_IN) * 86400),0) "step_dur_seconds",  
	TRIM(SYSUSER.SYS_USER_LOGIN_NAME) "emp_login_name",
	userrole.DISPLAY_NAME "emp_displayname",
    	CASE
        	WHEN userrole.ROLE_SET LIKE '%super%' THEN 'Super User'
        	WHEN userrole.ROLE_SET LIKE '%rph%' THEN 'RPh'
        	WHEN userrole.ROLE_SET LIKE '%intern%' THEN 'Intern'
        	WHEN userrole.ROLE_SET LIKE '%tech%' THEN 'Tech'
        	WHEN userrole.ROLE_SET LIKE '%extern%' THEN 'Extern'
        	WHEN userrole.ROLE_SET LIKE '%stl%' THEN 'STL'      
        	ELSE 'Other'
    	END "emp_erx_role",
	REPLACE(userrole.ROLE_SET,',','/') "rightsroles",

	NEXTWFS.WFSD_STEP_DESCRIPTION "next_wfs_desc",
	FWF.FWFS_IS_DECLINED "is_declined",
	DR.DR_DECLINE_REASON "decline_reason",
  
	DRUG.DRUG_NDC "ndc_wo",
	REPLACE(DRUG.DRUG_LABEL_NAME,',','') "drug_name",
	fwf.WRITTEN_QTY "qty_written",
	FWF.FWFS_QTY_DISPENSED "qty_dispensed",    
	
	NVL((SELECT Max(bpv.DAYS_SUPPLY)
	  FROM TREXONE_AUD_DATA.RX_FILL bpv
	 WHERE bpv.RX_RECORD_NUM = fwf.FWFS_RX_RECORD_NUM
	   AND bpv.RX_FILL_SEQ = fwf.FWFS_RX_FILL_SEQ
	   AND bpv.H_LEVEL IN (
		   SELECT MAX(H_LEVEL)
			 FROM TREXONE_AUD_DATA.RX_FILL
			WHERE RX_RECORD_NUM = fwf.FWFS_RX_RECORD_NUM
			  AND RX_FILL_SEQ = fwf.FWFS_RX_FILL_SEQ
			  AND CAST(FROM_TZ(CAST(DATESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/Eastern' AS DATE) <=  fwf.FWFS_DT_OUT
	   )
	),0) "days_supply",

	ORDERSOURCE.OS_ORDER_SOURCE_DESC "order_source",
	DELMETHOD.DM_DELIVERY_METHOD_DESC "del_method",
    fillstat.FS_FILL_STATUS_DESC "status_desc",
	NVL(FWF.IS_OUT_OF_STOCK,'N') "is_outofstock",
	fwf.FWFS_ORDER_PRIORITY "order_priority",
	CFIND.IS_CENTRAL_FILL "cf_ind",
	CFIND.IS_PULLED_BACK "pulled_back",
	CFIND.IS_PACKED "is_cf_packed",
	CFIND.IS_CENTRAL_FILL_DECLINED "cf_instock_declined",
	FWF.RX_TRANSACTION_CODE "tx_number",
	NVL(FWF.FWFS_IS_BAR,'N') "is_bar",

	TRUNC(FWF.FWFS_PICKUP_TIME) "pickup_date",
	FWF.FWFS_PICKUP_TIME "pickup_datetime",
	TRUNC(FWF.READY_DATE) "ready_date",
	FWF.READY_DATE "ready_datetime",
	TRUNC(FWF.FWFS_DT_QUEUE) "initial_wfs_date",
	FWF.FWFS_DT_QUEUE "initial_wfs_datetime",
  
	FWF.FWFS_RX_RECORD_NUM "rx_record_num",
	FWF.FWFS_RX_FILL_SEQ "rx_fill_seq",
	FWF.DRUG_KEY "drug_key",
	FWF.PRD_PRODUCT_KEY "product_key",
	FWF.PRS_PRESCRIBER_KEY "prescriber_key",
	FWF.PADR_KEY "padr_key",
	SYSUSER.SYS_USER_KEY "sys_user_key",
	fwf.FWFS_KEY "fwfs_key"

FROM TREXONE_DW_DATA.FILL_WORKFLOW_FACT FWF

LEFT OUTER JOIN TREXONE_DW_DATA.PATIENT patient
    ON fwf.PD_PATIENT_KEY = patient.PD_PATIENT_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.FACILITY OWNSTORE
    ON FWF.OWNING_FACILITY_KEY = OWNSTORE.FD_FACILITY_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.FACILITY WLBSTORE
    ON WLBSTORE.FD_FACILITY_KEY = FWF.FD_FACILITY_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.FACILITY COMPLETESTORE
    ON FWF.fwfs_complete_FACILITY_KEY = completeSTORE.FD_FACILITY_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.WF_STEP WFS
    ON WFS.WFSD_KEY = FWF.WFSD_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.ORDER_SOURCE_TYPE ordersource
    ON fwf.OS_ORDER_SOURCE_KEY = ordersource.OS_ORDER_SOURCE_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.DRUG DRUG
    ON FWF.DRUG_KEY = DRUG.DRUG_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.WF_STEP NextWfS
  ON NEXTWFS.WFSD_KEY = FWF.NEXT_WFSD_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.DELIVERY_METHOD_TYPE DELMETHOD
  ON FWF.DM_DELIVERY_METHOD_KEY = DELMETHOD.DM_DELIVERY_METHOD_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.FILL_STATUS_TYPE FILLSTAT
  ON fwf.FS_FILL_STATUS_KEY = fillstat.FS_FILL_STATUS_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.CENTRAL_FILL_INDICATOR CFIND
  ON CFIND.CENTRAL_FILL_INDICATOR_KEY = FWF.CENTRAL_FILL_INDICATOR_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.DECLINE_REASON_TYPE DR
  ON DR.DR_DECLINE_REASON_KEY = FWF.DR_DECLINE_REASON_KEY
LEFT OUTER JOIN TREXONE_DW_DATA.SYS_USER SYSUSER
  ON SYSUSER.SYS_USER_KEY = FWF.SYS_USER_KEY
LEFT OUTER JOIN TREXONE_AUD_DATA.SYSTEM_USER userrole
    ON sysuser.SYS_USER_NUM = userrole.SYSTEM_USER_NUM
    AND SYSUSER.H_LEVEL = USERROLE.H_LEVEL

WHERE FWF.FWFS_DT_OUT BETWEEN (:RunDate - 1) 
                          AND (:RunDate - 1 + INTERVAL '23:59:59' HOUR TO SECOND)

ORDER BY fwf.FWFS_DT_OUT,fwf.FWFS_DT_IN,OWNSTORE.FD_FACILITY_ID,fwf.FWFS_RX_NUMBER