
  CREATE TABLE "WEGMANS"."SENT_TO_SURE_SCRIPTS" 
   (	"FILL_FACT_KEY" NUMBER(18,0), 
	"PD_PATIENT_KEY" NUMBER(18,0), 
	"FD_FACILITY_KEY" NUMBER(18,0), 
	"RX_NUMBER" VARCHAR2(20 CHAR), 
	"SOLD_DATE_KEY" NUMBER(18,0), 
	"RUN_DATE" DATE, 
	"DATE_SENT" DATE DEFAULT sysdate, 
	"RECORD_TYPE" VARCHAR2(3 CHAR), 
	"RESPONSE_FILE_NAME" VARCHAR2(100 CHAR), 
	"ERROR_CODE" VARCHAR2(4 CHAR), 
	"ERROR_DESCRIPTION" VARCHAR2(200 CHAR), 
	"REJECT_EXPLANATION" VARCHAR2(200 CHAR), 
	"REVIEWER" VARCHAR2(50 CHAR), 
	"IGNORE_ERROR_DATE" DATE, 
	"RESUBMIT_REQUESTED_DATE" DATE, 
	"RESUBMITTED_DATE" DATE, 
	"REFILL_NUM" NUMBER(18,0), 
	"STATE_FILE" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW_LARGE_DATA01" ;

   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."FILL_FACT_KEY" IS 'The PK for the DW Fill_Fact table is being used to send Sure Scripts unique values for their RecordSequenceNumber while allowing us to also identify unique records in ERx.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."RECORD_TYPE" IS 'Value is IMM for PNL file, and PEF for Medical History file.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."ERROR_CODE" IS 'The error code in the response file from Sure scripts.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."ERROR_DESCRIPTION" IS 'The error description in the response file from Sure scripts.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."REVIEWER" IS 'The logon id of the business user reviewing the errors in the response files from Sure Scripts.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."IGNORE_ERROR_DATE" IS 'The date the business user determined this record never needs to be resubmitted - can be ignored.';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."RESUBMIT_REQUESTED_DATE" IS 'The date the business user determined this record has been corrected in ERx and can be resubmitted in the next job run (after the next ETL).';
   COMMENT ON COLUMN "WEGMANS"."SENT_TO_SURE_SCRIPTS"."RESUBMITTED_DATE" IS 'The date the record was resubmitted to Sure Scripts.';
   COMMENT ON TABLE "WEGMANS"."SENT_TO_SURE_SCRIPTS"  IS 'Once Sure Scripts is sent a specific prescription for a given patient, then do not send another one even if the DW Fill_Fact table has additional sold date records for the same prescription.';

  CREATE INDEX "WEGMANS"."SENT_TO_SURE_SCRIPTS_X1" ON "WEGMANS"."SENT_TO_SURE_SCRIPTS" ("PD_PATIENT_KEY", "FD_FACILITY_KEY", "RX_NUMBER", "RUN_DATE", "RECORD_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW_LARGE_DATA01" ;

  CREATE INDEX "WEGMANS"."SENT_TO_SURE_SCRIPTS_X2" ON "WEGMANS"."SENT_TO_SURE_SCRIPTS" ("FD_FACILITY_KEY", "RX_NUMBER", "REFILL_NUM", "RECORD_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW_LARGE_DATA01" ;