
  CREATE TABLE "WEGMANS"."TEMP_WORKFLOW_GROUP" 
   (	"FACILITY_ID" VARCHAR2(10 BYTE), 
	"START_TIME" VARCHAR2(8 BYTE), 
	"END_TIME" VARCHAR2(8 BYTE), 
	"WORKFLOW_STEP_COUNT" NUMBER(15,5), 
	"WORKFLOW_STEP" VARCHAR2(100 BYTE), 
	"NDC_COUNT" NUMBER, 
	"NDC_SUM_QTY_DISPENSED" NUMBER, 
	"NDC" VARCHAR2(20 BYTE), 
	"DRUG_NAME" VARCHAR2(35 BYTE), 
	"WORKFLOW_STEP_SUM" NUMBER, 
	"SKIP_PRE_VER_CODE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW_LARGE_DATA01" ;