
  CREATE TABLE "WEGMANS"."TEMP_WORKFLOW_STEP" 
   (	"FACILITY_ID" VARCHAR2(10 BYTE), 
	"RX_NUMBER" VARCHAR2(20 BYTE), 
	"NDC" VARCHAR2(20 BYTE), 
	"DRUG_NAME" VARCHAR2(35 BYTE), 
	"DATE_IN" DATE, 
	"DATE_OUT" DATE, 
	"WORKFLOW_STEP" VARCHAR2(100 BYTE), 
	"DELIVERY_METHOD" VARCHAR2(45 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"QTY_DISPENSED" NUMBER(13,3), 
	"OWNING_FACILITY" VARCHAR2(10 BYTE), 
	"WLB" VARCHAR2(3 BYTE), 
	"SKIP_PRE_VER_CODE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW_LARGE_DATA01" ;