SELECT *
  FROM ( SELECT DISTINCT FF.RX_NUMBER AS RxNumber
              , DD.CAL_DATE AS SoldDate
              , FAC.FD_FACILITY_ID AS FacilityId
              , PAT.PD_LAST_NAME AS PatientLastName
              , PAT.PD_FIRST_NAME AS PatientFirstName
              , FF.REFILL_NUM AS RefillNumber
              , PRD.PRD_NAME AS ProductName
              , FF.QTY_DISPENSED AS Quantity
              , FF.DAYS_SUPPLY AS DaysSupply
              , FF.TOTAL_REFILLS_REMAINING AS TotalRefillsRemaining
              , D.DRUG_NDC AS DrugNDC
              , TPP2.TPD_CARDHOLDER_ID AS CardholderOrPatientId
              , TP.TPLD_PLAN_CODE AS PlanCode
              , SF.SHIPMENT_ADDRESS1 AS ShipAddress1
              , SF.SHIPMENT_ADDRESS2 AS ShipAddress2
              , SF.SHIPMENT_CITY AS ShipCity
              , SF.SHIPMENT_STATE AS ShipState
              , SF.SHIPMENT_ZIPCODE AS ShipZipCode
              , PAT.PD_BIRTH_DATE AS PatientDateOfBirth
              , TDS.HOUR_MIN_SEC_TXT AS SoldTime
	          , DA.CAL_DATE AS DateOfService
	          , TPP2.TPD_PERSON_CODE AS PersonCode
	          , FF.RX_FILL_SEQ AS RxFillSequence
	          , DW.CAL_DATE AS WrittenDate
              , NVL(PRE.PRS_FIRST_NAME, PRE.PRS_ESV_FIRST_NAME) AS PrescriberFirstName
              , NVL(PRE.PRS_LAST_NAME, PRE.PRS_ESV_LAST_NAME) AS PrescriberLastName
              , PI1.PID_PRESCIBER_ID AS PrescriberNpi
              , PI2.PID_PRESCIBER_ID AS PrescriberDea
              , PRA.PADR_ADDRESS1 AS PrescriberAddress1
              , PRA.PADR_ADDRESS2 AS PrescriberAddress2
              , PRA.PADR_CITY AS PrescriberCity
              , PRA.PADR_STATE_CODE AS PrescriberState
              , PRA.PADR_ZIPCODE AS PrescriberZip
              , NVL(PRP.PRSP_AREA_CODE || PRP.PRSP_PHONE_NUMBER, '5555555555') AS PrescriberPhone
              , PAT.PD_PATIENT_NUM AS PatientNum
	          , FF.PATIENT_PRICE_PAID AS PatientPricePaid
              , CST.COURIER_NAME AS CourierName
              , SF.TRACKING_NUMBER AS TrackingNumber
              , FF.TOTAL_REFILLS_ALLOWED AS TotalRefillsAllowed
              , FF.FACILITY_ORDER_NUMBER AS OrderNumber
              , PATG.GROUP_NAME AS PatientGroupName
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PRP.PADR_KEY ORDER BY PRP.PRSP_STATUS, PRP.PRSP_SOURCE_CODE, PRP.H_LEVEL DESC, PRP.ROWID) AS PrescriberPhoneRank
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PI1.PRS_PRESCRIBER_KEY ORDER BY PI1.H_LEVEL DESC, PI1.ROWID) AS PrescriberNpiRank
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PI2.PRS_PRESCRIBER_KEY ORDER BY PI2.H_LEVEL DESC, PI2.ROWID) AS PrescriberDeaRank
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, TPP2.TPD_TP_PLAN_NUM ORDER BY TPP2.H_LEVEL DESC, TPP2.ROWID) AS TpPatientRank
           FROM TREXONE_DW_DATA.DRUG D
          INNER JOIN TREXONE_DW_DATA.PRODUCT PRD ON (D.DRUG_NUM = PRD.PRD_DRUG_NUM AND PRD.PRD_DEACTIVATE_DATE IS NULL)
          INNER JOIN TREXONE_DW_DATA.PRODUCT_GROUP PG ON (PRD.PRD_PRODUCT_NUM = PG.PRODUCT_NUM AND PG.MEMBER_STATUS = 'Active' AND PG.GROUP_NAME = 'ASTUTE')
          INNER JOIN TREXONE_DW_DATA.FILL_FACT FF ON (PRD.PRD_PRODUCT_KEY = FF.DISPENSED_PRD_PRODUCT_KEY)
          INNER JOIN TREXONE_DW_DATA.DATE_DIM DD ON (FF.SOLD_DATE_KEY = DD.DATE_KEY)
          INNER JOIN TREXONE_DW_DATA.TIME_DIM TDS ON (FF.SOLD_TIME_KEY = TDS.TIME_KEY)
          INNER JOIN TREXONE_DW_DATA.PATIENT PAT ON (FF.PD_PATIENT_KEY = PAT.PD_PATIENT_KEY)
          INNER JOIN TREXONE_DW_DATA.FACILITY FAC ON (FF.FD_FACILITY_KEY = FAC.FD_FACILITY_KEY)
          INNER JOIN TREXONE_DW_DATA.DATE_DIM DA ON (FF.ADJ_DATE_OF_SERVICE_KEY = DA.DATE_KEY)
          INNER JOIN TREXONE_DW_DATA.DATE_DIM DW ON (FF.WRITTEN_DATE_KEY = DW.DATE_KEY)
           LEFT JOIN TREXONE_DW_DATA.TP_PATIENT TPP ON (TPP.TPD_KEY = FF.TPD_KEY)
           LEFT JOIN TREXONE_DW_DATA.TP_PATIENT TPP2 ON (FF.PD_PATIENT_KEY = TPP2.PD_PATIENT_KEY AND TPP.TPD_TP_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM 
                AND TPP2.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY') AND TPP2.TPD_IS_ACTIVE = 'Y')
           LEFT JOIN TREXONE_DW_DATA.TP_PLAN TP ON (TP.TPLD_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM)
           LEFT JOIN TREXONE_AUD_DATA.ITEM I ON (I.RX_RECORD_NUM = FF.RX_RECORD_NUM AND I.RX_FILL_SEQ = FF.RX_FILL_SEQ AND I.ORDER_NUM = FF.ORDER_NUM 
                AND I.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY'))
           LEFT JOIN TREXONE_DW_DATA.SHIPMENT_FACT SF ON (SF.ORDER_NUM = I.ORDER_NUM)
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER PRE ON (FF.PRS_PRESCRIBER_KEY = PRE.PRS_PRESCRIBER_KEY)
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_ADDRESS PRA ON (PRA.PADR_KEY = FF.PADR_KEY)
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_PHONE PRP ON (PRP.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PRP.PADR_KEY = FF.PADR_KEY AND PRP.PRSP_PHONE_ADDRESS_TYPE = 'PRIM' 
                AND PRP.PRSP_STATUS = 'A')
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_ID_TYPE PT1 ON (PT1.PIT_CODE = '01' AND PT1.PIT_ID_DESCRIPTION = 'National Provider Identifier (NPI)')
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_IDS PI1 ON (PI1.PIT_KEY = PT1.PIT_KEY AND PI1.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PI1.PID_STATUS = 'A')
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_ID_TYPE PT2 ON PT2.PIT_CODE = '12' AND PT2.PIT_ID_DESCRIPTION = 'Drug Enforcement Administration (DEA) Number' 
           LEFT JOIN TREXONE_DW_DATA.PRESCRIBER_IDS PI2 ON (PI2.PIT_KEY = PT2.PIT_KEY AND PI2.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PI2.PID_STATUS = 'A')
           LEFT JOIN TREXONE_DW_DATA.COURIER_SHIPMENT_TYPE CST ON (SF.COURIER_SHIPMENT_KEY = CST.COURIER_SHIPMENT_KEY)
           LEFT JOIN TREXONE_DW_DATA.PATIENT_GROUP PATG on (PAT.PD_PATIENT_NUM = PATG.PATIENT_NUM AND PATG.MEMBER_STATUS = 'Active' and PATG.GROUP_NAME = 'JPAP')
          WHERE NVL(FF.IS_BAR, 'N') = 'N'
            AND FF.CANCEL_DATE_KEY = 0
            AND DD.CAL_DATE BETWEEN :StartDate AND :EndDate
)
 WHERE PrescriberPhoneRank = 1
   AND PrescriberNpiRank = 1
   AND PrescriberDeaRank = 1
   AND TpPatientRank = 1
 ORDER BY SoldDate, SoldTime
