namespace Library.McKessonDWInterface.DataModel
{

    public class TpcDataRow
    {
        public string? BenefitGroupId { get; set; }
        public DateTime? DateOfService { get; set; }
        public string? DawCode { get; set; }
        public decimal? DaysSupply { get; set; }
        public decimal? DispensedDrugNumber { get; set; }
        public decimal? DispensedQtyAwp { get; set; }
        public decimal? FacilityNum { get; set; }
        public DateTime? FillStateChgTs { get; set; }
        public string? FillStateCode { get; set; }
        public decimal? FillStateKey { get; set; }
        public decimal? FillStatePriceNum { get; set; }
        public decimal? FinalPrice { get; set; }
        public decimal? IncentiveFeeAmount { get; set; }
        public decimal? InternalFillId { get; set; }
        public string? IsSameDayReversal { get; set; }
        public decimal? MedicalConditionNum { get; set; }
        public decimal? OriginalProductQty { get; set; }
        public decimal? PartialFillSeq { get; set; }
        public decimal? PatientNum { get; set; }
        public decimal? PatientPayAmount { get; set; }
        public DateTime? PrescribedDate { get; set; }
        public decimal? PrescriberAddressNum { get; set; }
        public string? PrescriberIdDea { get; set; }
        public string? PrescriberIdNpi { get; set; }
        public decimal? PrescriberNum { get; set; }
        public string? PrescriberState { get; set; }
        public string? PrescriberZip { get; set; }
        public decimal? QtyDispensed { get; set; }
        public decimal? RefillNum { get; set; }
        public decimal? RefillAuthorized { get; set; }
        public decimal? RefillsRemaining { get; set; }
        public decimal? RxFillSeq { get; set; }
        public string? RxNumber { get; set; }
        public string? RxOriginCode { get; set; }
        public decimal? RxRecordNum { get; set; }
        public string? ShortFillStatus { get; set; }
        public string? SplitBillingCode { get; set; }
        public decimal? TlogSequenceNum { get; set; }
        public decimal? TotalCost { get; set; }
        public decimal? TotalFee { get; set; }
        public decimal? TotalUandc { get; set; }
        public decimal? TotalUserDefined { get; set; }
        public decimal? TpCurrPatientPayAmount { get; set; }
        public decimal? TpCurrTotalCost { get; set; }
        public decimal? TpCurrTotalFee { get; set; }
        public decimal? TpItemClaimKey { get; set; }
        public decimal? TpItemClaimNum { get; set; }
        public decimal? TpMessageKey { get; set; }
        public decimal? TpPatientNum { get; set; }
        public decimal? TpPlanAmountPaid { get; set; }
        public decimal? TpPlanNumber { get; set; }
        public decimal? TpPriorAuthNum { get; set; }
        public decimal? TpProcessorDestNum { get; set; }
        public string? TransactionCode { get; set; }
        public DateTime? FsFillStateChgTs { get; set; }
        public decimal? FsFillStateCode { get; set; }
        public decimal? FsRxFillSeq { get; set; }
        public decimal? FsRxRecordNum { get; set; }
        public string? IngredientNdc1 { get; set; }
        public string? IngredientNdc2 { get; set; }
        public string? IngredientNdc3 { get; set; }
        public string? IngredientNdc4 { get; set; }
        public string? IngredientNdc5 { get; set; }
        public string? IngredientNdc6 { get; set; }
        public decimal? IngredientPrice1 { get; set; }
        public decimal? IngredientPrice2 { get; set; }
        public decimal? IngredientPrice3 { get; set; }
        public decimal? IngredientPrice4 { get; set; }
        public decimal? IngredientPrice5 { get; set; }
        public decimal? IngredientPrice6 { get; set; }
        public decimal? IngredientQty1 { get; set; }
        public decimal? IngredientQty2 { get; set; }
        public decimal? IngredientQty3 { get; set; }
        public decimal? IngredientQty4 { get; set; }
        public decimal? IngredientQty5 { get; set; }
        public decimal? IngredientQty6 { get; set; }
        public DateTime? BirthDate { get; set; }
        public string? PFirstName { get; set; }
        public string? PGender { get; set; }
        public string? PLastName { get; set; }
        public string? PMiddleName { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? City { get; set; }
        public string? PaFirstName { get; set; }
        public string? PaGender { get; set; }
        public string? PaLastName { get; set; }
        public string? PaMiddleName { get; set; }
        public string? PhoneNum { get; set; }
        public string? State { get; set; }
        public string? Zip { get; set; }
        public string? AuthNumber { get; set; }
        public string? EmergencyConditionCode { get; set; }
        public string? ExternalBillingIndicator { get; set; }
        public decimal? HLevel { get; set; }
        public decimal? TpMessageNum { get; set; }
        public string? BinNum { get; set; }
        public string? ProcessorControlNum { get; set; }
        public decimal? RsBasisOfReimbursmentDet { get; set; }
        public string? RsNetworkReimbursmentId { get; set; }
        public string? DrugGcnSeq { get; set; }
        public string? DrugIsMaintDrug { get; set; }
        public string? DrugNdc { get; set; }
        public decimal? DrugPackageSize { get; set; }
        public string? DrugStrength { get; set; }
        public string? DrugStrengthUnits { get; set; }
        public string? FdFacilityId { get; set; }
        public string? FdNcpdpProvider { get; set; }
        public string? McdFrmttdCondRefNum { get; set; }
        public string? PresFirstName { get; set; }
        public string? PresLastName { get; set; }
        public decimal? PrsPrescriberKey { get; set; }
        public decimal? PrsPrescirberNum { get; set; }
        public decimal? PadrKey { get; set; }
        public string? PadrAddress1 { get; set; }
        public string? PadrAddress2 { get; set; }
        public string? PadrCity { get; set; }
        public string? PrdIsCompound { get; set; }
        public string? PrdIsGeneric { get; set; }
        public string? PrdIsPriceMaintained { get; set; }
        public string? PrdName { get; set; }
        public decimal? PrdPackageSize { get; set; }
        public decimal? PdPatientKey { get; set; }
        public string? TpdCardholderId { get; set; }
        public decimal? TpdCardHolderPatientNum { get; set; }
        public decimal? TpdRelationshipNum { get; set; }
        public decimal? TpdTpPlanNum { get; set; }
        public string? TpldPlanCode { get; set; }
        public string? RequestMessage { get; set; }
        public DateTime? LookUpTransmissionDate { get; set; }
        public DateTime? LookUpFirstAdjudicatedDate { get; set; }
        public DateTime? LookUpFirstDispenseDate { get; set; }
        public decimal? LookUpQtyDispensed { get; set; }
        public decimal? LookUpDaysSupply { get; set; }
        public decimal? LookUpAcquisitionCost { get; set; }
        public string? LookUpCfStoreIndicator { get; set; }
        public string? IsSenior { get; set; } 
        public decimal? OrderNum { get; set; }
    }
}
