using Library.McKessonDWInterface.DataModel;
using Library.TenTenInterface.XmlTemplateHandlers.Implementations;
using System.Runtime.CompilerServices;
//using System.Windows.Forms;

namespace INN.JobRunner.Commands.CommandHelpers.TenTenImportRxErpFromMcKessonDWHelper
{
    public class MapperImp : IMapper
    {
        /// <inheritdoc />
        public IEnumerable<RxErp> MapToTenTenRxErp(IEnumerable<RxErpRow> rxErpRows)
        {
            return rxErpRows.Select(r => new RxErp 
            {
                RxErpChangeDate = r.RxErpChangeDate,
                PatientNbr = r.PatientNbr,
                StoreNbr = r.StoreNbr,
                RxNbr = r.RxNbr,
                RxNbrTxt = r.RxNbrTxt,
                NdcWithoutDashes = r.NdcWithoutDashes,
                DrugName = r.DrugName,
                DaysSupply = r.DaysSupply,
                RefillsAuthorized = r.RefillsAuthorized,
                LastFillDate = r.LastFillDate,
                ErpOrigTargetDate = r.ErpOrigTargetDate,
                ErpTargetDate = r.ErpTargetDate,
                ErpEnrollStatus = r.ErpEnrollStatus,
                ErpEnrollStatusDateTime = r.ErpEnrollStatusDateTime,
                ErpEnrollReason = r.ErpEnrollReason,
                ErpExcludeReason = r.ErpExcludeReason,
                ErpDeliveryMethod = r.ErpDeliveryMethod,
                ErpDeliveryMethodPersist = r.ErpDeliveryMethodPersist,
                IsConsentToFill = r.IsConsentToFill,
                UserConsentToFill = r.UserConsentToFill,
                DateConsentToFill = r.DateConsentToFill,
                RxRecordEffectiveStartDateTime = r.RxRecordEffectiveStartDateTime,
                RecordType = r.RecordType,
                ErpUsermodifiedTargetDate = r.ErpUsermodifiedTargetDate,
                ErpModifiedUserType = r.ErpModifiedUserType,
                ErpModifiedUser = r.ErpModifiedUser,
                ErpUserModifiedRecordType = r.ErpUserModifiedRecordType,
                ErpUserModifiedOnDate = r.ErpUserModifiedOnDate,
                RecordUpdates = r.RecordUpdates,
                PatientAutofillEnrollStatus = r.PatientAutofillEnrollStatus,
                PatientErpEnrollStatus = r.PatientErpEnrollStatus,
                PatientErpEnrollDate = r.PatientErpEnrollDate,
                PatientAutoEnrollFutureRxs = r.PatientAutoEnrollFutureRxs,
                PatientPreferredDeliveryMethod = r.PatientPreferredDeliveryMethod,
                PatientPrefersMailDelivery = r.PatientPrefersMailDelivery,
                PatientErpPaymentMethod = r.PatientErpPaymentMethod,
                PatientRequestConsentToFill = r.PatientRequestConsentToFill,
                PatientRequestConsentToErp = r.PatientRequestConsentToErp,
                PatientExternalId = r.PatientExternalId,
                ProhibitRenewalRequest = r.ProhibitRenewalRequest,
                CsrDiagnosisCode = r.CsrDiagnosisCode,
                DrugForm = r.DrugForm,
                QtyAuthorized = r.QtyAuthorized,
                RefillQty = r.RefillQty,
                ExpireDate = r.ExpireDate,
                ReassignedRxNum = r.ReassignedRxNum,
                RxCreatedDate = r.RxCreatedDate,
                RxCreatedUser = r.RxCreatedUser,
                RxOriginCode = r.RxOriginCode,
                RxStatus = r.RxStatus,
                RxRecordNum = r.RxRecordNum,
                FirstFillQty = r.FirstFillQty,
                DatePrescribed = r.DatePrescribed,
                OriginalNdcWithoutDashes = r.OriginalNdcWithoutDashes,
                OriginalDrugName = r.OriginalDrugName,
                OriginalQty = r.OriginalQty,
                Serial = r.Serial,
                DawCode = r.DawCode,
                SelectedUpc = r.SelectedUpc,
                AckCode = r.AckCode,
                LetterOnFile = r.LetterOnFile,
                EmployeeLoginName = r.EmployeeLoginName,
                LastAckChangeDate = r.LastAckChangeDate,
                LastAckChangeUser = r.LastAckChangeUser,
                LastAckChangeUserName = r.LastAckChangeUserName,
                OriginalFillDate = r.OriginalFillDate,
                TotalDailyDose = r.TotalDailyDose,
                TotalQtyDispensed = r.TotalQtyDispensed,
                TotalQtyTransferred = r.TotalQtyTransferred,
                LegalFills = r.LegalFills,
                LatestFill = r.LatestFill,
                LatestFillDuration = r.LatestFillDuration,
                LatestFillNonInprocess = r.LatestFillNonInprocess,
                LatestFillCanceled = r.LatestFillCanceled,
                LastDispFill = r.LastDispFill,
                LastFillRefill = r.LastFillRefill,
                LastFillReleased = r.LastFillReleased,
                LastSoldFill = r.LastSoldFill,
                ProfileIncludeDate = r.ProfileIncludeDate,
                FirstFill = r.FirstFill,
                FirstRefill = r.FirstRefill,
                EarliestFillDate = r.EarliestFillDate,
                PrevFillReleased = r.PrevFillReleased,
                SyncDate = r.SyncDate,
                IsLinked = r.IsLinked,
                CancelReason = r.CancelReason,
                PrescriberNum = r.PrescriberNum,
                PrescriberAddressNum = r.PrescriberAddressNum,
                PrescriberOrderNbr = r.PrescriberOrderNbr,
                IsEPCS = r.IsEPCS,
                RrrDenied = r.RrrDenied
            });
        }
    }
}
