SELECT
 ID_DISCLOSURE
,ID_STORENBR
,N_CATEGORY
,Round((DT_DISCLOSURE - To_Date('20350101','YYYYMMDD')),6) AS DT_DISCLOSURE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(C_PATIENTCODE,'"',''),chr(13),''),chr(10),'') AS C_PATIENTCODE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_ACCIDENTALNAME,'"',''),chr(13),''),chr(10),'') AS STR_ACCIDENTALNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_CATEGORYADDRESS,'"',''),chr(13),''),chr(10),'') AS STR_CATEGORYADDRESS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_PHIDESCRIPTION,'"',''),chr(13),''),chr(10),'') AS STR_PHIDESCRIPTION
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_PHIPURPOSE,'"',''),chr(13),''),chr(10),'') AS STR_PHIPURPOSE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_SUBMITTINGNAME,'"',''),chr(13),''),chr(10),'') AS STR_SUBMITTINGNAME
,ID_PATIENTSTORE
,ID_RXNUMBER
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_PHI_ACQUIRED,'"',''),chr(13),''),chr(10),'') AS STR_PHI_ACQUIRED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_ITEMS_DISCLOSED,'"',''),chr(13),''),chr(10),'') AS STR_ITEMS_DISCLOSED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_UNAUTH_RECIPIENT,'"',''),chr(13),''),chr(10),'') AS STR_UNAUTH_RECIPIENT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_RECIPIENT_NAME,'"',''),chr(13),''),chr(10),'') AS STR_RECIPIENT_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_RECIPIENT_CONTACT,'"',''),chr(13),''),chr(10),'') AS STR_RECIPIENT_CONTACT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_UNAUTH_VIEWED,'"',''),chr(13),''),chr(10),'') AS STR_UNAUTH_VIEWED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_UNAUTH_VIEWED_DETAIL,'"',''),chr(13),''),chr(10),'') AS STR_UNAUTH_VIEWED_DETAIL
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_UNAUTH_VIEWED_EXPLAIN,'"',''),chr(13),''),chr(10),'') AS STR_UNAUTH_VIEWED_EXPLAIN
,Round((DT_MIT_CONTACT - To_Date('20350101','YYYYMMDD')),6) AS DT_MIT_CONTACT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MIT_EMP_CONTACT,'"',''),chr(13),''),chr(10),'') AS STR_MIT_EMP_CONTACT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MIT_CONTACT_NAME,'"',''),chr(13),''),chr(10),'') AS STR_MIT_CONTACT_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MIT_CONTACT_MANNER,'"',''),chr(13),''),chr(10),'') AS STR_MIT_CONTACT_MANNER
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MIT_ASSURANCE,'"',''),chr(13),''),chr(10),'') AS STR_MIT_ASSURANCE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MIT_NOTES,'"',''),chr(13),''),chr(10),'') AS STR_MIT_NOTES
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_SIGNIFICANT_RISK,'"',''),chr(13),''),chr(10),'') AS STR_SIGNIFICANT_RISK
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_RISK_REASONING,'"',''),chr(13),''),chr(10),'') AS STR_RISK_REASONING
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_RISK_DESC,'"',''),chr(13),''),chr(10),'') AS STR_RISK_DESC
,ID_REFERENCE_NUMBER
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_DISCLOSURE_STATE,'"',''),chr(13),''),chr(10),'') AS STR_DISCLOSURE_STATE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MEDICATION,'"',''),chr(13),''),chr(10),'') AS STR_MEDICATION
FROM RX.HIPAADISCLOSURE
ORDER BY DT_DISCLOSURE, ID_DISCLOSURE