SELECT 
 ir.ID_INC_INCIDENT AS ID_INC_INCIDENT
,ir.ID_INC_STORENBR AS ID_INC_STORENBR
,ir.ID_INC_RXNBR AS ID_INC_RXNBR
,ir.N_INC_INCIDENTTYPE AS N_INC_INCIDENTTYPE
,ir.N_INC_INGESTEDDOSES AS N_INC_INGESTEDDOSES
,ir.ID_INCRPTSOURCETYPE AS ID_INCRPTSOURCETYPE
,Round((ir.DT_INC_INCREPORTED - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_INCREPORTED
,Round((ir.DT_FU_COACHING - To_Date('20350101','YYYYMMDD')),6) AS DT_FU_COACHING
,Round((ir.DT_INC_FILLED - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_FILLED
,Round((ir.DT_FU_FOLLOWUPREPORTED - To_Date('20350101','YYYYMMDD')),6) AS DT_FU_FOLLOWUPREPORTED
,Round((ir.DT_INC_STOREMANAGER - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_STOREMANAGER
,Round((ir.DT_INC_POM - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_POM
,Round((ir.DT_INC_INCIDENT - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_INCIDENT
,Round((ir.DT_INC_NOTIFICATION - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_NOTIFICATION
,Round((ir.DT_INC_MEDICATIONGIVEN - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_MEDICATIONGIVEN
,Round((ir.DT_INC_PRACTCONTACTEDPHARM - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_PRACTCONTACTEDPHARM
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_INCIDENTCLOSED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_INCIDENTCLOSED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_PRACTCONTACTEDPHARM,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_PRACTCONTACTEDPHARM
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_PRACTCONTACTEDPAT,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_PRACTCONTACTEDPAT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_PATHEALTHAFFECTED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_PATHEALTHAFFECTED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_PATIENTCODE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_PATIENTCODE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_NEW,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_NEW
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_CALLIN,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_CALLIN
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_ORIGIN,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_ORIGIN
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_MEDICATIONGIVEN,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_MEDICATIONGIVEN
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_REPMEDICATION,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_REPMEDICATION
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_INGESTED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_INGESTED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_MEDATTENTION,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_MEDATTENTION
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_INC_OUTSIDEAGENCY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_INC_OUTSIDEAGENCY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_OE_CONFCUSTID,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_OE_CONFCUSTID
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_OE_VERIFYPRACT,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_OE_VERIFYPRACT
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_PATIENTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_PATIENTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_MEDNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_MEDNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_STRENGTH,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_STRENGTH
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_QUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_QUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_DIRECTIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_DIRECTIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_DE_PRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_DE_PRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_A_CHECKNDC,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_A_CHECKNDC
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_A_QUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_A_QUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_A_ASSEMBLES,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_A_ASSEMBLES
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_PATIENTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_PATIENTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_MEDNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_MEDNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_STRENGTH,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_STRENGTH
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_QUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_QUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_DIRECTIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_DIRECTIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_PRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_PRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_CHECKMED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_CHECKMED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_QA_CONFIRMBAG,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_QA_CONFIRMBAG
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_WC_PATIENTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_WC_PATIENTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_WC_ADDRESS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_WC_ADDRESS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_WC_NUMRXS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_WC_NUMRXS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_TO_RECITEBACK,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_TO_RECITEBACK
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_TO_CONFIRMED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_TO_CONFIRMED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_TC_REVIEWMED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_TC_REVIEWMED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_TC_STATENAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_TC_STATENAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_C_COMPNOISSUE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_C_COMPNOISSUE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.C_FU_C_NOTWITHIN24,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS C_FU_C_NOTWITHIN24
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_QA_PHARM,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_QA_PHARM
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_ADDITIONFACTS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_ADDITIONFACTS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AUTHORNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AUTHORNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_NOTIFIERNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_NOTIFIERNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PARENTGUARDIAN,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PARENTGUARDIAN
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERMEDNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERMEDNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERMEDTYPE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERMEDTYPE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERSTRENGTH,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERSTRENGTH
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERDIRECTIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERDIRECTIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERQUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERQUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXORDERPRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXORDERPRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELMEDNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELMEDNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELMEDTYPE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELMEDTYPE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELSTRENGTH,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELSTRENGTH
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELDIRECTIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELDIRECTIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELQUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELQUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_RXLABELPRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_RXLABELPRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDMEDNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDMEDNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDMEDTYPE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDMEDTYPE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDSTRENGTH,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDSTRENGTH
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDDIRECTIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDDIRECTIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDQUANTITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDQUANTITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_DISPENSEDPRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_DISPENSEDPRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_MEDICATIONGIVENNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_MEDICATIONGIVENNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PATHEALTHDESC,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PATHEALTHDESC
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PATCONDITIONS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PATCONDITIONS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTADDRESS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTADDRESS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTCITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTCITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTSTATE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTSTATE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTZIP,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTZIP
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_PRACTPHONE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_PRACTPHONE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_MEDATTENTIONDESC,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_MEDATTENTIONDESC
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYREPNAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYREPNAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYADDRESS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYADDRESS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYCITY,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYCITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYSTATE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYSTATE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYZIP,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYZIP
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYPHONE,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYPHONE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_AGENCYCASENBR,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_AGENCYCASENBR
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_OE_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_OE_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_DE_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_DE_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_AN_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_AN_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_QA_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_QA_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_VER_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_VER_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_WC_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_WC_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_TO_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_TO_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_TC_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_TC_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_CP_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_CP_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_POM_MGR_NAME,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_POM_MGR_NAME
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_FACTORS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_FACTORS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_INC_COMMENTS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_INC_COMMENTS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_EMP_COMMENTS,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_EMP_COMMENTS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_FU_COACHING_SUM,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_FU_COACHING_SUM
,ir.ID_PATIENTSTORE AS ID_PATIENTSTORE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_WLBOCCURED,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_WLBOCCURED
,ir.ID_INC_WLBOCCUREDFACILITY AS ID_INC_WLBOCCUREDFACILITY
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_CLINICALREASON,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_CLINICALREASON
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(ir.STR_INC_CLINICALREASONDESC,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INC_CLINICALREASONDESC
,Round((ir.DT_INC_SMANDPOMNOTIFIED - To_Date('20350101','YYYYMMDD')),6) AS DT_INC_SMANDPOMNOTIFIED

,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(it.STR_INCIDENTTYPEDESC,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS STR_INCIDENTTYPEDESC
,it.ACTIVE AS ACTIVE

,u.ID_USER AS qa_id_user
,u.ID_STORENBR AS qa_id_storenbr
,Round((u.DT_EXPORTDAT - To_Date('20350101','YYYYMMDD')),6) AS qa_dt_exportdat
,u.STR_QALASTNAME AS qa_str_qalastname
,u.STR_QAFIRSTNAME AS qa_str_qafirstname

,w.ID_USER AS wlb_qa_id_user
,w.ID_STORENBR AS wlb_qa_id_storenbr
,Round((w.DT_EXPORTDAT - To_Date('20350101','YYYYMMDD')),6) AS wlb_qa_dt_exportdat
,w.STR_QALASTNAME AS wlb_qa_str_qalastname
,w.STR_QAFIRSTNAME AS wlb_qa_str_qafirstname

FROM    Rx.HIPAAIncidentReporting ir
        JOIN Rx.HIPAAIncidentType it ON (ir.n_inc_incidenttype = it.id_incidenttype)
        JOIN Rx.StoreExt se ON (ir.id_inc_storenbr = se.id_storenbr)
        LEFT JOIN (
            SELECT  id_user,
                    id_storenbr,
                    dt_exportdat,
                    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(str_userslastname,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS str_qalastname,
                    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(str_usersfirstname,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS str_qafirstname,
                    ROW_NUMBER() OVER(
                        PARTITION BY id_user, id_storenbr
                        ORDER BY dt_exportdat DESC NULLS LAST
                    ) AS rn
            FROM    Rx.RxUser
            WHERE   str_userslastname IS NOT NULL
        ) u ON (
                ir.id_inc_storenbr  = u.id_storenbr
            AND ir.str_inc_qa_pharm = u.id_user
            AND u.rn = 1
        )
         LEFT JOIN (
            SELECT  id_user,
                    id_storenbr,
                    dt_exportdat,
                    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(str_userslastname,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS str_qalastname,
                    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(str_usersfirstname,'\^',chr(39)),chr(34),chr(39)),chr(13),' '),chr(10),' ') AS str_qafirstname,
                    ROW_NUMBER() OVER(
                        PARTITION BY id_user, id_storenbr
                        ORDER BY dt_exportdat DESC NULLS LAST
                    ) AS rn
            FROM    Rx.RxUser
            WHERE   str_userslastname IS NOT NULL
        ) w ON (
                ir.ID_INC_WLBOCCUREDFACILITY  = w.id_storenbr
            AND ir.str_inc_qa_pharm = w.id_user
            AND w.rn = 1
        )
ORDER BY DT_INC_INCIDENT desc, ID_INC_STORENBR