SELECT
 ID_HIPAABREACHRISK
,ID_REFERENCE
,Round((DT_REVIEWED - To_Date('20350101','YYYYMMDD')),6) AS DT_REVIEWED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_EMPLOYEE,'"',''),chr(13),''),chr(10),'') AS STR_EMPLOYEE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_INDIVIDUALS_REVIEW,'"',''),chr(13),''),chr(10),'') AS STR_INDIVIDUALS_REVIEW
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_IDENTIFIER_TYPES,'"',''),chr(13),''),chr(10),'') AS STR_IDENTIFIER_TYPES
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_REIDENTIFICATION,'"',''),chr(13),''),chr(10),'') AS STR_REIDENTIFICATION
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_DISCLOSURE_TO,'"',''),chr(13),''),chr(10),'') AS STR_DISCLOSURE_TO
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_PHI_ACQUIRED,'"',''),chr(13),''),chr(10),'') AS STR_PHI_ACQUIRED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_STEPS_TAKEN,'"',''),chr(13),''),chr(10),'') AS STR_STEPS_TAKEN
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_LEVEL_COMPROMISED,'"',''),chr(13),''),chr(10),'') AS STR_LEVEL_COMPROMISED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_NOTIFICATION_REQUIRED,'"',''),chr(13),''),chr(10),'') AS STR_NOTIFICATION_REQUIRED
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MAIL_NOTICE,'"',''),chr(13),''),chr(10),'') AS STR_MAIL_NOTICE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_LESS_INDIVIDUALS,'"',''),chr(13),''),chr(10),'') AS STR_LESS_INDIVIDUALS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_ALTERNATIVE_NOTICE,'"',''),chr(13),''),chr(10),'') AS STR_ALTERNATIVE_NOTICE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_PHONE_NOTICE,'"',''),chr(13),''),chr(10),'') AS STR_PHONE_NOTICE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_OTHER,'"',''),chr(13),''),chr(10),'') AS STR_OTHER
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_MORE_INDIVIDUALS,'"',''),chr(13),''),chr(10),'') AS STR_MORE_INDIVIDUALS
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_CONSPICUOUS_POST,'"',''),chr(13),''),chr(10),'') AS STR_CONSPICUOUS_POST
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_CONSPICUOUS_NOTICE,'"',''),chr(13),''),chr(10),'') AS STR_CONSPICUOUS_NOTICE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_ADDITIONAL_NOTICE,'"',''),chr(13),''),chr(10),'') AS STR_ADDITIONAL_NOTICE
,REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(STR_ADDITIONAL_DESC,'"',''),chr(13),''),chr(10),'') AS STR_ADDITIONAL_DESC
FROM RX.HIPAABREACHRISK
ORDER BY DT_REVIEWED, ID_HIPAABREACHRISK