create or replace TYPE T_WLB_INTERVALS_OBJ AS OBJECT (
     INTV_STR_NUM_OUT            CHAR(3 CHAR)
    ,INTV_DEPT_NAME_OUT          CHAR(15 CHAR)
    ,INTV_DATE_OUT               CHAR(10 CHAR)
    ,INTV_DEP_OUT                CHAR(3 CHAR)
    ,INTV_DEP_DESC               CHAR(7 CHAR)
    ,INTV_CAT_OUT                CHAR(2 CHAR)
    ,INTV_CAT_DESC               CHAR(7 CHAR)
    ,INTV_CLS_OUT                CHAR(2 CHAR)
    ,INTV_CLS_DESC               CHAR(7 CHAR)
    ,FILLER1_OUT                 CHAR(2 CHAR)
    ,FILLER1_DESC_OUT            CHAR(7 CHAR)
    ,FILLER2_OUT                 CHAR(2 CHAR)
    ,FILLER2_DESC_OUT            CHAR(7 CHAR)
    ,FILLER3_OUT                 CHAR(2 CHAR)
    ,FILLER3_DESC_OUT            CHAR(7 CHAR)
    ,INTV_COM_CODE_OUT           CHAR(64 CHAR)
    ,INTV_DESCRP_OUT             CHAR(30 CHAR)
    ,INTV_DSD_ITEM_OUT           CHAR(1 CHAR)
    ,INTV_DATA_TYPE_OUT          CHAR(1 CHAR)
    ,INTV_ITEM_PER_CASE_OUT      CHAR(7 CHAR)
    ,INTV_UNITS_OUT              CHAR(10 CHAR)
    ,INTV_ITEM_SEL_UNIT_OUT      CHAR(10 CHAR)
    ,INTV_WEIGHT_OUT             CHAR(10 CHAR)
    ,INTV_ITEM_PERLB_OUT         CHAR(10 CHAR)
    ,INTV_ITEM_SHRINK_OUT        CHAR(10 CHAR)
    ,INTV_SALES_OUT              CHAR(10 CHAR)
    ,INTV_TIME_OUT               CHAR(5 CHAR)
    ,INTV_DRVR_NAME_OUT          CHAR(9 CHAR)
);

create or replace TYPE T_WLB_INTERVALS_TABLE IS TABLE OF T_WLB_INTERVALS_OBJ;
