create or replace TYPE T_WLB_TOTALS_OBJ AS OBJECT (
     DATA_STR_NUM_ITEM_OUT         CHAR(3 CHAR)
    ,DATA_DEPT_NAME_ITEM_OUT       CHAR(15 CHAR)
    ,DATA_COM_CODE_ITEM_OUT        CHAR(64 CHAR)
    ,DCC_ITEM_OUT                  CHAR(7 CHAR)
    ,DATA_DESCRP_ITEM_OUT          CHAR(35 CHAR)
    ,DATA_DATE_ITEM_OUT            CHAR(10 CHAR)
    ,DATA_DATA_TYPE_ITEM_OUT       CHAR(1 CHAR)
    ,DATA_UNITS_ITEM_OUT           CHAR(10 CHAR)
    ,DATA_WEIGHT_ITEM_OUT          CHAR(10 CHAR)
);

create or replace TYPE T_WLB_TOTALS_TABLE IS TABLE OF T_WLB_TOTALS_OBJ;
