SELECT 
     DISTINCT
     TO_NUMBER(DW__FACILITY.FD_FACILITY_ID) AS STORE_NUM
    ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.FILL_STATE_CHG_TS::DATE,'YYYYMMDD')) AS SOLD_DATE
    ,ROUND((AUD__FILL_FACT.FILL_STATE_CHG_TS - TO_DATE('20350101','YYYYMMDD')),6) AS SOLD_DATETIME
    ,AUD__ORDER_RECORD.FACILITY_ORDER_NUMBER AS ORDER_NUM        
    ,TO_NUMBER(AUD__FILL_FACT.RX_NUMBER) AS RX_NUM        
    ,AUD__FILL_FACT.REFILL_NUM
    ,AUD__FILL_FACT.PARTIAL_FILL_SEQ AS PART_SEQ_NUM    
    ,DW__PAYMENT_TYPE.PAYMENT_TYPE_NAME
    ,(AUD__FILL_FACT.FINAL_PRICE * (CASE WHEN AUD__FILL_FACT.FILL_STATE_CODE = 16 THEN -1 ELSE 1 END)) AS TOTAL_PRICE_PAID
    ,(AUD__FILL_FACT.PATIENT_PAY_AMOUNT * (CASE WHEN AUD__FILL_FACT.FILL_STATE_CODE = 16 THEN -1 ELSE 1 END)) AS PATIENT_PRICE_PAID
    ,(AUD__FILL_FACT.TOTAL_UANDC * (CASE WHEN AUD__FILL_FACT.FILL_STATE_CODE = 16 THEN -1 ELSE 1 END)) AS TOTAL_UNC        
    ,TO_NUMBER(TO_CHAR(AUD__PAYMENT.PAYMENT_DATE::DATE,'YYYYMMDD')) AS PAYMENT_DATE
    ,DW__SHIPMENT_FACT.TRACKING_NUMBER
    ,DW__SHIPMENT_FACT.PAD_KEY AS SHIP_PAD_KEY
    ,(DW__SHIPMENT_FACT.SHIP_HANDLE_FEE * (CASE WHEN AUD__FILL_FACT.FILL_STATE_CODE = 16 THEN -1 ELSE 1 END)) AS SHIP_HANDLE_FEE
    ,(DW__SHIPMENT_FACT.COURIER_SHIP_CHARGE * (CASE WHEN AUD__FILL_FACT.FILL_STATE_CODE = 16 THEN -1 ELSE 1 END)) AS COURIER_SHIP_CHARGE
    ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.DATE_OF_SERVICE::DATE,'YYYYMMDD')) AS DATE_OF_SERVICE
    ,DW__DRUG.DRUG_NDC
    ,DW__TP_PLAN.TPLD_PLAN_CODE
    ,AUD__FILL_FACT.DISPENSED_PROD_NUM AS PRODUCT_NUM
    ,DW__TP_PLAN.TPLD_PLAN_KEY AS PRIMARY_TPLD_PLAN_KEY
    ,AUD__FILL_FACT.PATIENT_NUM AS PD_PATIENT_NUM
    ,AUD__FILL_FACT.RX_FILL_SEQ
    ,AUD__FILL_FACT.RX_RECORD_NUM
    ,NVL(AUD__FILL_FACT.IS_BAR,'N') AS IS_BAR
FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT AUD__FILL_FACT
  INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__FACILITY
     ON DW__FACILITY.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
    AND DW__FACILITY.FD_IS_PPI_ENABLED = 'Y'
  INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DW__DRUG
     ON DW__DRUG.DRUG_NUM = AUD__FILL_FACT.DISPENSED_DRUG_NUM
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT DW__TP_PATIENT
     ON DW__TP_PATIENT.TPD_TP_PATIENT_NUM = AUD__FILL_FACT.TP_PATIENT_NUM
    AND DW__TP_PATIENT.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN DW__TP_PLAN
     ON DW__TP_PLAN.TPLD_PLAN_NUM = AUD__FILL_FACT.TP_PLAN_NUM
  LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM AUD__ITEM
     ON AUD__ITEM.RX_RECORD_NUM = AUD__FILL_FACT.RX_RECORD_NUM
    AND AUD__ITEM.RX_FILL_SEQ = AUD__FILL_FACT.RX_FILL_SEQ
    AND AUD__ITEM.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
    AND AUD__ITEM.H_TYPE != 'D'
  LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ORDER_RECORD AUD__ORDER_RECORD
     ON AUD__ORDER_RECORD.ORDER_NUM = AUD__ITEM.ORDER_NUM
    AND AUD__ORDER_RECORD.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT DW__SHIPMENT_FACT
     ON DW__SHIPMENT_FACT.ORDER_NUM = AUD__ITEM.ORDER_NUM
    AND DW__SHIPMENT_FACT.PD_PATIENT_KEY = DW__TP_PATIENT.PD_PATIENT_KEY
  INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT_GROUP_LIST AUD__PAYMENT_GROUP_LIST
     ON AUD__PAYMENT_GROUP_LIST.PAYMENT_GROUP_NUM = AUD__ITEM.PAYMENT_GROUP_NUM
    AND AUD__PAYMENT_GROUP_LIST.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')  
  INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT AUD__PAYMENT
     ON AUD__PAYMENT.PAYMENT_NUM = AUD__PAYMENT_GROUP_LIST.PAYMENT_NUM
    AND AUD__PAYMENT.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PAYMENT_TYPE DW__PAYMENT_TYPE
     ON DW__PAYMENT_TYPE.PAYMENT_TYPE_NUM = AUD__PAYMENT.PAYMENT_TYPE_NUM
  LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT_STATUS AUD__PAYMENT_STATUS
     ON AUD__PAYMENT_STATUS.PAYMENT_STATUS_NUM = AUD__PAYMENT.PAYMENT_STATUS_NUM
WHERE AUD__FILL_FACT.FILL_STATE_CHG_TS BETWEEN (TRUNC(:RUNDATE, 'DAY') - 1) AND (TRUNC(:RUNDATE, 'DAY') - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
  AND AUD__FILL_FACT.FILL_STATE_CODE IN (14,16)
  AND AUD__FILL_FACT.RX_NUMBER NOT LIKE 'RR%'
  AND DW__PAYMENT_TYPE.PAYMENT_TYPE_NAME NOT IN ('CREDIT CARD','CREDIT CARD REVERSAL')
  AND AUD__FILL_FACT.IS_SAME_DAY_REVERSAL != 'Y'
  AND UPPER(AUD__PAYMENT_STATUS.PAYMENT_STATUS_NAME) != 'CANCELLED'
ORDER BY
     AUD__ORDER_RECORD.FACILITY_ORDER_NUMBER
    ,AUD__FILL_FACT.RX_NUMBER
    ,ROUND((AUD__FILL_FACT.FILL_STATE_CHG_TS - TO_DATE('20350101','YYYYMMDD')),6)
    ,TO_NUMBER(TO_CHAR(AUD__PAYMENT.PAYMENT_DATE::DATE,'YYYYMMDD'))