SELECT 
	TO_NUMBER(FACILITY.FD_FACILITY_ID) "STORE_NUM",
	TO_NUMBER(REGEXP_REPLACE(PAYMENT.RX_NUMBER,'[^0-9]+','')) "RX_NUM",
	PAYMENT.REFILL_NUM "REFILL_NUM",
	PAYMENT.FACILITY_ORDER_NUMBER "ORDER_NUM",
	PATIENT.PD_PATIENT_NUM "PATIENT_NUM",
	CASE WHEN PAYMENT.COMPLETION_DATE_KEY = 0 THEN NULL ELSE PAYMENT.COMPLETION_DATE_KEY END "PAYMENT_DATE",
	CASE WHEN PAYMENT.COMPLETION_DATE_KEY = 0 THEN NULL
		 ELSE ROUND(((TO_DATE(TO_CHAR(PAYMENT.COMPLETION_DATE_KEY),'YYYYMMDD') + ((PAYMENT.COMPLETION_TIME_KEY - 2)/86400)) - TO_DATE('20350101','YYYYMMDD')),6)
	END "PAYMENT_DATETIME",
	PAYMENT.PAYMENT_AMOUNT "PAYMENT_AMOUNT",
	CASE WHEN SHIPFACT.SHIP_DATE_KEY = 0 THEN NULL ELSE SHIPFACT.SHIP_DATE_KEY END "SHIP_DATE",
	SHIPFACT.SHIP_HANDLE_FEE "SHIP_FEE",
	DRUG.DRUG_NDC "NDC_WO",
	WEGMANS.CLEAN_STRING_FORTENUP(DRUG.DRUG_LABEL_NAME) "DRUG_NAME",
	PAYMENT.PAYMENT_NUM "PAYMENT_NUM",
	PAYMENT.REVERSAL_PAYMENT_NUM "REVPAYMENT_NUM",
	CASE WHEN PAYMENT.HEALTH_CARD_DESIGNATION = 'FSA' THEN 1 ELSE 0 END "IS_FSA",
	CASE WHEN PAYMENT.PAYMENT_TYPE_KEY = 7 THEN 1 ELSE 0 END "IS_REFUND",
	CCRESPONSE.CC_TRANS_PAYMENT_TYPE "CC_TYPE",
	TO_CHAR(PAYMENT.LAST4_PAN,'0000') "CC_LAST4",
	CASE WHEN PAYMENT.EXPIRATION_DATE_KEY = 0 THEN NULL ELSE PAYMENT.EXPIRATION_DATE_KEY END "CC_EXPIRE_DATE",
	CCRESPONSE.CC_TRANS_REFERENCE_NUM "VANTIV_REF_NUM",
	CCRESPONSE.CC_TRANS_AUTHORIZATION_CODE "VANTIV_AUTH_CODE",
	CASE PAYMENT.PAYMENT_SOURCE
	  WHEN 'U' THEN 'USER ENTERED'
	  WHEN 'R' THEN 'CC RESPONSE'
	  ELSE NULL
	END "PAYMENT_SOURCE",
	PAYTYPE.PAYMENT_TYPE_NAME "PAYMENT_TYPE",
	PAYMENT.QTY_DISPENSED "QTY_DISPENSED",
	CASE WHEN PAYMENT.IS_CENTRAL_FILL_MAIL = 'Y' THEN 'CF MAIL'
		 WHEN PAYMENT.IS_STORE_MAIL= 'Y' THEN 'STORE MAIL'
		 ELSE NULL
	END "CFSTORE_MAIL",
	PAYMENT.RX_FILL_SEQ "RX_FILL_SEQ",
	PAYMENT.ORDER_NUM "DW_ORDER_NUM",
	PAYMENT.ITEM_SEQ "ITEM SEQ"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PAYMENT_FACT PAYMENT
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
    ON PAYMENT.FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY
  LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
    ON PAYMENT.DRUG_KEY = DRUG.DRUG_KEY
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PATIENT
    ON PAYMENT.PD_PATIENT_KEY = PATIENT.PD_PATIENT_KEY
  LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CC_TRANS_REQUEST CCREQUEST
    ON PAYMENT.PAYMENT_NUM = CCREQUEST.CC_TRANS_ERX_PAYMENT_NUM
   AND CCREQUEST.CC_TRANS_SUBMISSION_STATUS != 'D'
   AND CCREQUEST.CC_TRANS_COMMAND_TYPE != 'PRE_AUTH'
   AND CCREQUEST.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
   AND CCREQUEST.EFF_START_DATE >= (TRUNC(:RUNDATE, 'DAY') - 1)
  LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CC_TRANS_RESPONSE CCRESPONSE
    ON CCREQUEST.CC_TRANS_REQUEST_NUM = CCRESPONSE.CC_TRANS_REQUEST_NUM
   AND CCRESPONSE.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
   AND CCRESPONSE.EFF_START_DATE >= (TRUNC(:RUNDATE, 'DAY') - 1)
  LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PAYMENT_TYPE PAYTYPE
    ON PAYMENT.PAYMENT_TYPE_KEY = PAYTYPE.PAYMENT_TYPE_KEY
  LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT SHIPFACT
    ON PAYMENT.ORDER_NUM = SHIPFACT.ORDER_NUM
   AND SHIPFACT.PD_PATIENT_KEY = PAYMENT.PD_PATIENT_KEY
WHERE PAYMENT.COMPLETION_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE, 'YYYYMMDD'))
--FILES TO 1010DATA MUST BE ONE RUN DATE PER FILE.
  AND PAYMENT.IS_ACTIVE = 'Y'