SELECT TOP :Limit C_CUSTOMER_ID, C_FIRST_NAME, C_LAST_NAME, C_EMAIL_ADDRESS 
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER
WHERE C_CREATEDDATE < :RunDate
AND CONTAINS(C_FIRST_NAME, :FirstNameContains);