SELECT 
  V.STORE_NUM,
  V.RX_NUM,
  V.REFILL_NUM,
  V.PART_SEQ_NUM,
  V.DUR_DATE,
  V.PATIENT_NUM,
  V.NDC_WO,
  V.DRUG_NAME,
  V.SDGI,
  V.GCN,
  V.GCN_SEQ_NUM,
  V.DEA_CLASS,
  V.CONFLICT_CODE,
  V.CONFLICT_DESC,
  V.CONFLICT_TYPE,
  V.SEVERITY_DESC,
  V.RESULT_OF_SERVICE,
  V.PROF_SERVICE,
  V.LEVEL_OF_EFFORT,
  V.REASON_FOR_SERVICE,
  V.IS_CRITICAL,
  V.IS_EXCEPTION,
  V.RX_FILL_SEQ,
  V.RX_RECORD_NUM,
  V.PRESCRIBER_KEY,
  V.USER_KEY
FROM (
		SELECT
			FACILITY.FD_FACILITY_ID AS STORE_NUM,
			DUR.RX_NUMBER AS RX_NUM,
			DUR.REFILL_NUM AS REFILL_NUM,
			(DECODE(DUR.PARTIAL_FILL_SEQ,NULL,0,DUR.PARTIAL_FILL_SEQ)) AS PART_SEQ_NUM,
			DURDATE.CAL_DATE AS DUR_DATE,
			PT.PD_PATIENT_NUM AS PATIENT_NUM,
			TO_CHAR(DRUG.DRUG_NDC) AS NDC_WO,
			DRUG.DRUG_LABEL_NAME AS DRUG_NAME,
			PRODUCT.PRD_IS_GENERIC AS SDGI,
			DRUG.DRUG_GCN AS GCN,
			DRUG.DRUG_GCN_SEQ AS GCN_SEQ_NUM,
			DRUG.DRUG_DEA_CLASS AS DEA_CLASS,
			CC.DUR_CONFLICT_CODE AS CONFLICT_CODE,
			CC.DUR_CONFLICT_CODE_DESC AS CONFLICT_DESC,
			CTYPE.DUR_CONFLICT_DESC AS CONFLICT_TYPE,
			SEVTYPE.DUR_SEVERITY_DESC AS SEVERITY_DESC,
			DUR.RESULT_SERVICE_CODE AS RESULT_OF_SERVICE,
			DUR.PROF_SERVICE_CODE AS PROF_SERVICE,
			DUR.LEVEL_OF_EFFORT_NUM AS LEVEL_OF_EFFORT,
			DUR.REASON_FOR_SERVICE_CODE AS REASON_FOR_SERVICE,
			DURIND.IS_CRITICAL AS IS_CRITICAL,
			DURIND.IS_EXCEPTION AS IS_EXCEPTION,
			DUR.FILL_SEQ_NUM AS RX_FILL_SEQ,
			DUR.RX_RECORD_NUM AS RX_RECORD_NUM,
			DUR.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
			DUR.SYS_USER_KEY AS USER_KEY,
			DUR.DATE_KEY
		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.DUR_CONFLICT_FACT DUR
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DURDATE
			   ON DUR.DATE_KEY = DURDATE.DATE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
			   ON DUR.FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PT
			   ON DUR.PD_PATIENT_KEY = PT.PD_PATIENT_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRODUCT
			   ON DUR.PRD_PRODUCT_KEY = PRODUCT.PRD_PRODUCT_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
			   ON PRODUCT.PRD_DRUG_NUM = DRUG.DRUG_NUM
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DUR_CONFLICT_CODE CC
			   ON DUR.DUR_CONFLICT_CODE_KEY = CC.DUR_CONFLICT_CODE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DUR_CONFLICT_TYPE CTYPE
			   ON DUR.DUR_CONFLICT_TYPE_KEY = CTYPE.DUR_CONFLICT_TYPE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DUR_SEVERITY_TYPE SEVTYPE
			   ON DUR.DUR_SEVERITY_TYPE_KEY = SEVTYPE.DUR_SEVERITY_TYPE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DUR_INDICATOR DURIND
			   ON DUR.DUR_INDICATOR_KEY = DURIND.DUR_INDICATOR_KEY
     ) V
WHERE V.DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE, 'YYYYMMDD'))
  AND V.CONFLICT_CODE IS NOT NULL
  AND V.CONFLICT_TYPE NOT IN ('LOAD ERROR')
ORDER BY 
  V.STORE_NUM,
  V.RX_NUM,
  V.REFILL_NUM