SELECT END_TIME
FROM TREXONE_ODS_DATA.ETL_RUN
WHERE STATUS = 'C'
  AND START_TIME BETWEEN (:RUNDATE - 1 + INTERVAL '23:00:00' HOUR TO SECOND)
                     AND (:RUNDATE + INTERVAL '15 HOURS')
  AND END_TIME   BETWEEN :RUNDATE 
                     AND (:RUNDATE + INTERVAL '15 HOURS')
  AND ROW_NUMBER() OVER (ORDER BY END_TIME) = 1
ORDER BY START_TIME DESC