SELECT 'START_TIME:"' ||
       TO_CHAR(ER.START_TIME::DATE,'MM/DD HH24:MI:SS') ||
       '", END_TIME:"' ||
       TO_CHAR(ER.END_TIME::DATE,'MM/DD HH24:MI:SS') ||
       '", RUN_TYPE:"' ||
       ER.RUN_TYPE ||
       '", STATUS:"' ||
       ER.STATUS ||
       '"' AS LOGGING_INFO
FROM  TREXONE_ODS_DATA.ETL_RUN ER
WHERE ER.START_TIME = (
     SELECT MAX(ER2.START_TIME)
     FROM TREXONE_ODS_DATA.ETL_RUN ER2
     WHERE ER2.START_TIME > (SYSDATE() - 2)
)