SELECT (:RUNDATE - 1) AS DATE_OF_SERVICE,
        TO_CHAR(DRUG.DRUG_NDC) "NDC_WO",
        TO_CHAR(DRUG.DRUG_NDC,'00000G0000G00','NLS_NUMERIC_CHARACTERS=.-') "NDC",
        DRUG.DRUG_LABEL_NAME "DRUG_NAME",
        DRUG.DRUG_LABELER "DRUG_MANUFACTURER",
        DRUG.DRUG_GNN "GENERIC_NAME",
        DRUG.DRUG_PACKAGE_SIZE "PACK_SIZE",
        DRUG.DRUG_CASE_SIZE*DRUG.DRUG_PACKAGE_SIZE "TRUE_PACK",
        PRODUCT.PRD_IS_PRICE_MAINTAINED "PM",
        PROD_P_MSG.PREFERRED "IS PREFERRED",
        
        NVL(PRODCOSTFACT.COST,MANUALPRDCOSTBASIS.MANUAL_COST) AS "CON_UNIT",
        NVL(COSTBASISSOURCE.COST_BASIS_SOURCE_NAME,CASE WHEN MANUALPRDCOSTBASIS.MANUAL_COST IS NULL THEN NULL ELSE 'MANUAL COST' END) "CON_SOURCE",
        COSTBASISSOURCE.PROVIDER "CON_VENDOR",
        NVL(PRODCOSTFACT.EFFECTIVE_DATE,CASE WHEN MANUALPRDCOSTBASIS.MANUAL_COST IS NULL THEN NULL ELSE MANUALPRDCOSTBASIS.MANUAL_COST_EFF_DATE END) "CON_EFF_DATE",
        NVL(PRODCOSTBASIS.EFFECTIVE_DATE,CASE WHEN MANUALPRDCOSTBASIS.MANUAL_COST IS NULL THEN NULL ELSE MANUALPRDCOSTBASIS.MANUAL_COST_EFF_DATE END) "SUPPLIER_EFF_DATE",
        
        VENDOR_ITEM.ITEM_NUM "ITEMNO",
        REPLACE(PROD_P_MSG.PRODUCT_MSG, CHR(10), ' ') "PRODUCT_MSG",
        PROD_P_MSG.MSG_EFF_DATE "MSG_EFF_DATE",
        PROD_P_MSG.MSG_EXP_DATE "MSG_EXP_DATE",

        NVL(POG.PRODUCT_ORDERING_GROUP_NAME,SECPOG.PRODUCT_ORDERING_GROUP_NAME) "POG_NAME",
          NVL(DECODE(POG.INCLUDE_EXCLUDE_FLAG,'N','INCLUDE BY NDC','G','INCLUDE BY GCN','P','INCLUDE BY PACK SIZE AND GCN','X','EXCLUDE BY NDC','D','DEFAULT'),
          CASE POG.IS_PRIMARY_PRODUCT WHEN 'Y' THEN 'PRIMARY PRODUCT'
          ELSE DECODE(SECPOG.INCLUDE_EXCLUDE_FLAG,'N','INCLUDE BY NDC','G','INCLUDE BY GCN','P','INCLUDE BY PACK SIZE AND GCN','X','EXCLUDE BY NDC','D','DEFAULT') END) "INCLUDE_EXCLUDE",
        NVL(POG.IS_DIRECT_INCLUSION,SECPOG.IS_DIRECT_INCLUSION) "POG_DIRECT_INCLUSION",
        NVL(POG.IS_PRIMARY_PRODUCT,SECPOG.IS_PRIMARY_PRODUCT) "POG_IS_PRIMARY",
        NVL(POG.IS_ORDERING_PRODUCT,SECPOG.IS_ORDERING_PRODUCT) "ORDERING_PRODUCT",
        NVL(POG.SYS_USER_KEY,SECPOG.SYS_USER_KEY) "POG_USER_KEY",
        NVL(POG.DATESTAMP,SECPOG.DATESTAMP) "POG_CHANGE_DATE",
        
        TO_CHAR(PRODMAPPING.DRUG_NDC) "LAST_MAPPED_TO_NDC",
        PRODMAPPING.MAP_START_DATE "DATE_MAPPED",
        
        CFBLOCKED.BLOCK_STORE_COUNT "CFBLOCKED_STORE_COUNT",
        CFBLOCKED.BLOCK_DATE "DATE_CFBLOCKED",

        PRODGROUP.GROUP_NAME "DECILE",
        SECPRODGROUP.GROUP_NAME "PRODUCT_GROUP",
        PRODUCT.PRD_IS_GENERIC "SDGI",
        PRODUCT.PRD_ALTERNATE_LABEL_NAME "ALT_LABEL_NAME",
        PRODUCT.PRD_SOURCE_INDICATOR "SOURCE",
        DRUG.DRUG_GCN "GCN",
        DRUG.DRUG_GCN_SEQ "GCN_SEQ_NUM",
        UPPER(DRUG.DRUG_STRENGTH||' '||DRUG.DRUG_STRENGTH_UNITS) "STRENGTH",
        DRUG.DRUG_ORANGE_BOOK_CODE "ORANGE_BOOK_CODE",
        
        DRUG.DRUG_KEY "DRUG_KEY",
        DRUG.DRUG_NUM "DRUG_NUM",
        PRODUCT.PRD_PRODUCT_KEY "PRODUCT_KEY",
        PRODUCT.PRD_PRODUCT_NUM "PRODUCT_NUM",
       
        DRUG.DRUG_DEA_CLASS "DEA_SCHED",
        DRUG.DRUG_DATE_OF_ADD "DATE_ADDED",
        DRUG.DRUG_OBSOLETE_DATE "OBSOLETE_DATE",
        PRODUCT.PRD_DEACTIVATE_DATE "DEACTIVE_DATE",
        DRUG.DRUG_DOSAGE_FORM "DOSAGE_FORM",
        SUBSTR(DRUG.DRUG_AHFS,1,2)||':'||SUBSTR(DRUG.DRUG_AHFS,3,2)||':'||SUBSTR(DRUG.DRUG_AHFS,5,5) "AHFS_CLASS",
        DRUG.DRUG_AHFS_DESCRIPTION "AHFS_DESC",
        DRUG.DRUG_GEN_THERAPEUTIC_CLASS "THER_CLASS",
        DRUG.DRUG_GC3_CODE "HIC3_CODE",
        DRUG.DRUG_GC3 "HIC3_DESC",
        DRUG.DRUG_HCFA_DESI "DESI_CODE",
        DRUG.DRUG_HCPCS_CODE "HCPCS_CODE",
        DRUG.DRUG_LAST_PROVIDER_UPDATE "LAST_PROVIDER_UPDATE",
        DRUG.DRUG_HCFA_APPROVAL_DATE "FDA_APPROVE_DATE",
        
        CASE DRUG.DRUG_HCFA_TYPE WHEN '1' THEN 'RX'
        WHEN '2' THEN 'OTC'
        ELSE 'NOT PROVIDED' END AS "HCFA_TYPE",
        DRUG.DRUG_HCFA_MARKET_ENTRY_DATE "MFG_RELEASE_DATE"

FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRODUCT
ON DRUG.DRUG_NUM = PRODUCT.PRD_DRUG_NUM

--LINKING TABLE TO GET THE NEXT JOINS FOR COST BASIS SOURCE AND COST
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_COST_BASIS PRODCOSTBASIS
ON DRUG.DRUG_KEY = PRODCOSTBASIS.DRUG_KEY
AND PRODCOSTBASIS.TERMINATION_DATE IS NULL
AND PRODCOSTBASIS.COST_BASIS_KEY = 535
AND PRODCOSTBASIS.COST_BASIS_SOURCE_KEY <> 0

LEFT OUTER JOIN
(SELECT MANUALPRDCOSTBASIS.DRUG_KEY AS "DRUG_KEY",
        AVG(DISTINCT MANUALPRDCOSTBASIS.ADJUST_MODIFIER) AS "MANUAL_COST",
        MAX(MANUALPRDCOSTBASIS.EFFECTIVE_DATE) AS "MANUAL_COST_EFF_DATE"
        
        FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_COST_BASIS MANUALPRDCOSTBASIS
        
WHERE MANUALPRDCOSTBASIS.TERMINATION_DATE IS NULL
AND MANUALPRDCOSTBASIS.COST_BASIS_KEY = 535
AND MANUALPRDCOSTBASIS.COST_BASIS_SOURCE_KEY = 0

GROUP BY MANUALPRDCOSTBASIS.DRUG_KEY)MANUALPRDCOSTBASIS
        
ON DRUG.DRUG_KEY = MANUALPRDCOSTBASIS.DRUG_KEY

--TO GET THE SOURCE OF THE COST BASIS (ANDA PRIMARY, HARVARD PRIMARY, ETC.)
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COST_BASIS_SOURCE COSTBASISSOURCE
ON PRODCOSTBASIS.COST_BASIS_SOURCE_KEY = COSTBASISSOURCE.COST_BASIS_SOURCE_KEY
AND TRUNC(COSTBASISSOURCE.EFF_END_DATE, 'DAY') = TO_DATE('12/31/2999','MM/DD/YYYY')

--TO GET THE CON (OR ANY OTHER COST FACTORS) OF THE DRUG)
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_COST_FACT PRODCOSTFACT
ON PRODCOSTFACT.DRUG_KEY = DRUG.DRUG_KEY
AND PRODCOSTFACT.COST_BASIS_SOURCE_KEY = PRODCOSTBASIS.COST_BASIS_SOURCE_KEY
AND PRODCOSTFACT.TERMINATION_DATE IS NULL

--THIS IS FOR DECILE
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_GROUP PRODGROUP
ON PRODUCT.PRD_PRODUCT_NUM = PRODGROUP.PRODUCT_NUM
AND PRODGROUP.MEMBER_STATUS = 'ACTIVE'
AND PRODGROUP.GROUP_NAME IN ('0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J')

--THIS IS FOR NON-DECILE SECONDARY GROUPS
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_GROUP SECPRODGROUP
ON PRODUCT.PRD_PRODUCT_NUM = SECPRODGROUP.PRODUCT_NUM
AND SECPRODGROUP.MEMBER_STATUS = 'ACTIVE'
AND SECPRODGROUP.GROUP_NAME NOT IN ('0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J')
AND ROW_NUMBER() OVER (ORDER BY :RUNDATE) = 1

--LINKS IN POG INFORMATION --DIRECT INCLUSIONS ONLY
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_ORDERING_GROUP_MEMBER POG
ON PRODUCT.PRD_PRODUCT_KEY = POG.PRD_PRODUCT_KEY
AND TRUNC(POG.EFF_END_DATE, 'DAY') = TO_DATE('12/31/2999','MM/DD/YYYY') AND ROW_NUMBER() OVER (ORDER BY :RUNDATE) = 1
AND POG.IS_DIRECT_INCLUSION = 'Y'

--LINK IN POG INFORMATION --NOT DIRECT INCLUSIONS
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_ORDERING_GROUP_MEMBER SECPOG
ON PRODUCT.PRD_PRODUCT_KEY = SECPOG.PRD_PRODUCT_KEY
AND TRUNC(SECPOG.EFF_END_DATE, 'DAY') = TO_DATE('12/31/2999','MM/DD/YYYY') AND ROW_NUMBER() OVER (ORDER BY :RUNDATE) = 1
AND SECPOG.IS_DIRECT_INCLUSION = 'N'

--START-- LINKS IN PRODUCT MAPPING INFORMATION
LEFT OUTER JOIN
      (SELECT PRODDMAP.PRD_PRODUCT_KEY AS "MAP_PRODUCT_KEY",
              MAPTODRUG.DRUG_NDC AS "DRUG_NDC",
              PRODDMAP.EFF_START_DATE AS "MAP_START_DATE"
         FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.CENTRAL_FILL_PRODUCT_MAP PRODDMAP
       LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT MAPTOPROD
            ON PRODDMAP.MAP_TO_PRD_PRODUCT_KEY = MAPTOPROD.PRD_PRODUCT_KEY
       LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG MAPTODRUG
            ON MAPTOPROD.PRD_DRUG_NUM = MAPTODRUG.DRUG_NUM
       WHERE PRODDMAP.FD_FACILITY_KEY = 573
        AND TRUNC(PRODDMAP.EFF_END_DATE, 'DAY') = TO_DATE('12/31/2999','MM/DD/YYYY')) PRODMAPPING
  ON PRODUCT.PRD_PRODUCT_KEY = PRODMAPPING.MAP_PRODUCT_KEY
--END-- LINKS IN PRODUCT MAPPING INFORMATION

--START -- LINKS IN PREFERRED PRODUCT INFO  MESSAGE, FROM AUDIT TABLES
LEFT OUTER JOIN
      (SELECT PRODP.PRODUCT_NUM AS "PRODUCT_NUM",
              PRODP.IS_PREFERRED_PRODUCT AS "PREFERRED",
              PRODMSG.MESSAGE_TEXT AS "PRODUCT_MSG",
              PRODMSG.EFFECTIVE_DATE AS "MSG_EFF_DATE",
              PRODMSG.EXPIRATION_DATE AS "MSG_EXP_DATE"
              
FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PRODUCT PRODP

    LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PRODUCT_MESSAGE PRODMSG
          ON PRODP.PRODUCT_NUM = PRODMSG.PRODUCT_NUM
          AND PRODMSG.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
          AND PRODMSG.SYS_USER <> 0
          AND PRODMSG.PRIORITY = 1
          
WHERE TRUNC(PRODP.EFF_END_DATE, 'DAY') = TO_DATE('12/31/2999','MM/DD/YYYY')) PROD_P_MSG
    ON PRODUCT.PRD_PRODUCT_NUM = PROD_P_MSG.PRODUCT_NUM
--END   -- LINKS IN PREFERRED PRODUCT INFO  MESSAGE, FROM AUDIT TABLES

-- LINKS CF BLOCKED LIST
LEFT OUTER JOIN
      (SELECT CFBLOCK.PRD_PRODUCT_KEY AS "BLOCK_PRODUCT_KEY",
        --DRUG.DRUG_NDC,
        --DRUG.DRUG_LABEL_NAME,
        COUNT(UNIQUE CFBLOCK.LOCAL_FD_FACILITY_KEY) AS "BLOCK_STORE_COUNT",
        MAX(CFBLOCK.EFF_START_DATE) AS "BLOCK_DATE"
        
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.CENTRAL_FILL_PRODUCT_EXCLUSION CFBLOCK
    
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PROD
   ON CFBLOCK.PRD_PRODUCT_KEY = PROD.PRD_PRODUCT_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
    ON DRUG.DRUG_NUM = PROD.PRD_DRUG_NUM

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
    ON CFBLOCK.LOCAL_FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY

WHERE CFBLOCK.FD_FACILITY_KEY = 573
AND CFBLOCK.PRD_PRODUCT_KEY <> 0
AND TRUNC(CFBLOCK.EFF_END_DATE, 'DAY') = TO_DATE('12/31/9999','MM/DD/YYYY')
AND CFBLOCK.FD_FACILITY_KEY NOT IN (574,634898)

GROUP BY CFBLOCK.PRD_PRODUCT_KEY)CFBLOCKED
ON CFBLOCKED.BLOCK_PRODUCT_KEY = PRODUCT.PRD_PRODUCT_KEY
-- ENDS LINK CF BLOCKED LIST

--START QUERY FOR VENDOR ITEM NUMBER
LEFT OUTER JOIN
(SELECT PRICECAT.DRUG_KEY AS "DRUG_KEY",
      PRICECAT.VENDOR_PRODUCT_ID AS "ITEM_NUM",
      VENDOR.VENDOR_NAME AS "VENDOR"

FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR_PRICE_CATALOG PRICECAT

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR VENDOR
ON PRICECAT.VENDOR_KEY = VENDOR.VENDOR_KEY

WHERE PRICECAT.VENDOR_KEY <> 0
AND PRICECAT.EFFECTIVE_END_DATE = TO_DATE('2999-12-31','YYYY-MM-DD'))VENDOR_ITEM
ON DRUG.DRUG_KEY = VENDOR_ITEM.DRUG_KEY
AND COSTBASISSOURCE.PROVIDER = VENDOR_ITEM.VENDOR
--ENDS QUERY FOR VENDOR ITEM NUMBER

WHERE PRODUCT.PRD_DEACTIVATE_DATE IS NULL
AND NOT(PRODUCT.PRD_DEACTIVATE_DATE IS NOT NULL AND PRODUCT.PRD_SOURCE_INDICATOR = 'CORPORATE')
AND DRUG.DRUG_NDC <> '99999999999'
AND PRODUCT.PRD_DEACTIVATE_DATE IS NULL
AND NVL(DRUG.DRUG_OBSOLETE_DATE, '31-DEC-2999') > (SYSDATE() - 730)
----AND DRUG.DRUG_GNN IS NOT NULL --REMOVED THIS LINE ON 5/9/2018
--SHOWS ONLY ACTIVE DRUGS--
AND DRUG.DRUG_NDC_MFG NOT IN (00247,00363,00440,00490,00615,11917,12280,16590,
16881,19458,21140,21695,23490,24385,33358,34575,35356,37205,40986,49002,49614,
49999,50428,51655,52959,53265,54569,54868,55045,55289,55887,57866,58016,58864,
63874,65243,66116,66267,66336,67544,68016,68030,68071,68094,68115,68258,68387,91899,00000)
--EXCLUDING GARBAGE MANUFACTURERS

ORDER BY DRUG.DRUG_LABEL_NAME