SELECT FILL_FACT_KEY, SRC, ORDER_DATE_KEY, REFILL_QTY, FULL_PACKAGE_UNC
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT
WHERE READY_DATE_KEY = :ReadyDateKey
  OR RX_NUMBER = :RxNumber
  OR TOTAL_PRICE_PAID = :TotalPricePaid
  OR DISPENSED_ITEM_EXPIRATION_DATE = :DispensedItemExpirationDate
  OR LOCAL_TRANSACTION_DATE = :LocalTransactionDate
LIMIT 10;