SELECT *
  FROM ( SELECT DISTINCT F.FD_FACILITY_ID AS STORENUMBER
              , FF.RX_NUMBER AS RXNUMBER
              , FF.REFILL_NUM AS REFILLNUMBER
              , SF.SHIPMENT_ADDRESS1 AS SHIPADDRESS1
              , SF.SHIPMENT_ADDRESS2 AS SHIPADDRESS2
              , SF.SHIPMENT_CITY AS SHIPCITY
              , SF.SHIPMENT_STATE AS SHIPSTATE
              , SF.SHIPMENT_ZIPCODE AS SHIPZIP
              , FF.QTY_DISPENSED AS QUANTITYDISPENSED
              , D.DRUG_NDC AS DRUGNDC
              , TP.TPLD_PLAN_CODE AS PLANCODE
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, TPP2.TPD_TP_PLAN_NUM ORDER BY TPP2.H_LEVEL DESC, ROW_NUMBER() OVER (ORDER BY TPP2.H_LEVEL)) AS TPPATIENTRANK
           FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON (FF.FD_FACILITY_KEY = F.FD_FACILITY_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT P ON (FF.DISPENSED_PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON (P.PRD_DRUG_NUM = D.DRUG_NUM AND P.PRD_DEACTIVATE_DATE IS NULL)
           LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM I ON (FF.RX_RECORD_NUM = I.RX_RECORD_NUM AND FF.RX_FILL_SEQ = I.RX_FILL_SEQ 
                AND FF.ORDER_NUM = I.ORDER_NUM AND I.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY'))
           LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT SF ON (I.ORDER_NUM = SF.ORDER_NUM)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPP ON (TPP.TPD_KEY = FF.TPD_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPP2 ON (FF.PD_PATIENT_KEY = TPP2.PD_PATIENT_KEY AND TPP.TPD_TP_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM 
                AND TPP2.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY') AND TPP2.TPD_IS_ACTIVE = 'Y')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TP ON (TP.TPLD_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM)
          WHERE FF.SOLD_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE, 'YYYYMMDD'))
            AND F.FD_FACILITY_ID IN ('198', '199')
            AND D.DRUG_NDC IN ('50458057760', '50458057830', '50458057930', '50458058030')
            AND NVL(FF.IS_BAR, 'N') = 'N'
            AND SF.SHIPMENT_STATE NOT IN ('IL','HI','LA')
            AND FF.CANCEL_DATE_KEY = 0
            AND (TP.TPLD_PLAN_CODE IS NULL OR TP.TPLD_PLAN_CODE NOT IN ('OTHEPAON','OTHEPAOR','OTHPAR'))
       )
 WHERE TPPATIENTRANK = 1