SELECT FACILITY.FD_FACILITY_ID AS "STORE_NUM"
,PO.PO_NUMBER "PO_NUMBER"
,PO.PURCHASE_ORDER_TYPE_CODE AS "PO_TYPE"
,VENDRUG.VENDOR_NAME AS "VENDOR_NAME"
,PO.IS_SCHEDULE_2_ORDER AS "IS_C2_ORDER"
,ROUND((POIT.CREATE_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_CREATE_DATETIME"
,POIT.LINE_NUMBER AS "LINE_NUM"
,POIT.H_TYPE AS "UPDATE_TYPE"
,ROUND((POIT.DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS "UPDATE_DATETIME"
,SYSUSERS.SYS_USER_LOGIN_NAME AS "USER_LOGIN"
,POIT.PURCHASE_ORDER_ITEM_NUM
,VENDRUG.NDC_WO "ORDERED_NDC_WO"
,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(VENDRUG.DRUG_NAME),1,35) AS "ORDERED_DRUG_NAME"
,VENDRUGSUB.NDC_WO "SUBSITUTED_NDC_WO"
,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(VENDRUGSUB.DRUG_NAME),1,35) AS "SUBSITUTED_DRUG_NAME"
,POIT.ORDERED_QUANTITY AS "ORDERED_QTY"
,POIT.RECEIVED_QUANTITY AS "RECEIVED_QTY"
,ROUND((POIT.RECEIVED_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "RECEIVED_DATETIME"
,POIT.EXPECTED_ACQ_COST AS "EXPECTED_ACQ_COST"
,POIT.ACTUAL_ACQ_COST AS "ACTUAL_ACQ_COST"
,POIT.RCVNG_EXCPTN_STATUS_CODE AS "REC_EXCEPTION_STATUS"
,POIT.MODIFIED_AFTER_ORDERED AS "MODIFIED_AFER_ORDERED"

FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PURCHASE_ORDER_ITEM POIT

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
ON POIT.FACILITY_NUM = FACILITY.FD_FACILITY_NUM

LEFT OUTER JOIN 
(SELECT DRUG.DRUG_NDC AS "NDC_WO"
,DRUG.DRUG_LABEL_NAME AS "DRUG_NAME"
,VENDORPRICE.VENDOR_ITEM_NUM AS "VENDOR_ITEM_NUM"
,VENDORPRICE.EFFECTIVE_START_DATE AS "START_DATE"
,VENDORPRICE.EFFECTIVE_END_DATE AS "END_DATE"
,VENDOR.VENDOR_NAME AS "VENDOR_NAME"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR_PRICE_CATALOG VENDORPRICE
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
ON VENDORPRICE.DRUG_KEY = DRUG.DRUG_KEY
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR VENDOR
ON VENDORPRICE.VENDOR_KEY = VENDOR.VENDOR_KEY)VENDRUG

ON POIT.CREATE_DATE BETWEEN VENDRUG.START_DATE AND VENDRUG.END_DATE
AND VENDRUG.VENDOR_ITEM_NUM = POIT.ORDERED_VENDOR_ITEM_NUM


LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PURCHASE_ORDER PO
ON POIT.PURCHASE_ORDER_NUM = PO.PURCHASE_ORDER_NUM
AND PO.EFF_END_DATE = TO_DATE('12312999','MMDDYYYY')

LEFT OUTER JOIN 
(SELECT DRUG.DRUG_NDC AS "NDC_WO"
,DRUG.DRUG_LABEL_NAME AS "DRUG_NAME"
,VENDORPRICESUB.VENDOR_ITEM_NUM AS "VENDOR_ITEM_NUM"
,VENDORPRICESUB.EFFECTIVE_START_DATE AS "START_DATE"
,VENDORPRICESUB.EFFECTIVE_END_DATE AS "END_DATE"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR_PRICE_CATALOG VENDORPRICESUB
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
ON VENDORPRICESUB.DRUG_KEY = DRUG.DRUG_KEY)VENDRUGSUB

ON POIT.CREATE_DATE BETWEEN VENDRUGSUB.START_DATE AND VENDRUGSUB.END_DATE
AND VENDRUGSUB.VENDOR_ITEM_NUM = POIT.SUBSTITUTED_VENDOR_ITEM_NUM

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SYSUSERS
ON POIT.SYS_USER = SYSUSERS.SYS_USER_NUM

WHERE POIT.DATESTAMP BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')