SELECT FACILITY.FD_FACILITY_ID AS "STORE_NUM"
,POIT.PO_NUMBER AS "PO_NUM"
,POIT.PO_TYPE_CODE AS "PO_TYPE"
,VENDOR.VENDOR_NAME AS "VENDOR_NAME"
,POIT.IS_SCHEDULE_2_ORDER AS "IS_C2_ORDER"
,SYSUSERS.SYS_USER_LOGIN_NAME AS "PO_CREATED_BY_USER"
,ROUND((POCREATEDDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_CREATED_DATE"
,POCREATEDTIME.HOUR_MIN_SEC_TXT AS "PO_CREATED_TIME"
,ROUND((PORECEIVEDDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_RECEIVED_DATE"
,PORECEIVEDTIME.HOUR_MIN_SEC_TXT AS "PO_RECEIVED_TIME"
,ROUND((POEXPRIATIONDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_EXPIRATION_DATE"
,POEXPIRATIONTIME.HOUR_MIN_SEC_TXT AS "PO_EXPIRATION_TIME"
,ROUND((POREMOVEDDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_REMOVED_DATE"
,POREMOVEDTIME.HOUR_MIN_SEC_TXT AS "PO_REMOVED_TIME"
,POIT.H_TYPE AS "UPDATE_TYPE"
,USERS.SYS_USER_LOGIN_NAME AS "UPDATE_USER"
,ROUND((POIT.PO_LAST_UPD_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_LAST_UPDATE_DATE"
,POSTATUSTYPE.DESCRIPTION AS "PO_STATUS_TYPE"
,POIT.LINE_NUMBER AS "LINE_NUM"
,DRUG.DRUG_NDC AS "NDC_WO"
,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DRUG.DRUG_LABEL_NAME),1,35) AS "DRUG_NAME"
,ROUND((ITEMCREATEDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_ITEM_CREATED_DATE"
,POITEMCREATEDTIME.HOUR_MIN_SEC_TXT AS "PO_ITEM_CREATED_TIME"
,ROUND((ITEMRECEIVEDDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_ITEM_RECEIVED_DATE"
,POITEMRECEIVEDTIME.HOUR_MIN_SEC_TXT AS "PO_ITEM_RECEIVED_TIME"
,ROUND((ITEMRREMOVEDDATE.CAL_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_ITEM_REMOVED_DATE"
,POITEMREMOVEDTIME.HOUR_MIN_SEC_TXT AS "PO_ITEM_REMOVED_TIME"
---,POIT.VENDOR_PRICE_CATALOG_KEY AS "VENDOR_PRICE_CATALOG_KEY"
---,POIT.SUBSTITUTED_PRICE_CATALOG_KEY AS "SUB_PRICE_CATALOG_KEY"
,POSHIPSTATUS.PO_ACK_SHIPPING_STATUS AS "PO_ACK_SHIPPING_STATUS"
,POSHIPSTATUS.PO_ACK_SHIPPING_DESC AS "ACK_SHIPPING_STATUS_DESC"
,POIT.ORDERED_QTY AS "ORDERED_QTY"
,POIT.RECEIVED_QTY AS "RECEIVED_QTY"
,POIT.ACK_QUANTITY AS "ACK_QTY"
,POIT.EXPECTED_ACQ_COST AS "EXPECTED_ACQ_COST"
,POIT.ACTUAL_ACQ_COST AS "ACTUAL_ACQ_COST"
,POIT.ACK_ACQUISITION_COST AS "ACK_ACQ_COST"
,POIT.RCVNG_EXCPTN_STATUS_CODE AS "REC_EXCEPTION_STATUS"
,POIT.MODIFIED_AFTER_ORDERED AS "MODIFIED_AFER_ORDERED"
,ROUND((POIT.PO_ACK_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS "PO_ACK_DATE"
,POACKSHIP.DESCRIPTION AS "PO_ACK_TYPE"

FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PURCHASE_ORDER_ITEM_FACT POIT
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
ON POIT.FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
ON POIT.DRUG_KEY = DRUG.DRUG_KEY
--COPY THIS FOR OTHER DATE KEYS
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ITEMCREATEDATE
ON POIT.PO_ITEM_CREATED_DATE_KEY = ITEMCREATEDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ITEMRECEIVEDDATE
ON POIT.PO_ITEM_RECEIVED_DATE_KEY = ITEMRECEIVEDDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ITEMRREMOVEDDATE
ON POIT.PO_ITEM_REMOVED_DATE_KEY = ITEMRREMOVEDDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM POCREATEDDATE
ON POIT.PO_CREATED_DATE_KEY = POCREATEDDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM PORECEIVEDDATE
ON POIT.PO_RECEIVED_DATE_KEY = PORECEIVEDDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM POEXPRIATIONDATE
ON POIT.PO_EXPRIATION_DATE_KEY = POEXPRIATIONDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM POREMOVEDDATE
ON POIT.PO_REMOVED_DATE_KEY = POREMOVEDDATE.DATE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR VENDOR
ON POIT.VENDOR_KEY = VENDOR.VENDOR_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SYSUSERS
ON POIT.PO_CREATED_USER_KEY = SYSUSERS.SYS_USER_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER USERS
ON POIT.PO_LAST_UPD_SYS_USER_KEY = USERS.SYS_USER_KEY

--TIME
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POCREATEDTIME
ON POIT.PO_CREATED_TIME_KEY = POCREATEDTIME.TIME_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM PORECEIVEDTIME
ON POIT.PO_RECEIVED_TIME_KEY = PORECEIVEDTIME.TIME_KEY


LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POEXPIRATIONTIME
ON POIT.PO_EXPIRATION_TIME_KEY = POEXPIRATIONTIME.TIME_KEY


LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POREMOVEDTIME
ON POIT.PO_REMOVED_TIME_KEY = POREMOVEDTIME.TIME_KEY


LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POITEMCREATEDTIME
ON POIT.PO_ITEM_CREATED_TIME_KEY = POITEMCREATEDTIME.TIME_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POITEMRECEIVEDTIME
ON POIT.PO_ITEM_RECEIVED_TIME_KEY = POITEMRECEIVEDTIME.TIME_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM POITEMREMOVEDTIME
ON POIT.PO_ITEM_REMOVED_TIME_KEY = POITEMREMOVEDTIME.TIME_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PO_STATUS_TYPE POSTATUSTYPE
ON POIT.PO_STATUS_TYPE_KEY = POSTATUSTYPE.PO_STATUS_TYPE_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PO_ACK_SHIPPING_STATUS_TYPE POSHIPSTATUS
ON POIT.PO_ACK_SHIPPING_STATUS_KEY = POSHIPSTATUS.PO_ACK_SHIPPING_STATUS_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.ACK_SHIPPING_STATUS_TYPE POACKSHIP
ON POIT.PO_ACK_TYPE_CODE = POACKSHIP.ACK_SHIPPING_STATUS

WHERE POIT.PO_CREATED_DATE_KEY BETWEEN TO_NUMBER(TO_CHAR((:RUNDATE - 30)::DATE,'YYYYMMDD')) AND TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
AND POIT.PO_LAST_UPD_DATE BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')