SELECT 
    STORENUM.FD_FACILITY_ID AS "STORE_NUM",
    DRUG.DRUG_NDC AS "NDC_WO",
    PURCHPLANITEM.OVERRIDE_MIN_QTY AS "MIN_QTY_OVERRIDE",
    PURCHPLANITEM.OVERRIDE_MAX_QTY AS "MAX_QTY_OVERRIDE",
    PURCHPLANITEM.PURCHASE_PLAN_NAME AS "PURCHASE_PLAN",
    TO_NUMBER(TO_CHAR(UPDATEDATE.CAL_DATE::DATE,'YYYYMMDD')) AS "LAST_UPDATED"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PURCHASING_PLAN_ITEM PURCHPLANITEM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM UPDATEDATE
        ON UPDATEDATE.DATE_KEY = PURCHPLANITEM.REORDER_PARAM_UPDATE_DATE_KEY
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY STORENUM
        ON PURCHPLANITEM.FD_FACILITY_KEY = STORENUM.FD_FACILITY_KEY
       AND STORENUM.FACILITY_STATUS_NUM = 1
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
        ON PURCHPLANITEM.DRUG_KEY = DRUG.DRUG_KEY
WHERE PURCHPLANITEM.EFF_END_DATE = TO_DATE('12312999','MMDDYYYY')
  AND PURCHPLANITEM.OVERRIDE_MIN_QTY > 0
  AND PURCHPLANITEM.IS_ACTIVE = 'Y'
ORDER BY 1, 2