SELECT *
  FROM ( SELECT DISTINCT FF.RX_NUMBER AS RXNUMBER
              , DD.CAL_DATE AS SOLDDATE
              , FAC.FD_FACILITY_ID AS FACILITYID
              , PAT.PD_LAST_NAME AS PATIENTLASTNAME
              , PAT.PD_FIRST_NAME AS PATIENTFIRSTNAME
              , FF.REFILL_NUM AS REFILLNUMBER
              , PRD.PRD_NAME AS PRODUCTNAME
              , FF.QTY_DISPENSED AS QUANTITY
              , FF.DAYS_SUPPLY AS DAYSSUPPLY
              , FF.TOTAL_REFILLS_REMAINING AS TOTALREFILLSREMAINING
              , D.DRUG_NDC AS DRUGNDC
              , TPP2.TPD_CARDHOLDER_ID AS CARDHOLDERORPATIENTID
              , TP.TPLD_PLAN_CODE AS PLANCODE
              , SF.SHIPMENT_ADDRESS1 AS SHIPADDRESS1
              , SF.SHIPMENT_ADDRESS2 AS SHIPADDRESS2
              , SF.SHIPMENT_CITY AS SHIPCITY
              , SF.SHIPMENT_STATE AS SHIPSTATE
              , SF.SHIPMENT_ZIPCODE AS SHIPZIPCODE
              , PAT.PD_BIRTH_DATE AS PATIENTDATEOFBIRTH
              , TDS.HOUR_MIN_SEC_TXT AS SOLDTIME
	          , DA.CAL_DATE AS DATEOFSERVICE
	          , TPP2.TPD_PERSON_CODE AS PERSONCODE
	          , FF.RX_FILL_SEQ AS RXFILLSEQUENCE
	          , DW.CAL_DATE AS WRITTENDATE
              , NVL(PRE.PRS_FIRST_NAME, PRE.PRS_ESV_FIRST_NAME) AS PRESCRIBERFIRSTNAME
              , NVL(PRE.PRS_LAST_NAME, PRE.PRS_ESV_LAST_NAME) AS PRESCRIBERLASTNAME
              , PI1.PID_PRESCIBER_ID AS PRESCRIBERNPI
              , PI2.PID_PRESCIBER_ID AS PRESCRIBERDEA
              , PRA.PADR_ADDRESS1 AS PRESCRIBERADDRESS1
              , PRA.PADR_ADDRESS2 AS PRESCRIBERADDRESS2
              , PRA.PADR_CITY AS PRESCRIBERCITY
              , PRA.PADR_STATE_CODE AS PRESCRIBERSTATE
              , PRA.PADR_ZIPCODE AS PRESCRIBERZIP
              , NVL(PRP.PRSP_AREA_CODE || PRP.PRSP_PRESCRIBER_PHONE_NUMBER, '5555555555') AS PRESCRIBERPHONE
              , PAT.PD_PATIENT_NUM AS PATIENTNUM
	          , FF.PATIENT_PRICE_PAID AS PATIENTPRICEPAID
              , CST.COURIER_NAME AS COURIERNAME
              , SF.TRACKING_NUMBER AS TRACKINGNUMBER
              , FF.TOTAL_REFILLS_ALLOWED AS TOTALREFILLSALLOWED
              , FF.FACILITY_ORDER_NUMBER AS ORDERNUMBER
              , PATG.GROUP_NAME AS PATIENTGROUPNAME
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PRP.PADR_KEY ORDER BY PRP.PRSP_STATUS, PRP.PRSP_SOURCE_CODE, PRP.H_LEVEL DESC, ROW_NUMBER() OVER (ORDER BY PRP.PRSP_STATUS)) AS PRESCRIBERPHONERANK
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PI1.PRS_PRESCRIBER_KEY ORDER BY PI1.H_LEVEL DESC, ROW_NUMBER() OVER (ORDER BY PI1.H_LEVEL)) AS PRESCRIBERNPIRANK
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PI2.PRS_PRESCRIBER_KEY ORDER BY PI2.H_LEVEL DESC, ROW_NUMBER() OVER (ORDER BY PI2.H_LEVEL)) AS PRESCRIBERDEARANK
              , RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, TPP2.TPD_TP_PLAN_NUM ORDER BY TPP2.H_LEVEL DESC, ROW_NUMBER() OVER (ORDER BY TPP2.H_LEVEL)) AS TPPATIENTRANK
           FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD ON (D.DRUG_NUM = PRD.PRD_DRUG_NUM AND PRD.PRD_DEACTIVATE_DATE IS NULL)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_GROUP PG ON (PRD.PRD_PRODUCT_NUM = PG.PRODUCT_NUM AND PG.MEMBER_STATUS = 'ACTIVE' AND PG.GROUP_NAME = 'ASTUTE')
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF ON (PRD.PRD_PRODUCT_KEY = FF.DISPENSED_PRD_PRODUCT_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DD ON (FF.SOLD_DATE_KEY = DD.DATE_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM TDS ON (FF.SOLD_TIME_KEY = TDS.TIME_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PAT ON (FF.PD_PATIENT_KEY = PAT.PD_PATIENT_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC ON (FF.FD_FACILITY_KEY = FAC.FD_FACILITY_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DA ON (FF.ADJ_DATE_OF_SERVICE_KEY = DA.DATE_KEY)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DW ON (FF.WRITTEN_DATE_KEY = DW.DATE_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPP ON (TPP.TPD_KEY = FF.TPD_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPP2 ON (FF.PD_PATIENT_KEY = TPP2.PD_PATIENT_KEY AND TPP.TPD_TP_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM 
                AND TPP2.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY') AND TPP2.TPD_IS_ACTIVE = 'Y')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TP ON (TP.TPLD_PLAN_NUM = TPP2.TPD_TP_PLAN_NUM)
           LEFT JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM I ON (I.RX_RECORD_NUM = FF.RX_RECORD_NUM AND I.RX_FILL_SEQ = FF.RX_FILL_SEQ AND I.ORDER_NUM = FF.ORDER_NUM 
                AND I.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY'))
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT SF ON (SF.ORDER_NUM = I.ORDER_NUM)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRE ON (FF.PRS_PRESCRIBER_KEY = PRE.PRS_PRESCRIBER_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ADDRESS PRA ON (PRA.PADR_KEY = FF.PADR_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_PHONE PRP ON (PRP.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PRP.PADR_KEY = FF.PADR_KEY AND PRP.PRSP_PHONE_ADDRESS_TYPE = 'PRIM' 
                AND PRP.PRSP_STATUS = 'A')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ID_TYPE PT1 ON (PT1.PIT_CODE = '01' AND PT1.PIT_ID_DESCRIPTION = 'NATIONAL PROVIDER IDENTIFIER (NPI)')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PI1 ON (PI1.PIT_KEY = PT1.PIT_KEY AND PI1.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PI1.PID_STATUS = 'A')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ID_TYPE PT2 ON PT2.PIT_CODE = '12' AND PT2.PIT_ID_DESCRIPTION = 'DRUG ENFORCEMENT ADMINISTRATION (DEA) NUMBER' 
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PI2 ON (PI2.PIT_KEY = PT2.PIT_KEY AND PI2.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY AND PI2.PID_STATUS = 'A')
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COURIER_SHIPMENT_TYPE CST ON (SF.COURIER_SHIPMENT_KEY = CST.COURIER_SHIPMENT_KEY)
           LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_GROUP PATG ON (PAT.PD_PATIENT_NUM = PATG.PD_PATIENT_KEY AND PATG.MEMBER_STATUS = 'ACTIVE' AND PATG.GROUP_NAME = 'JPAP')
          WHERE NVL(FF.IS_BAR, 'N') = 'N'
            AND FF.CANCEL_DATE_KEY = 0
            AND DD.CAL_DATE BETWEEN :STARTDATE AND :ENDDATE
)
 WHERE PRESCRIBERPHONERANK = 1
   AND PRESCRIBERNPIRANK = 1
   AND PRESCRIBERDEARANK = 1
   AND TPPATIENTRANK = 1
 ORDER BY SOLDDATE, SOLDTIME