SELECT
     --KEYS:
     FILL_STATE_CHG_TS AS CLAIMDATE
    ,FD_FACILITY_ID AS ORIGINATINGSTOREID
    ,RX_NUMBER AS PRESCRIPTIONNUMBER
    ,REFILL_NUM AS REFILLNUMBER               
    ,SPLIT_BILLING_CODE AS ERXSPLITFILLNUMBER
    ,FILL_STATE_CODE AS FILLFACTFILLSTATECODE
                
     --HIPAA FIELDS:
    ,ADDRESS1 AS CARDHOLDERADDRESS1
    ,ADDRESS2 AS CARDHOLDERADDRESS2
    ,CITY AS CARDHOLDERCITY
    ,BIRTH_DATE AS CARDHOLDERDATEOFBIRTH
    ,PA_FIRST_NAME AS CARDHOLDERFIRSTNAME
    ,PA_LAST_NAME AS CARDHOLDERLASTNAME
    ,PA_MIDDLE_NAME AS CARDHOLDERMIDDLEINITIAL
    ,PHONE_NUM AS CARDHOLDERPHONENUMBER
    ,BIRTH_DATE AS OTHERPAYERDATEOFBIRTH
    ,PA_FIRST_NAME AS OTHERPAYERFIRSTNAME
    ,PA_LAST_NAME AS OTHERPAYERLASTNAME
    ,PA_MIDDLE_NAME AS OTHERPAYERMIDDLEINITIAL
    ,ADDRESS1 AS PATIENTADDRESS1
    ,ADDRESS2 AS PATIENTADDRESS2
    ,CITY AS PATIENTCITY
    ,BIRTH_DATE AS PATIENTDATEOFBIRTH
    ,P_FIRST_NAME AS PATIENTFIRSTNAME
    ,P_LAST_NAME AS PATIENTLASTNAME
    ,P_MIDDLE_NAME AS PATIENTMIDDLEINITIAL
    ,PHONE_NUM AS PATIENTPHONENUMBER
    ,PADR_ADDRESS1 AS PRESCRIBERADDRESS1
    ,PADR_ADDRESS2 AS PRESCRIBERADDRESS2
    ,PADR_CITY AS PRESCRIBERCITY
    ,PRESCRIBER_ID_DEA AS PRESCRIBERDEA 
    ,PRS_FIRST_NAME AS PRESCRIBERFIRSTNAME
    ,PRS_PRESCRIBER_KEY AS PRESCRIBERID
    ,PRS_LAST_NAME AS PRESCRIBERLASTNAME
            
FROM WEGMANS.THIRD_PARTY_CLAIMS_STAGING
WHERE RUN_DATE = :RUNDATE