SELECT
     IAF.DATE_KEY
    ,FAC.FD_FACILITY_ID AS "STORE_NUM"
    ,D.DRUG_LABEL_NAME
    ,D.DRUG_NDC
    ,IAF.ADJUSTMENT_QUANTITY
    ,IAF.ADJUSTMENT_UNIT_COST
    ,IAF.ADJUSTMENT_EXTENDED_COST
    ,IAF.ADJUSTMENT_TYPE_CODE
    ,IAF.INVENTORY_ADJUSTMENT_NUM
    ,R.ADJUSTMENT_REASON_CODE
    ,R.DESCRIPTION
    ,SU.SYS_USER_FNAME
    ,SU.SYS_USER_LNAME
    ,TO_NUMBER(SU.SYS_USER_KEY) AS "SYS_USER_KEY"
    ,TRIM(LPAD(SUBSTR(DRUG_NDC::TEXT, 1, 5), 5, '0') || '-' ||
		  LPAD(SUBSTR(DRUG_NDC::TEXT, 6, 4), 4, '0') || '-' ||
		  LPAD(SUBSTR(DRUG_NDC::TEXT, 10, 2), 2, '0')) AS "NDC"
    ,IAF.REFERENCE_NUMBER AS "REF_NUM"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.INV_ADJUSTMENT_FACT IAF
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
         ON FAC.FD_FACILITY_KEY = IAF.FD_FACILITY_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SU
         ON SU.SYS_USER_KEY = IAF.SYS_USER_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
         ON D.DRUG_KEY = IAF.DRUG_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.INV_ADJUSTMENT_REASON_TYPE R
         ON R.ADJUSTMENT_REASON_KEY = IAF.ADJUSTMENT_REASON_KEY
WHERE IAF.DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))