SELECT *
FROM (
	SELECT PATIENT.PD_FIRST_NAME AS STR_FIRST_NAME
			,PATIENT.PD_MIDDLE_NAME AS STR_MIDDLE_NAME
			,PATIENT.PD_LAST_NAME AS STR_LAST_NAME
			,TO_CHAR(PATIENT.PD_BIRTH_DATE::DATE,'YYYY-MM-DD HH24:MI:SS') AS DT_BIRTH_DATE
			,PTDEM.GENDER AS C_GENDER
			,PTADDR.PAD_ADDRESS1 AS STR_ADDRESS_ONE
			,PTADDR.PAD_ADDRESS2 AS STR_ADDRESS_TWO
			,PTADDR.PAD_CITY AS STR_CITY
			,PTADDR.PAD_STATE AS STR_STATE
			,PTADDR.PAD_ZIP AS STR_ZIP
			,DRUG.DRUG_LABEL_NAME AS STR_PRODUCT_NAME
			,DRUG.DRUG_NDC AS STR_PRODUCT_NDC
			,(CASE WHEN SUBSTR(TO_CHAR(FILLFACT.QTY_DISPENSED),1,1) = '.'
				   THEN '0' || TO_CHAR(FILLFACT.QTY_DISPENSED)
				   ELSE TO_CHAR(FILLFACT.QTY_DISPENSED)
			  END) AS DEC_DISPENSED_QTY
			,PRODUCT.PRD_IS_GENERIC AS C_GENERIC_IDENTIFIER
			,SYSUSER.SYS_USER_FNAME AS STR_VERIFIED_RPH_FIRST
			,SYSUSER.SYS_USER_LNAME AS STR_VERIFIED_RPH_LAST
			,FAC.FD_FACILITY_ID AS STR_FACILITY_ID
			,FILLFACT.RX_NUMBER AS STR_RX_NUMBER
			,DRUG.DRUG_DOSAGE_FORM AS STR_DOSAGE_FORM
			,DRUG.DRUG_STRENGTH AS STR_STRENGTH
			,TO_CHAR(TO_DATE(TO_CHAR(FILLFACT.SOLD_DATE_KEY),'YYYYMMDD'),'YYYY-MM-DD HH24:MI:SS') AS DT_SOLD_DATE
			,DECODE(FILLFACT.CANCEL_DATE_KEY,0,NULL,TO_CHAR(FILLFACT.CANCEL_DATE_KEY)) AS DT_CANCELLED_DATE
			,DECODE(FILLFACT.CANCEL_DATE_KEY,0,'A','D') AS C_ACTION_CODE
			,FAC.FD_DEA_NUMBER AS STR_DEA
			,FACID.FD_VALUE AS STR_NPI
			,PATIENT.PD_PATIENT_NUM AS DEC_INTERNALPTNUM
			,FPF.LOT_NUMBER AS LOT_NUMBER
			,TO_CHAR(FPF.EXP_DATE,'YYYY-MM-DD HH24:MI:SS') AS EXP_DATE
			,PATIENT.PATIENT_EMAIL AS STR_PATIENTEMAIL
			,TO_CHAR(TO_DATE(TO_CHAR(FILLFACT.SOLD_DATE_KEY),'YYYYMMDD'),'YYYY-MM-DD HH24:MI:SS') AS VIS_PRESENTED_DATE
			,FILLFACT.ADMINISTERING_SITE AS ADMINISTRATION_SITE

			--CONSENT IS REQUIRED IN NJ, AND TESTED IN PRODUCTION THROUGH TEST STORES.
			,(CASE WHEN FAC.FD_STATE_CODE = 'NJ' THEN 'Y' --THE DEFAULT VALUE IS 'Y' MEANING DO SHARE DATA (NOT HIDE).
				   ELSE NULL                              --OTHER STATES ARE NOT USING THIS FLAG.
			  END) AS PROTECTION_INDICATOR

			,NULL AS RECIP_RACE_1
			,NULL AS RECIP_ETHNICITY
			,FILLFACT.VFC_STATUS AS VFC_STATUS
			,NULL AS NY_PRIORITY_GROUP
			,REGEXP_REPLACE(PP.PATP_AREA_CODE || PP.PATP_PHONE_NUMBER,'[^0-9]','') AS PHONE_NUMBER
			,RANK() OVER (PARTITION BY FILLFACT.FILL_FACT_KEY, PP.PD_PATIENT_KEY
								  ORDER BY 
								      (CASE WHEN PP.PATP_PHONE_USAGE = '1' THEN NULL ELSE PP.PATP_PHONE_USAGE END) NULLS FIRST
									 ,ROW_NUMBER() OVER (ORDER BY PP.PATP_PHONE_USAGE)
					 ) AS PATIENTPHONERANK
			,FILLFACT.REFILL_NUM
			,ACTIVE_PRESCRIBERS.NPI AS PRESCRIBED_BY_ID

	FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FILLFACT

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES
				ON PRES.PRS_PRESCRIBER_KEY = FILLFACT.PRS_PRESCRIBER_KEY
       
				LEFT OUTER JOIN
				(SELECT PID_NPI.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
					PID_NPI.PID_ID_TEXT AS NPI,
					PID_NPI.USE_FOR_BILLING AS USE_FOR_BILLING,
					PID_NPI.PID_EXPIRATION_DATE AS EXPIRE_DATE    
				FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_NPI
				WHERE PID_NPI.PID_STATUS = 'A'
				AND PID_NPI.PIT_KEY = 509    
				ORDER BY PID_NPI.PID_EXPIRATION_DATE DESC NULLS LAST) ACTIVE_PRESCRIBERS
				ON PRES.PRS_PRESCRIBER_KEY = ACTIVE_PRESCRIBERS.PRESCRIBER_KEY

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
				ON FAC.FD_FACILITY_KEY = FILLFACT.FD_FACILITY_KEY

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FACID
				ON FACID.FD_FACILITY_KEY = FAC.FD_FACILITY_NUM
				AND FACID.FD_TYPE = 'F08' --NATIONAL PROVIDER IDENTIFIER

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PATIENT
				ON PATIENT.PD_PATIENT_KEY = FILLFACT.PD_PATIENT_KEY

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_DEMOGRAPHIC PTDEM
				ON PTDEM.PATIENT_DEMOGRAPHIC_KEY = FILLFACT.PATIENT_DEMOGRAPHIC_KEY

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS PTADDR
				ON PTADDR.PD_PATIENT_KEY = FILLFACT.PD_PATIENT_KEY
				AND PTADDR.H_LEVEL = (SELECT MIN(H_LEVEL) 
										FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS 
										WHERE PD_PATIENT_KEY=FILLFACT.PD_PATIENT_KEY 
										AND PAD_END_DATE = TO_DATE('2999-12-31', 'YYYY-MM-DD')
										AND PAD_ADDRESS_USAGE = 1)
										
				LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_PHONE PP
				ON PP.PD_PATIENT_KEY = FILLFACT.PD_PATIENT_KEY
				AND PP.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')	
				AND PP.PATP_USAGE = '1'  -- HOME1			
									
				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRODUCT
				ON PRODUCT.PRD_PRODUCT_KEY = FILLFACT.DISPENSED_PRD_PRODUCT_KEY                

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
				ON DRUG.DRUG_KEY = FILLFACT.DISPENSED_DRUG_KEY 

				INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SYSUSER
				ON SYSUSER.SYS_USER_KEY = FILLFACT.VERIFY_RPH_SYS_USER_KEY 

				INNER JOIN (SELECT FD_FACILITY_KEY, RX_NUMBER, SOLD_DATE_KEY, CANCEL_DATE_KEY, MAX(DISPENSED_ITEM_LOT_NUMBER) LOT_NUMBER, MAX(DISPENSED_ITEM_EXPIRATION_DATE) EXP_DATE 
							FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_PRICING_FACT 
							WHERE PARTITION_DATE BETWEEN (:RUNDATE - 60) AND (:RUNDATE + 1)
							GROUP BY FD_FACILITY_KEY, RX_NUMBER, SOLD_DATE_KEY, CANCEL_DATE_KEY) FPF
					ON FPF.FD_FACILITY_KEY = FAC.FD_FACILITY_KEY
					AND FPF.RX_NUMBER = FILLFACT.RX_NUMBER 
					AND FPF.SOLD_DATE_KEY = FILLFACT.SOLD_DATE_KEY
					AND FPF.CANCEL_DATE_KEY = FILLFACT.CANCEL_DATE_KEY

	WHERE FILLFACT.PARTITION_DATE BETWEEN (:RUNDATE - 60) AND (:RUNDATE + 1)
	AND (   --SOLD AND NOT CANCELLED ON DTSOLD DATE
		(FILLFACT.SOLD_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1), 'YYYYMMDD')) 
			AND FILLFACT.CANCEL_DATE_KEY = 0) 
		OR   --NOT SOLD ON DTSOLD DATE BUT WAS SOLD WITHIN PRIOR TWO WEEKS AND CANCELLED ON DTSOLD DATE
		(FILLFACT.CANCEL_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1), 'YYYYMMDD')) 
			AND FILLFACT.SOLD_DATE_KEY BETWEEN TO_NUMBER(TO_CHAR((:RUNDATE - 14), 'YYYYMMDD')) 
											AND TO_NUMBER(TO_CHAR((:RUNDATE - 2), 'YYYYMMDD')))
		)

	--AND FAC.FD_FACILITY_ID IN (SELECT FD_FACILITY_ID FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY WHERE FD_STATE_CODE IN ('NY','MA','MD','VA','PA','NJ') AND FD_IS_ACTIVE = 'Y' AND FD_FACILITY_ID < '200') 
	AND (FAC.FD_IS_PPI_ENABLED = 'Y' --LICENSED STORES
		 OR
		 FAC.FD_FACILITY_ID IN ('275','299') --ALLOW TESTING IN PRODUCTION THROUGH TEST STORES.
		)
	AND DRUG.DRUG_NDC IN 

		(SELECT D.DRUG_NDC
			FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D 
			INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT P ON (D.DRUG_NUM = P.PRD_DRUG_NUM)
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_IDENTIFIER PI ON (P.PRD_PRODUCT_KEY = PI.PRD_PRODUCT_KEY)
			WHERE --P.PRD_DEACTIVATE_DATE IS NULL
				  (P.PRD_DEACTIVATE_DATE IS NULL OR P.PRD_DEACTIVATE_DATE > (:RUNDATE + 1))
			AND (D.DRUG_OBSOLETE_DATE > (:RUNDATE + 1) OR D.DRUG_OBSOLETE_DATE IS NULL) 
			AND (
				(D.DRUG_GC3 IN (
				 'COVID-19 VACCINES'
				,'ENTERIC VIRUS VACCINES'
				,'GRAM NEGATIVE COCCI VACCINES'
				,'GRAM POSITIVE COCCI VACCINES'
				,'INFLUENZA VIRUS VACCINES'
				,'NEUROTOXIC VIRUS VACCINES'
				,'TOXIN-PRODUCING BACILLI VACCINES/TOXOIDS'
				,'VACCINE/TOXOID PREPARATIONS,COMBINATIONS'
				,'GRAM (-) BACILLI (NON-ENTERIC) VACCINES'
				,'VIRAL/TUMORIGENIC VACCINES'
				,'ANTINEOPLASTICS,MISCELLANEOUS'))
				OR
				(PI.IDENTIFIER = 'VAX' AND PI.IS_ACTIVE='Y')
				)
			AND DRUG_ROUTE <> 'ORAL'
		)
	AND NVL(FILLFACT.IS_BAR, 'N') = 'N'
	-- 5/7/18 ADDING AN EXCLUSION FOR NY STATE - WE DO NOT WANT TO REPORT ON IMMUNIZATIONS THAT ARE DISPENSED TO BE ADMINISTERED AT A DOCTOR'S OFFICE
	--AND ( NOT (FAC.FD_STATE_CODE, DRUG.DRUG_GC3) IN (
	--		('NY', 'ENTERIC VIRUS VACCINES'),
	--		('NY', 'NEUROTOXIC VIRUS VACCINES'),
	--		('NY', 'TOXIN-PRODUCING BACILLI VACCINES/TOXOIDS'),
	--		('NY', 'GRAM (-) BACILLI (NON-ENTERIC) VACCINES'),
	--		('NY', 'VIRAL/TUMORIGENIC VACCINES'),
	--		('NY', 'ANTINEOPLASTICS,MISCELLANEOUS') )
	--	OR ( FAC.FD_STATE_CODE = 'NY' AND DRUG.DRUG_GC3 = 'VIRAL/TUMORIGENIC VACCINES' AND UPPER(DRUG.DRUG_GNN) LIKE '%ZOSTER%' )
	--	OR ( FAC.FD_STATE_CODE = 'NY' AND DRUG.DRUG_GC3 IS NULL )
	--	)
)
WHERE PATIENTPHONERANK = 1