WITH FILTER_PRESCRIBER AS (
    SELECT DISTINCT REGEXP_SUBSTR(:PRESCRIBERNPICSV,'[^,]+', 1, LEVEL) AS PRESCRIBER_NPI 
    CONNECT BY LEVEL <= REGEXP_COUNT(:PRESCRIBERNPICSV, '[^,]+')
), FILTER_NDC AS (
    SELECT DISTINCT DRUG_NDC
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG 
    WHERE DRUG_NDC IN (
        SELECT REGEXP_SUBSTR(:NDCCSV,'[^,]+', 1, LEVEL) AS NDC 
        CONNECT BY LEVEL <= REGEXP_COUNT(:NDCCSV, '[^,]+')
    )
)
SELECT 
     REPORTINGNAME --"NAME OF PERSON PROVIDING REPORTS"
    ,REPORTINGPHONE --"TELEPHONE NUMBER OF PERSON PROVIDING REPORT"
    ,REPORTINGEMAIL --"EMAIL OF PERSON PROVIDING DIRECTORY INFORMATION"
    ,PHARMACYNAME --"PHARMACY NAME (HOW PHARMACY IS GENERALLY KNOWN IN THE COMMUNITY)"
    ,PHARMACYNBR --"STORE NUMBER"
	,ZIPCODE --"ZIPCODE"
    ,PHARMACYNPI --"PHARMACY NPI"
    ,PRESCRIBERNPI --"DISPENSING ENCOUNTER: LINKED NPI (PROVIDER)"
    ,DRUGNAME --"PLEASE INCLUDE EACH  DISPENSING ENCOUNTER: FORMULATION NAME"
    ,DRUGNDC --"DISPENSING PER ENCOUNTER: FORMULATION NDC"
    ,TO_CHAR(SUM(DRUGQTY)) AS DRUGQTY --"DISPENSING ENCOUNTER: COUNT OF NDC DISPENSED PER ENCOUNTER"
FROM (
		SELECT 
			 :REPORTINGNAME AS REPORTINGNAME
			,:REPORTINGPHONE AS REPORTINGPHONE
			,:REPORTINGEMAIL AS REPORTINGEMAIL
			,:REPORTINGNAME AS PHARMACYNAME
			,FAC.FD_FACILITY_ID AS PHARMACYNBR
			,FAC.FD_ZIPCODE AS ZIPCODE
			,FAC_ID.FD_VALUE AS PHARMACYNPI
			,FF.PRESCRIBER_ID_NPI AS PRESCRIBERNPI
			,D.DRUG_LABEL_NAME AS DRUGNAME
			,D.DRUG_NDC AS DRUGNDC
			,(CASE WHEN FF.FILL_STATE_CODE = '14' THEN 1   --SOLD=14
			       WHEN FF.FILL_STATE_CODE = '16' THEN -1  --DECLINESOLD/REFUND=16
				   ELSE 0
			  END) AS DRUGQTY
		FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT FF
			 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
				 ON FAC.FD_FACILITY_NUM = FF.FACILITY_NUM
				AND FAC.FD_IS_ACTIVE = 'Y'
			 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FAC_ID
				 ON FAC_ID.FD_FACILITY_KEY = FF.FACILITY_NUM
				AND FAC_ID.FD_TYPE = 'F08'
			 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES
				 ON PRES.PRS_PRESCRIBER_NUM = FF.PRESCRIBER_NUM
			 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
				 ON D.DRUG_NUM = FF.DISPENSED_DRUG_NUM
			 INNER JOIN FILTER_PRESCRIBER FP
				 ON FP.PRESCRIBER_NPI = FF.PRESCRIBER_ID_NPI
			 INNER JOIN FILTER_NDC FN
				 ON FN.DRUG_NDC = D.DRUG_NDC
		WHERE FF.FILL_STATE_CHG_TS BETWEEN :STARTDATE AND :ENDDATE
		  AND FF.FILL_STATE_CODE IN ('14','16') --SOLD=14, DECLINESOLD/REFUND=16
		  AND FF.IS_SAME_DAY_REVERSAL = 'N' 
     )
GROUP BY
     REPORTINGNAME
    ,REPORTINGPHONE
    ,REPORTINGEMAIL
    ,PHARMACYNAME
    ,PHARMACYNBR
	,ZIPCODE
    ,PHARMACYNPI
    ,PRESCRIBERNPI
    ,DRUGNAME
    ,DRUGNDC
ORDER BY 5, 8, 9