SELECT
     CANCELLEDDATE
    ,COMPLETIONDATE
    ,DATEOFSERVICE
    ,FACILITYTABLEFACILITYNUMBER
    ,FILLFACTTABLEFACILITYKEY
    ,FILLFACTTABLEFILLSEQUENCE
    ,FILLFACTTABLEKEY
    ,FILLFACTTABLEPARTITIONDATE
    ,FILLFACTTABLEPATIENTKEY
    ,FILLFACTTABLEPRIMARYPLANKEY
    ,FILLFACTTABLERECORDNUMBER
    ,FILLFACTTABLETHIRDPARTYPLANKEY
    ,HEALTHCARDDESIGNATION
    ,ISBILLEDAFTERRETURN
    ,ITEMTABLEORDERNUMBER
    ,ITEMTABLEPAYMENTGROUPNUMBER
    ,ITEMTABLEPRODUCTNUMBER
    ,LASTFOUR
    ,ORDERNUMBER
    ,PARTIALFILLSEQUENCE
    ,PATIENTPRICEPAID
    ,PAYMENTAMOUNT
    ,PAYMENTNUMBER
    ,PAYMENTTABLEACCOUNTNUMBER
    ,PAYMENTTABLEPAYMENTTYPENUMBER
    ,PAYMENTTABLEREVERSALNUMBER
    ,PAYMENTTYPENAME
    ,PRESCRIPTIONNUMBER
    ,PRODUCTTABLEDRUGNUMBER
    ,REFILLNUMBER
    ,REVERSALPAYMENTAMOUNT
    ,SHIPHANDLEFEE
    ,SOLDDATEKEY
    ,SOLDDATESECONDS
    ,STORENATIONALDRUGPROGRAMSID
    ,STORENUMBER
    ,STORENATIONALPROVIDERID
    ,TARGETCENTRALFILLFACILITY
    ,TOTALPRICEPAID
    ,TOTALUSUALANDCUSTOMARY
    ,TRACKINGNUMBER
    ,DELIVERYMETHOD
    ,COURIERNAME
    ,SHIPPINGMETHOD
    ,COURIERSHIPCHARGE
    ,PATIENTNUM
    ,PATIENTADDRESSKEY
    ,PATIENTCITY
    ,PATIENTSTATE
    ,PATIENTZIP
    ,CARDTYPE
    ,FILLSTATECODE
    ,NULL AS ISREVERSALFORCOB
    ,LATESTFILLSTATUSDESC
    ,PATIENTPRICEPAIDFORORDER
FROM (
    SELECT
         CANCELLED_DATE                    CANCELLEDDATE
        ,COMPLETION_DATE                   COMPLETIONDATE
        ,DATE_OF_SERVICE                   DATEOFSERVICE
        ,FD_FACILITY_NUM                   FACILITYTABLEFACILITYNUMBER
        ,FD_FACILITY_KEY                   FILLFACTTABLEFACILITYKEY
        ,RX_FILL_SEQ                       FILLFACTTABLEFILLSEQUENCE
        ,FILL_FACT_KEY                     FILLFACTTABLEKEY
        ,PARTITION_DATE                    FILLFACTTABLEPARTITIONDATE
        ,PD_PATIENT_KEY                    FILLFACTTABLEPATIENTKEY
        ,PRIMARY_TPLD_PLAN_KEY             FILLFACTTABLEPRIMARYPLANKEY
        ,RX_RECORD_NUM                     FILLFACTTABLERECORDNUMBER
        ,TPD_KEY                           FILLFACTTABLETHIRDPARTYPLANKEY
        ,HEALTH_CARD_DESIGNATION           HEALTHCARDDESIGNATION
        ,IS_BAR                            ISBILLEDAFTERRETURN
        ,ORDER_NUM                         ITEMTABLEORDERNUMBER
        ,PAYMENT_GROUP_NUM                 ITEMTABLEPAYMENTGROUPNUMBER
        ,PRODUCT_NUM                       ITEMTABLEPRODUCTNUMBER
        ,LAST4_PAN                         LASTFOUR
        ,FACILITY_ORDER_NUMBER             ORDERNUMBER
        ,PARTIAL_FILL_SEQ                  PARTIALFILLSEQUENCE
        ,PATIENT_PRICE_PAID                PATIENTPRICEPAID
        ,PAYMENT_AMOUNT                    PAYMENTAMOUNT
        ,PAYMENT_NUM                       PAYMENTNUMBER
        ,ACCOUNT_MEMBER_CREDIT_CARD_NUM    PAYMENTTABLEACCOUNTNUMBER
        ,PAYMENT_TYPE_NUM                  PAYMENTTABLEPAYMENTTYPENUMBER
        ,REVERSAL_PAYMENT_NUM              PAYMENTTABLEREVERSALNUMBER
        ,PAYMENT_TYPE_NAME                 PAYMENTTYPENAME
        ,RX_NUMBER                         PRESCRIPTIONNUMBER
        ,PRD_DRUG_NUM                      PRODUCTTABLEDRUGNUMBER
        ,REFILL_NUM                        REFILLNUMBER
        ,REVERSAL_PAYMENT_AMOUNT           REVERSALPAYMENTAMOUNT
        ,SHIP_HANDLE_FEE                   SHIPHANDLEFEE
        ,SOLD_DATE_KEY                     SOLDDATEKEY
        ,SOLD_DATE_SECONDS                 SOLDDATESECONDS
        ,FD_NCPDP_PROVIDER_ID              STORENATIONALDRUGPROGRAMSID
        ,FD_FACILITY_ID                    STORENUMBER
        ,FD_VALUE                          STORENATIONALPROVIDERID
        ,TARGET_CF_FACILITY_NUM            TARGETCENTRALFILLFACILITY
        ,TOTAL_PRICE_PAID                  TOTALPRICEPAID
        ,TOTAL_UNC                         TOTALUSUALANDCUSTOMARY
        ,TRACKING_NUMBER                   TRACKINGNUMBER
        ,DM_DELIVERY_METHOD_DESC           DELIVERYMETHOD
        ,COURIER_NAME                      COURIERNAME
        ,SHIPPING_METHOD_DESC              SHIPPINGMETHOD
        ,COURIER_SHIP_CHARGE               COURIERSHIPCHARGE
        ,PD_PATIENT_NUM                    PATIENTNUM
        ,PAD_KEY                           PATIENTADDRESSKEY
        ,PAD_CITY                          PATIENTCITY
        ,PAD_STATE                         PATIENTSTATE
        ,PAD_ZIP                           PATIENTZIP
        ,CARD_TYPE_DESC                    CARDTYPE
        ,FILL_STATE_CODE                   FILLSTATECODE
        ,LATESTFILLSTATUSDESC
        ,SUM((CASE WHEN ORDER_RX_RANK = 1 THEN PATIENT_PRICE_PAID ELSE 0 END)) OVER 
            (PARTITION BY FACILITY_ORDER_NUMBER, PAYMENT_NUM)
            AS PATIENTPRICEPAIDFORORDER
        ,(CASE WHEN LATESTFILLSTATUSDESC = 'CANCELLED'
                    THEN RANK() OVER (PARTITION BY PARTITION_DATE, FACILITY_ORDER_NUMBER, PAYMENT_NUM, RX_NUMBER
                                      ORDER BY COMPLETION_DATE DESC, ROW_NUMBER() OVER (ORDER BY COMPLETION_DATE) DESC)
               ELSE 1 END) AS AVOID_DUPLICATES_RANK
    FROM (
          SELECT 
             DW__FACILITY.FD_FACILITY_ID --STORE NUMBER
            ,DW__FACILITY.FD_NCPDP_PROVIDER_ID --STORE NCPDP
            ,DW__FACILITY_ID.FD_VALUE --STORE NPI
            ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.FILL_STATE_CHG_TS::DATE,'YYYYMMDD')) AS SOLD_DATE_KEY
            ,ROUND(((AUD__FILL_FACT.FILL_STATE_CHG_TS - TRUNC(AUD__FILL_FACT.FILL_STATE_CHG_TS, 'DAY')) * 86400),0) AS SOLD_DATE_SECONDS
            ,AUD__PAYMENT.CANCELLED_DATE
            ,AUD__PAYMENT.COMPLETION_DATE
            ,AUD__ORDER_RECORD.FACILITY_ORDER_NUMBER
            ,AUD__PAYMENT.PAYMENT_AMOUNT
            ,AUD__PAYMENTREV.PAYMENT_AMOUNT AS REVERSAL_PAYMENT_AMOUNT --NEED TO RENAME DUE TO DUPLICATE FIELD NAME
            ,AUD__FILL_FACT.FINAL_PRICE AS TOTAL_PRICE_PAID
            ,AUD__FILL_FACT.PATIENT_PAY_AMOUNT AS PATIENT_PRICE_PAID
            ,AUD__FILL_FACT.TOTAL_UANDC AS TOTAL_UNC
            ,AUD__PAYMENT.PAYMENT_NUM
            ,AUD__PAYMENT.HEALTH_CARD_DESIGNATION
            ,DW__PAYMENT_TYPE.PAYMENT_TYPE_NAME
            ,AUD__ITEM.TARGET_CF_FACILITY_NUM
            ,AUD__ITEM.DATE_OF_SERVICE
            ,AUD__FILL_FACT.RX_NUMBER
            ,AUD__FILL_FACT.REFILL_NUM
            ,AUD__FILL_FACT.PARTIAL_FILL_SEQ
            ,DW__SHIPMENT_FACT.COURIER_SHIP_CHARGE
            ,DW__PATIENT_ADDRESS.PAD_CITY
            ,DW__PATIENT_ADDRESS.PAD_STATE
            ,DW__PATIENT_ADDRESS.PAD_ZIP
            ,AUD__CREDIT_CARD_TYPE.CARD_TYPE_DESC
            ,DW__DELIVERY_METHOD_TYPE.DM_DELIVERY_METHOD_DESC
            ,DW__COURIER_SHIPMENT_TYPE.COURIER_NAME
            ,DW__COURIER_SHIPMENT_TYPE.SHIPPING_METHOD_DESC
            ,DW__SHIPMENT_FACT.TRACKING_NUMBER
            ,DW__SHIPMENT_FACT.SHIP_HANDLE_FEE
            ,AUD__ACCOUNT_MEMBER_CC.LAST4_PAN
            ,NVL(AUD__FILL_FACT.IS_BAR,'N') AS IS_BAR
            ,AUD__FILL_FACT.FILL_STATE_CHG_TS AS PARTITION_DATE
            ,0 AS FILL_FACT_KEY
            ,DW__FACILITY.FD_FACILITY_KEY
            ,AUD__FILL_FACT.RX_FILL_SEQ
            ,AUD__FILL_FACT.RX_RECORD_NUM
            ,DW__FACILITY.FD_FACILITY_NUM
            ,AUD__ITEM.ORDER_NUM
            ,AUD__ITEM.PRODUCT_NUM
            ,AUD__ITEM.PAYMENT_GROUP_NUM
            ,AUD__PAYMENT.REVERSAL_PAYMENT_NUM
            ,AUD__PAYMENT.PAYMENT_TYPE_NUM
            ,AUD__PAYMENT.ACCOUNT_MEMBER_CREDIT_CARD_NUM
            ,AUD__FILL_FACT.DISPENSED_PROD_NUM AS PRD_DRUG_NUM
            ,DW__PATIENT_ADDRESS.PD_PATIENT_KEY
            ,DW__TP_PATIENT.TPD_KEY
            ,DW__TP_PLAN.TPLD_PLAN_KEY AS PRIMARY_TPLD_PLAN_KEY
            ,NVL(AUD__FILL_FACT.PATIENT_NUM,0) AS PD_PATIENT_NUM
            ,NVL(DW__SHIPMENT_FACT.PAD_KEY,0) AS PAD_KEY
            ,AUD__FILL_FACT.FILL_STATE_CODE
            ,AUD__FILL_FACT.FILL_STATE_CHG_TS
    
            ,(SELECT FS_FILL_STATUS_DESC
              FROM (SELECT
                        FST.FS_FILL_STATUS_DESC,
                        RANK() OVER (ORDER BY FWF.FWFS_DT_OUT DESC, ROW_NUMBER() OVER (ORDER BY COMPLETION_DATE) DESC) AS FILL_STATUS_RANK
                    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_WORKFLOW_FACT FWF
                         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_STATUS_TYPE FST
                            ON FST.FS_FILL_STATUS_KEY = FWF.FS_FILL_STATUS_KEY
                    WHERE FWF.FWFS_RX_RECORD_NUM = AUD__FILL_FACT.RX_RECORD_NUM
                      AND FWF.FWFS_RX_FILL_SEQ = AUD__FILL_FACT.RX_FILL_SEQ
                      AND FWF.FWFS_DT_OUT < :RUNDATE
                   )
              WHERE FILL_STATUS_RANK = 1
             ) AS LATESTFILLSTATUSDESC
    
            ,RANK() OVER (PARTITION BY
                               AUD__ORDER_RECORD.FACILITY_ORDER_NUMBER
                              ,AUD__FILL_FACT.RX_NUMBER
                              ,AUD__FILL_FACT.REFILL_NUM
                          ORDER BY
                               AUD__FILL_FACT.FILL_STATE_CHG_TS DESC
                              ,ROW_NUMBER() OVER (ORDER BY COMPLETION_DATE) DESC
                          ) AS ORDER_RX_RANK
        
        FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT AUD__FILL_FACT
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__FACILITY
            ON DW__FACILITY.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
           AND DW__FACILITY.FD_IS_PPI_ENABLED = 'Y'
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID DW__FACILITY_ID
            ON DW__FACILITY_ID.FD_FACILITY_KEY = DW__FACILITY.FD_FACILITY_NUM
           AND DW__FACILITY_ID.FD_TYPE = 'F08'
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DW__DRUG
            ON DW__DRUG.DRUG_NUM = AUD__FILL_FACT.DISPENSED_DRUG_NUM
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT DW__TP_PATIENT
            ON DW__TP_PATIENT.TPD_TP_PATIENT_NUM = AUD__FILL_FACT.TP_PATIENT_NUM
           AND DW__TP_PATIENT.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN DW__TP_PLAN
            ON DW__TP_PLAN.TPLD_PLAN_NUM = AUD__FILL_FACT.TP_PLAN_NUM
         LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM AUD__ITEM
            ON AUD__ITEM.RX_RECORD_NUM = AUD__FILL_FACT.RX_RECORD_NUM
           AND AUD__ITEM.RX_FILL_SEQ = AUD__FILL_FACT.RX_FILL_SEQ
           AND AUD__ITEM.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
           AND AUD__ITEM.H_TYPE != 'D'
         LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ORDER_RECORD AUD__ORDER_RECORD
             ON AUD__ORDER_RECORD.ORDER_NUM = AUD__ITEM.ORDER_NUM
            AND AUD__ORDER_RECORD.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT DW__PATIENT
             ON DW__PATIENT.PD_PATIENT_NUM = AUD__FILL_FACT.PATIENT_NUM
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT DW__SHIPMENT_FACT
             ON DW__SHIPMENT_FACT.ORDER_NUM = AUD__ITEM.ORDER_NUM
            AND DW__SHIPMENT_FACT.PD_PATIENT_KEY = DW__PATIENT.PD_PATIENT_KEY
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS DW__PATIENT_ADDRESS
            ON DW__PATIENT_ADDRESS.PAD_PATIENT_ADDRESS_KEY = DW__SHIPMENT_FACT.PAD_KEY
         INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT_GROUP_LIST AUD__PAYMENT_GROUP_LIST
            ON AUD__PAYMENT_GROUP_LIST.PAYMENT_GROUP_NUM = AUD__ITEM.PAYMENT_GROUP_NUM
           AND AUD__PAYMENT_GROUP_LIST.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')  
         INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT AUD__PAYMENT
            ON AUD__PAYMENT.PAYMENT_NUM = AUD__PAYMENT_GROUP_LIST.PAYMENT_NUM
           AND AUD__PAYMENT.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
         LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT AUD__PAYMENTREV
            ON AUD__PAYMENTREV.PAYMENT_NUM = AUD__PAYMENT.REVERSAL_PAYMENT_NUM
           AND AUD__PAYMENTREV.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PAYMENT_TYPE DW__PAYMENT_TYPE
            ON DW__PAYMENT_TYPE.PAYMENT_TYPE_NUM = AUD__PAYMENT.PAYMENT_TYPE_NUM
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COURIER_SHIPMENT_TYPE DW__COURIER_SHIPMENT_TYPE
            ON DW__COURIER_SHIPMENT_TYPE.COURIER_SHIPMENT_KEY = DW__SHIPMENT_FACT.COURIER_SHIPMENT_KEY
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DW__DELIVERY_METHOD_TYPE
            ON DW__DELIVERY_METHOD_TYPE.DM_DELIVERY_METHOD_KEY = DW__SHIPMENT_FACT.DM_DELIVERY_METHOD_KEY
         LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ACCOUNT_MEMBER_CREDIT_CARD AUD__ACCOUNT_MEMBER_CC
            ON AUD__ACCOUNT_MEMBER_CC.ACCOUNT_MEMBER_CREDIT_CARD_NUM = AUD__PAYMENT.ACCOUNT_MEMBER_CREDIT_CARD_NUM
           AND AUD__ACCOUNT_MEMBER_CC.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
         LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CREDIT_CARD_TYPE AUD__CREDIT_CARD_TYPE
            ON AUD__CREDIT_CARD_TYPE.CREDIT_CARD_TYPE_NUM = AUD__ACCOUNT_MEMBER_CC.CREDIT_CARD_TYPE_NUM
           AND AUD__CREDIT_CARD_TYPE.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
        WHERE AUD__FILL_FACT.RX_NUMBER NOT LIKE 'RR%'
          AND AUD__PAYMENT.CANCELLED_DATE IS NULL		  
          AND AUD__FILL_FACT.FILL_STATE_CODE = '14'
          AND AUD__FILL_FACT.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
    )
)
WHERE AVOID_DUPLICATES_RANK = 1