WITH FILL_FACTS AS (
    SELECT FACTS.*
    FROM (
        SELECT 
            DW__FACILITY_ID.FD_VALUE AS PHARMACY_NPI,
            AUD__FILL_FACT.RX_NUMBER AS PRESCRIPTION_NBR,
            AUD__FILL_FACT.REFILL_NUM AS REFILL_NBR,
            AUD__FILL_FACT.DATE_OF_SERVICE AS DATE_OF_SERVICE,
            TRUNC(AUD__FILL_FACT.FILL_STATE_CHG_TS, 'DAY') AS FILL_STATE_DATE,
            DW__DRUG.DRUG_NDC AS NDC_NBR,
            SUBSTR(DW__TP_PATIENT.TPD_CARDHOLDER_ID, 1, 10) AS CARDHOLDER_ID,
            AUD__TP_ITEM_CLAIM.AUTHORIZATION_NUMBER AS AUTHORIZATION_NBR,
            AUD__TP_PROCESSOR_DESTINATION.BIN_NUMBER AS BIN_0,
            LEAD(AUD__TP_PROCESSOR_DESTINATION.BIN_NUMBER,1)
                 OVER(PARTITION BY AUD__FILL_FACT.FILL_STATE_PRICE_NUM, AUD__FILL_FACT.FILL_STATE_CODE
                 ORDER BY AUD__FILL_FACT.SPLIT_BILLING_CODE) AS BIN_1,
            LEAD(AUD__TP_PROCESSOR_DESTINATION.BIN_NUMBER,2)
                 OVER(PARTITION BY AUD__FILL_FACT.FILL_STATE_PRICE_NUM, AUD__FILL_FACT.FILL_STATE_CODE
                 ORDER BY AUD__FILL_FACT.SPLIT_BILLING_CODE) AS BIN_2,            
            RANK() OVER (PARTITION BY
                              DW__FACILITY_ID.FD_VALUE
                             ,AUD__FILL_FACT.RX_NUMBER
                             ,AUD__FILL_FACT.REFILL_NUM
                             ,DW__DRUG.DRUG_NDC
                         ORDER BY DW__TP_PATIENT.TPD_EFF_END_DATE DESC
                                 ,AUD__FILL_FACT.FILL_STATE_CHG_TS DESC
                                 ,ROW_NUMBER() OVER (ORDER BY DW__TP_PATIENT.TPD_EFF_END_DATE) DESC
                        ) AS CLAIMRANK,                        
            AUD__FILL_FACT.FACILITY_NUM,
            AUD__FILL_FACT.RX_NUMBER,
            AUD__FILL_FACT.REFILL_NUM,
            AUD__FILL_FACT.DISPENSED_DRUG_NUM, AUD__FILL_FACT.TP_PATIENT_NUM
        FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT AUD__FILL_FACT
             INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__FACILITY
                     ON DW__FACILITY.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
             INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID DW__FACILITY_ID
                     ON DW__FACILITY_ID.FD_FACILITY_KEY = DW__FACILITY.FD_FACILITY_NUM
             INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DW__DRUG
                     ON DW__DRUG.DRUG_NUM = AUD__FILL_FACT.DISPENSED_DRUG_NUM	
             LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT DW__TP_PATIENT
                     ON DW__TP_PATIENT.TPD_TP_PATIENT_NUM = AUD__FILL_FACT.TP_PATIENT_NUM
             LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_PROCESSOR_DESTINATION AUD__TP_PROCESSOR_DESTINATION
                     ON AUD__TP_PROCESSOR_DESTINATION.TP_PROCESSOR_DESTINATION_SEQ = AUD__FILL_FACT.TP_PROCESSOR_DEST_NUM
                    AND AUD__TP_PROCESSOR_DESTINATION.EFF_END_DATE BETWEEN (:RUNDATE - 1) 
                                                                       AND TO_DATE('29991231','YYYYMMDD')
			 LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_ITEM_CLAIM AUD__TP_ITEM_CLAIM
                     ON AUD__TP_ITEM_CLAIM.TP_ITEM_CLAIM_NUM = AUD__FILL_FACT.TP_ITEM_CLAIM_NUM
                    AND AUD__TP_ITEM_CLAIM.H_LEVEL = AUD__FILL_FACT.TP_ITEM_CLAIM_KEY
                    AND AUD__TP_ITEM_CLAIM.EFF_END_DATE BETWEEN (:RUNDATE - 1) 
                                                            AND TO_DATE('29991231','YYYYMMDD')
        WHERE AUD__FILL_FACT.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 1) 
                                                   AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
          AND AUD__FILL_FACT.FILL_STATE_CODE = '14' --SOLD
          AND DW__FACILITY_ID.FD_TYPE = 'F08'
          AND (DW__TP_PATIENT.TPD_EFF_END_DATE IS NULL OR 
              DW__TP_PATIENT.TPD_EFF_END_DATE BETWEEN (:RUNDATE - 1) 
                                                  AND TO_DATE('29991231','YYYYMMDD'))
          AND AUD__FILL_FACT.IS_SAME_DAY_REVERSAL = 'N'
         ) FACTS
    WHERE (FACTS.BIN_0 = '004303' OR FACTS.BIN_1 = '004303' OR FACTS.BIN_2 = '004303')
      AND FACTS.CLAIMRANK = 1
)
SELECT 
	RPAD(NVL(PHARMACY_NPI,' '), 10, '0') AS PHARMACY_NPI,
	LPAD(NVL(PRESCRIPTION_NBR,' '), 12, '0') AS PRESCRIPTION_NBR,
	LPAD(NVL(TO_CHAR(REFILL_NBR),' '), 3, '0') AS REFILL_NBR,
	TO_CHAR(DATE_OF_SERVICE::DATE,'YYYYMMDD') AS DATE_OF_SERVICE,
	TO_CHAR(FIRST_SOLD_DATE_ANY_PLAN::DATE,'YYYYMMDD') AS SOLD_DATE,
	RPAD(NVL(NDC_NBR,' '), 11, ' ') AS NDC_NBR,
	RPAD(NVL(CARDHOLDER_ID,' '), 15, ' ') AS CARDHOLDER_ID,
	RPAD(NVL(TO_CHAR(AUTHORIZATION_NBR),' '), 20, ' ') AS AUTHORIZATION_NBR,
	RPAD(' ', 8, ' ') AS RESERVED_FOR_FUTURE_USE
FROM (
      SELECT 
          PHARMACY_NPI,
          PRESCRIPTION_NBR,
          REFILL_NBR,
          DATE_OF_SERVICE,
          FILL_STATE_DATE,
          NDC_NBR,
          CARDHOLDER_ID,
          AUTHORIZATION_NBR,
          (SELECT  TRUNC(MIN(FF.FILL_STATE_CHG_TS), 'DAY')
           FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT FF
           WHERE FF.FACILITY_NUM = FILLS.FACILITY_NUM
             AND FF.RX_NUMBER = FILLS.RX_NUMBER
             AND FF.REFILL_NUM = FILLS.REFILL_NUM
             AND FF.DATE_OF_SERVICE = FILLS.DATE_OF_SERVICE
             AND FF.DISPENSED_DRUG_NUM = FILLS.DISPENSED_DRUG_NUM
             AND FF.FILL_STATE_CODE = '14' --SOLD
             AND FF.IS_SAME_DAY_REVERSAL = 'N'
             AND FF.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 365) 
                                          AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
          ) AS FIRST_SOLD_DATE_ANY_PLAN,
          (SELECT  TRUNC(MIN(FF.FILL_STATE_CHG_TS), 'DAY')
           FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT FF
                INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_PROCESSOR_DESTINATION TPPD
                   ON TPPD.TP_PROCESSOR_DESTINATION_SEQ = FF.TP_PROCESSOR_DEST_NUM
                  AND TPPD.BIN_NUMBER = '004303'
                  AND TPPD.EFF_END_DATE BETWEEN (:RUNDATE - 1) 
                                            AND TO_DATE('29991231','YYYYMMDD')
           WHERE FF.FACILITY_NUM = FILLS.FACILITY_NUM
             AND FF.RX_NUMBER = FILLS.RX_NUMBER
             AND FF.REFILL_NUM = FILLS.REFILL_NUM
             AND FF.DATE_OF_SERVICE = FILLS.DATE_OF_SERVICE
             AND FF.DISPENSED_DRUG_NUM = FILLS.DISPENSED_DRUG_NUM
             AND FF.FILL_STATE_CODE = '14' --SOLD
             AND FF.IS_SAME_DAY_REVERSAL = 'N'
             AND FF.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 365) 
                                          AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
          ) AS FIRST_MEDICARE_PART_B_SOLD_DATE
      FROM FILL_FACTS FILLS
     )
WHERE FIRST_MEDICARE_PART_B_SOLD_DATE = FILL_STATE_DATE
ORDER BY
    PHARMACY_NPI,
    PRESCRIPTION_NBR,
    REFILL_NBR,
    DATE_OF_SERVICE,
    FIRST_SOLD_DATE_ANY_PLAN,
    NDC_NBR