SELECT *
FROM (
		SELECT PTADDR.PAD_PATIENT_ADDRESS_KEY "PADR_KEY",
				DWPATIENT.PD_PATIENT_NUM "PATIENT_NUM",
				SUBSTR(REGEXP_REPLACE(PTADDR.PAD_ADDRESS1,'[,>|]',''),1,100) "ADDRESS_ONE",
				SUBSTR(REGEXP_REPLACE(PTADDR.PAD_ADDRESS2,'[,>|]',''),1,50) "ADDRESS_TWO",
				PTADDR.PAD_CITY "ADDR_CITY",
				PTADDR.PAD_STATE "ADDR_STATE",
				SUBSTR(REGEXP_REPLACE(LPAD(PTADDR.PAD_ZIP,5,'0'),'    ',NULL),1,20) "ADDR_ZIPCODE",
				SUBSTR(REGEXP_REPLACE(LPAD(PTADDR.PAD_EXT,4,'0'),'    ',NULL),1,6) "ADDRESS_ZIPEXT",
				PTADDR.PAD_COUNTY "COUNTY",
				DECODE(PTADDR.PAD_ADDRESS_USAGE
					   ,1,'HOME 1'
					   ,2,'HOME 2'
					   ,4,'WORK'
					   ,8,'OTHER'
					   ,0,NULL
					   ,'UNSPECIFIED') "ADDRESS_TYPE",
				DECODE(PTADDR.PAD_USAGE
					   ,2,'SHIPPING'
					   ,3,'DEFAULT BILLING/SHIPPING'
					   ,4,'DISPLAY'
					   ,5,'DEFAULT BILLING/DISPLAY'
					   ,6,'DISPLAY/SHIPPING'
					   ,7,'DEFAULT BILLING/DISPLAY/SHIPPING'
					   ,0,NULL
					   ,'OTHER') "ADDRESS_USAGE",
			   PTADDR.STATUS "ADDR_STATUS",
			   PTPHONE.PATP_AREA_CODE "AREA_CODE",
			   SUBSTR(PTPHONE.PATP_PHONE_NUMBER,1,3)||'-'||SUBSTR(PTPHONE.PATP_PHONE_NUMBER,4,4) "PHONE_NUM",
			   PTPHONE.PATP_EXT "PHONE_EXT",
               TO_NUMBER(NVL(TO_VARCHAR(PTADDR.DW_LAST_UPDATE_DT,'yyyyMMdd'),20070101)) "ADDRESS_UPDATED",
               TO_NUMBER(NVL(TO_VARCHAR(PTPHONE.DW_LAST_UPDATE_DT,'yyyyMMdd'),20070101)) "PHONE_UPDATED",
			   PTADDR.PAD_ADDRESS_NUM "DWADDRESSNUM",
			   PTPHONE.PATP_PHONE_NUM "DWPHONENUM"
        
		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS PTADDR

		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT DWPATIENT
		ON DWPATIENT.PD_PATIENT_KEY = PTADDR.PD_PATIENT_KEY

		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_PHONE PTPHONE
		ON PTPHONE.PD_PATIENT_KEY = PTADDR.PD_PATIENT_KEY
		AND PTPHONE.PAD_PATIENT_ADDRESS_KEY = PTADDR.PAD_PATIENT_ADDRESS_KEY
		AND PTPHONE.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')

		WHERE PTADDR.PAD_EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
     )
WHERE "ADDRESS_UPDATED" = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
   OR "PHONE_UPDATED" = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
   OR :RUNDATE = TO_DATE('20200101','YYYYMMDD')
--WHEN RUNDATE IS 1/1/2020 THEN THE WHOLE VIEW WILL RETURN.