SELECT
    PATIENT.PD_PATIENT_NUM AS PATIENT_NUM,
    PATIENT.PD_SPECIES_NAME AS SPECIES,
    PATIENT.PD_CREATE_DT AS CREATE_DATE,
    'Y' AS PET
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PATIENT
WHERE PATIENT.PD_SPECIES_NAME IS NOT NULL
  AND PATIENT.PD_STATUS = 'A'