SELECT * 
FROM (
		SELECT DISTINCT
			PRESCRIB.PRS_PRESCRIBER_KEY PRESCRIBER_KEY,
			PRESCRIB.PRS_PRESCRIBER_NUM PRESCRIBER_NUM,
			PRESCRIB.PRS_ACTIVE_PRESCRIBER_NUM ACTIVE_PRESCRIBER_NUM,
			NVL(PRESCRIB.PRS_TITLE_ABBR,PRESCRIB.PRS_ESV_TITLE_ABBR) TITLE_ABBR,
			NVL(PRESCRIB.PRS_FIRST_NAME,PRESCRIB.PRS_ESV_FIRST_NAME) FIRST_NAME,
			NVL(PRESCRIB.PRS_MIDDLE_NAME,PRESCRIB.PRS_ESV_MIDDLE_NAME) MIDDLE_NAME,
			NVL(PRESCRIB.PRS_LAST_NAME,PRESCRIB.PRS_ESV_LAST_NAME) LAST_NAME,
			NVL(PRESCRIB.PRS_NAME_SUFFIX_ABBR,PRESCRIB.PRS_ESV_NAME_SUFFIX_ABBR) SUFFIX_ABBR,
			PRESCRIB.PRS_GENDER_CODE GENDER_CODE,
			PRESCRIB.PRS_STATUS STATUS,
			NVL(PRESCRIB.PRS_PROFESSIONAL_ACTIVITY,PRESCRIB.PRS_ESV_PROFESSIONAL_ACTIVITY) AMA_ACTIVITY,
			DECODE(PRESCRIB.PRS_INACTIVITY_CODE,
				1,'NO RX ACTIVITY',
				2,'MERGED',
				3,'REPLACED',
				4,'LICENSE/DEA REVOKED',
				5,'RETIRED',
				9,'OTHER',NULL) INACTIVE_CODE,
			PRESCRIB.PRS_PREF_GENERIC_IF_AVAIL PREF_GENERIC,
			PRESCRIB.PRS_PREF_THERAPEUTIC_SUB PREF_THER_SUB,
			PRESCRIB.SYS_USER_KEY CREATE_USER_KEY,
			CASE PRESCRIB.PRS_SOURCE_CODE WHEN 'E' THEN 'ESV' ELSE 'MANUAL' END ADD_SOURCE,
			PRESCRIB.PRS_SUPV_PRESCRIBER_NUM SUPV_PRS_NUM,
			PRESCRIB.PRS_PRESCRIBER_BASE_NUM UNIQ_PRS_NUM,
			PRESCRIB.PRS_ESV_PRESCRIBER_ID PRESCRIBER_ID,
			PRESCRIB.PRS_ESV_MATCHED_IND ESV_MATCH,
			PRESCRIB.PRS_VALIDATED IS_ESV_VALID,
			PRESCRIB.PRS_CREATE_DATE CREATE_DATE,
			NVL(PRESCRIB.PRS_BIRTH_DATE,PRESCRIB.PRS_ESV_BIRTH_DATE) BIRTH_DATE,
			NVL(PRESCRIB.PRS_DECEASED_DATE,PRESCRIB.PRS_ESV_DECEASED_DATE) DECEASED_DATE,
			PRESCRIB.PRS_INACTIVE_STATUS_DATE INACTIVE_DATE,
			PRESCRIB.PRS_IS_PPI PPI_ENABLED,
			NPI.NPI NPI,
			NVL(NPI.USE_FOR_BILLING,'N') NPI_BILLING,
			NPI.EXPIRE_DATE NPI_EXPIRE_DATE,
			STATELIC.STATEID STATE_LIC_NUM,
			NVL(STATELIC.USE_FOR_BILLING,'N') STATE_LIC_BILLING,
			STATELIC.STATE LICENSE_STATE,
			STATELIC.EXPIRE_DATE STATE_LIC_EXPIRE_DATE,
			DEA.DEA_NUM DEA_NUM,
			NVL(DEA.USE_FOR_BILLING,'N') DEA_BILLING,
			DEA.EXPIRE_DATE DEA_EXPIRE_DATE,
			MEDICAID.MEDICAID_NUM MEDICAID_NUM,
			FEDID.FEDTAXID_NUM FEDTAXID_NUM,
			STATEISSUE.STATEISSUE_NUM STATEISSUE_NUM,
			NARCDEA.NARCDEA_NUM NARCDEA_NUM,
			NCPDP.NCPDP_NUM NCPDP_NUM,
			DW_LAST_UPDATE_DT AS LAST_UPDATE       
            
		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRESCRIB

		--PIT_KEY
		--509 - NATIONAL PROVIDER IDENTIFIER (NPI)
		--511 - STATE LICENSE
		--515 - DRUG ENFORCEMENT ADMINISTRATION (DEA) NUMBER-
		--504 - MEDICAID
		--505 - UPIN (UNIQUE PHYSICIAN/PRACTITIONER IDENTIFICATION NUMBER)-REPLACED
		--510 - FEDERAL TAX ID
		--517 - STATE ISSUED
		--518 - NARCOTIC ADDICTION DEA NUMBER
		--506 - NCPDP PROVIDER ID-


		--START - JOIN TO GET NPI INFO
		LEFT OUTER JOIN
		(SELECT PID_NPI.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_NPI.PID_ID_TEXT AS NPI,
				PID_NPI.USE_FOR_BILLING AS USE_FOR_BILLING,
				PID_NPI.PID_EXPIRATION_DATE AS EXPIRE_DATE

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_NPI
		WHERE PID_NPI.PID_STATUS = 'A'
		AND PID_NPI.PIT_KEY = 509

		ORDER BY PID_NPI.PID_EXPIRATION_DATE DESC NULLS LAST) NPI
		ON PRESCRIB.PRS_PRESCRIBER_KEY = NPI.PRESCRIBER_KEY
		--END - JOIN TO GET NPI INFO

		--START - JOIN TO GET STATEID LICENSE INFO
		LEFT OUTER JOIN
		(SELECT PID_STATEID.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_STATEID.PID_ID_TEXT AS STATEID,
				PID_STATEID.USE_FOR_BILLING AS USE_FOR_BILLING,
				PID_STATEID.PID_EXPIRATION_DATE AS EXPIRE_DATE,
				PID_STATEID.PID_STATE_CODE AS STATE

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_STATEID
		WHERE PID_STATEID.PID_STATUS = 'A'
		AND PID_STATEID.PIT_KEY = 511

		ORDER BY PID_STATEID.PID_EXPIRATION_DATE DESC NULLS LAST) STATELIC
		ON PRESCRIB.PRS_PRESCRIBER_KEY = STATELIC.PRESCRIBER_KEY
		--END - JOIN TO GET STATEID LICENSE INFO

		--START - JOIN TO GET DEA INFO
		LEFT OUTER JOIN
		(SELECT PID_DEA.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_DEA.PID_ID_TEXT AS DEA_NUM,
				PID_DEA.USE_FOR_BILLING AS USE_FOR_BILLING,
				PID_DEA.PID_EXPIRATION_DATE AS EXPIRE_DATE

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_DEA
		WHERE PID_DEA.PID_STATUS = 'A'
		AND PID_DEA.PIT_KEY = 515

		ORDER BY PID_DEA.PID_EXPIRATION_DATE DESC NULLS LAST) DEA
		ON PRESCRIB.PRS_PRESCRIBER_KEY = DEA.PRESCRIBER_KEY
		--END - JOIN TO GET DEA INFO

		--START - JOIN TO GET MEDICAID INFO
		LEFT OUTER JOIN
		(SELECT PID_MEDICAID.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_MEDICAID.PID_ID_TEXT AS MEDICAID_NUM

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_MEDICAID
		WHERE PID_MEDICAID.PID_STATUS = 'A'
		AND PID_MEDICAID.PIT_KEY = 504

		ORDER BY PID_MEDICAID.PID_EXPIRATION_DATE DESC NULLS LAST) MEDICAID
		ON PRESCRIB.PRS_PRESCRIBER_KEY = MEDICAID.PRESCRIBER_KEY
		--END - JOIN TO GET MEDICAID INFO


		--START - JOIN TO GET FEDID INFO
		LEFT OUTER JOIN
		(SELECT PID_FEDID.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_FEDID.PID_ID_TEXT AS FEDTAXID_NUM

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_FEDID
		WHERE PID_FEDID.PID_STATUS = 'A'
		AND PID_FEDID.PIT_KEY = 510

		ORDER BY PID_FEDID.PID_EXPIRATION_DATE DESC NULLS LAST) FEDID
		ON PRESCRIB.PRS_PRESCRIBER_KEY = FEDID.PRESCRIBER_KEY
		--END - JOIN TO GET FEDID INFO

		--START - JOIN TO GET STATEISSUE INFO
		LEFT OUTER JOIN
		(SELECT PID_STATEISS.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_STATEISS.PID_ID_TEXT AS STATEISSUE_NUM

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_STATEISS
		WHERE PID_STATEISS.PID_STATUS = 'A'
		AND PID_STATEISS.PIT_KEY = 517

		ORDER BY PID_STATEISS.PID_EXPIRATION_DATE DESC NULLS LAST) STATEISSUE
		ON PRESCRIB.PRS_PRESCRIBER_KEY = STATEISSUE.PRESCRIBER_KEY
		--END - JOIN TO GET STATEISSUE INFO

		--START - JOIN TO GET NARCOTIC DEA INFO
		LEFT OUTER JOIN
		(SELECT PID_NARCDEA.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_NARCDEA.PID_ID_TEXT AS NARCDEA_NUM

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_NARCDEA
		WHERE PID_NARCDEA.PID_STATUS = 'A'
		AND PID_NARCDEA.PIT_KEY = 518

		ORDER BY PID_NARCDEA.PID_EXPIRATION_DATE DESC NULLS LAST) NARCDEA
		ON PRESCRIB.PRS_PRESCRIBER_KEY = NARCDEA.PRESCRIBER_KEY
		--END - JOIN TO GET NARCOTIC DEA INFO

		--START - JOIN TO GET NCPDP INFO
		LEFT OUTER JOIN
		(SELECT PID_NCPDP.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
				PID_NCPDP.PID_ID_TEXT AS NCPDP_NUM

		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PID_NCPDP
		WHERE PID_NCPDP.PID_STATUS = 'A'
		AND PID_NCPDP.PIT_KEY = 506

		ORDER BY PID_NCPDP.PID_EXPIRATION_DATE DESC NULLS LAST) NCPDP
		ON PRESCRIB.PRS_PRESCRIBER_KEY = NCPDP.PRESCRIBER_KEY
		--END - JOIN TO GET NCPDP INFO
     )
WHERE LAST_UPDATE = (:RUNDATE - 1)::DATE
OR PRESCRIBER_KEY = 6915303