SELECT * 
FROM (
		SELECT FACILITY.FD_FACILITY_ID STORE_NUM,--1
				FILLFACT.RX_NUMBER RX_NUM,--2
				FILLFACT.REFILL_NUM REFILL_NUM,--3
				NVL(FILLFACT.PARTIAL_FILL_SEQ,0) PART_SEQ_NUM,--4
				PT.PD_PATIENT_NUM PATIENT_NUM,--5
				READYDATE.CAL_DATE READY_DATE,--6
				FILLFACT.READY_TIME_KEY READY_TIME_KEY,--7
				TRUNC(FILLFACT.TOTAL_REFILLS_REMAINING) REFILLS_REMAIN,--8
				OS.OS_ORDER_SOURCE_DESC ORDER_SOURCE,--9
				FILLFACT.RX_ORIGIN_CODE||'-'||ORIGIN.DESCRIPTION RX_ORIGIN_CODE,--10
				DELMETHOD.DM_DELIVERY_METHOD_DESC DEL_METHOD,--11
				FILLFACT.FACILITY_ORDER_NUMBER ORDER_NUM,---12
				FILLFACT.SHIPMENT_NUM SHIPMENT_NUM,---13
				FILLSTAT.FS_FILL_STATUS_DESC STATUS_DESC,--14
				FILLFACT.COST_PRICING_FORMULA_NAME PRICING_FORMULA_NAME,---15
				REPLACE(REPLACE(FILLFACT.SIG,CHR(10),''),CHR(124),'') SIG_TEXT,---16
				DISPENSEDATE.CAL_DATE DISPENSED_DATE,---17
				DISPDRUG.DRUG_NDC DISPENSED_NDC,--18
				DISPDRUG.DRUG_LABEL_NAME DISPENSED_DRUG_NAME,--19
				FILLFACT.QTY_DISPENSED QTY_DISPENSED,---20
				NULLIF(TRUNC(WRITTENDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) WRITTEN_DATE,--21
				WRITDRUG.DRUG_NDC WRITTEN_NDC,--22
				WRITDRUG.DRUG_LABEL_NAME WRITTEN_DRUG_NAME,--23
				FILLFACT.WRITTEN_QTY WRITTEN_QTY,--24
				CFDRUG.DRUG_NDC BEFORE_MAP_NDC,--25
				CFDRUG.DRUG_LABEL_NAME BEFORE_MAP_DRUG_NAME,--26
				CFFACILITY.FD_FACILITY_ID CF_STORE,--27
				CASE WHEN CFFACILITY.FD_FACILITY_ID IS NULL THEN 'N' ELSE 'Y' END CF_STORE_INDICATOR,--28
				FILLFACT.SKIP_PRE_VER_CODE BYPASS_PV_CODE,--29
			FILLFACT.TRANSACTION_CODE TX_NUMBER,--30
				FILLFACT.ADJUDICATION_GROUP_NUM,--31
				ORDERDATE.CAL_DATE ORDER_DATE,---32
				NULLIF(TRUNC(SOLDDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) SOLD_DATE,---33
				NULLIF(TRUNC(UNSOLDDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) UNSOLD_DATE,---34
				NULLIF(TRUNC(SYNCDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) SYNC_DATE,---35
				NULLIF(TRUNC(ADJDOS.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) ADJ_DATE_OF_SERVICE,---36
				NULLIF(TRUNC(ADJDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) ADJ_DATE,---37
				NULLIF(TRUNC(RTPDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) RTP_DATE,---38
				NULLIF(TRUNC(RTSDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) RTS_DATE,---39
				FILLFACT.IS_RETURNED_TO_STOCK IS_RTS,---40
				FILLFACT.RETURNED_TO_STOCK_QTY RTS_QTY,---41
				FILLFACT.FILL_DURATION_SECS FILL_DUR_SEC,---42
				FILLFACT.RX_RECORD_NUM RX_RECORD_NUM,--43
				FILLFACT.RX_FILL_SEQ RX_FILL_SEQ,--44
				FILLFACT.IS_PRN IS_PRN,--45
				FILLFACT.IS_MAIL IS_MAIL,--46
				FILLFACT.PRS_PRESCRIBER_KEY PRESCRIBER_KEY,---47
				FILLFACT.PRIMARY_TPLD_PLAN_KEY TPLD_PLAN_KEY,---48
				FILLFACT.VERIFY_RPH_SYS_USER_KEY RPH_USER_KEY,---49
				FILLFACT.DATA_ENTRY_USER_KEY DATA_ENTRY_USER_KEY,---50
				FILLFACT.DISPENSING_USER_KEY DISP_USER_KEY,---51
				FILLFACT.ERP_ENROLLMENT_CODE_NUM ERP_CODE,---52
				FILLFACT.ERP_ENROLLMENT_STATUS_DATE ERP_CODE_CHANGED_DATE,---53
				FILLFACT.ERP_TARGET_DATE ERP_TARGET_DATE,---54
				FILLINDC.CASH_TP_INDICATOR CASH_TP,---55
				FILLFACT.PRIORITY HIGH_PRI,---56
				FILLFACT.BIN_NAME BIN_NAME,--57
				PRESCRIBEDATE.CAL_DATE PRESCRIBE_DATE,--58
				PROMISEDATE.CAL_DATE PROMISE_DATE,--59
				DAW.DC_DAW_CODE DAW,--60
				FILLFACT.DAYS_SUPPLY DAYS_SUPPLY,--61
				FILLFACT.BILLED_AMOUNT PRIM_TP_BALANCE,--62
				FILLFACT.PATIENT_PRICE_PAID PRIM_PATIENT_PAY,--63
				FILLFACT.DISPENSING_FEE_AMOUNT PRIM_FEE,--64
				FILLFACT.TOTAL_PRICE_PAID TX_PRICE,--65
				FILLFACT.DISPENSED_QTY_AWP TX_AWP,--66
				FILLFACT.USER_DEFINED_STEP_AMT ACQ_COST,--67
				FILLFACT.TOTAL_UNC U_C_PRICE,--68
				FILLFACT.TP_PRICE_PAID TOTAL_TP_BALANCE,--69
				NULLIF(TRUNC(CANCELDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) CANCEL_DATE,--70
				NULLIF(TRUNC(FIRSTFILLDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) FIRST_FILL_DATE,--71
				NULLIF(TRUNC(LASTFILLDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) LAST_FILL_DATE,--72
				NULLIF(TRUNC(FUTUREFILLDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) FUTURE_FILL_DATE,--73        
				FILLFACT.PROMISE_TIME_KEY PROMISE_TIME_KEY,--ADDED 11/28/17, ES
				NULLIF(TRUNC(EXPIRYDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) EXPIRY_DATE,--ADDED 11/28/17, ES
				FILLFACT.COUNSELING_COMMENTS COUNSEL_COMMENTS,--ADDED 11/28/17, ES
				FILLFACT.COUNSELING_NAME COUNSEL_RPH,--ADDED 11/28/17, ES
				FILLFACT.COUNSELING_INITIALS COUNSEL_RPH_INITIAL,--ADDED 11/28/17, ES
				FILLFACT.INGREDIENT_COST INGRED_COST_PAID,--ADDED 11/28/17, ES
				FILLFACT.PADR_KEY PRESCRIBE_ADDR_KEY,--PRESCRIBER ADDRESS KEY ADDED 11/28/17, ES
				PT.PD_PRESCRIBER_NUM PATIENT_PRIM_PRESCRIBE_NUM, --ADDED 11/28/17, ES
				FILLFACT.FOA_DATE FOA_DATE, --ADDED 11/28/17, ES
				FILLFACT.DISPENSED_ITEM_LOT_NUMBER DISP_ITEM_LOT_NUM, --ADDED 11/28/17, ES
				FILLFACT.ACUTE_PROMISE_REASON_CODE ACUTE_PROMISE_REASON_CODE --ADDED 11/28/17, RXBST
		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FILLFACT
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ORDERDATE
				ON FILLFACT.ORDER_DATE_KEY = ORDERDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM ORDERTIME
				ON FILLFACT.ORDER_TIME_KEY = ORDERTIME.TIME_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM READYDATE
				ON FILLFACT.READY_DATE_KEY = READYDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM READYTIME
				ON FILLFACT.READY_TIME_KEY = READYTIME.TIME_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
				ON FILLFACT.FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PT
				ON FILLFACT.PD_PATIENT_KEY = PT.PD_PATIENT_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.ORDER_SOURCE_TYPE OS
				ON FILLFACT.OS_ORDER_SOURCE_KEY = OS.OS_ORDER_SOURCE_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_INDICATOR FILLINDC
				ON FILLFACT.FILL_INDICATOR_KEY = FILLINDC.FILL_INDICATOR_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DISPENSEDATE
				ON FILLFACT.DISPENSED_DATE_KEY = DISPENSEDATE.DATE_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DELMETHOD
				ON FILLFACT.DM_DELIVERY_METHOD_KEY = DELMETHOD.DM_DELIVERY_METHOD_KEY
		LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_ORIGINATION ORIGIN
				ON FILLFACT.RX_ORIGIN_CODE = ORIGIN.RX_ORIGINATION_NUM
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM SOLDDATE
				ON FILLFACT.SOLD_DATE_KEY = SOLDDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM UNSOLDDATE
				ON FILLFACT.UNSOLD_DATE_KEY = UNSOLDDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM SYNCDATE
				ON FILLFACT.SYNC_DATE_KEY = SYNCDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM RTSDATE
				ON FILLFACT.RETURNED_TO_STOCK_DATE_KEY = RTSDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ADJDOS
				ON FILLFACT.ADJ_DATE_OF_SERVICE_KEY = ADJDOS.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM ADJDATE
				ON FILLFACT.ADJUDICATION_DATE_KEY = ADJDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM RTPDATE
				ON FILLFACT.RTP_DATE_KEY = RTPDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM PRESCRIBEDATE
				ON FILLFACT.PRESCRIBED_DATE_KEY = PRESCRIBEDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM PROMISEDATE
				ON FILLFACT.PROMISE_DATE_KEY = PROMISEDATE.DATE_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DISPDRUG
				ON FILLFACT.DISPENSED_DRUG_KEY = DISPDRUG.DRUG_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG WRITDRUG
				ON FILLFACT.WRITTEN_DRUG_KEY = WRITDRUG.DRUG_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DAW_CODE_TYPE DAW
				ON FILLFACT.DC_DAW_CODE_KEY = DAW.DC_DAW_CODE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM CANCELDATE
				ON FILLFACT.CANCEL_DATE_KEY = CANCELDATE.DATE_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT CFPRODUCT
				ON FILLFACT.CF_LOCAL_PRD_PRODUCT_KEY = CFPRODUCT.PRD_PRODUCT_KEY
		LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG CFDRUG
				ON CFPRODUCT.PRD_DRUG_NUM = CFDRUG.DRUG_NUM
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM WRITTENDATE
				ON FILLFACT.WRITTEN_DATE_KEY = WRITTENDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM FIRSTFILLDATE
				ON FILLFACT.FIRST_FILL_DATE_KEY = FIRSTFILLDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM LASTFILLDATE
				ON FILLFACT.LAST_FILL_DATE_KEY = LASTFILLDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM RTSDATE
				ON FILLFACT.RETURNED_TO_STOCK_DATE_KEY = RTSDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM FUTUREFILLDATE
				ON FILLFACT.FUTURE_FILL_DATE_KEY = FUTUREFILLDATE.DATE_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY CFFACILITY
				ON FILLFACT.CENTRAL_FILL_FD_FACILITY_KEY = CFFACILITY.FD_FACILITY_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_STATUS_TYPE FILLSTAT
				ON FILLFACT.FS_FILL_STATUS_KEY = FILLSTAT.FS_FILL_STATUS_KEY
		INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM EXPIRYDATE
				ON FILLFACT.EXPIRY_DATE_KEY = EXPIRYDATE.DATE_KEY --ADDED 11/28/17, ES
     )
WHERE READY_DATE = (:RUNDATE - 1)