SELECT
  BASE_STORE_NUM,
  BASE_STORE_NAME,
  TO_STORE_NUM,
  TO_STORE,
  FROM_STORE_NUM,
  FROM_STORE,
  TRANSFER_DEST,
  PATIENT_NUM,
  ORIG_RX_NUM,
  REFILL_NUM,
  TRANSFER_DATE,
  SOLD_DATE,
  READY_DATE,
  CANCEL_DATE,
  TRANSFER_TIME_KEY,
  WRITTEN_NDC_WO,
  WRITTEN_DRUG_NAME,
  DISP_NDC_WO,
  DISP_DRUG_NAME,
  ROUND(QTY_DISPENSED,0) as  QTY_DISPENSED,
  DAW,
  TRANS_TYPE,
  TRANS_METHOD,
  SIG_TEXT,
  PRESCRIBER_KEY,
  RX_RECORD_NUM,
  RX_FILL_SEQ,
  Round(PATIENT_PAY,2) as PATIENT_PAY,
  Round(TP_PAY,2) as TP_PAY,
  Round(TX_PRICE,2) as TX_PRICE,
  Round(ACQ_COST,2) as ACQ_COST,
  Round(U_C_PRICE,2) as U_C_PRICE,
  FIRST_FILL_DATE,
  LAST_FILL_DATE,
  SENDING_RPH,
  RECEIVE_RPH,
  XFER_ADDR,
  XFER_ADDRE,
  XFER_CITY,
  XFER_ST,
  XFER_ZIP,
  XFER_PHONE,
  TRANSFER_REASON,
  NEW_RX_RECORD_NUM,
  COMPETITOR_GROUP,
  COMPETITOR_STORE_NUM
FROM (
		SELECT
			BASEFAC.FD_FACILITY_ID AS BASE_STORE_NUM,
			BASEFAC.FD_LEGAL_NAME AS BASE_STORE_NAME,
			(CASE WHEN TRANSTYPE.RX_TRANSFER_TYPE_IND = 'OUT' THEN TRANSFACT.FACILITY_ID
				  ELSE BASEFAC.FD_FACILITY_ID
			 END) AS TO_STORE_NUM,  
			(CASE WHEN TRANSTYPE.RX_TRANSFER_TYPE_IND = 'OUT' THEN TRANSFACT.FACILITY_NAME
				  ELSE BASEFAC.FD_LEGAL_NAME
			 END) AS TO_STORE,
			(CASE WHEN TRANSTYPE.RX_TRANSFER_TYPE_IND = 'IN' THEN TRANSFACT.FACILITY_ID
				  ELSE BASEFAC.FD_FACILITY_ID
			 END) AS FROM_STORE_NUM,
			(CASE WHEN TRANSTYPE.RX_TRANSFER_TYPE_IND = 'IN' THEN TRANSFACT.FACILITY_NAME
				  ELSE BASEFAC.FD_LEGAL_NAME
			 END) AS FROM_STORE,
			(CASE WHEN TRANSFACT.FACILITY_NAME = FACNAME.FD_LEGAL_NAME THEN 'In-Chain'
				  ELSE 'Out-Of-Chain'
			 END) AS TRANSFER_DEST,
			PT.PD_PATIENT_NUM AS PATIENT_NUM,
			TRANSFACT.RX_NUMBER AS ORIG_RX_NUM,
			TRANSFACT.REFILL_NUM AS REFILL_NUM,
			TRANSDATE.CAL_DATE AS TRANSFER_DATE,
			NULLIF(TRUNC(SOLDDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) AS SOLD_DATE,
			NULLIF(TRUNC(READYDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) AS READY_DATE,
			NULLIF(TRUNC(CANCELDATE.CAL_DATE, 'DAY'),TRUNC(TO_DATE('5555-12-31','YYYY-MM-DD'), 'DAY')) AS CANCEL_DATE,
			TRANSFACT.TRANSFER_TIME_KEY AS TRANSFER_TIME_KEY,
			TO_CHAR(WRITDRUG.DRUG_NDC) AS WRITTEN_NDC_WO,
			WRITDRUG.DRUG_LABEL_NAME AS WRITTEN_DRUG_NAME,
			TO_CHAR(DISPDRUG.DRUG_NDC) AS DISP_NDC_WO,
			DISPDRUG.DRUG_LABEL_NAME AS DISP_DRUG_NAME,
			TRANSFACT.QTY_DISPENSED AS QTY_DISPENSED,
			DAW.DC_DAW_CODE AS DAW,
			TRANSTYPE.RX_TRANSFER_TYPE_IND AS TRANS_TYPE,
			TRANSMETH.RX_TRANSFER_METHOD_IND AS TRANS_METHOD,
			REPLACE(TRANSFACT.SIG,CHR(10),'') AS SIG_TEXT,
			TRANSFACT.PRS_PRESCRIBER_KEY AS PRESCRIBER_KEY,
			TRANSFACT.RX_RECORD_NUM AS RX_RECORD_NUM,
			TRANSFACT.RX_FILL_SEQ AS RX_FILL_SEQ,
			TRANSFACT.PATIENT_PRICE_PAID AS PATIENT_PAY,
			TRANSFACT.TOTAL_TP_PAID AS TP_PAY,
			TRANSFACT.TOTAL_PRICE_PAID AS TX_PRICE,
			TRANSFACT.USER_DEFINED_STEP_AMT AS ACQ_COST,
			TRANSFACT.TOTAL_UNC AS U_C_PRICE,
			TRANSFACT.FIRST_FILL_DATE AS FIRST_FILL_DATE,
			TRANSFACT.LAST_FILL_DATE AS LAST_FILL_DATE,
			TRANSFACT.SENDING_PHARMACIST AS SENDING_RPH,
			TRANSFACT.RECEIVING_PHARMACIST AS RECEIVE_RPH,
			TRANSFACT.REC_PHARMACY_ADDR1 AS XFER_ADDR,
			TRANSFACT.REC_PHARMACY_ADDR2 AS XFER_ADDRE,
			TRANSFACT.REC_PHARMACY_CITY AS XFER_CITY,
			TRANSFACT.REC_PHARMACY_STATE AS XFER_ST,
			TRANSFACT.REC_PHARMACY_ZIP AS XFER_ZIP,
			TRANSFACT.REC_PHARMACY_PHONE AS XFER_PHONE,
			TRANSFACT.TRANSFER_REASON AS TRANSFER_REASON,
			TRANSFACT.TRANSFER_TO_RX_RECORD_NUM AS NEW_RX_RECORD_NUM,
			TRANSFACT.COMPETITOR_GROUP_CODE AS COMPETITOR_GROUP,
			TRANSFACT.STORE_NUMBER AS COMPETITOR_STORE_NUM,
			TRANSFACT.TRANSFER_DATE_KEY
		FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.RX_TRANSFER_FACT TRANSFACT
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PT
			   ON TRANSFACT.PD_PATIENT_KEY = PT.PD_PATIENT_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.RX_TRANSFER_METHOD_TYPE TRANSMETH
			   ON TRANSFACT.RX_TRANSFER_METHOD_KEY = TRANSMETH.RX_TRANSFER_METHOD_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.RX_TRANSFER_TYPE TRANSTYPE
			   ON TRANSFACT.RX_TRANSFER_TYPE_KEY = TRANSTYPE.RX_TRANSFER_TYPE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY BASEFAC
			   ON TRANSFACT.FD_FACILITY_KEY = BASEFAC.FD_FACILITY_KEY    
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT WRITPROD
			   ON TRANSFACT.PRD_PRODUCT_KEY = WRITPROD.PRD_PRODUCT_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG WRITDRUG
			   ON WRITPROD.PRD_DRUG_NUM = WRITDRUG.DRUG_NUM    
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT DISPPROD
			   ON TRANSFACT.DISPENSED_PRD_PRODUCT_KEY = DISPPROD.PRD_PRODUCT_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DISPDRUG
			   ON DISPPROD.PRD_DRUG_NUM = DISPDRUG.DRUG_NUM    
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DAW_CODE_TYPE DAW
			   ON TRANSFACT.DC_DAW_CODE_KEY = DAW.DC_DAW_CODE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM TRANSDATE
			   ON TRANSFACT.TRANSFER_DATE_KEY = TRANSDATE.DATE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TIME_DIM TRANSTIME
			   ON TRANSFACT.TRANSFER_TIME_KEY = TRANSTIME.TIME_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM SOLDDATE
			   ON TRANSFACT.SOLD_DATE_KEY = SOLDDATE.DATE_KEY
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM READYDATE
			   ON TRANSFACT.READY_DATE_KEY = READYDATE.DATE_KEY    
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACNAME
			   ON TRANSFACT.FACILITY_NAME = FACNAME.FD_LEGAL_NAME
			LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM CANCELDATE
			   ON TRANSFACT.CANCEL_DATE_KEY = CANCELDATE.DATE_KEY

     )
WHERE TRANSFER_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE, 'YYYYMMDD'))
ORDER BY TRANSFER_TIME_KEY