SELECT
	 FF.FILL_FACT_KEY AS RECORDSEQUENCENUMBER

	--PATIENT--
	,P.PD_PATIENT_NUM AS PARTICIPANTPATIENTID
	,P.PD_LAST_NAME AS PATIENTLASTNAME
	,P.PD_FIRST_NAME AS PATIENTFIRSTNAME
	,P.PD_MIDDLE_NAME AS PATIENTMIDDLENAME
	,P.PD_TITLE_ABBR AS PATIENTPREFIX
	,P.PD_NAME_SUFFIX_ABBR AS PATIENTSUFIX
	,P.PD_BIRTH_DATE AS PATIENTDATEOFBIRTH
	,PD.GENDER AS PATIENTGENDER
	,PA.PAD_ADDRESS1 AS PATIENTADDRESS1
	,PA.PAD_CITY AS PATIENTCITY
	,PA.PAD_STATE AS PATIENTSTATE
	,PA.PAD_ZIP AS PATIENTZIPCODE

	--PHARMACY--
	,F.FD_NCPDP_PROVIDER_ID AS NCPDPID
	,F.FD_FACILITY_ID AS CHAINSITEID
	,F.FD_FACILITY_NAME AS PHARMACYNAME
	,F.FD_ADDRESS1 AS FACILITYADDRESS1
	,F.FD_CITY AS FACILITYCITY
	,F.FD_STATE_CODE AS FACILITYSTATE
	,F.FD_ZIPCODE AS FACILITYZIPCODE
	,F.FD_PHONE1 AS FACILITYPHONENUMBER

	--PRESCRIBER--
	,PRES.PRS_LAST_NAME AS FPRIMARYCAREPROVIDERLASTNAME
	,PRES.PRS_FIRST_NAME AS PRIMARYCAREPROVIDERFIRSTNAME
	,PRES_ADDR.PADR_ADDRESS1 AS PRIMARYCAREPROVIDERADDRESS1
	,PRES_ADDR.PADR_CITY AS PRIMARYCAREPROVIDERCITY
	,PRES_ADDR.PADR_STATE_CODE AS PRIMARYCAREPROVIDERSTATE
	,PRES_ADDR.PADR_ZIPCODE AS PRIMARYCAREPROVIDERZIPCODE
	,PRES_PHONE.PRSP_AREA_CODE AS PRIMARYCAREPROVIDERAREACODE
	,PRES_PHONE.PRSP_PHONE_NUMBER AS PRIMARYCAREPROVIDERPHONENUMBER

	--MEDICATION--
	,FF.RX_NUMBER AS PRESCRIPTIONNUMBER
	,FF.REFILL_NUM AS FILLNUMBER
	,D.DRUG_NDC AS NDCNUMBERDISPENSED
	,D.DRUG_LABEL_NAME AS MEDICATIONNAME
	,FF.INTENDED_QTY_DISPENSED AS QUANTITYPRESCRIBED
	,FF.QTY_DISPENSED AS QUANTITYDISPENSED
	,FF.DAYS_SUPPLY AS DAYSSUPPLY
	,FF.SIG AS SIGTEXT
	,FF.WRITTEN_DATE_KEY AS DATEWRITTEN
	,FF.READY_DATE_KEY AS DATEFILLED
	,FF.SOLD_DATE_KEY AS DATEPICKEDUPDISPENSED
	,FF.TOTAL_REFILLS_ALLOWED AS REFILLSORIGINALLYAUTHORIZED
	,FF.TOTAL_REFILLS_REMAINING AS REFILLSREMAINING

	--FIELDS NEEDED FOR BUSINESS LOGIC BUT NOT IN DATA EXTRACT--
	,FF.FILL_FACT_KEY AS LOGIC_FILLFACTKEY
	,FF.PD_PATIENT_KEY AS LOGIC_PDPATIENTKEY
	,PA.PAD_ADDRESS_USAGE AS LOGIC_PATIENTADDRESSUSAGE
	,PA.PAD_EFF_START_DATE AS LOGIC_PATIENTADDRESSCREATEDATE
	,PRES_PHONE.PADR_KEY AS LOGIC_PRESPHONEKEY
	,PRES_PHONE.PRSP_STATUS AS LOGIC_PRESPHONESTATUS
	,PRES_PHONE.PRSP_SOURCE_CODE AS LOGIC_PRESPHONESOURCECODE
	,PRES_PHONE.DW_CREATED_DT AS LOGIC_PRESPHONEHLEVEL
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F
        ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT P
        ON P.PD_PATIENT_KEY = FF.PD_PATIENT_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS PA
        ON PA.PD_PATIENT_KEY = FF.PD_PATIENT_KEY
       AND PA.PAD_EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_DEMOGRAPHIC PD
        ON PD.PATIENT_DEMOGRAPHIC_KEY = FF.PATIENT_DEMOGRAPHIC_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES
        ON PRES.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ADDRESS PRES_ADDR
        ON PRES_ADDR.PRS_PRESCRIBER_KEY = PRES.PRS_PRESCRIBER_KEY
       AND PRES_ADDR.PADR_IS_DEFAULT = 'Y'        
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_PHONE PRES_PHONE
        ON PRES_PHONE.PADR_KEY = PRES_ADDR.PADR_KEY
       AND PRES_PHONE.PRSP_PHONE_ADDRESS_TYPE = 'PRIM'
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
        ON D.DRUG_KEY = FF.DISPENSED_DRUG_KEY
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PR
        ON PR.PRD_DRUG_NUM = D.DRUG_NUM
       AND PR.PRD_DEACTIVATE_DATE IS NULL
WHERE FF.SOLD_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
  AND FF.CANCEL_DATE_KEY = 0