SELECT 
	TRUNC(RXERP.DATESTAMP, 'DAY') "RXERP_CHANGE_DATE",--1
        RXERP.PATIENT_NUM "PATIENT_NUM",--2
        FACILITY.FD_FACILITY_ID "STORE_NUM",--3
        REGEXP_REPLACE(RXERP.RX_NUMBER, '[^0-9]+', '') "RX_NUM",--4
        RXERP.RX_NUMBER "RX_NUM_TXT",--5
        DRUG.DRUG_NDC "NDCWO",--6
	REPLACE(DRUG.DRUG_LABEL_NAME,',','') "DRUG_NAME",--7
        RXERP.DAYS_SUPPLY "DAYS_SUPPLY",--8
        RXERP.REFILLS_AUTHORIZED "REFILLS_AUTHORIZED",--9
        RXERP.LAST_FILL_DATE "LAST_FILL_DATE",--10
        
        RXERP.ERP_ORIGINAL_TARGET_DATE "ERP_ORIG_TARGET_DATE",--11
        RXERP.ERP_TARGET_DATE "ERP_TARGET_DATE",--12
        
        DECODE(RXERP.ERP_ENROLLMENT_CODE_NUM,
                1,'1-HAS NOT BEEN ASKED',
                2,'2-DECLINED',
                3,'3-ENROLLED',
                4,'4-UNENROLLED',
                5,'5-INELIGIBLE',
		6,'6-ONETIME',
                NULLIF(RXERP.ERP_ENROLLMENT_CODE_NUM||'-','-')) "ERP_ENROLL_STATUS",--13
        RXERP.ERP_ENROLLMENT_STATUS_DATE "ERP_ENROLL_STATUS_DATE",--14
        
        DECODE(RXERP.ERP_ENROLLMENT_REASON_CODE_NUM,
                1,'1-AUTO ENROLL',
                2,'2-PATIENT REQUEST',
                3,'3-RETURN TO STOCK',
                4,'4-RX TRANSFER',
                NULLIF(RXERP.ERP_ENROLLMENT_REASON_CODE_NUM||'-','-')) "ERP_ENROLL_REASON",--15
                
        DECODE(RXERP.ERP_EXCLUSION_REASON_CODE_NUM,
                1,'1-NOT ACTIVE',
                2,'2-MAXIMUM DAYS SUPPLY',
                3,'3-MINIMUM DAYS SUPPLY',
                4,'4-PRODUCT NOT ELIGIBLE',
                5,'5-SOLD DATE',
                6,'6-REFILLS ALLOWED CHECK',
                7,'7-THIRD PARTY NOT ELIGIBLE',
                8,'8-FACILITY NOT PARTICIPATING IN ERP',
                9,'9-MEDSYNC RX',
                10,'10-PRESCRIBER INACTIVE REASON',
                11,'11-CONTACT EVENT FOUND',
                12,'12-PATIENT NOT ENROLLED',
                13,'13-PATIENT CONSENT NOT PROVIDED',
            NULLIF(RXERP.ERP_EXCLUSION_REASON_CODE_NUM||'-','-')) "ERP_EXCLUDE_REASON",--16
            DELIVERYMETHOD.DM_DELIVERY_METHOD_DESC "ERP_DELIVERY_METHOD",--17
            RXERP.ERP_DELIVERY_METHOD_PERSIST "ERP_DELIVERY_METHOD_PERSIST",--18
            RXERP.IS_CONSENTED_TO_FILL "IS_CONSENTED_TO_FILL",--19
            RXERP.USER_CONSENTED_TO_FILL "USER_CONSENTED_TO_FILL",--20
            RXERP.DATE_CONSENTED_TO_FILL "DATE_CONSENTED_TO_FILL",--21
            RXERP.EFF_START_DATE AS "EFF_START_DATE",--22
--RX-ERP DATA--
                DECODE(RXERP.H_TYPE,
                        'U','UPDATE',
                        'I','ADDED',
                        'D','REMOVED',
                        RXERP.H_TYPE) "RECORD_TYPE",--23
                        
                RXERP.ERP_USER_MODIFIED_TARGET_DATE "ERP_USERMODIFIED_TARGET_DATE",--24
                
                CASE WHEN RXERP.ERP_UM_DATE_BY IS NULL
                THEN 'SYSTEM'
                ELSE
                    CASE WHEN PTERP.STATUS IS NULL
                    THEN 'ERX USER'
                    ELSE 'PATIENT'
                    END
                END AS "ERP_MODIFIED_USERTYPE",--25
                
                NVL(PTERP.PATIENT_NUM,RXERP.ERP_UM_DATE_BY) AS "ERP_MODIFIED_USER",--26
                RXERP.ERP_UM_DATE_BY_TYPE "ERP_USERMODIFIED_RECTYPE",--27
                RXERP.ERP_UM_DATE_MODIFIED_ON "ERP_USERMODIFIED_ONDATE",--28
                RXERP.NUM_UPDATES "REC_UPDATES",--29
--RX-ERP DATA--
                
                
                
--PATIENT-ERP DATA--
                CASE PATIENT.ERP_ENROLLMENT_STATUS_CODE WHEN 3 THEN
                    CASE PATIENT.REQUIRE_CONSENT_TO_FILL WHEN 'N' THEN 'AUTOFILL' ELSE 'CONSENT REQUIRED' END
                ELSE 'NOT ENROLLED' END
                AS "PT_AUTOFILL_ENROLL_STATUS",--30
        
            DECODE(PATIENT.ERP_ENROLLMENT_STATUS_CODE,
		1,'1-HAS NOT BEEN ASKED',
		2,'2-DECLINED',
		3,'3-ENROLLED',
		4,'4-UNENROLLED',
		5,'5-INELIGIBLE',
		6,'6-ONETIME',
		NULLIF(PATIENT.ERP_ENROLLMENT_STATUS_CODE||'-','-')) "PT_ERP_ENROLL_STATUS",--31
            PATIENT.ERP_ENROLLMENT_STATUS_DATE "PT_ERP_ENROLL_DATE",--32
            PATIENT.IS_ERP_AUTO_ENROLLED "PT_AUTOENROLL_FUTURE_RXS",--33
            DELIVERYMETHOD.DM_DELIVERY_METHOD_DESC "PT_PREFERRED_DELIVERY_METHOD",--34
            PATIENT.ERP_PREFERS_MAIL_DELIVERY "PT_PREFERS_MAIL_DELIVERY",--35
            PATIENT.ERP_PAYMENT_METHOD "PT_ERP_PAYMENT_METHOD",--36
            PATIENT.REQUIRE_CONSENT_TO_FILL "PT_REQ_CONSENT_TOFILL",--37
            PATIENT.REQUIRE_CONSENT_TO_ERP_PROCESS "PT_REQ_CONSENT_TOERP",--38
            PATIENT.EXTERNAL_PATIENT_ID "PT_EXTERNAL_ID",--39
--PATIENT-ERP DATA--
     
--RX/DRUG DATA--
            RXERP.PROHIBIT_RENEWAL_REQUEST "PROHIBIT_RENEWAL_REQUEST",--40
            RXERP.CSR_DIAGNOSIS_CODE_NC_CDT "CSR_DIAGNOSIS_CODE",--41
            DRUG.DRUG_DOSAGE_FORM "DRUG_FORM",--42
            RXERP.TOTAL_AUTHORIZED_QTY "QTY_AUTHORIZED",--43
            RXERP.REFILL_QTY "REFILL_QTY",--44
            --CAST(REPLACE(REPLACE(REPLACE(SUBSTR(RXERP.DIRECTIONS,1,500),CHR(30),''),CHR(13),''),CHR(10),'') AS VARCHAR(500)) "DIRECTIONS",--45
            RXERP.EXPIRY_DATE "EXPIRE_DATE",--46
            RXERP.REASSIGNED_RX_NUM "REASSIGNED_RX_NUM",--47
            TRUNC(RXERP.CREATE_DATE, 'DAY') "CREATE_DATE",--48
            RXERP.CREATE_USER "CREATE_USER",--49
            TO_CHAR(RXERP.RX_ORIGINATION_NUM)||'-'||ORIGIN.DESCRIPTION "RX_ORIGIN_CODE",--50
            RXSTAT.DESCRIPTION "RX_STATUS",--51
            RXERP.RX_RECORD_NUM "RX_RECORD_NUM",--52
            RXERP.FIRST_FILL_QTY "FIRST_FILL_QTY",--53
            RXERP.PRESCRIBED_DATE "DATE_PRESCRIBED",--54
            ORIG_DRUG.DRUG_NDC "ORIGINAL_NDCWO",--55
            ORIG_DRUG.DRUG_LABEL_NAME "ORIGINAL_DRUG_NAME",--56
            RXERP.ORIGINAL_PRODUCT_QTY "ORIGINAL_QTY",--57
            RXERP.TRIPLICATE_SERIAL_NUM "SERIAL",--58
            RXERP.DAW_CODE "DAW_CODE",--59
            RXERP.SELECTED_UPC "SELECTED_UPC",--60
--RX/DRUG DATA--

--MISC RX DATA--
        RXERP.ACKNOWLEDGE_TYPE_CODE "ACK_CODE",--61
        RXERP.IS_LETTER_ON_FILE "LETTER_ON_FILE",--62
        TRIM(SYSUSER.SYS_USER_LOGIN_NAME) "EMP_LOGIN_NAME",--63
        RXERP.LAST_ACK_CHANGE_DATE "LAST_ACK_CHANGE_DATE",--64
        TRIM(ACK_SYSUSER.SYS_USER_LOGIN_NAME) "LAST_ACK_CHANGE_USER",--65
        ACK_SYSUSER.SYS_USER_FNAME||' '||ACK_SYSUSER.SYS_USER_LNAME "LAST_ACK_CHANGE_USERNAME",--66
        RXERP.ORIGINAL_FILL_DATE "ORIG_FILL_DATE",--67
        RXERP.TOTAL_DAILY_DOSE "TOTAL_DAILY_DOSE",--68
        RXERP.TOTAL_QTY_DISPENSED "TOTAL_QTY_DISP",--69
        RXERP.TOTAL_QTY_TRANSFERRED "TOTAL_QTY_XFERRED",--70
        RXERP.NUMBER_OF_LEGAL_FILLS "LEGAL_FILLS",--71
        RXERP.LATEST_FILL "LATEST_FILL",--72
        RXERP.LATEST_FILL_DUR "LATEST_FILL_DUR",--73
        RXERP.LATEST_FILL_NON_IN_PROCESS "LATEST_FILL_NON_INPROCESS",--74
        RXERP.LATEST_CANCELLED_FILL "LATEST_FILL_CANCELED",--75
        RXERP.LAST_DISPENSED_FILL "LAST_DISP_FILL",--76
        RXERP.LAST_FILL_FOR_REFILL "LAST_FILL_REFILL",--77
        RXERP.LAST_FILL_RELEASED "LAST_FILL_RELEASED",--78
        RXERP.LAST_SOLD_FILL_NON_COMPLETION "LAST_SOLD_FILL",--79
        
        RXERP.PROFILE_INCLUSION_DATE "PROFILE_INCLUDE_DATE",--80
        
        RXERP.FIRST_FILL "FIRST_FILL",--81
        RXERP.FIRST_REFILL "FIRST_REFILL",--82
        RXERP.EARLIEST_FILL_DATE "EARLIEST_FILL_DATE",--83
        RXERP.PREVIOUS_FILL_RELEASED "PREV_FILL_RELEASED",--84
        RXERP.SYNC_DATE "SYNC_DATE",--85
        RXERP.IS_LINKED_FROM_RX_PROFILE "IS_LINKED",--86
        RXERP.CANCEL_REASON_CODE "CANCEL_REASON",--87
        RXERP.PRESCRIBER_NUM "PRESCRIBER_NUM",--88
        RXERP.PRESCRIBER_ADDRESS_NUM "PRESCRIBER_ADDRESS_NUM",--89
        RXERP.PRESCRIBER_ORDER_NUMBER "PRESCRIBER_ORDER_NUM",--90
        RXERP.IS_EPCS "IS_EPCS",--91
        RXERP.IS_RRR_DENIED "RRR_DENIED"--92
--MISC RX DATA--

FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX RXERP

LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT PATIENT
    ON RXERP.PATIENT_NUM = PATIENT.PATIENT_NUM
    AND PATIENT.EFF_END_DATE = TO_DATE('12312999','MMDDYYYY')

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER PTUM
    ON RXERP.ERP_UM_DATE_BY = TO_CHAR(PTUM.SYS_USER_NUM)
LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT PTERP
    ON PTUM.SYS_USER_LOGIN_NAME = TO_CHAR(PTERP.PATIENT_NUM)
    AND PTERP.EFF_END_DATE = TO_DATE('12312999','MMDDYYYY')

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER ACK_SYSUSER
    ON RXERP.LAST_ACK_CHANGE_USER = ACK_SYSUSER.SYS_USER_NUM
LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_STATUS RXSTAT
    ON RXERP.RX_STATUS_NUM = RXSTAT.RX_STATUS_NUM
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
    ON RXERP.FACILITY_NUM = FACILITY.FD_FACILITY_NUM
    --AND FACILITY.FD_FACILITY_KEY IN (530,531,532,533,502,534,535,536,537,51894,539,540,553,554,555,557,558,559,560,561,556,3659902,516015)
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SYSUSER
    ON RXERP.SYS_USER = SYSUSER.SYS_USER_NUM
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COURIER_SHIPMENT_TYPE SHIPMETHOD
    ON RXERP.ERP_DELIVERY_METHOD_NUM = SHIPMETHOD.SHIPPING_METHOD_NUM

LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_ORIGINATION ORIGIN
    ON RXERP.RX_ORIGINATION_NUM = ORIGIN.RX_ORIGINATION_NUM
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT ORIG_PROD
    ON RXERP.ORIGINAL_PRODUCT_NUM = ORIG_PROD.PRD_PRODUCT_NUM
        LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG ORIG_DRUG
            ON ORIG_PROD.PRD_DRUG_NUM = ORIG_DRUG.DRUG_NUM

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PROD
    ON RXERP.PRODUCT_NUM = PROD.PRD_PRODUCT_NUM
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
    ON PROD.PRD_DRUG_NUM = DRUG.DRUG_NUM
LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DELIVERYMETHOD
    ON RXERP.ERP_DELIVERY_METHOD_NUM = DELIVERYMETHOD.DM_DELIVERY_METHOD

WHERE RXERP.EFF_START_DATE BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')