SELECT 
    LAST_UPDATED.CAL_DATE "DATE_OF_SERVICE",
    FACILITY.FD_FACILITY_ID "STORE_NUM",
    TO_CHAR(DRUG.DRUG_NDC) "NDC_WO",
    DRUG.DRUG_LABEL_NAME "DRUG_NAME",
    PRODUCT.PRD_IS_GENERIC "SDGI",
    DRUG.DRUG_GCN "GCN",
    DRUG.DRUG_GCN_SEQ "GCN_SEQ_NUM",
    DRUG.DRUG_ORANGE_BOOK_CODE "ORANGE_BOOK_CODE",
    DRUG.DRUG_DRUG_FORM_CODE "FORM_CODE",
    DRUG.DRUG_PACKAGE_SIZE "PACK_SIZE",
    NVL(DRUG.DRUG_CASE_SIZE,1)*DRUG.DRUG_PACKAGE_SIZE "TRUE_PACK",
    PRODUCT.PRD_IS_PRICE_MAINTAINED "PM",
    PRODUCT.IS_PREFERRED_PRODUCT "IS_PREFERRED",
    INV.LAST_ACQUISITION_COST "LASTACQCOST_PACK",
    INV.LAST_ACQUISITION_UNIT_COST "LASTACQCOST_UNIT",
    INV.LAST_ACQUISITION_COST_DATE "LASTACQCOST_DATE",
    INV.CURRENT_QTY "ONHAND_QTY",
    (INV.CURRENT_QTY * NVL(INV.EXPECTED_UNIT_COST,INV.LAST_ACQUISITION_UNIT_COST)) "ONHAND_VALUE",
    INV.COMMITTED_QTY "COMMITED_QTY",
    (INV.COMMITTED_QTY * NVL(INV.EXPECTED_UNIT_COST,INV.LAST_ACQUISITION_UNIT_COST)) "COMMITED_VALUE",
    (INV.CURRENT_QTY + INV.COMMITTED_QTY) "TOTAL_QTY",
    ((INV.COMMITTED_QTY * NVL(INV.EXPECTED_UNIT_COST,INV.LAST_ACQUISITION_UNIT_COST)) + (INV.CURRENT_QTY * NVL(INV.EXPECTED_UNIT_COST,INV.LAST_ACQUISITION_UNIT_COST))) "TOTAL_VALUE",
    NVL(INV.EXPECTED_COST,INV.LAST_ACQUISITION_COST) "ACQ_COST_PACK",
    NVL(INV.EXPECTED_UNIT_COST,INV.LAST_ACQUISITION_UNIT_COST) "ACQ_COST_UNIT",
    VEND.VENDOR_NAME "PRIM_SUPPLIER",
    LAST_UPDATED.CAL_DATE "LAST_CHG_DATE"
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.INVENTORY_ITEM_FACT INV
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM LAST_UPDATED
       ON INV.DATE_KEY = LAST_UPDATED.DATE_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
       ON INV.DRUG_KEY = DRUG.DRUG_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FACILITY
       ON INV.FD_FACILITY_KEY = FACILITY.FD_FACILITY_KEY
      AND FACILITY.FD_IS_PPI_ENABLED = 'Y'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR VEND
       ON INV.PRIMARY_VENDOR_KEY = VEND.VENDOR_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRODUCT
       ON INV.PRD_PRODUCT_KEY = PRODUCT.PRD_PRODUCT_KEY
WHERE LAST_UPDATED.CAL_DATE = (:RUNDATE - 1)
  AND (INV.CURRENT_QTY + INV.COMMITTED_QTY) <> 0
ORDER BY FACILITY.FD_FACILITY_ID