SELECT DISTINCT AUDPATIENTGROUP.DATESTAMP "PT_ADD_DATE",
              DWFACILITY.FD_FACILITY_ID "STORE_NUM",
              AUDPATIENTGROUP.PATIENT_NUM "PATIENT_NUM",
              AUDPATIENTGROUP.GROUP_NUM "GROUP_NUM",
              DWGROUPS.GRP_NAME "GROUP_NAME",
              DWGROUPS.GRP_DESCRIPTION "GROUP_DESC",
              DWSYSUSER.SYS_USER_LOGIN_NAME "EMP_USERNAME",
              DWSYSUSER.SYS_USER_FNAME "EMP_FNAME",
              DWSYSUSER.SYS_USER_LNAME "EMP_LNAME",
              (CASE WHEN (AUDPATIENTGROUP.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY'))
              THEN('ADDED')
              ELSE('REMOVED') END) AS "EVENT_DESCRIPTION",
              DWGROUPS.GRP_CREATE_DATE "GROUP_START_DATE"

FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT_GROUP AUDPATIENTGROUP

LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FACILITY_LOGIN FACILITYLOGIN
ON FACILITYLOGIN.SYSTEM_USER_NUM = AUDPATIENTGROUP.SYS_USER
AND AUDPATIENTGROUP.EFF_START_DATE BETWEEN FACILITYLOGIN.EFF_START_DATE AND FACILITYLOGIN.EFF_END_DATE

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DWFACILITY
ON DWFACILITY.FD_FACILITY_NUM = FACILITYLOGIN.FACILITY_NUM

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER DWSYSUSER
ON DWSYSUSER.SYS_USER_NUM = AUDPATIENTGROUP.SYS_USER

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.GROUPS DWGROUPS
ON DWGROUPS.GRP_GROUP_NUM = AUDPATIENTGROUP.GROUP_NUM

WHERE TRUNC(AUDPATIENTGROUP.DATESTAMP, 'DAY') = (:RUNDATE-1)

--WHERE AUDPATIENTGROUP.DATESTAMP BETWEEN
--TO_DATE('12/14/2020 00:00:00','MM/DD/YYYY HH24:MI:SS') AND
--TO_DATE('12/20/2020 23:59:59','MM/DD/YYYY HH24:MI:SS')
--^ THIS IS FOR ADHOC PULL OR BACKPOPULATE TO PICK DATE RANGE

AND DWGROUPS.GRP_TYPE = 'A'