SELECT FAC.FD_FACILITY_ID "STORE_NUM",
	FF.RX_NUMBER "RX_NUM",
	FF.REFILL_NUM "REFILL_NUM",
	NVL(FF.PARTIAL_FILL_SEQ, 0) AS "PART_SEQ_NUM",
	SOLDDATE.CAL_DATE "SOLD_DATE",
	FF.FACILITY_ORDER_NUMBER "ORDER_NUM",
	FF.QTY_DISPENSED "QTY_DISPENSED",
	DR.DRUG_NDC "NDC_WO",
	FF.USER_DEFINED_STEP_AMT "ACQ_COST",
	FF.TP_PRICE_PAID "TP_PAY",
	FF.PATIENT_PRICE_PAID "PATIENT_PAY",
	FF.TOTAL_PRICE_PAID "TX_PRICE"

FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF

INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
	ON FAC.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DR
	ON DR.DRUG_KEY = FF.DISPENSED_DRUG_KEY
INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM SOLDDATE
	ON FF.SOLD_DATE_KEY = SOLDDATE.DATE_KEY

WHERE SOLDDATE.CAL_DATE = TRUNC(:RUNDATE - 1, 'DAY')