WITH QUERY_VARIABLES AS (
    SELECT
         :START_DATE AS V_START_DATE --TYPICALLY IS PREVIOUS SUNDAY
        ,:END_DATE AS V_END_DATE --TYPICALLY IS PREVIOUS SATURDAY
        ,:TAT_TARGET AS V_TAT_TARGET --ONE OF THESE: 'SPECIALTY', 'EXCELLUS', 'IHA'
        ,'SPECIALTY' AS TAT_TARGET_SPECIALTY
        ,'EXCELLUS' AS TAT_TARGET_EXCELLUS
        ,'IHA' AS TAT_TARGET_IHA
    
), SPECIALTY_GCN_LIST AS (
    SELECT '30788' AS SPECIALTY_GCN  UNION ALL
    SELECT '39483' AS SPECIALTY_GCN  UNION ALL
    SELECT '40869' AS SPECIALTY_GCN  UNION ALL
    SELECT '45877' AS SPECIALTY_GCN  UNION ALL
    SELECT '45878' AS SPECIALTY_GCN  UNION ALL
    SELECT '48664' AS SPECIALTY_GCN  UNION ALL
    SELECT '48814' AS SPECIALTY_GCN  UNION ALL
    SELECT '48815' AS SPECIALTY_GCN  UNION ALL
    SELECT '48899' AS SPECIALTY_GCN  UNION ALL
    SELECT '49812' AS SPECIALTY_GCN  UNION ALL
    SELECT '50035' AS SPECIALTY_GCN  UNION ALL
    SELECT '50039' AS SPECIALTY_GCN  UNION ALL
    SELECT '50210' AS SPECIALTY_GCN  UNION ALL
    SELECT '50736' AS SPECIALTY_GCN  UNION ALL
    SELECT '51599' AS SPECIALTY_GCN  UNION ALL
    SELECT '51637' AS SPECIALTY_GCN  UNION ALL
    SELECT '52882' AS SPECIALTY_GCN  UNION ALL
    SELECT '53430' AS SPECIALTY_GCN  UNION ALL
    SELECT '58214' AS SPECIALTY_GCN  UNION ALL
    SELECT '58776' AS SPECIALTY_GCN  UNION ALL
    SELECT '58877' AS SPECIALTY_GCN  UNION ALL
    SELECT '58878' AS SPECIALTY_GCN  UNION ALL
    SELECT '58879' AS SPECIALTY_GCN  UNION ALL
    SELECT '58880' AS SPECIALTY_GCN  UNION ALL
    SELECT '60102' AS SPECIALTY_GCN  UNION ALL
    SELECT '60107' AS SPECIALTY_GCN  UNION ALL
    SELECT '60108' AS SPECIALTY_GCN  UNION ALL
    SELECT '61205' AS SPECIALTY_GCN  UNION ALL
    SELECT '61938' AS SPECIALTY_GCN  UNION ALL
    SELECT '62602' AS SPECIALTY_GCN  UNION ALL
    SELECT '62624' AS SPECIALTY_GCN  UNION ALL
    SELECT '63724' AS SPECIALTY_GCN  UNION ALL
    SELECT '63903' AS SPECIALTY_GCN  UNION ALL
    SELECT '64481' AS SPECIALTY_GCN  UNION ALL
    SELECT '64967' AS SPECIALTY_GCN  UNION ALL
    SELECT '65113' AS SPECIALTY_GCN  UNION ALL
    SELECT '65114' AS SPECIALTY_GCN  UNION ALL
    SELECT '65189' AS SPECIALTY_GCN  UNION ALL
    SELECT '65409' AS SPECIALTY_GCN  UNION ALL
    SELECT '65410' AS SPECIALTY_GCN  UNION ALL
    SELECT '65411' AS SPECIALTY_GCN  UNION ALL
    SELECT '65993' AS SPECIALTY_GCN  UNION ALL
    SELECT '65994' AS SPECIALTY_GCN  UNION ALL
    SELECT '66396' AS SPECIALTY_GCN  UNION ALL
    SELECT '66709' AS SPECIALTY_GCN  UNION ALL
    SELECT '67394' AS SPECIALTY_GCN  UNION ALL
    SELECT '67628' AS SPECIALTY_GCN  UNION ALL
    SELECT '67681' AS SPECIALTY_GCN  UNION ALL
    SELECT '68047' AS SPECIALTY_GCN  UNION ALL
    SELECT '68048' AS SPECIALTY_GCN  UNION ALL
    SELECT '69046' AS SPECIALTY_GCN  UNION ALL
    SELECT '69151' AS SPECIALTY_GCN  UNION ALL
    SELECT '70233' AS SPECIALTY_GCN  UNION ALL
    SELECT '70586' AS SPECIALTY_GCN  UNION ALL
    SELECT '70587' AS SPECIALTY_GCN  UNION ALL
    SELECT '70588' AS SPECIALTY_GCN  UNION ALL
    SELECT '71017' AS SPECIALTY_GCN  UNION ALL
    SELECT '71250' AS SPECIALTY_GCN  UNION ALL
    SELECT '71262' AS SPECIALTY_GCN  UNION ALL
    SELECT '71590' AS SPECIALTY_GCN  UNION ALL
    SELECT '71708' AS SPECIALTY_GCN  UNION ALL
    SELECT '71748' AS SPECIALTY_GCN  UNION ALL
    SELECT '71942' AS SPECIALTY_GCN  UNION ALL
    SELECT '72075' AS SPECIALTY_GCN  UNION ALL
    SELECT '72785' AS SPECIALTY_GCN  UNION ALL
    SELECT '72786' AS SPECIALTY_GCN  UNION ALL
    SELECT '72926' AS SPECIALTY_GCN  UNION ALL
    SELECT '73237' AS SPECIALTY_GCN  UNION ALL
    SELECT '73370' AS SPECIALTY_GCN  UNION ALL
    SELECT '73394' AS SPECIALTY_GCN  UNION ALL
    SELECT '73395' AS SPECIALTY_GCN  UNION ALL
    SELECT '73444' AS SPECIALTY_GCN  UNION ALL
    SELECT '74510' AS SPECIALTY_GCN  UNION ALL
    SELECT '74511' AS SPECIALTY_GCN  UNION ALL
    SELECT '74512' AS SPECIALTY_GCN  UNION ALL
    SELECT '74513' AS SPECIALTY_GCN  UNION ALL
    SELECT '74564' AS SPECIALTY_GCN  UNION ALL
    SELECT '74663' AS SPECIALTY_GCN  UNION ALL
    SELECT '75514' AS SPECIALTY_GCN  UNION ALL
    SELECT '75641' AS SPECIALTY_GCN  UNION ALL
    SELECT '75731' AS SPECIALTY_GCN  UNION ALL
    SELECT '75732' AS SPECIALTY_GCN  UNION ALL
    SELECT '76265' AS SPECIALTY_GCN  UNION ALL
    SELECT '76305' AS SPECIALTY_GCN  UNION ALL
    SELECT '76353' AS SPECIALTY_GCN  UNION ALL
    SELECT '77469' AS SPECIALTY_GCN  UNION ALL
    SELECT '77470' AS SPECIALTY_GCN  UNION ALL
    SELECT '77565' AS SPECIALTY_GCN  UNION ALL
    SELECT '77584' AS SPECIALTY_GCN  UNION ALL
    SELECT '77637' AS SPECIALTY_GCN  UNION ALL
    SELECT '77783' AS SPECIALTY_GCN  UNION ALL
    SELECT '77870' AS SPECIALTY_GCN  UNION ALL
    SELECT '78185' AS SPECIALTY_GCN  UNION ALL
    SELECT '78186' AS SPECIALTY_GCN  UNION ALL
    SELECT '78187' AS SPECIALTY_GCN  UNION ALL
    SELECT '78258' AS SPECIALTY_GCN  UNION ALL
    SELECT '78538' AS SPECIALTY_GCN  UNION ALL
    SELECT '78672' AS SPECIALTY_GCN  UNION ALL
    SELECT '78672' AS SPECIALTY_GCN  UNION ALL
    SELECT '78707' AS SPECIALTY_GCN  UNION ALL
    SELECT '79520' AS SPECIALTY_GCN  UNION ALL
    SELECT '79673' AS SPECIALTY_GCN  UNION ALL
    SELECT '79675' AS SPECIALTY_GCN  UNION ALL
    SELECT '80271' AS SPECIALTY_GCN  UNION ALL
    SELECT '82340' AS SPECIALTY_GCN 
), RELEASE_TO_PATIENT AS (
    
    SELECT 
         FF.FACILITY_ORDER_NUMBER AS ORDER_NUMBER
        ,F.FD_FACILITY_ID AS FACILITY
        ,FF.PD_PATIENT_KEY AS MCKESSON_PATIENT_KEY
        ,FF.RX_NUMBER AS RX_NBR
        ,FF.REFILL_NUM AS REFILL_NBR
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TPP ON TPP.TPLD_PLAN_KEY = FF.PRIMARY_TPLD_PLAN_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD ON FF.DISPENSED_PRD_PRODUCT_KEY = PRD.PRD_PRODUCT_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON D.DRUG_NUM = PRD.PRD_DRUG_NUM AND PRD.PRD_DEACTIVATE_DATE IS NULL
         INNER JOIN SPECIALTY_GCN_LIST SP ON SP.SPECIALTY_GCN = D.DRUG_GCN_SEQ
         CROSS JOIN QUERY_VARIABLES QV
    WHERE FF.PARTITION_DATE BETWEEN (QV.V_START_DATE - 10) AND (QV.V_END_DATE + 10) --FILTER ON PARTITION_DATE SIMPLY TO INCREASE PERFORMANCE.
          --RTP_DATE_KEY INDEX IS IB_FILL_FACT_64
      AND FF.RTP_DATE_KEY BETWEEN TO_NUMBER(TO_CHAR(QV.V_START_DATE::DATE,'YYYYMMDD'))
                              AND TO_NUMBER(TO_CHAR(QV.V_END_DATE::DATE,'YYYYMMDD'))
      AND D.DRUG_NDC NOT IN (
              '00000999990' --D.DRUG_LABEL_NAME='TREMFYA NO DISPENSE'
          )
      AND FF.SOLD_DATE_KEY != 0
      AND FF.CANCEL_DATE_KEY = 0
      AND FF.IS_SAME_DAY_REVERSAL = 'N'
      AND QV.V_TAT_TARGET = QV.TAT_TARGET_SPECIALTY
    GROUP BY
         FF.FACILITY_ORDER_NUMBER
        ,FF.PD_PATIENT_KEY
        ,F.FD_FACILITY_ID
        ,FF.RX_NUMBER
        ,FF.REFILL_NUM

    UNION ALL

    SELECT 
         FF.FACILITY_ORDER_NUMBER AS ORDER_NUMBER
        ,F.FD_FACILITY_ID AS FACILITY
        ,FF.PD_PATIENT_KEY AS MCKESSON_PATIENT_KEY
        ,FF.RX_NUMBER AS RX_NBR
        ,FF.REFILL_NUM AS REFILL_NBR
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TPP ON TPP.TPLD_PLAN_KEY = FF.PRIMARY_TPLD_PLAN_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD ON FF.DISPENSED_PRD_PRODUCT_KEY = PRD.PRD_PRODUCT_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON D.DRUG_NUM = PRD.PRD_DRUG_NUM AND PRD.PRD_DEACTIVATE_DATE IS NULL
         CROSS JOIN QUERY_VARIABLES QV
    WHERE FF.PARTITION_DATE BETWEEN (QV.V_START_DATE - 10) AND (QV.V_END_DATE + 10) --FILTER ON PARTITION_DATE SIMPLY TO INCREASE PERFORMANCE.
          --RTP_DATE_KEY INDEX IS IB_FILL_FACT_64
      AND FF.RTP_DATE_KEY BETWEEN TO_NUMBER(TO_CHAR(QV.V_START_DATE::DATE,'YYYYMMDD'))
                              AND TO_NUMBER(TO_CHAR(QV.V_END_DATE::DATE,'YYYYMMDD'))
      AND F.FD_FACILITY_ID = '199'
      AND D.DRUG_NDC NOT IN (
              '00000999990' --D.DRUG_LABEL_NAME='TREMFYA NO DISPENSE'
          )
      AND TPP.BIN IN ('610014','003858') --EXCELLUS
      AND EXISTS (
                  SELECT *
                  FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT AUD__FILL_FACT
                       INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__FACILITY
                          ON DW__FACILITY.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
                  WHERE (AUD__FILL_FACT.BENEFIT_GROUP_ID LIKE 'LHPG%' OR AUD__FILL_FACT.BENEFIT_GROUP_ID LIKE 'EXL%')
                    AND AUD__FILL_FACT.FILL_STATE_CHG_TS BETWEEN TO_DATE(TO_CHAR(FF.RTP_DATE_KEY ),'YYYYMMDD') AND SYSDATE()
                    AND DW__FACILITY.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
                    AND AUD__FILL_FACT.RX_NUMBER = FF.RX_NUMBER
                    AND AUD__FILL_FACT.REFILL_NUM = FF.REFILL_NUM
          )
      AND FF.SOLD_DATE_KEY != 0
      AND FF.CANCEL_DATE_KEY = 0
      AND FF.IS_SAME_DAY_REVERSAL = 'N'
      AND QV.V_TAT_TARGET = QV.TAT_TARGET_EXCELLUS
    GROUP BY
         FF.FACILITY_ORDER_NUMBER
        ,FF.PD_PATIENT_KEY
        ,F.FD_FACILITY_ID
        ,FF.RX_NUMBER
        ,FF.REFILL_NUM

    UNION ALL

    SELECT 
         FF.FACILITY_ORDER_NUMBER AS ORDER_NUMBER
        ,F.FD_FACILITY_ID AS FACILITY
        ,FF.PD_PATIENT_KEY AS MCKESSON_PATIENT_KEY
        ,FF.RX_NUMBER AS RX_NBR
        ,FF.REFILL_NUM AS REFILL_NBR
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TPP ON TPP.TPLD_PLAN_KEY = FF.PRIMARY_TPLD_PLAN_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD ON FF.DISPENSED_PRD_PRODUCT_KEY = PRD.PRD_PRODUCT_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON D.DRUG_NUM = PRD.PRD_DRUG_NUM AND PRD.PRD_DEACTIVATE_DATE IS NULL
         CROSS JOIN QUERY_VARIABLES QV
    WHERE FF.PARTITION_DATE BETWEEN (QV.V_START_DATE - 10) AND (QV.V_END_DATE + 10) --FILTER ON PARTITION_DATE SIMPLY TO INCREASE PERFORMANCE.
          --RTP_DATE_KEY INDEX IS IB_FILL_FACT_64
      AND FF.RTP_DATE_KEY BETWEEN TO_NUMBER(TO_CHAR(QV.V_START_DATE::DATE,'YYYYMMDD'))
                              AND TO_NUMBER(TO_CHAR(QV.V_END_DATE::DATE,'YYYYMMDD'))
      AND F.FD_FACILITY_ID = '199'
      AND D.DRUG_NDC NOT IN (
              '00000999990' --D.DRUG_LABEL_NAME='TREMFYA NO DISPENSE'
          )
      AND TPP.BIN IN ('004626','012635','016557','012486') --IHA
      AND FF.SOLD_DATE_KEY != 0
      AND FF.CANCEL_DATE_KEY = 0
      AND FF.IS_SAME_DAY_REVERSAL = 'N'
      AND QV.V_TAT_TARGET = QV.TAT_TARGET_IHA
    GROUP BY
         FF.FACILITY_ORDER_NUMBER
        ,FF.PD_PATIENT_KEY
        ,F.FD_FACILITY_ID
        ,FF.RX_NUMBER
        ,FF.REFILL_NUM
)

SELECT
     FWF.FACILITY_ORDER_NUMBER AS ORDER_NUMBER
    ,FAC.FD_FACILITY_ID AS FACILITY
    ,FWF.PD_PATIENT_KEY AS MCKESSON_PATIENT_KEY
    ,FWF.FWFS_RX_NUMBER AS RX_NBR
    ,FWF.FWFS_REFILL_NUM AS REFILL_NBR
    ,FWF.FWFS_DT_IN AS DATE_IN
    ,FWF.FWFS_DT_OUT AS DATE_OUT
    ,WS.WFSD_KEY
    ,WS.WFSD_STEP_DESCRIPTION
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_WORKFLOW_FACT FWF
        LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.WF_STEP WS 
           ON WS.WFSD_KEY = FWF.WFSD_KEY
        LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC 
           ON FAC.FD_FACILITY_KEY = FWF.FD_FACILITY_KEY
        CROSS JOIN QUERY_VARIABLES QV
WHERE FWF.FWFS_DT_IN BETWEEN (QV.V_START_DATE - 365) AND (QV.V_END_DATE + 1) --ORDER NUMBERS CAN BE REPEATED AFTER A FEW YEARS, BUT ARE NOT REUSED WITHIN A YEAR.
  AND (FWF.FACILITY_ORDER_NUMBER, FWF.PD_PATIENT_KEY) IN (
          SELECT RTP.ORDER_NUMBER, RTP.MCKESSON_PATIENT_KEY
          FROM RELEASE_TO_PATIENT RTP
      )
ORDER BY
     FWF.FACILITY_ORDER_NUMBER
    ,FWF.FWFS_RX_NUMBER
    ,FWF.FWFS_REFILL_NUM
    ,FWF.FWFS_DT_IN
    ,FWF.FWFS_DT_OUT