-- QUERY PRESCRIPTION FILL
       SELECT F.FD_FACILITY_ID FACILITY_ID
             , FWF.FWFS_RX_NUMBER RX_NUMBER
             , D.DRUG_NDC NDC
             , REPLACE(D.DRUG_BRAND_NAME,',','') DRUG_NAME
             , FWF.FWFS_DT_IN DATE_IN
             , FWF.FWFS_DT_OUT DATE_OUT
             --, WS.WFSD_STEP_DESCRIPTION WORKFLOW_STEP
             , DECODE(WS.WFSD_STEP_DESCRIPTION,'PRE-VERIFICATION 1','PRE-VERIFICATION',DECODE(WS.WFSD_STEP_DESCRIPTION,'DUR - PRE-VERIFICATION 1','DUR - PRE-VERIFICATION',WS.WFSD_STEP_DESCRIPTION)) WORKFLOW_STEP
             , DMT.DM_DELIVERY_METHOD_DESC DELIVERY_METHOD
             , SU.SYS_USER_LOGIN_NAME USER_ID
             , FWF.FWFS_QTY_DISPENSED QTY_DISPENSED
             , F2.FD_FACILITY_ID OWNING_FACILITY
             , DECODE(F.FD_FACILITY_ID, F2.FD_FACILITY_ID, 'NO', 'YES') WLB
             , (SELECT SKIP_PRE_VER_CODE
                  FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_FILL BPV
                 WHERE BPV.RX_RECORD_NUM = FWF.FWFS_RX_RECORD_NUM
                   AND BPV.RX_FILL_SEQ = FWF.FWFS_RX_FILL_SEQ
                   AND BPV.H_LEVEL IN (
                       SELECT MAX(H_LEVEL)
                         FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_FILL
                        WHERE RX_RECORD_NUM = FWF.FWFS_RX_RECORD_NUM
                          AND RX_FILL_SEQ = FWF.FWFS_RX_FILL_SEQ
                          AND CAST(FROM_TZ(CAST(DATESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/EASTERN' AS DATE) <=  FWF.FWFS_DT_OUT
                   )
               ) SKIP_PRE_VER_CODE
          FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_WORKFLOW_FACT FWF
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON (FWF.FD_FACILITY_KEY = F.FD_FACILITY_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DMT ON (FWF.DM_DELIVERY_METHOD_KEY = DMT.DM_DELIVERY_METHOD_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.WF_STEP WS ON (FWF.WFSD_KEY = WS.WFSD_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SU ON (FWF.SYS_USER_KEY = SU.SYS_USER_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON (FWF.DRUG_KEY = D.DRUG_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F2 ON (FWF.OWNING_FACILITY_KEY = F2.FD_FACILITY_KEY)
          LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.ORDER_SOURCE_TYPE OST ON (FWF.OS_ORDER_SOURCE_KEY = OST.OS_ORDER_SOURCE_KEY)
        WHERE FWF.FWFS_DT_OUT BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
          AND SU.SYS_USER_LOGIN_NAME <> 'SYSTEM'
          AND WS.WFSD_STEP_DESCRIPTION NOT IN ('COMPLETION PENDING', 'CANCELLED', 'ORDER GROUPING', 'CHECK OUT', 'POST-VERIFICATION', 'IN PROCESS', 'MAIL SHIPPING', 'RETURNS', 'SYSTEM BLOCK')
UNION ALL -- QUERY NEW PATIENT
SELECT 
             FAC.FD_FACILITY_ID FACILITY_ID
             , NULL AS RX_NUMBER
             , NULL AS NDC
             , NULL AS DRUG_NAME
             , PAT.CREATE_DATE DATE_IN
             , PAT.CREATE_DATE DATE_OUT
             , 'NEW PATIENTS' AS WORKFLOW_STEP
             , NULL AS DELIVERY_METHOD
             , NULL AS USER_ID
             , COUNT(*) AS QTY_DISPENSED
             , NULL AS OWNING_FACILITY
             , NULL AS WLB
             , NULL AS SKIP_PRE_VER_COD
        FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT PAT
	       INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC ON FAC.FD_FACILITY_NUM = PAT.CREATE_FACILITY_NUM
        WHERE PAT.CREATE_DATE BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
          AND PAT.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY') 
       GROUP BY FAC.FD_FACILITY_ID, PAT.CREATE_DATE
UNION ALL -- QUERY DRUGS RECIEVED
SELECT
        FAC.FD_FACILITY_ID AS FACILITY_ID
        ,NULL AS RX_NUMBER
        ,NULL AS NDC
        ,NULL AS DRUG_NAME
        ,POI.RECEIVED_DATE AS DATE_IN 
        ,POI.RECEIVED_DATE AS DATE_OUT
        ,'ITEMS RECEIVED' AS WORKFLOW_STEP
        ,NULL AS DELIVERY_METHOD
        ,NULL AS USER_ID
        ,COUNT(*) AS QTY_DISPENSED
        ,NULL AS OWNING_FACILITY
        ,NULL AS WLB
        ,NULL AS SKIP_PRE_VER_CODE
      FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PURCHASE_ORDER_ITEM POI
        INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PURCHASE_ORDER PO ON PO.PURCHASE_ORDER_NUM = POI.PURCHASE_ORDER_NUM
        INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC ON FAC.FD_FACILITY_NUM = PO.FACILITY_NUM
      WHERE POI.RECEIVED_DATE BETWEEN (:RUNDATE - 1) AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
       AND POI.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
       AND PO.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
    GROUP BY FAC.FD_FACILITY_ID, POI.RECEIVED_DATE