SELECT
     FF.FILL_FACT_KEY AS RECORDSEQUENCENUMBER

    --PATIENT--
    ,P.PD_PATIENT_NUM AS PARTICIPANTPATIENTID
    ,P.PD_LAST_NAME AS PATIENTLASTNAME
    ,P.PD_FIRST_NAME AS PATIENTFIRSTNAME
    ,P.PD_MIDDLE_NAME AS PATIENTMIDDLENAME
    ,PP.PATP_AREA_CODE AS PATIENTPHONEAREACODE
    ,PP.PATP_PHONE_NUMBER AS PATIENTPHONENUMBER
    ,P.PD_BIRTH_DATE AS PATIENTDATEOFBIRTH
    ,PD.GENDER AS PATIENTGENDER
    ,PA.PAD_ADDRESS1 AS PATIENTADDRESS1
    ,PA.PAD_ADDRESS2 AS PATIENTADDRESS2
    ,PA.PAD_CITY AS PATIENTCITY
    ,PA.PAD_STATE AS PATIENTSTATE
    ,PA.PAD_ZIP AS PATIENTZIPCODE

    --PATIENTS PRIMARY CARE PROVIDER--
    --NOTE THE 'ALL' STATE FILTER USES PRIMARY CARE PROVIDER (ABBREVIATED PCP) FOR ALL PRESCRIBER DATA.
    --NOTE THE 'PA' STATE FILTER TYPICALLY USES THE PRECRIBER FROM TRANSACTION (ABBREVIATED FF, SHORT FOR FILL FACT) FOR ALL PRESCRIBER DATA.
    --     ALSO FOR 'PA', MOST PRESCRIBER DATA FIELDS ARE INTENTIONALLY LEFT BLANK.
    ,PRES_PCP_NPI.PID_ID_TEXT AS PRIMARYCAREPROVIDERNPI
    ,PRES_PCP.PRS_PRESCRIBER_NUM AS INTERNALPRIMARYCAREPROVIDERID
    ,PRES_FF.PRS_LAST_NAME AS TRANSACTIONPRECRIBERLASTNAME
    ,PRES_PCP.PRS_LAST_NAME AS PRIMARYCAREPROVIDERLASTNAME
    ,PRES_FF.PRS_FIRST_NAME AS TRANSACTIONPRECRIBERFIRSTNAME
    ,PRES_PCP.PRS_FIRST_NAME AS PRIMARYCAREPROVIDERFIRSTNAME
    ,PRES_PCP_ADDR.PADR_ADDRESS1 AS PRIMARYCAREPROVIDERADDRESS1
    ,PRES_PCP_ADDR.PADR_CITY AS PRIMARYCAREPROVIDERCITY
    ,PRES_PCP_ADDR.PADR_STATE_CODE AS PRIMARYCAREPROVIDERSTATE
    ,PRES_PCP_ADDR.PADR_ZIPCODE AS PRIMARYCAREPROVIDERZIPCODE
    ,PRES_PCP_PHONE.PRSP_AREA_CODE AS PRIMARYCAREPROVIDERPHONEAREACODE
    ,PRES_PCP_PHONE.PRSP_PRESCRIBER_PHONE_NUMBER AS PRIMARYCAREPROVIDERPHONENUMBER

    --NOTE THE 'PA' FAX NUMBER IS HARD CODED BECAUSE THERE IS A DEDICATED FAX NUMBER NOT LISTED IN THE PRESCRIBER TABLE.
    ,PRES_PCP_FAX.PRSP_AREA_CODE AS PRIMARYCAREPROVIDERFAXAREACODE
    ,PRES_PCP_FAX.PRSP_PRESCRIBER_PHONE_NUMBER AS PRIMARYCAREPROVIDERFAXNUMBER

    --VACCINE INFORMATION--
    ,PR.CVX_CODE AS VACCINECVXCODE
    ,D.DRUG_LABELER AS VACCINEMANUFACTURERNAME
    ,D.DRUG_LABEL_NAME AS VACCINENAME
    ,FPF.DISPENSED_ITEM_LOT_NUMBER AS VACCINELOTNUMBER
    ,FPF.DISPENSED_ITEM_EXPIRATION_DATE AS VACCINEEXPIRATIONDATE
    ,D.DRUG_GC3 AS VACCINEINFORMATIONSTATEMENTNAME
    ,FF.RTP_DATE_KEY AS ADMINISTEREDDATE

    --ADMINISTRATION DETAILS--
    ,FF.QTY_DISPENSED AS ADMINISTEREDAMOUNT
    ,D.DRUG_PACKAGE_UNITS AS ADMINISTEREDUNITS
    ,D.DRUG_ROUTE AS ROUTEOFADMINISTRATIONDESCRIPTION

    --CARE FACILITY WHERE THE VACCINE WAS GIVEN--
    ,FID.FD_VALUE AS FACILITYNPI
    ,F.FD_FACILITY_NAME AS OTHERFACILITYIDENTIFICATION
    ,F.FD_ADDRESS1 AS FACILITYADDRESS1
    ,F.FD_ADDRESS2 AS FACILITYADDRESS2
    ,F.FD_CITY AS FACILITYCITY
    ,F.FD_STATE_CODE AS FACILITYSTATE
    ,F.FD_ZIPCODE AS FACILITYZIPCODE
    ,F.FD_PHONE1 AS FACILITYPHONENUMBER

    --PROCESSING INFORMATION--
    ,FPF.COUNSELING_ACCEPTED AS PROFESSIONALCONSULTATIONCOMPLETE

    --FIELDS NEEDED FOR BUSINESS LOGIC BUT NOT IN DATA EXTRACT--
	,D.DRUG_NDC AS LOGIC_DRUGNDC
    ,FF.FILL_FACT_KEY AS LOGIC_FILLFACTKEY
    ,FF.PD_PATIENT_KEY AS LOGIC_FILLFACTPATIENTKEY
    ,FID.FD_FACILITY_KEY AS LOGIC_FACILITYIDNUM
    ,FID.FD_DATESTAMP AS LOGIC_FACILITYIDDATESTAMP
    ,PA.PAD_ADDRESS_USAGE AS LOGIC_PATIENTADDRUSAGE
    ,PA.PAD_EFF_START_DATE AS LOGIC_PATIENTADDRCREATEDATE
    ,PRES_PCP_PHONE.PADR_KEY AS LOGIC_PRESPHONEKEY
    ,PRES_PCP_PHONE.PRSP_STATUS AS LOGIC_PRESPHONESTATUS
    ,PRES_PCP_PHONE.PRSP_SOURCE_CODE AS LOGIC_PRESPHONESOURCECODE
    ,PRES_PCP_PHONE.H_LEVEL AS LOGIC_PRESPHONEHLEVEL
    ,PRES_PCP_FAX.PADR_KEY AS LOGIC_PRESFAXKEY
    ,PRES_PCP_FAX.PRSP_STATUS AS LOGIC_PRESFAXSTATUS
    ,PRES_PCP_FAX.PRSP_SOURCE_CODE AS LOGIC_PRESFAXSOURCECODE
    ,PRES_PCP_FAX.H_LEVEL AS LOGIC_PRESFAXHLEVEL
    ,PRES_PCP_NPI.PRS_PRESCRIBER_KEY AS LOGIC_PRESNPIPRESKEY
    ,PRES_PCP_NPI.H_LEVEL AS LOGIC_PRESNPIHLEVEL
    ,FPF.ORDER_NUM AS LOGIC_FPFORDERNUM
    ,FPF.RESPONSIBLE_PARTY_KEY AS LOGIC_FPFRESPPARTYKEY
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F
        ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY  
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FID
        ON FID.FD_FACILITY_KEY = F.FD_FACILITY_NUM
       AND FID.FD_TYPE = 'F08'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT P
        ON P.PD_PATIENT_KEY = FF.PD_PATIENT_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_PHONE PP
        ON PP.PD_PATIENT_KEY = FF.PD_PATIENT_KEY
       AND PP.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS PA
        ON PA.PD_PATIENT_KEY = FF.PD_PATIENT_KEY
       AND PA.PAD_EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_DEMOGRAPHIC PD
        ON PD.PATIENT_DEMOGRAPHIC_KEY = FF.PATIENT_DEMOGRAPHIC_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES_PCP
        ON PRES_PCP.PRS_PRESCRIBER_NUM = P.PD_PRESCRIBER_NUM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES_FF
        ON PRES_FF.PRS_PRESCRIBER_KEY = FF.PRS_PRESCRIBER_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ADDRESS PRES_PCP_ADDR
        ON PRES_PCP_ADDR.PRS_PRESCRIBER_KEY = PRES_PCP.PRS_PRESCRIBER_KEY
       AND PRES_PCP_ADDR.PADR_IS_DEFAULT = 'Y'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_PHONE PRES_PCP_PHONE
        ON PRES_PCP_PHONE.PADR_KEY = PRES_PCP_ADDR.PADR_KEY
       AND PRES_PCP_PHONE.PRSP_PHONE_ADDRESS_TYPE = 'PRIM'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_PHONE PRES_PCP_FAX
        ON PRES_PCP_FAX.PADR_KEY = PRES_PCP_ADDR.PADR_KEY
       AND PRES_PCP_FAX.PRSP_PHONE_ADDRESS_TYPE = 'FAX'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PRES_PCP_NPI
        ON PRES_PCP_NPI.PRS_PRESCRIBER_KEY = PRES_PCP.PRS_PRESCRIBER_KEY
       AND PRES_PCP_NPI.PIT_KEY = 509 --SEE {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ID_TYPE.PIT_ID_DESCRIPTION = 'NATIONAL PROVIDER IDENTIFIER (NPI)'
       AND PRES_PCP_NPI.PID_STATUS = 'A'
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
         ON D.DRUG_KEY = FF.DISPENSED_DRUG_KEY
        AND D.DRUG_ROUTE != 'ORAL'
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PR
         ON PR.PRD_DRUG_NUM = D.DRUG_NUM
        AND PR.PRD_DEACTIVATE_DATE IS NULL
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT_IDENTIFIER PI
         ON PI.PRD_PRODUCT_KEY = PR.PRD_PRODUCT_KEY
        AND PI.IDENTIFIER = 'VAX'
        AND PI.IS_ACTIVE = 'Y'
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_PRICING_FACT FPF
         ON FPF.SOLD_DATE_KEY = FF.SOLD_DATE_KEY
        AND FPF.RX_FILL_SEQ = FF.RX_FILL_SEQ
        AND FPF.PARTITION_DATE BETWEEN (:RUNDATE - 60) AND (:RUNDATE + 1)
WHERE FF.PARTITION_DATE BETWEEN (:RUNDATE - 60) AND (:RUNDATE + 1)
  AND FF.SOLD_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
  AND FF.CANCEL_DATE_KEY = 0
  --EXCLUDE PREVIOUSLY SOLD PRESCRIPTIONS (SOME UPDATED RECORDS TO EXCLUDE MAY APPEAR LIKE A NEW SOLD RECORD BECAUSE IT WAS BARD).
  AND NOT EXISTS (
        SELECT  *
        FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT PRIOR_SALES
        WHERE PRIOR_SALES.FACILITY_NUM = F.FD_FACILITY_NUM
          AND PRIOR_SALES.RX_NUMBER = FF.RX_NUMBER
          AND PRIOR_SALES.REFILL_NUM = FF.REFILL_NUM
          AND PRIOR_SALES.DISPENSED_DRUG_NUM = D.DRUG_NUM
          AND PRIOR_SALES.FILL_STATE_CODE = '14' --SOLD
          AND PRIOR_SALES.IS_SAME_DAY_REVERSAL = 'N'
		  --PRESCIPTION NUMBERS ARE ONLY VALID FOR UP TO ONE YEAR.
          AND PRIOR_SALES.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 365) AND (:RUNDATE - 2 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')		  
      )
  AND (
        (PI.IDENTIFIER = 'VAX' AND PI.IS_ACTIVE = 'Y')
        OR
        (D.DRUG_GC3 IN (
           'COVID-19 VACCINES'
          ,'ENTERIC VIRUS VACCINES'
          ,'GRAM NEGATIVE COCCI VACCINES'
          ,'GRAM POSITIVE COCCI VACCINES'
          ,'INFLUENZA VIRUS VACCINES'
          ,'NEUROTOXIC VIRUS VACCINES'
          ,'TOXIN-PRODUCING BACILLI VACCINES/TOXOIDS'
          ,'VACCINE/TOXOID PREPARATIONS,COMBINATIONS'
          ,'GRAM (-) BACILLI (NON-ENTERIC) VACCINES'
          ,'VIRAL/TUMORIGENIC VACCINES'
          ,'ANTINEOPLASTICS,MISCELLANEOUS'
          )
        )
	    OR
        --NEW FLU SHOTS FOR FALL 2018, PER SR 208272
        (D.DRUG_NDC IN (
           '00000000010'
          ,'00000000042'
          ,'00000000057'
          ,'00000000043'
          ,'00000000056'
          ,'00000000045'
          ,'00000000046'
          ,'00000000048'
          ,'00000000049'
          ,'00000000050'
          ,'00000000051'
          ,'00000000052'
          ,'00000000053'
          ,'00000000054'
          ,'00000000055'
          ,'00000000047'
          ,'00000000044'
          ,'33332041810'
          ,'33332031801'
          ,'33332011810'
          ,'58160089841'
          ,'58160089852'
          ,'49281071888'
          ,'49281071810'
          ,'70461031803'
          ,'19515090952'
          ,'19515090941'
          ,'19515090011'
          ,'19515090001'
          ,'66019030510'
          ,'49281040365'
          ,'49281040388'
          ,'49281041888'
          ,'49281041850'
          ,'49281062978'
          ,'49281062915'
          ,'49281041810'
          ,'49281041858'
          ,'49281051800'
          ,'49281051825'
          ,'00000000037'
          ,'00000000038'
          ,'00000000039'
          ,'00000000040'
          )
        )
      )