WITH LOGIN_TIMES AS (
    SELECT
         SEA.DATE_KEY AS LOGIN_DATE
        ,USER_NAME.SYS_USER_LOGIN_NAME AS USER_LOGIN_NAME
        ,USER_NAME.SYS_USER_FNAME AS USER_FIRST_NAME 
        ,USER_NAME.SYS_USER_LNAME AS USER_LAST_NAME
        ,CASE WHEN USER_ROLE.ROLE_SET LIKE '%SUPER%' THEN 'SUPER USER'
              WHEN USER_ROLE.ROLE_SET LIKE '%RPH%' THEN 'RPH'
              WHEN USER_ROLE.ROLE_SET LIKE '%INTERN%' THEN 'INTERN'
              WHEN USER_ROLE.ROLE_SET LIKE '%TECH%' THEN 'TECH'
              WHEN USER_ROLE.ROLE_SET LIKE '%EXTERN%' THEN 'EXTERN'
              WHEN USER_ROLE.ROLE_SET LIKE '%STL%' THEN 'STL'      
              ELSE 'OTHER'
         END AS USER_JOB_ROLE 
        ,FAC.FD_FACILITY_ID AS STORE_NBR
        ,SEA.FD_FACILITY_KEY
        ,LISTAGG(DISTINCT TO_CHAR(SEA.SAE_START_TIME::DATE,'HH24:MI:SS'),',')
         WITHIN GROUP (ORDER BY TO_CHAR(SEA.SAE_START_TIME::DATE, 'HH24:MI:SS')) AS LOGIN_TIMES_CSV
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYSTEM_EVENT_AUDIT SEA
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
            ON FAC.FD_FACILITY_KEY = SEA.FD_FACILITY_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER USER_NAME
            ON USER_NAME.SYS_USER_KEY = SEA.SYS_USER_KEY
         INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.SYSTEM_USER USER_ROLE
            ON USER_ROLE.SYSTEM_USER_NUM = USER_NAME.SYS_USER_NUM
           AND USER_ROLE.H_LEVEL = USER_NAME.H_LEVEL
    WHERE USER_NAME.SYS_USER_LOGIN_NAME NOT IN ('SYSTEM','SCHEDULEDTASK')
      AND SEA.SAE_AUDIT_NAME = 'COM.TECHRX.SECURITY.MODULE.RDACLOGINMODULE.LOGIN'
      AND SEA.SAE_START_TIME BETWEEN
          NEXT_DAY(TRUNC(:RUNDATE, 'DAY') - 14, 'SUN') AND
          NEXT_DAY(TRUNC(:RUNDATE, 'DAY') - 7, 'SAT') + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS'
      AND (SEA.TIME_KEY BETWEEN 0 AND 25200 --BETWEEN MIDNIGHT AND 7 AM
           OR
           SEA.TIME_KEY BETWEEN 79200 AND 86400 --BETWEEN 10 PM AND MIDNIGHT
          )
    GROUP BY
         SEA.DATE_KEY
        ,USER_NAME.SYS_USER_LOGIN_NAME
        ,USER_NAME.SYS_USER_FNAME
        ,USER_NAME.SYS_USER_LNAME
        ,CASE WHEN USER_ROLE.ROLE_SET LIKE '%SUPER%' THEN 'SUPER USER'
              WHEN USER_ROLE.ROLE_SET LIKE '%RPH%' THEN 'RPH'
              WHEN USER_ROLE.ROLE_SET LIKE '%INTERN%' THEN 'INTERN'
              WHEN USER_ROLE.ROLE_SET LIKE '%TECH%' THEN 'TECH'
              WHEN USER_ROLE.ROLE_SET LIKE '%EXTERN%' THEN 'EXTERN'
              WHEN USER_ROLE.ROLE_SET LIKE '%STL%' THEN 'STL'      
              ELSE 'OTHER'
         END
        ,FAC.FD_FACILITY_ID
        ,SEA.FD_FACILITY_KEY
    ORDER BY 1, 2, 3
), PRESCRIPTIONS_ACCESSED AS (
    SELECT DISTINCT 
         SEA.DATE_KEY AS LOGIN_DATE
        ,USER_NAME.SYS_USER_LOGIN_NAME AS USER_LOGIN_NAME
        ,USER_NAME.SYS_USER_FNAME AS USER_FIRST_NAME 
        ,USER_NAME.SYS_USER_LNAME AS USER_LAST_NAME 
        ,FAC.FD_FACILITY_ID AS STORE_NBR
        ,(SELECT MAX(FWF.PD_PATIENT_KEY)
          FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_WORKFLOW_FACT FWF
          WHERE FWF.FWFS_RX_RECORD_NUM = SEA.SAE_RX_RECORD_NUM
            AND FWF.FWFS_RX_FILL_SEQ = SEA.SAE_RX_FILL_SEQ
            AND FWF.FD_FACILITY_KEY = SEA.FD_FACILITY_KEY
            AND FWF.FWFS_DT_OUT <= SYSDATE()
         ) AS PD_PATIENT_KEY
        ,SEA.PATIENT_KEY
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYSTEM_EVENT_AUDIT SEA
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
            ON FAC.FD_FACILITY_KEY = SEA.FD_FACILITY_KEY
         INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER USER_NAME
            ON USER_NAME.SYS_USER_KEY = SEA.SYS_USER_KEY
         INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.SYSTEM_USER USER_ROLE
            ON USER_ROLE.SYSTEM_USER_NUM = USER_NAME.SYS_USER_NUM
           AND USER_ROLE.H_LEVEL = USER_NAME.H_LEVEL
    WHERE (SEA.DATE_KEY, USER_NAME.SYS_USER_LOGIN_NAME, FAC.FD_FACILITY_ID) IN (
              SELECT LOGIN_DATE, LOGIN_NAME, STORE_NBR
              FROM LOGIN_TIMES
          )
      AND SEA.SAE_START_TIME BETWEEN
          NEXT_DAY(TRUNC(:RUNDATE, 'DAY') - 14, 'SUN') AND
          NEXT_DAY(TRUNC(:RUNDATE, 'DAY') - 7, 'SAT') + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS'
      AND (SEA.TIME_KEY BETWEEN 0 AND 25200 --BETWEEN MIDNIGHT AND 7 AM
           OR
           SEA.TIME_KEY BETWEEN 79200 AND 86400 --BETWEEN 10 PM AND MIDNIGHT
          )
    ORDER BY 1, 2, 3, 4
), PATIENTS_ACCESSED AS (
    SELECT
         PA.LOGIN_DATE
        ,PA.USER_LOGIN_NAME
        ,PA.USER_FIRST_NAME 
        ,PA.USER_LAST_NAME 
        ,PA.STORE_NBR
        ,LISTAGG(DISTINCT P.PD_PATIENT_NUM,',')
         WITHIN GROUP (ORDER BY P.PD_PATIENT_NUM) AS PATIENT_NUMS_CSV
        ,LISTAGG(DISTINCT P.PD_LAST_NAME,',')
         WITHIN GROUP (ORDER BY P.PD_PATIENT_NUM) AS PATIENT_NAMES_CSV
    FROM PRESCRIPTIONS_ACCESSED PA
         LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT P
            ON (P.PD_PATIENT_KEY = PA.PD_PATIENT_KEY OR
                P.PD_PATIENT_KEY = PA.PATIENT_KEY)
    GROUP BY
         PA.LOGIN_DATE
        ,PA.USER_LOGIN_NAME
        ,PA.USER_FIRST_NAME 
        ,PA.USER_LAST_NAME
        ,PA.STORE_NBR
    ORDER BY 1, 2, 3
)
SELECT
     LT.USER_LOGIN_NAME
    ,LT.USER_FIRST_NAME 
    ,LT.USER_LAST_NAME 
    ,LT.USER_JOB_ROLE
    ,LT.STORE_NBR
    ,LT.LOGIN_DATE
    ,LT.LOGIN_TIMES_CSV
    ,PA.PATIENT_NUMS_CSV
    ,PA.PATIENT_NAMES_CSV
FROM LOGIN_TIMES LT
     LEFT OUTER JOIN PATIENTS_ACCESSED PA
        ON PA.LOGIN_DATE = LT.LOGIN_DATE
       AND PA.USER_LOGIN_NAME = LT.USER_LOGIN_NAME
       AND PA.STORE_NBR = LT.STORE_NBR
ORDER BY 3, 4, 5