WITH STEP_KEYS AS (
    SELECT
        F.FWFS_KEY,          
        F.FWFS_RX_RECORD_NUM,
        F.FWFS_RX_FILL_SEQ,
        F.FWFS_DT_IN,
        F.FWFS_DT_OUT,
        F.FWFS_RX_NUMBER,
        F.PD_PATIENT_KEY,
        F.OWNING_FACILITY_KEY,
        F.FD_FACILITY_KEY,
        F.FWFS_COMPLETE_FACILITY_KEY,
        F.WFSD_KEY,
        F.OS_ORDER_SOURCE_KEY,
        F.DRUG_KEY,
        F.NEXT_WFSD_KEY,
        F.DM_DELIVERY_METHOD_KEY,
        F.FS_FILL_STATUS_KEY,
        F.CENTRAL_FILL_INDICATOR_KEY,
        F.DR_DECLINE_REASON_KEY,
        F.SYS_USER_KEY,        
        F.PADR_KEY,
        F.PRS_PRESCRIBER_KEY,
        F.PRD_PRODUCT_KEY,
        F.FWFS_DT_QUEUE,
        F.READY_DATE,
        F.FWFS_PICKUP_TIME,
        F.FWFS_IS_BAR,
        F.RX_TRANSACTION_CODE,
        F.FWFS_ORDER_PRIORITY,
        F.IS_OUT_OF_STOCK,
        F.FWFS_QTY_DISPENSED,
        F.WRITTEN_QTY,
        F.FWFS_IS_DECLINED,
        F.FWFS_ORDER_DATE,
        F.FACILITY_ORDER_NUMBER,
        F.PARTIAL_FILL_SEQ,
        F.FWFS_REFILL_NUM
    FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_WORKFLOW_FACT F
    WHERE F.FWFS_DT_OUT BETWEEN (:RUNDATE - 1) 
                            AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
), FILLS AS (
    SELECT 
         MAX_RX_FILL.SKIP_PRE_VER_CODE
        ,MAX_RX_FILL.DAYS_SUPPLY
        ,MAX_RX_FILL.RX_RECORD_NUM
        ,MAX_RX_FILL.RX_FILL_SEQ
        ,MAX_RX_FILL.FWFS_DT_OUT
        
         --NEW FIELDS ARE BELOW HERE
        ,MAX_RX_FILL.RXF_DISPENSE_DATE --DATE
        ,MAX_RX_FILL.RXF_DAYS_SUPPLY --NUMBER(9,3)
        ,MAX_RX_FILL.RXF_QTY_DISPENSED --NUMBER(13,3)
        ,MAX_RX_FILL.RXF_METRIC_QTY_DISPENSED --NUMBER(13,5)
        ,MAX_RX_FILL.RXF_INTENDED_QTY_DISPENSED --NUMBER(13,3)
        ,MAX_RX_FILL.RXF_INTENDED_DAYS_SUPPLY --NUMBER(9,3)
        ,MAX_RX_FILL.RXF_IS_CENTRAL_FILL --CHAR(1)
        ,MAX_RX_FILL.RXF_SELECTED_UPC --VARCHAR2(20)
        ,MAX_RX_FILL.RXF_RTP_DATE --DATE
        ,MAX_RX_FILL.RXF_READY_DATE --DATE
        ,MAX_RX_FILL.RXF_IS_340B --CHAR(1)
        ,MAX_RX_FILL.RXF_IS_CASH --CHAR(1)
        ,MAX_RX_FILL.RXF_SKIP_PRE_VER_CODE --NUMBER(2)
    
        ,MAX_RX_FILL.ADS_ACTUAL_SHIPPING_METHOD --VARCHAR2(100)
        ,MAX_RX_FILL.ADS_ACTUAL_SHIP_CHARGE --NUMBER(12,2)
        ,MAX_RX_FILL.ADS_ACTUAL_SHIP_DATE --DATE
        ,MAX_RX_FILL.ADS_ESTIMATED_DELIVERY_DATE --DATE
        ,MAX_RX_FILL.ADS_TOTE_LICENSE_PLATE --VARCHAR2(50)
        ,MAX_RX_FILL.ADS_MANIFEST_DELIVERY_DATE --VARCHAR2(50)
        ,MAX_RX_FILL.ADS_EXCEPTION_TEXT --VARCHAR2(250)
        ,MAX_RX_FILL.ADS_EXTERNAL_ORDER_NUMBER --VARCHAR2(12)
        ,MAX_RX_FILL.ADS_REJECT_CODE --VARCHAR2(10)
        ,MAX_RX_FILL.ADS_QTY_DISPENSED --QTY_PICKED --NUMBER(13,3)
        ,MAX_RX_FILL.ADS_NUMBER_OF_VIALS --NUMBER(3)
        ,MAX_RX_FILL.ADS_PACKAGE_SIZE --NUMBER(13,3)
        ,MAX_RX_FILL.ADS_DATE_COMPLETED --DATE
        ,MAX_RX_FILL.ADS_DATE_FILLED --DATE
        ,MAX_RX_FILL.ADS_NDC_REQUESTED --VARCHAR2(13)
        ,MAX_RX_FILL.ADS_NDC_DISPENSED --VARCHAR2(13)
        ,MAX_RX_FILL.ADS_QC_INITIALS --VARCHAR2(3)
        ,MAX_RX_FILL.ADS_IS_EASY_OPEN_CAP --CHAR(1)
        ,MAX_RX_FILL.ADS_STATUS_CODE --VARCHAR2(10)
        ,MAX_RX_FILL.ADS_STATUS_DESC --VARCHAR2(36)
        ,MAX_RX_FILL.ADS_DATE_UPDATED --DATE
        ,MAX_RX_FILL.ADS_DATESTAMP --DATE
        
        ,MAX_RX_FILL.MAN_CHECK_OUT_DATESTAMP --DATE
        ,MAX_RX_FILL.MAN_CHECK_IN_DATESTAMP --DATE
        ,MAX_RX_FILL.MAN_DATESTAMP --DATE
        ,MAX_RX_FILL.MAN_IS_PULLED_BACK --CHAR(1)
		
        ,MAX_RX_FILL.ORDER_NUM
        ,MAX_RX_FILL.ITEM_SEQ
    FROM (
        SELECT 
             AUD__ITEM.ORDER_NUM
            ,AUD__ITEM.ITEM_SEQ
            ,AUD__RX_FILL.SKIP_PRE_VER_CODE
            ,AUD__RX_FILL.DAYS_SUPPLY
            ,AUD__RX_FILL.RX_RECORD_NUM
            ,AUD__RX_FILL.RX_FILL_SEQ
            ,STEPS.FWFS_DT_OUT
                         
            --NEW FIELDS ARE BELOW HERE        
            ,ROUND((AUD__RX_FILL.DISPENSE_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_DISPENSE_DATE --DATE
            ,AUD__RX_FILL.DAYS_SUPPLY AS RXF_DAYS_SUPPLY --NUMBER(9,3)
            ,AUD__RX_FILL.QTY_DISPENSED AS RXF_QTY_DISPENSED --NUMBER(13,3)
            ,AUD__RX_FILL.METRIC_QTY_DISPENSED AS RXF_METRIC_QTY_DISPENSED --NUMBER(13,5)
            ,AUD__RX_FILL.INTENDED_QTY_DISPENSED AS RXF_INTENDED_QTY_DISPENSED --NUMBER(13,3)
            ,AUD__RX_FILL.INTENDED_DAYS_SUPPLY AS RXF_INTENDED_DAYS_SUPPLY --NUMBER(9,3)
            ,AUD__RX_FILL.IS_CENTRAL_FILL AS RXF_IS_CENTRAL_FILL --CHAR(1)
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__RX_FILL.SELECTED_UPC),1,20) AS RXF_SELECTED_UPC --VARCHAR2(20)
            ,ROUND((AUD__RX_FILL.RELEASED_TO_PATIENT_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_RTP_DATE --DATE
            ,ROUND((AUD__RX_FILL.READY_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_READY_DATE --DATE
            ,AUD__RX_FILL.IS_340B AS RXF_IS_340B --CHAR(1)
            ,AUD__RX_FILL.IS_CASH AS RXF_IS_CASH --CHAR(1)
            ,AUD__RX_FILL.SKIP_PRE_VER_CODE AS RXF_SKIP_PRE_VER_CODE --NUMBER(2)
        
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.ACTUAL_SHIPPING_METHOD),1,100) AS ADS_ACTUAL_SHIPPING_METHOD --VARCHAR2(100)
            ,AUD__ADS_RESPONSE.ACTUAL_SHIP_CHARGE AS ADS_ACTUAL_SHIP_CHARGE --NUMBER(12,2)
            ,ROUND((AUD__ADS_RESPONSE.ACTUAL_SHIP_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_ACTUAL_SHIP_DATE --DATE
            ,ROUND((AUD__ADS_RESPONSE.ESTIMATED_DELIVERY_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_ESTIMATED_DELIVERY_DATE --DATE
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.TOTE_LICENSE_PLATE),1,50) AS ADS_TOTE_LICENSE_PLATE --VARCHAR2(50)
            ,ROUND((TO_DATE(AUD__ADS_RESPONSE.MANIFEST_SYS_EST_DELIVERY_DATE,'MM/DD/YYYY HH:MI AM') - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_MANIFEST_DELIVERY_DATE --VARCHAR2(50)
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.EXCEPTION_TEXT),1,250) AS ADS_EXCEPTION_TEXT --VARCHAR2(250)
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.EXTERNAL_ORDER_NUMBER),1,12) AS ADS_EXTERNAL_ORDER_NUMBER --VARCHAR2(12)
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.REJECT_CODE),1,10) AS ADS_REJECT_CODE --VARCHAR2(10)
            ,AUD__ADS_RESPONSE.QTY_DISPENSED AS ADS_QTY_DISPENSED --QTY_PICKED --NUMBER(13,3)
            ,AUD__ADS_RESPONSE.NUMBER_OF_VIALS AS ADS_NUMBER_OF_VIALS --NUMBER(3)
            ,AUD__ADS_RESPONSE.PACKAGE_SIZE AS ADS_PACKAGE_SIZE --NUMBER(13,3)
            ,ROUND((AUD__ADS_RESPONSE.DATE_COMPLETED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_COMPLETED --DATE
            ,ROUND((AUD__ADS_RESPONSE.DATE_FILLED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_FILLED --DATE
            ,AUD__ADS_RESPONSE.NDC_REQUESTED AS ADS_NDC_REQUESTED --VARCHAR2(13)
            ,AUD__ADS_RESPONSE.NDC_DISPENSED AS ADS_NDC_DISPENSED --VARCHAR2(13)
            ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.QC_INITIALS),1,3) AS ADS_QC_INITIALS --VARCHAR2(3)
            ,AUD__ADS_RESPONSE.IS_EASY_OPEN_CAP AS ADS_IS_EASY_OPEN_CAP --CHAR(1)
            ,AUD__ADS_RESPONSE.STATUS AS ADS_STATUS_CODE --VARCHAR2(10)
            ,(CASE AUD__ADS_RESPONSE.STATUS
                   WHEN 'A' THEN 'RX ACCEPTED - FILLING AT CF FACILITY'
                   WHEN 'H' THEN 'ORDER SHIPPED'
                   WHEN 'P' THEN 'COMPLETE - FILLED AT STORE'
                   WHEN 'R' THEN 'RX REJECTED BY CFD'
                   WHEN 'V' THEN 'RECEIVED AT STORE'
                   WHEN 'C' THEN 'ORDER CANCELLED'
                   WHEN 'E' THEN 'ERROR IN PROCESSING RESPONSE'
                   WHEN 'F' THEN 'REFUSED CANCEL'
                   ELSE NULL    
              END) AS ADS_STATUS_DESC --VARCHAR2(36)
            ,ROUND((AUD__ADS_RESPONSE.DATE_UPDATED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_UPDATED --DATE
            ,ROUND((AUD__ADS_RESPONSE.DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATESTAMP --DATE
            
            ,ROUND((AUD__MANIFEST_ITEM.CHECK_OUT_DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_CHECK_OUT_DATESTAMP --DATE
            ,ROUND((AUD__MANIFEST_ITEM.CHECK_IN_DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_CHECK_IN_DATESTAMP --DATE
            ,ROUND((AUD__MANIFEST_ITEM.DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_DATESTAMP --DATE
            ,AUD__MANIFEST_ITEM.IS_PULLED_BACK AS MAN_IS_PULLED_BACK --CHAR(1)
                         
            ,RANK() OVER (PARTITION BY 
                               AUD__RX_FILL.RX_RECORD_NUM
                              ,AUD__RX_FILL.RX_FILL_SEQ
                              ,STEPS.FWFS_DT_OUT
                              ,AUD__ITEM.ORDER_NUM
                              ,AUD__ITEM.ITEM_SEQ
                          ORDER BY 
                               AUD__RX_FILL.H_LEVEL DESC
                              --,AUD__ITEM.EFF_START_DATE DESC
                              --,AUD__ITEM.EFF_END_DATE DESC
                              ,AUD__ADS_RESPONSE.EFF_START_DATE DESC
                              ,AUD__ADS_RESPONSE.EFF_END_DATE DESC
                              ,AUD__MANIFEST_ITEM.EFF_START_DATE --DESC
                              ,AUD__MANIFEST_ITEM.EFF_END_DATE DESC
                              ,ROW_NUMBER() OVER (ORDER BY AUD__RX_FILL.H_LEVEL) DESC
                         ) AS CENTRALFILL_RANK

        FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_FILL AUD__RX_FILL
             INNER JOIN STEP_KEYS STEPS
                ON AUD__RX_FILL.RX_RECORD_NUM = STEPS.FWFS_RX_RECORD_NUM
               AND AUD__RX_FILL.RX_FILL_SEQ = STEPS.FWFS_RX_FILL_SEQ
               AND STEPS.FWFS_DT_OUT BETWEEN CONVERT_TIMEZONE('UTC', 'US/EASTERN', CAST(AUD__RX_FILL.DATESTAMP AS TIMESTAMP)) AND AUD__RX_FILL.EFF_END_DATE
             LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM AUD__ITEM
                ON AUD__ITEM.RX_RECORD_NUM = STEPS.FWFS_RX_RECORD_NUM
               AND AUD__ITEM.RX_FILL_SEQ = STEPS.FWFS_RX_FILL_SEQ
               --AND STEPS.FWFS_DT_OUT BETWEEN AUD__ITEM.EFF_START_DATE AND AUD__ITEM.EFF_END_DATE
               AND STEPS.FWFS_DT_OUT BETWEEN CAST(FROM_TZ(CAST(AUD__ITEM.EFF_START_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/EASTERN' AS DATE)
                                         AND CAST(FROM_TZ(CAST(AUD__ITEM.EFF_END_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/EASTERN' AS DATE)
             LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ADS_RESPONSE AUD__ADS_RESPONSE
                ON AUD__ADS_RESPONSE.ORDER_NUM = AUD__ITEM.ORDER_NUM
               AND AUD__ADS_RESPONSE.ITEM_SEQ = AUD__ITEM.ITEM_SEQ
               AND STEPS.FWFS_DT_OUT >= AUD__ADS_RESPONSE.DATE_UPDATED
             LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.MANIFEST_ITEM AUD__MANIFEST_ITEM
                ON AUD__MANIFEST_ITEM.ORDER_NUM = AUD__ITEM.ORDER_NUM
               AND AUD__MANIFEST_ITEM.ITEM_SEQ = AUD__ITEM.ITEM_SEQ
               AND (STEPS.FWFS_DT_OUT = CAST(FROM_TZ(CAST(AUD__MANIFEST_ITEM.EFF_START_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/EASTERN' AS DATE)
                    OR 
                    AUD__MANIFEST_ITEM.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
                    )
               AND STEPS.FWFS_DT_OUT <= CAST(FROM_TZ(CAST(AUD__MANIFEST_ITEM.EFF_END_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'US/EASTERN' AS DATE)
         ) MAX_RX_FILL
    WHERE MAX_RX_FILL.CENTRALFILL_RANK = 1
)
SELECT
	OWNSTORE.FD_FACILITY_ID "STORE_NUM",
	WLBSTORE.FD_FACILITY_ID "STORE_NUM_WLB",
	REGEXP_REPLACE(FWF.FWFS_RX_NUMBER, '[^0-9]+', '') "RX_NUM",
	FWF.FWFS_RX_NUMBER "RX_NUM_TXT",
	FWF.FWFS_REFILL_NUM "REFILL_NUM",
	TO_NUMBER(NVL(FWF.PARTIAL_FILL_SEQ,'0')) "PART_SEQ_NUM",
	PATIENT.PD_PATIENT_NUM "PATIENT_NUM",
	FWF.FACILITY_ORDER_NUMBER "ORDER_NUM",
	WFS.WFSD_STEP_DESCRIPTION "WFS_DESC",
	TO_NUMBER(TO_CHAR(FWF.FWFS_ORDER_DATE::DATE,'YYYYMMDD')) "ORDER_DATE",	
	
	NVL(BPV.SKIP_PRE_VER_CODE,0) "BYPASSPV",

	TO_NUMBER(TO_CHAR(FWF.FWFS_DT_IN::DATE,'YYYYMMDD')) "DATE_ENTERED_WFS",
	ROUND((FWF.FWFS_DT_IN - TO_DATE('20350101','YYYYMMDD')),6) "DATETIME_ENTERED_WFS",
	TO_NUMBER(TO_CHAR(FWF.FWFS_DT_OUT::DATE,'YYYYMMDD')) "DATE_EXITED_WFS",
	ROUND((FWF.FWFS_DT_OUT - TO_DATE('20350101','YYYYMMDD')),6) "DATETIME_EXITED_WFS",

	ROUND(((FWF.FWFS_DT_OUT - FWF.FWFS_DT_IN) * 86400),0) "STEP_DUR_SECONDS",  

    CASE
        WHEN INSTR(SYSUSER.SYS_USER_LOGIN_NAME, '@') > 0 THEN
             TRIM(SUBSTR(SYSUSER.SYS_USER_LOGIN_NAME, 1, INSTR(SYSUSER.SYS_USER_LOGIN_NAME, '@') - 1))
        ELSE TRIM(SYSUSER.SYS_USER_LOGIN_NAME)
    END AS "EMP_LOGIN_NAME",
	
    WEGMANS.CLEAN_STRING_FORTENUP(USERROLE.DISPLAY_NAME) "EMP_DISPLAYNAME",
    	CASE
        	WHEN USERROLE.ROLE_SET LIKE '%SUPER%' THEN 'SUPER USER'
        	WHEN USERROLE.ROLE_SET LIKE '%RPH%' THEN 'RPH'
        	WHEN USERROLE.ROLE_SET LIKE '%INTERN%' THEN 'INTERN'
        	WHEN USERROLE.ROLE_SET LIKE '%TECH%' THEN 'TECH'
        	WHEN USERROLE.ROLE_SET LIKE '%EXTERN%' THEN 'EXTERN'
        	WHEN USERROLE.ROLE_SET LIKE '%STL%' THEN 'STL'      
        	ELSE 'OTHER'
    	END "EMP_ERX_ROLE",
	REPLACE(USERROLE.ROLE_SET,',','/') "RIGHTSROLES",

	NEXTWFS.WFSD_STEP_DESCRIPTION "NEXT_WFS_DESC",
	FWF.FWFS_IS_DECLINED "IS_DECLINED",
	DR.DR_DECLINE_REASON "DECLINE_REASON",
  
	DRUG.DRUG_NDC "NDC_WO",
	WEGMANS.CLEAN_STRING_FORTENUP(DRUG.DRUG_LABEL_NAME) "DRUG_NAME",
	FWF.WRITTEN_QTY "QTY_WRITTEN",
	FWF.FWFS_QTY_DISPENSED "QTY_DISPENSED",    
	
	NVL(BPV.DAYS_SUPPLY,0) "DAYS_SUPPLY",

	ORDERSOURCE.OS_ORDER_SOURCE_DESC "ORDER_SOURCE",
	DELMETHOD.DM_DELIVERY_METHOD_DESC "DEL_METHOD",
    FILLSTAT.FS_FILL_STATUS_DESC "STATUS_DESC",
	NVL(FWF.IS_OUT_OF_STOCK,'N') "IS_OUTOFSTOCK",
	FWF.FWFS_ORDER_PRIORITY "ORDER_PRIORITY",
	CFIND.IS_CENTRAL_FILL "CF_IND",
	CFIND.IS_PULLED_BACK "PULLED_BACK",
	CFIND.IS_PACKED "IS_CF_PACKED",
	CFIND.IS_CENTRAL_FILL_DECLINED "CF_INSTOCK_DECLINED",
	FWF.RX_TRANSACTION_CODE "TX_NUMBER",
	NVL(FWF.FWFS_IS_BAR,'N') "IS_BAR",

	TO_NUMBER(TO_CHAR(FWF.FWFS_PICKUP_TIME::DATE,'YYYYMMDD')) "PICKUP_DATE",
	ROUND((FWF.FWFS_PICKUP_TIME - TO_DATE('20350101','YYYYMMDD')),6) "PICKUP_DATETIME",
	TO_NUMBER(TO_CHAR(FWF.READY_DATE::DATE,'YYYYMMDD')) "READY_DATE",
	ROUND((FWF.READY_DATE - TO_DATE('20350101','YYYYMMDD')),6) "READY_DATETIME",
	TO_NUMBER(TO_CHAR(FWF.FWFS_DT_QUEUE::DATE,'YYYYMMDD')) "INITIAL_WFS_DATE",
	ROUND((FWF.FWFS_DT_QUEUE - TO_DATE('20350101','YYYYMMDD')),6) "INITIAL_WFS_DATETIME",
  
	FWF.FWFS_RX_RECORD_NUM "RX_RECORD_NUM",
	FWF.FWFS_RX_FILL_SEQ "RX_FILL_SEQ",
	FWF.DRUG_KEY "DRUG_KEY",
	FWF.PRD_PRODUCT_KEY "PRODUCT_KEY",
	FWF.PRS_PRESCRIBER_KEY "PRESCRIBER_KEY",
	FWF.PADR_KEY "PADR_KEY",
	SYSUSER.SYS_USER_KEY "SYS_USER_KEY",
	FWF.FWFS_KEY "FWFS_KEY"
	
    --NEW FIELDS ARE BELOW HERE
    ,BPV.RXF_DISPENSE_DATE --DATE
    ,BPV.RXF_DAYS_SUPPLY --NUMBER(9,3)
    ,BPV.RXF_QTY_DISPENSED --NUMBER(13,3)
    ,BPV.RXF_METRIC_QTY_DISPENSED --NUMBER(13,5)
    ,BPV.RXF_INTENDED_QTY_DISPENSED --NUMBER(13,3)
    ,BPV.RXF_INTENDED_DAYS_SUPPLY --NUMBER(9,3)
    ,BPV.RXF_IS_CENTRAL_FILL --CHAR(1)
    ,BPV.RXF_SELECTED_UPC --VARCHAR2(20)
    ,BPV.RXF_RTP_DATE --DATE
    ,BPV.RXF_READY_DATE --DATE
    ,BPV.RXF_IS_340B --CHAR(1)
    ,BPV.RXF_IS_CASH --CHAR(1)
    ,BPV.RXF_SKIP_PRE_VER_CODE --NUMBER(2)

    ,BPV.ADS_ACTUAL_SHIPPING_METHOD --VARCHAR2(100)
    ,BPV.ADS_ACTUAL_SHIP_CHARGE --NUMBER(12,2)
    ,BPV.ADS_ACTUAL_SHIP_DATE --DATE
    ,BPV.ADS_ESTIMATED_DELIVERY_DATE --DATE
    ,BPV.ADS_TOTE_LICENSE_PLATE --VARCHAR2(50)
    ,BPV.ADS_MANIFEST_DELIVERY_DATE --VARCHAR2(50)
    ,BPV.ADS_EXCEPTION_TEXT --VARCHAR2(250)
    ,BPV.ADS_EXTERNAL_ORDER_NUMBER --VARCHAR2(12)
    ,BPV.ADS_REJECT_CODE --VARCHAR2(10)
    ,BPV.ADS_QTY_DISPENSED --QTY_PICKED --NUMBER(13,3)
    ,BPV.ADS_NUMBER_OF_VIALS --NUMBER(3)
    ,BPV.ADS_PACKAGE_SIZE --NUMBER(13,3)
    ,BPV.ADS_DATE_COMPLETED --DATE
    ,BPV.ADS_DATE_FILLED --DATE
    ,BPV.ADS_NDC_REQUESTED --VARCHAR2(13)
    ,BPV.ADS_NDC_DISPENSED --VARCHAR2(13)
    ,BPV.ADS_QC_INITIALS --VARCHAR2(3)
    ,BPV.ADS_IS_EASY_OPEN_CAP --CHAR(1)
    ,BPV.ADS_STATUS_CODE --VARCHAR2(10)
    ,BPV.ADS_STATUS_DESC --VARCHAR2(36)
    ,BPV.ADS_DATE_UPDATED --DATE
    ,BPV.ADS_DATESTAMP --DATE
    
    ,BPV.MAN_CHECK_OUT_DATESTAMP --DATE
    ,BPV.MAN_CHECK_IN_DATESTAMP --DATE
    ,BPV.MAN_DATESTAMP --DATE
    ,BPV.MAN_IS_PULLED_BACK --CHAR(1)
    
    ,BPV.ORDER_NUM
    ,BPV.ITEM_SEQ

FROM STEP_KEYS FWF
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PATIENT
      ON PATIENT.PD_PATIENT_KEY = FWF.PD_PATIENT_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY OWNSTORE
      ON OWNSTORE.FD_FACILITY_KEY = FWF.OWNING_FACILITY_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY WLBSTORE
      ON WLBSTORE.FD_FACILITY_KEY = FWF.FD_FACILITY_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY COMPLETESTORE
      ON COMPLETESTORE.FD_FACILITY_KEY = FWF.FWFS_COMPLETE_FACILITY_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.WF_STEP WFS
      ON WFS.WFSD_KEY = FWF.WFSD_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.ORDER_SOURCE_TYPE ORDERSOURCE
      ON ORDERSOURCE.OS_ORDER_SOURCE_KEY = FWF.OS_ORDER_SOURCE_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
      ON DRUG.DRUG_KEY = FWF.DRUG_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.WF_STEP NEXTWFS
      ON NEXTWFS.WFSD_KEY = FWF.NEXT_WFSD_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DELMETHOD
      ON DELMETHOD.DM_DELIVERY_METHOD_KEY = FWF.DM_DELIVERY_METHOD_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_STATUS_TYPE FILLSTAT
      ON FILLSTAT.FS_FILL_STATUS_KEY = FWF.FS_FILL_STATUS_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.CENTRAL_FILL_INDICATOR CFIND
      ON CFIND.CENTRAL_FILL_INDICATOR_KEY = FWF.CENTRAL_FILL_INDICATOR_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DECLINE_REASON_TYPE DR
      ON DR.DR_DECLINE_REASON_KEY = FWF.DR_DECLINE_REASON_KEY
    LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SYS_USER SYSUSER
      ON SYSUSER.SYS_USER_KEY = FWF.SYS_USER_KEY
    LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.SYSTEM_USER USERROLE
      ON USERROLE.SYSTEM_USER_NUM = SYSUSER.SYS_USER_NUM
     AND USERROLE.H_LEVEL = SYSUSER.H_LEVEL
    LEFT OUTER JOIN FILLS BPV
      ON BPV.RX_RECORD_NUM = FWF.FWFS_RX_RECORD_NUM
     AND BPV.RX_FILL_SEQ = FWF.FWFS_RX_FILL_SEQ
     AND BPV.FWFS_DT_OUT = FWF.FWFS_DT_OUT
ORDER BY FWF.FWFS_DT_OUT, FWF.FWFS_DT_IN, OWNSTORE.FD_FACILITY_ID, FWF.FWFS_RX_NUMBER