SELECT 
	 FILL_STATE_CHG_TS
	,FILL_STATE_CHG_TS_DATE
	,FILL_STATE_CHG_TS_DATETIME
	,STORE_NUM
	,STORE_NPI
	,STORE_NCPDP
	,FACILITY_NPI
	,RX_NUM
	,RX_NUM_TXT
	,REFILL_NUM
	,PARTIAL_FILL_SEQ
	,BENEFIT_GROUP_ID
	,DATE_OF_SERVICE
	,DAW_CODE
	,DAYS_SUPPLY
	,DISPENSED_DRUG_NUM
	,DISPENSED_QTY_AWP
	,FACILITY_NUM
	,FILL_STATE_CODE
	,FILL_STATE_KEY
	,FILL_STATE_PRICE_NUM
	,FINAL_PRICE
	,INCENTIVE_FEE_AMOUNT
	,INTERNAL_FILL_ID
	,IS_SAME_DAY_REVERSAL
	,MEDICAL_CONDITION_NUM
	,ORIGINAL_PRODUCT_QTY
	,PATIENT_NUM
	,PATIENT_PAY_AMOUNT
	,PRESCRIBED_DATE
	,PRESCRIBER_ADDRESS_NUM
	,PRESCRIBER_ID_DEA
	,PRESCRIBER_ID_NPI
	,PRESCRIBER_NUM
	,QTY_DISPENSED
	,REFILLS_AUTHORIZED
	,REFILLS_REMAINING
	,RX_FILL_SEQ
	,RX_ORIGIN_CODE
	,RX_RECORD_NUM
	,SHORT_FILL_STATUS
	,SPLIT_BILLING_CODE
	,TLOG_SEQUENCE_NUM
	,TOTAL_COST
	,TOTAL_FEE
	,TOTAL_UANDC
	,TOTAL_USER_DEFINED
	,TP_CURR_PATIENT_PAY_AMOUNT
	,TP_CURR_TOTAL_COST
	,TP_CURR_TOTAL_FEE
	,TP_ITEM_CLAIM_KEY
	,TP_ITEM_CLAIM_NUM
	,TP_MESSAGE_KEY
	,TP_PATIENT_NUM
	,TP_PLAN_AMOUNT_PAID
	,TP_PLAN_NUM
	,TP_PRIOR_AUTH_NUM
	,TP_PROCESSOR_DEST_NUM
	,TRANSACTION_CODE
	,IS_BAR
	,ORDER_NUM
	,FS_FILL_STATE_CHG_TS_DATETIME
	,FS_FILL_STATE_CODE
	,FS_RX_FILL_SEQ
	,FS_RX_RECORD_NUM
	,INGREDIENT_NDC1
	,INGREDIENT_NDC2
	,INGREDIENT_NDC3
	,INGREDIENT_NDC4
	,INGREDIENT_NDC5
	,INGREDIENT_NDC6
	,INGREDIENT_PRICE1
	,INGREDIENT_PRICE2
	,INGREDIENT_PRICE3
	,INGREDIENT_PRICE4
	,INGREDIENT_PRICE5
	,INGREDIENT_PRICE6
	,INGREDIENT_QTY1
	,INGREDIENT_QTY2
	,INGREDIENT_QTY3
	,INGREDIENT_QTY4
	,INGREDIENT_QTY5
	,INGREDIENT_QTY6
	,AUTHORIZATION_NUMBER
	,EMERGENCY_CONDITION_CODE
	,EXTERNAL_BILLING_INDICATOR
	,H_LEVEL        
	,TP_MESSAGE_NUM
	,BIN_NUMBER
	,PROCESSOR_CONTROL_NUMBER
	,DRUG_GCN_SEQ
	,DRUG_IS_MAINT_DRUG
	,DRUG_NDC
	,DRUG_PACKAGE_SIZE
	,DRUG_STRENGTH
	,DRUG_STRENGTH_UNITS
	,MCD_FRMTTD_COND_REF_NUM
	,PRS_PRESCRIBER_KEY
	,PRS_PRESCRIBER_NUM
	,PADR_KEY
	,PRD_IS_COMPOUND
	,PRD_IS_GENERIC
	,PRD_IS_PRICE_MAINTAINED
	,PRD_NAME
	,PRD_PACKAGE_SIZE
	,PD_PATIENT_KEY
	,TPD_CARDHOLDER_ID
	,TPD_CARDHOLDER_PATIENT_NUM
	,TPD_RELATIONSHIP_NUM
	,TPD_TP_PLAN_NUM
	,TPLD_PLAN_CODE
	,PCN
	,PCR_TP_PLAN_AMOUNT_PAID
	,PCR_CASH_TP_INDICATOR
	,PCR_FILL_STATE_PRICE_NUM
	,PCR_TOTAL_COST
	,PCR_PATIENT_PAY_AMOUNT
	,PCR_TOTAL_FEE
	,PCR_FINAL_PRICE
	,PCR_DISPENSED_QTY_AWP
	,PCR_DISPENSING_FEE_AMOUNT
	,PCR_TOTAL_USER_DEFINED
	,PCR2_TP_PLAN_AMOUNT_PAID
	,TARGET_CF_FACILITY_NUM
	,PICKUP_DATETIME
	,FACILITY_ORDER_NUMBER
	,RQ_TPMSG_KEY
	,RQ_TP_MESSAGE_NUM
	,RQ_TP_ITEM_CLAIM_NUM
	,RQ_TP_PROCESSOR_DEST_SEQ
	,RQ_TP_PROCESSOR_NUM
	,RQ_TPMSG_SUBMISSION_DATETIME
	,RQ_TPMSG_SUBMISSION_STATUS
	,RQ_TPMSG_MSG_CATEGORY
	,RQ_TPMSG_COMM_FAILURE
	,RQ_BIN_NUM
	,RQ_VERSION_RELEASE_NUM
	,RQ_TRANSACTION_CODE
	,RQ_PROCESSOR_CONTROL_NUM
	,RQ_TRANSACTION_COUNT
	,RQ_SERVICE_PROVIDER_ID_QUAL
	,RQ_SERVICE_PROVIDER_ID
	,RQ_DATE_OF_SERVICE
	,RQ_SOFTWARE_CERT_ID
	,RQ_RX_SERVICE_REF_QUAL
	,RQ_RX_SERVICE_REF_NUM
	,RQ_PRODUCT_SERVICE_ID_QUAL
	,RQ_PRODUCT_SERVICE_ID
	,RQ_QUANTITY_DISPENSED
	,RQ_FILL_NUMBER
	,RQ_DAYS_SUPPLY
	,RQ_COMPOUND_CODE
	,RQ_DAW_CODE
	,RQ_RX_WRITTEN_DATE
	,RQ_NUM_REFILLS_AUTHORIZED
	,RQ_RX_ORIGIN_CODE
	,RQ_SUBMISSION_CLARIFICATION
	,RQ_OTHER_COVERAGE_CODE
	,RQ_ORIG_RX_PROD_SVC_ID_QUAL
	,RQ_ORIG_RX_PROD_SVC_CODE
	,RQ_ORIG_RX_QTY
	,RQ_SCHEDULED_PRESCRIPTION_ID
	,RQ_UNIT_OF_MEASURE
	,RQ_PRIOR_AUTH_NUM_SUBMITTED
	,RQ_INTERMEDIARY_AUTH_ID
	,RQ_PHARMACY_SERVICE_TYPE
	,RQ_CARDHOLDER_ID
	,RQ_GROUP_ID
	,RQ_PERSON_CODE
	,RQ_PATIENT_RELATIONSHIP_CODE
	,RQ_PRESCRIBER_ID_QUAL
	,RQ_PRESCRIBER_ID
	,RQ_PRESCRIBER_LNAME
	,RQ_PRESCRIBER_FIRST_NAME
	,RQ_PRESCRIBER_STATE_ADDRESS
	,RQ_INGREDIENT_COST_SUBMITTED
	,RQ_DISPENSING_FEE_SUBMITTED
	,RQ_UANDC_CHARGE
	,RQ_GROSS_AMT_DUE
	,RQ_BASIS_OF_COST_DETERMINATION
	,RS_TPMSG_KEY
	,RS_TP_MESSAGE_NUM
	,RS_TP_ITEM_CLAIM_NUM
	,RS_TP_PROCESSOR_DESTINATN_SEQ
	,RS_TP_PROCESSOR_NUM
	,RS_TPMSG_SUBMISSION_DATETIME
	,RS_TPMSG_SUBMISSION_STATUS
	,RS_TPMSG_MSG_CATEGORY
	,RS_TPMSG_COMM_FAILURE
	,RS_VERSION_RELEASE_NUM
	,RS_TRANSACTION_CODE
	,RS_TRANSACTION_COUNT
	,RS_HEADER_RESPONSE_STATUS
	,RS_SVC_PROVIDER_ID_QUAL
	,RS_SVC_PROVIDER_ID
	,RS_DATE_OF_SERVICE
	,RS_TRANSACTION_RSP_STATUS
	,RS_AUTHORIZATION_NUM
	,RS_APPROVED_MSG_CODE_COUNT
	,RS_APPROVED_MSG_CODE1
	,RS_APPROVED_MSG_CODE2
	,RS_ADDTL_MESSAGE_INFO
	,RS_RX_SVC_REF_NUM
	,RS_GROUP_ID
	,RS_NETWRK_REIMBURSEMENT_ID
	,RS_PATIENT_PAY_AMT
	,RS_INGREDIENT_COST_PD
	,RS_DISPENSING_FEE_PD
	,RS_TAX_EXEMPT_IND
	,RS_FLAT_SALES_TAX_AMT_PD
	,RS_PCT_SALES_TAX_AMT_PD
	,RS_PCT_SALES_TAX_RATE_PD
	,RS_PCT_SALES_TAX_BASIS_PD
	,RS_INCENTIVE_FEE_PD
	,RS_PROF_SERVICE_FEE_PD
	,RS_TOTAL_AMT_PD
	,RS_BASIS_OF_REIMBRSMT_DET
	,RS_AMT_ATTR_TO_SALES_TAX
	,RS_ACCUMULATED_DEDUCT_AMT
	,RS_REMAINING_DEDUCT_AMT
	,RS_REMAINING_BENEFIT_AMT
	,RS_AMT_APPLIED_TO_PER_DEDUCT
	,RS_AMT_OF_COPAY
	,RS_AMT_ATTRIB_TO_PROD_SELECT
	,RS_AMT_EXCEED_PER_BENEFIT_MAX
	,RS_BASIS_OF_CALC_DISP_FEE
	,RS_BASIS_OF_CALC_COPAY
	,RS_BASIS_OF_CALC_FLT_SALES_TAX
	,RS_BASIS_OF_CALC_PCT_SALES_TAX
	,RS_ACTUAL_DISPENSE_FEE
	,RS_ACTUAL_TAX_EXEMPT_CODE
	,RS_ACTUAL_FLAT_SALES_TAX_AMT
	,RS_ACTUAL_SALES_TAX_PERCENT
	,RS_ACTUAL_SALES_TAX_RATE
	,RS_ACTUAL_SALES_TAX_BASIS
	,RS_ACTUAL_INCENTIVE_AMT
	,RS_ACTUAL_OTHER_AMT
	,RS_ACTUAL_SALES_TAX_AMT
	,RS_ACTUAL_COPAY_AMT
	,RS_PROCESSOR_FEE_AMT
	,RS_PATIENT_SALES_TAX_AMOUNT
	,RS_PLAN_SALES_TAX_AMOUNT
	,RS_COINSURANCE_AMT
	,SHIP_NUM
	,SHIP_STORE_NUM
	,SHIP_PD_PATIENT_KEY
	,SHIP_PAD_KEY
	,SHIP_DATE
	,SHIP_DATETIME
	,SHIP_ORIG_EXP_DELIV_DATE
	,SHIP_ORIG_EXP_DELIV_DATETIME
	,SHIP_EXP_DELIV_DATE
	,SHIP_EXP_DELIV_DATETIME
	,SHIP_FACILITY_ORDER_NUMBER
	,SHIP_ITEM_COUNT
	,SHIP_PACKAGE_COUNT
	,SHIP_DEA_CLASS
	,SHIP_REFRIGERATION
	,SHIP_WEIGHT
	,SHIP_WEIGHT_UNITS
	,SHIP_TRACKING_NUMBER
	,SHIP_HANDLE_FEE
	,SHIP_COURIER_CHARGE
	,SHIP_IS_COMPLETE
	,SHIP_ORIG_METHOD
	,SHIP_METHOD
	,SHIP_ORIG_COURIER_NAME
	,SHIP_COURIER_NAME
	,SHIP_DELIVERY_METHOD
	,SIG_REQUIRED
    
    --NEW FIELDS ARE BELOW HERE    
	,IS_CHANGE_STATUS
    ,ITEM_SEQ

    ,RXF_DISPENSE_DATE
    ,RXF_DAYS_SUPPLY
    ,RXF_QTY_DISPENSED
    ,RXF_METRIC_QTY_DISPENSED
    ,RXF_INTENDED_QTY_DISPENSED
    ,RXF_INTENDED_DAYS_SUPPLY
    ,RXF_IS_CENTRAL_FILL
    ,RXF_SELECTED_UPC
    ,RXF_RTP_DATE
    ,RXF_READY_DATE
    ,RXF_IS_340B
    ,RXF_IS_CASH
    ,RXF_SKIP_PRE_VER_CODE

    ,ADS_ACTUAL_SHIPPING_METHOD
    ,ADS_ACTUAL_SHIP_CHARGE
    ,ADS_ACTUAL_SHIP_DATE
    ,ADS_ESTIMATED_DELIVERY_DATE
    ,ADS_TOTE_LICENSE_PLATE
    ,ADS_MANIFEST_DELIVERY_DATE
    ,ADS_EXCEPTION_TEXT
    ,ADS_EXTERNAL_ORDER_NUMBER
    ,ADS_REJECT_CODE
    ,ADS_QTY_DISPENSED
    ,ADS_NUMBER_OF_VIALS
    ,ADS_PACKAGE_SIZE
    ,ADS_DATE_COMPLETED
    ,ADS_DATE_FILLED
    ,ADS_NDC_REQUESTED
    ,ADS_NDC_DISPENSED
    ,ADS_QC_INITIALS
    ,ADS_IS_EASY_OPEN_CAP
    ,ADS_STATUS_CODE
    ,ADS_STATUS_DESC
    ,ADS_DATE_UPDATED
    ,ADS_DATESTAMP
    
    ,MAN_CHECK_OUT_DATESTAMP
    ,MAN_CHECK_IN_DATESTAMP
    ,MAN_DATESTAMP
    ,MAN_IS_PULLED_BACK
FROM (
  SELECT
	 FILL_STATE_CHG_TS
	,FILL_STATE_CHG_TS_DATE
	,FILL_STATE_CHG_TS_DATETIME
	,STORE_NUM
	,STORE_NPI
	,STORE_NCPDP
	,FACILITY_NPI
	,RX_NUM
	,RX_NUM_TXT
	,REFILL_NUM
	,PARTIAL_FILL_SEQ
	,BENEFIT_GROUP_ID
	,DATE_OF_SERVICE
	,DAW_CODE
	,DAYS_SUPPLY
	,DISPENSED_DRUG_NUM
	,DISPENSED_QTY_AWP
	,FACILITY_NUM
	,FILL_STATE_CODE
	,FILL_STATE_KEY
	,FILL_STATE_PRICE_NUM
	,FINAL_PRICE
	,INCENTIVE_FEE_AMOUNT
	,INTERNAL_FILL_ID
	,IS_SAME_DAY_REVERSAL
	,MEDICAL_CONDITION_NUM
	,ORIGINAL_PRODUCT_QTY
	,PATIENT_NUM
	,PATIENT_PAY_AMOUNT
	,PRESCRIBED_DATE
	,PRESCRIBER_ADDRESS_NUM
	,PRESCRIBER_ID_DEA
	,PRESCRIBER_ID_NPI
	,PRESCRIBER_NUM
	,QTY_DISPENSED
	,REFILLS_AUTHORIZED
	,REFILLS_REMAINING
	,RX_FILL_SEQ
	,RX_ORIGIN_CODE
	,RX_RECORD_NUM
	,SHORT_FILL_STATUS
	,SPLIT_BILLING_CODE
	,TLOG_SEQUENCE_NUM
	,TOTAL_COST
	,TOTAL_FEE
	,TOTAL_UANDC
	,TOTAL_USER_DEFINED
	,TP_CURR_PATIENT_PAY_AMOUNT
	,TP_CURR_TOTAL_COST
	,TP_CURR_TOTAL_FEE
	,TP_ITEM_CLAIM_KEY
	,TP_ITEM_CLAIM_NUM
	,TP_MESSAGE_KEY
	,TP_PATIENT_NUM
	,TP_PLAN_AMOUNT_PAID
	,TP_PLAN_NUM
	,TP_PRIOR_AUTH_NUM
	,TP_PROCESSOR_DEST_NUM
	,TRANSACTION_CODE
	,IS_BAR
	,ORDER_NUM
	,FS_FILL_STATE_CHG_TS_DATETIME
	,FS_FILL_STATE_CODE
	,FS_RX_FILL_SEQ
	,FS_RX_RECORD_NUM
	,INGREDIENT_NDC1
	,INGREDIENT_NDC2
	,INGREDIENT_NDC3
	,INGREDIENT_NDC4
	,INGREDIENT_NDC5
	,INGREDIENT_NDC6
	,INGREDIENT_PRICE1
	,INGREDIENT_PRICE2
	,INGREDIENT_PRICE3
	,INGREDIENT_PRICE4
	,INGREDIENT_PRICE5
	,INGREDIENT_PRICE6
	,INGREDIENT_QTY1
	,INGREDIENT_QTY2
	,INGREDIENT_QTY3
	,INGREDIENT_QTY4
	,INGREDIENT_QTY5
	,INGREDIENT_QTY6
	,AUTHORIZATION_NUMBER
	,EMERGENCY_CONDITION_CODE
	,EXTERNAL_BILLING_INDICATOR
	,H_LEVEL        
	,TP_MESSAGE_NUM
	,BIN_NUMBER
	,PROCESSOR_CONTROL_NUMBER
	,DRUG_GCN_SEQ
	,DRUG_IS_MAINT_DRUG
	,DRUG_NDC
	,DRUG_PACKAGE_SIZE
	,DRUG_STRENGTH
	,DRUG_STRENGTH_UNITS
	,MCD_FRMTTD_COND_REF_NUM
	,PRS_PRESCRIBER_KEY
	,PRS_PRESCRIBER_NUM
	,PADR_KEY
	,PRD_IS_COMPOUND
	,PRD_IS_GENERIC
	,PRD_IS_PRICE_MAINTAINED
	,PRD_NAME
	,PRD_PACKAGE_SIZE
	,PD_PATIENT_KEY
	,TPD_CARDHOLDER_ID
	,TPD_CARDHOLDER_PATIENT_NUM
	,TPD_RELATIONSHIP_NUM
	,TPD_TP_PLAN_NUM
	,TPLD_PLAN_CODE
	,PCN
	,PCR_TP_PLAN_AMOUNT_PAID
	,PCR_CASH_TP_INDICATOR
	,PCR_FILL_STATE_PRICE_NUM
	,PCR_TOTAL_COST
	,PCR_PATIENT_PAY_AMOUNT
	,PCR_TOTAL_FEE
	,PCR_FINAL_PRICE
	,PCR_DISPENSED_QTY_AWP
	,PCR_DISPENSING_FEE_AMOUNT
	,PCR_TOTAL_USER_DEFINED
	,PCR2_TP_PLAN_AMOUNT_PAID
	,TARGET_CF_FACILITY_NUM
	,PICKUP_DATETIME
	,FACILITY_ORDER_NUMBER
	,RQ_TPMSG_KEY
	,RQ_TP_MESSAGE_NUM
	,RQ_TP_ITEM_CLAIM_NUM
	,RQ_TP_PROCESSOR_DEST_SEQ
	,RQ_TP_PROCESSOR_NUM
	,RQ_TPMSG_SUBMISSION_DATETIME
	,RQ_TPMSG_SUBMISSION_STATUS
	,RQ_TPMSG_MSG_CATEGORY
	,RQ_TPMSG_COMM_FAILURE
	,RQ_BIN_NUM
	,RQ_VERSION_RELEASE_NUM
	,RQ_TRANSACTION_CODE
	,RQ_PROCESSOR_CONTROL_NUM
	,RQ_TRANSACTION_COUNT
	,RQ_SERVICE_PROVIDER_ID_QUAL
	,RQ_SERVICE_PROVIDER_ID
	,RQ_DATE_OF_SERVICE
	,RQ_SOFTWARE_CERT_ID
	,RQ_RX_SERVICE_REF_QUAL
	,RQ_RX_SERVICE_REF_NUM
	,RQ_PRODUCT_SERVICE_ID_QUAL
	,RQ_PRODUCT_SERVICE_ID
	,RQ_QUANTITY_DISPENSED
	,RQ_FILL_NUMBER
	,RQ_DAYS_SUPPLY
	,RQ_COMPOUND_CODE
	,RQ_DAW_CODE
	,RQ_RX_WRITTEN_DATE
	,RQ_NUM_REFILLS_AUTHORIZED
	,RQ_RX_ORIGIN_CODE
	,RQ_SUBMISSION_CLARIFICATION
	,RQ_OTHER_COVERAGE_CODE
	,RQ_ORIG_RX_PROD_SVC_ID_QUAL
	,RQ_ORIG_RX_PROD_SVC_CODE
	,RQ_ORIG_RX_QTY
	,RQ_SCHEDULED_PRESCRIPTION_ID
	,RQ_UNIT_OF_MEASURE
	,RQ_PRIOR_AUTH_NUM_SUBMITTED
	,RQ_INTERMEDIARY_AUTH_ID
	,RQ_PHARMACY_SERVICE_TYPE
	,RQ_CARDHOLDER_ID
	,RQ_GROUP_ID
	,RQ_PERSON_CODE
	,RQ_PATIENT_RELATIONSHIP_CODE
	,RQ_PRESCRIBER_ID_QUAL
	,RQ_PRESCRIBER_ID
	,RQ_PRESCRIBER_LNAME
	,RQ_PRESCRIBER_FIRST_NAME
	,RQ_PRESCRIBER_STATE_ADDRESS
	,RQ_INGREDIENT_COST_SUBMITTED
	,RQ_DISPENSING_FEE_SUBMITTED
	,RQ_UANDC_CHARGE
	,RQ_GROSS_AMT_DUE
	,RQ_BASIS_OF_COST_DETERMINATION
	,RS_TPMSG_KEY
	,RS_TP_MESSAGE_NUM
	,RS_TP_ITEM_CLAIM_NUM
	,RS_TP_PROCESSOR_DESTINATN_SEQ
	,RS_TP_PROCESSOR_NUM
	,RS_TPMSG_SUBMISSION_DATETIME
	,RS_TPMSG_SUBMISSION_STATUS
	,RS_TPMSG_MSG_CATEGORY
	,RS_TPMSG_COMM_FAILURE
	,RS_VERSION_RELEASE_NUM
	,RS_TRANSACTION_CODE
	,RS_TRANSACTION_COUNT
	,RS_HEADER_RESPONSE_STATUS
	,RS_SVC_PROVIDER_ID_QUAL
	,RS_SVC_PROVIDER_ID
	,RS_DATE_OF_SERVICE
	,RS_TRANSACTION_RSP_STATUS
	,RS_AUTHORIZATION_NUM
	,RS_APPROVED_MSG_CODE_COUNT
	,RS_APPROVED_MSG_CODE1
	,RS_APPROVED_MSG_CODE2
	,RS_ADDTL_MESSAGE_INFO
	,RS_RX_SVC_REF_NUM
	,RS_GROUP_ID
	,RS_NETWRK_REIMBURSEMENT_ID
	,RS_PATIENT_PAY_AMT
	,RS_INGREDIENT_COST_PD
	,RS_DISPENSING_FEE_PD
	,RS_TAX_EXEMPT_IND
	,RS_FLAT_SALES_TAX_AMT_PD
	,RS_PCT_SALES_TAX_AMT_PD
	,RS_PCT_SALES_TAX_RATE_PD
	,RS_PCT_SALES_TAX_BASIS_PD
	,RS_INCENTIVE_FEE_PD
	,RS_PROF_SERVICE_FEE_PD
	,RS_TOTAL_AMT_PD
	,RS_BASIS_OF_REIMBRSMT_DET
	,RS_AMT_ATTR_TO_SALES_TAX
	,RS_ACCUMULATED_DEDUCT_AMT
	,RS_REMAINING_DEDUCT_AMT
	,RS_REMAINING_BENEFIT_AMT
	,RS_AMT_APPLIED_TO_PER_DEDUCT
	,RS_AMT_OF_COPAY
	,RS_AMT_ATTRIB_TO_PROD_SELECT
	,RS_AMT_EXCEED_PER_BENEFIT_MAX
	,RS_BASIS_OF_CALC_DISP_FEE
	,RS_BASIS_OF_CALC_COPAY
	,RS_BASIS_OF_CALC_FLT_SALES_TAX
	,RS_BASIS_OF_CALC_PCT_SALES_TAX
	,RS_ACTUAL_DISPENSE_FEE
	,RS_ACTUAL_TAX_EXEMPT_CODE
	,RS_ACTUAL_FLAT_SALES_TAX_AMT
	,RS_ACTUAL_SALES_TAX_PERCENT
	,RS_ACTUAL_SALES_TAX_RATE
	,RS_ACTUAL_SALES_TAX_BASIS
	,RS_ACTUAL_INCENTIVE_AMT
	,RS_ACTUAL_OTHER_AMT
	,RS_ACTUAL_SALES_TAX_AMT
	,RS_ACTUAL_COPAY_AMT
	,RS_PROCESSOR_FEE_AMT
	,RS_PATIENT_SALES_TAX_AMOUNT
	,RS_PLAN_SALES_TAX_AMOUNT
	,RS_COINSURANCE_AMT
	,SHIP_NUM
	,SHIP_STORE_NUM
	,SHIP_PD_PATIENT_KEY
	,SHIP_PAD_KEY
	,SHIP_DATE
	,SHIP_DATETIME
	,SHIP_ORIG_EXP_DELIV_DATE
	,SHIP_ORIG_EXP_DELIV_DATETIME
	,SHIP_EXP_DELIV_DATE
	,SHIP_EXP_DELIV_DATETIME
	,SHIP_FACILITY_ORDER_NUMBER
	,SHIP_ITEM_COUNT
	,SHIP_PACKAGE_COUNT
	,SHIP_DEA_CLASS
	,SHIP_REFRIGERATION
	,SHIP_WEIGHT
	,SHIP_WEIGHT_UNITS
	,SHIP_TRACKING_NUMBER
	,SHIP_HANDLE_FEE
	,SHIP_COURIER_CHARGE
	,SHIP_IS_COMPLETE
	,SHIP_ORIG_METHOD
	,SHIP_METHOD
	,SHIP_ORIG_COURIER_NAME
	,SHIP_COURIER_NAME
	,SHIP_DELIVERY_METHOD
	,SIG_REQUIRED
    
    --NEW FIELDS ARE BELOW HERE    
	,IS_CHANGE_STATUS
    ,ITEM_SEQ

    ,RXF_DISPENSE_DATE
    ,RXF_DAYS_SUPPLY
    ,RXF_QTY_DISPENSED
    ,RXF_METRIC_QTY_DISPENSED
    ,RXF_INTENDED_QTY_DISPENSED
    ,RXF_INTENDED_DAYS_SUPPLY
    ,RXF_IS_CENTRAL_FILL
    ,RXF_SELECTED_UPC
    ,RXF_RTP_DATE
    ,RXF_READY_DATE
    ,RXF_IS_340B
    ,RXF_IS_CASH
    ,RXF_SKIP_PRE_VER_CODE

    ,ADS_ACTUAL_SHIPPING_METHOD
    ,ADS_ACTUAL_SHIP_CHARGE
    ,ADS_ACTUAL_SHIP_DATE
    ,ADS_ESTIMATED_DELIVERY_DATE
    ,ADS_TOTE_LICENSE_PLATE
    ,ADS_MANIFEST_DELIVERY_DATE
    ,ADS_EXCEPTION_TEXT
    ,ADS_EXTERNAL_ORDER_NUMBER
    ,ADS_REJECT_CODE
    ,ADS_QTY_DISPENSED
    ,ADS_NUMBER_OF_VIALS
    ,ADS_PACKAGE_SIZE
    ,ADS_DATE_COMPLETED
    ,ADS_DATE_FILLED
    ,ADS_NDC_REQUESTED
    ,ADS_NDC_DISPENSED
    ,ADS_QC_INITIALS
    ,ADS_IS_EASY_OPEN_CAP
    ,ADS_STATUS_CODE
    ,ADS_STATUS_DESC
    ,ADS_DATE_UPDATED
    ,ADS_DATESTAMP
    
    ,MAN_CHECK_OUT_DATESTAMP
    ,MAN_CHECK_IN_DATESTAMP
    ,MAN_DATESTAMP
    ,MAN_IS_PULLED_BACK

    ,RANK() OVER (PARTITION BY
                       FILL_STATE_CHG_TS
                      ,FILL_STATE_CODE
                      ,FILL_STATE_KEY
                      ,ORDER_NUM
                      ,ITEM_SEQ
                  ORDER BY
                       EQUAL_FILL_STATE_PRICE_NUM DESC
                      ,EQUAL_FILL_STATE_PRICE_NUM2 DESC
                      ,EQUAL_PD_PATIENT_KEY DESC
                 ) AS MALARKEYRANK
  FROM (
    SELECT
     AUD__FILL_FACT.FILL_STATE_CHG_TS
    ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.FILL_STATE_CHG_TS::DATE,'YYYYMMDD')) AS FILL_STATE_CHG_TS_DATE
    ,ROUND((AUD__FILL_FACT.FILL_STATE_CHG_TS - TO_DATE('20350101','YYYYMMDD')),6) AS FILL_STATE_CHG_TS_DATETIME
    ,TO_NUMBER(DW__FACILITY.FD_FACILITY_ID) AS STORE_NUM
    ,AUD__TP_RESPONSE_MESSAGE.RS_SVC_PROVIDER_ID AS STORE_NPI
    ,DW__FACILITY.FD_NCPDP_PROVIDER_ID AS STORE_NCPDP
    ,DW__FACILITY_ID.FD_VALUE AS FACILITY_NPI
    ,TO_NUMBER(REGEXP_REPLACE(AUD__FILL_FACT.RX_NUMBER,'[^0-9]+','')) AS RX_NUM
    ,AUD__FILL_FACT.RX_NUMBER AS RX_NUM_TXT
    ,AUD__FILL_FACT.REFILL_NUM
    ,AUD__FILL_FACT.PARTIAL_FILL_SEQ
    ,AUD__FILL_FACT.BENEFIT_GROUP_ID
    ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.DATE_OF_SERVICE::DATE,'YYYYMMDD')) AS DATE_OF_SERVICE
    ,AUD__FILL_FACT.DAW_CODE
    ,AUD__FILL_FACT.DAYS_SUPPLY
    ,AUD__FILL_FACT.DISPENSED_DRUG_NUM
    ,AUD__FILL_FACT.DISPENSED_QTY_AWP
    ,AUD__FILL_FACT.FACILITY_NUM
    ,AUD__FILL_FACT.FILL_STATE_CODE
    ,AUD__FILL_FACT.FILL_STATE_KEY
    ,AUD__FILL_FACT.FILL_STATE_PRICE_NUM
    ,AUD__FILL_FACT.FINAL_PRICE
    ,AUD__FILL_FACT.INCENTIVE_FEE_AMOUNT
    ,AUD__FILL_FACT.INTERNAL_FILL_ID
    ,AUD__FILL_FACT.IS_SAME_DAY_REVERSAL
    ,AUD__FILL_FACT.MEDICAL_CONDITION_NUM
    ,AUD__FILL_FACT.ORIGINAL_PRODUCT_QTY
    ,AUD__FILL_FACT.PATIENT_NUM
    ,AUD__FILL_FACT.PATIENT_PAY_AMOUNT
    ,TO_NUMBER(TO_CHAR(AUD__FILL_FACT.PRESCRIBED_DATE::DATE,'YYYYMMDD')) AS PRESCRIBED_DATE
    ,AUD__FILL_FACT.PRESCRIBER_ADDRESS_NUM
    ,AUD__FILL_FACT.PRESCRIBER_ID_DEA
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__FILL_FACT.PRESCRIBER_ID_NPI),1,15) AS PRESCRIBER_ID_NPI
    ,AUD__FILL_FACT.PRESCRIBER_NUM
    ,AUD__FILL_FACT.QTY_DISPENSED
    ,AUD__FILL_FACT.REFILLS_AUTHORIZED
    ,AUD__FILL_FACT.REFILLS_REMAINING
    ,AUD__FILL_FACT.RX_FILL_SEQ
    ,AUD__FILL_FACT.RX_ORIGIN_CODE
    ,AUD__FILL_FACT.RX_RECORD_NUM
    ,AUD__FILL_FACT.SHORT_FILL_STATUS
    ,AUD__FILL_FACT.SPLIT_BILLING_CODE
    ,AUD__FILL_FACT.TLOG_SEQUENCE_NUM
    ,AUD__FILL_FACT.TOTAL_COST
    ,AUD__FILL_FACT.TOTAL_FEE
    ,AUD__FILL_FACT.TOTAL_UANDC
    ,AUD__FILL_FACT.TOTAL_USER_DEFINED
    ,AUD__FILL_FACT.TP_CURR_PATIENT_PAY_AMOUNT
    ,AUD__FILL_FACT.TP_CURR_TOTAL_COST
    ,AUD__FILL_FACT.TP_CURR_TOTAL_FEE
    ,AUD__FILL_FACT.TP_ITEM_CLAIM_KEY
    ,AUD__FILL_FACT.TP_ITEM_CLAIM_NUM
    ,AUD__FILL_FACT.TP_MESSAGE_KEY
    ,AUD__FILL_FACT.TP_PATIENT_NUM
    ,AUD__FILL_FACT.TP_PLAN_AMOUNT_PAID
    ,AUD__FILL_FACT.TP_PLAN_NUM
    ,AUD__FILL_FACT.TP_PRIOR_AUTH_NUM
    ,AUD__FILL_FACT.TP_PROCESSOR_DEST_NUM
    ,AUD__FILL_FACT.TRANSACTION_CODE
    ,AUD__FILL_FACT.IS_BAR
    ,AUD__FILL_STATE.ORDER_NUM
    ,ROUND((AUD__FILL_STATE.FILL_STATE_CHG_TS - TO_DATE('20350101','YYYYMMDD')),6) AS FS_FILL_STATE_CHG_TS_DATETIME
    ,AUD__FILL_STATE.FILL_STATE_CODE AS FS_FILL_STATE_CODE
    ,AUD__FILL_STATE.RX_FILL_SEQ AS FS_RX_FILL_SEQ
    ,AUD__FILL_STATE.RX_RECORD_NUM AS FS_RX_RECORD_NUM
    ,AUD__FILL_STATE.INGREDIENT_NDC1
    ,AUD__FILL_STATE.INGREDIENT_NDC2
    ,AUD__FILL_STATE.INGREDIENT_NDC3
    ,AUD__FILL_STATE.INGREDIENT_NDC4
    ,AUD__FILL_STATE.INGREDIENT_NDC5
    ,AUD__FILL_STATE.INGREDIENT_NDC6
    ,AUD__FILL_STATE.INGREDIENT_PRICE1
    ,AUD__FILL_STATE.INGREDIENT_PRICE2
    ,AUD__FILL_STATE.INGREDIENT_PRICE3
    ,AUD__FILL_STATE.INGREDIENT_PRICE4
    ,AUD__FILL_STATE.INGREDIENT_PRICE5
    ,AUD__FILL_STATE.INGREDIENT_PRICE6
    ,AUD__FILL_STATE.INGREDIENT_QTY1
    ,AUD__FILL_STATE.INGREDIENT_QTY2
    ,AUD__FILL_STATE.INGREDIENT_QTY3
    ,AUD__FILL_STATE.INGREDIENT_QTY4
    ,AUD__FILL_STATE.INGREDIENT_QTY5
    ,AUD__FILL_STATE.INGREDIENT_QTY6
    ,AUD__TP_ITEM_CLAIM.AUTHORIZATION_NUMBER
    ,AUD__TP_ITEM_CLAIM.EMERGENCY_CONDITION_CODE
    ,AUD__TP_ITEM_CLAIM.EXTERNAL_BILLING_INDICATOR
    ,AUD__TP_MESSAGE.H_LEVEL        
    ,AUD__TP_MESSAGE.TP_MESSAGE_NUM
    ,AUD__TP_PROCESSOR_DESTINATION.BIN_NUMBER
    ,AUD__TP_PROCESSOR_DESTINATION.PROCESSOR_CONTROL_NUMBER
    ,DW__DRUG.DRUG_GCN_SEQ
    ,DW__DRUG.DRUG_IS_MAINT_DRUG
    ,DW__DRUG.DRUG_NDC
    ,DW__DRUG.DRUG_PACKAGE_SIZE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DW__DRUG.DRUG_STRENGTH),1,19) AS DRUG_STRENGTH
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DW__DRUG.DRUG_STRENGTH_UNITS),1,15) AS DRUG_STRENGTH_UNITS
    ,DW__MEDICAL_CONDITION.MCD_FRMTTD_COND_REF_NUM
    ,DW__PRESCRIBER.PRS_PRESCRIBER_KEY
    ,DW__PRESCRIBER.PRS_PRESCRIBER_NUM
    ,DW__PRESCRIBER_ADDRESS.PADR_KEY
    ,DW__PRODUCT.PRD_IS_COMPOUND
    ,DW__PRODUCT.PRD_IS_GENERIC
    ,DW__PRODUCT.PRD_IS_PRICE_MAINTAINED
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DW__PRODUCT.PRD_NAME),1,30) AS PRD_NAME
    ,DW__PRODUCT.PRD_PACKAGE_SIZE
    ,DW__TP_PATIENT.PD_PATIENT_KEY
    ,DW__TP_PATIENT.TPD_CARDHOLDER_ID
    ,DW__TP_PATIENT.TPD_CARDHOLDER_PATIENT_NUM
    ,DW__TP_PATIENT.TPD_RELATIONSHIP_NUM
    ,DW__TP_PATIENT.TPD_TP_PLAN_NUM
    ,DW__TP_PLAN.TPLD_PLAN_CODE
    ,DW__TP_PLAN.PCN
    ,AUD__PRICE_CALC_RESULT.TP_PLAN_AMOUNT_PAID AS PCR_TP_PLAN_AMOUNT_PAID
    ,AUD__PRICE_CALC_RESULT.CASH_TP_INDICATOR AS PCR_CASH_TP_INDICATOR
    ,AUD__PRICE_CALC_RESULT.FILL_STATE_PRICE_NUM AS PCR_FILL_STATE_PRICE_NUM
    ,AUD__PRICE_CALC_RESULT.TOTAL_COST AS PCR_TOTAL_COST
    ,AUD__PRICE_CALC_RESULT.PATIENT_PAY_AMOUNT AS PCR_PATIENT_PAY_AMOUNT
    ,AUD__PRICE_CALC_RESULT.TOTAL_FEE AS PCR_TOTAL_FEE
    ,AUD__PRICE_CALC_RESULT.FINAL_PRICE AS PCR_FINAL_PRICE
    ,AUD__PRICE_CALC_RESULT.DISPENSED_QTY_AWP AS PCR_DISPENSED_QTY_AWP
    ,AUD__PRICE_CALC_RESULT.DISPENSING_FEE_AMOUNT AS PCR_DISPENSING_FEE_AMOUNT
    ,AUD__PRICE_CALC_RESULT.TOTAL_USER_DEFINED AS PCR_TOTAL_USER_DEFINED
    ,AUD__PRICE_CALC_RESULT2.TP_PLAN_AMOUNT_PAID AS PCR2_TP_PLAN_AMOUNT_PAID
    ,AUD__ITEM.TARGET_CF_FACILITY_NUM
    ,ROUND((AUD__ITEM.PICKUP_TIME - TO_DATE('20350101','YYYYMMDD')),6) AS PICKUP_DATETIME
    ,AUD__ORDER_RECORD.FACILITY_ORDER_NUMBER
    ,AUD__TP_REQUEST_MESSAGE.TPMSG_KEY AS RQ_TPMSG_KEY
    ,AUD__TP_REQUEST_MESSAGE.TP_MESSAGE_NUM AS RQ_TP_MESSAGE_NUM
    ,AUD__TP_REQUEST_MESSAGE.TP_ITEM_CLAIM_NUM AS RQ_TP_ITEM_CLAIM_NUM
    ,AUD__TP_REQUEST_MESSAGE.TP_PROCESSOR_DESTINATION_SEQ AS RQ_TP_PROCESSOR_DEST_SEQ
    ,AUD__TP_REQUEST_MESSAGE.TP_PROCESSOR_NUM AS RQ_TP_PROCESSOR_NUM
    ,ROUND((AUD__TP_REQUEST_MESSAGE.TPMSG_SUBMISSION_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RQ_TPMSG_SUBMISSION_DATETIME
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.TPMSG_SUBMISSION_STATUS),1,1) AS RQ_TPMSG_SUBMISSION_STATUS
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.TPMSG_MSG_CATEGORY),1,1) AS RQ_TPMSG_MSG_CATEGORY
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.TPMSG_COMM_FAILURE),1,1) AS RQ_TPMSG_COMM_FAILURE
    ,AUD__TP_REQUEST_MESSAGE.RQ_BIN_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_VERSION_RELEASE_NUM),1,2) AS RQ_VERSION_RELEASE_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_TRANSACTION_CODE),1,2) AS RQ_TRANSACTION_CODE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PROCESSOR_CONTROL_NUM),1,10) AS RQ_PROCESSOR_CONTROL_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_TRANSACTION_COUNT),1,1) AS RQ_TRANSACTION_COUNT
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_SERVICE_PROVIDER_ID_QUAL),1,2) AS RQ_SERVICE_PROVIDER_ID_QUAL
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_SERVICE_PROVIDER_ID),1,10) AS RQ_SERVICE_PROVIDER_ID
    ,TO_NUMBER(TO_CHAR(AUD__TP_REQUEST_MESSAGE.RQ_DATE_OF_SERVICE::DATE,'YYYYMMDD')) AS RQ_DATE_OF_SERVICE    
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_SOFTWARE_CERT_ID),1,10) AS RQ_SOFTWARE_CERT_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_RX_SERVICE_REF_QUAL),1,1) AS RQ_RX_SERVICE_REF_QUAL
    ,AUD__TP_REQUEST_MESSAGE.RQ_RX_SERVICE_REF_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PRODUCT_SERVICE_ID_QUAL),1,2) AS RQ_PRODUCT_SERVICE_ID_QUAL
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PRODUCT_SERVICE_ID),1,11) AS RQ_PRODUCT_SERVICE_ID
    ,AUD__TP_REQUEST_MESSAGE.RQ_QUANTITY_DISPENSED
    ,AUD__TP_REQUEST_MESSAGE.RQ_FILL_NUMBER
    ,AUD__TP_REQUEST_MESSAGE.RQ_DAYS_SUPPLY
    ,AUD__TP_REQUEST_MESSAGE.RQ_COMPOUND_CODE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_DAW_CODE),1,1) AS RQ_DAW_CODE
    ,TO_NUMBER(TO_CHAR(AUD__TP_REQUEST_MESSAGE.RQ_RX_WRITTEN_DATE::DATE,'YYYYMMDD')) AS RQ_RX_WRITTEN_DATE    
    ,AUD__TP_REQUEST_MESSAGE.RQ_NUM_REFILLS_AUTHORIZED
    ,AUD__TP_REQUEST_MESSAGE.RQ_RX_ORIGIN_CODE
    ,AUD__TP_REQUEST_MESSAGE.RQ_SUBMISSION_CLARIFICATION
    ,AUD__TP_REQUEST_MESSAGE.RQ_OTHER_COVERAGE_CODE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_ORIG_RX_PROD_SVC_ID_QUAL),1,2) AS RQ_ORIG_RX_PROD_SVC_ID_QUAL
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_ORIG_RX_PROD_SVC_CODE),1,11) AS RQ_ORIG_RX_PROD_SVC_CODE
    ,AUD__TP_REQUEST_MESSAGE.RQ_ORIG_RX_QTY
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_SCHEDULED_PRESCRIPTION_ID),1,12) AS RQ_SCHEDULED_PRESCRIPTION_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_UNIT_OF_MEASURE),1,2) AS RQ_UNIT_OF_MEASURE
    ,AUD__TP_REQUEST_MESSAGE.RQ_PRIOR_AUTH_NUM_SUBMITTED
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_INTERMEDIARY_AUTH_ID),1,11) AS RQ_INTERMEDIARY_AUTH_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.PHARMACY_SERVICE_TYPE),1,1) AS RQ_PHARMACY_SERVICE_TYPE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_CARDHOLDER_ID),1,20) AS RQ_CARDHOLDER_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_GROUP_ID),1,15) AS RQ_GROUP_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PERSON_CODE),1,3) AS RQ_PERSON_CODE
    ,AUD__TP_REQUEST_MESSAGE.RQ_PATIENT_RELATIONSHIP_CODE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PRESCRIBER_ID_QUAL),1,2) AS RQ_PRESCRIBER_ID_QUAL
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PRESCRIBER_ID),1,13) AS RQ_PRESCRIBER_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_PRESCRIBER_LNAME),1,15) AS RQ_PRESCRIBER_LNAME
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.PRESCRIBER_FIRST_NAME),1,12) AS RQ_PRESCRIBER_FIRST_NAME
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.PRESCRIBER_STATE_ADDRESS),1,2) AS RQ_PRESCRIBER_STATE_ADDRESS
    ,AUD__TP_REQUEST_MESSAGE.RQ_INGREDIENT_COST_SUBMITTED
    ,AUD__TP_REQUEST_MESSAGE.RQ_DISPENSING_FEE_SUBMITTED
    ,AUD__TP_REQUEST_MESSAGE.RQ_UANDC_CHARGE
    ,AUD__TP_REQUEST_MESSAGE.RQ_GROSS_AMT_DUE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_REQUEST_MESSAGE.RQ_BASIS_OF_COST_DETERMINATION),1,2) AS RQ_BASIS_OF_COST_DETERMINATION
    ,AUD__TP_RESPONSE_MESSAGE.TPMSG_KEY AS RS_TPMSG_KEY
    ,AUD__TP_RESPONSE_MESSAGE.TP_MESSAGE_NUM AS RS_TP_MESSAGE_NUM
    ,AUD__TP_RESPONSE_MESSAGE.TP_ITEM_CLAIM_NUM AS RS_TP_ITEM_CLAIM_NUM
    ,AUD__TP_RESPONSE_MESSAGE.TP_PROCESSOR_DESTINATION_SEQ AS RS_TP_PROCESSOR_DESTINATN_SEQ
    ,AUD__TP_RESPONSE_MESSAGE.TP_PROCESSOR_NUM AS RS_TP_PROCESSOR_NUM
    ,ROUND((AUD__TP_RESPONSE_MESSAGE.TPMSG_SUBMISSION_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RS_TPMSG_SUBMISSION_DATETIME    
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.TPMSG_SUBMISSION_STATUS),1,1) AS RS_TPMSG_SUBMISSION_STATUS
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.TPMSG_MSG_CATEGORY),1,1) AS RS_TPMSG_MSG_CATEGORY
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.TPMSG_COMM_FAILURE),1,1) AS RS_TPMSG_COMM_FAILURE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_VERSION_RELEASE_NUM),1,2) AS RS_VERSION_RELEASE_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_TRANSACTION_CODE),1,2) AS RS_TRANSACTION_CODE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_TRANSACTION_COUNT),1,1) AS RS_TRANSACTION_COUNT
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_HEADER_RESPONSE_STATUS),1,1) AS RS_HEADER_RESPONSE_STATUS
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_SVC_PROVIDER_ID_QUAL),1,2) AS RS_SVC_PROVIDER_ID_QUAL
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_SVC_PROVIDER_ID),1,10) AS RS_SVC_PROVIDER_ID
    ,TO_NUMBER(TO_CHAR(AUD__TP_RESPONSE_MESSAGE.RS_DATE_OF_SERVICE::DATE,'YYYYMMDD')) AS RS_DATE_OF_SERVICE    
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_TRANSACTION_RSP_STATUS),1,1) AS RS_TRANSACTION_RSP_STATUS
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_AUTHORIZATION_NUM),1,20) AS RS_AUTHORIZATION_NUM
    ,AUD__TP_RESPONSE_MESSAGE.RS_APPROVED_MSG_CODE_COUNT AS RS_APPROVED_MSG_CODE_COUNT
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_APPROVED_MSG_CODE1),1,3) AS RS_APPROVED_MSG_CODE1
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_APPROVED_MSG_CODE2),1,3) AS RS_APPROVED_MSG_CODE2
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_ADDTL_MESSAGE_INFO),1,100) AS RS_ADDTL_MESSAGE_INFO
    ,AUD__TP_RESPONSE_MESSAGE.RS_RX_SVC_REF_NUM AS RS_RX_SVC_REF_NUM
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_GROUP_ID),1,15) AS RS_GROUP_ID
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_NETWRK_REIMBURSEMENT_ID),1,10) AS RS_NETWRK_REIMBURSEMENT_ID
    ,AUD__TP_RESPONSE_MESSAGE.RS_PATIENT_PAY_AMT AS RS_PATIENT_PAY_AMT
    ,AUD__TP_RESPONSE_MESSAGE.RS_INGREDIENT_COST_PD AS RS_INGREDIENT_COST_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_DISPENSING_FEE_PD AS RS_DISPENSING_FEE_PD
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_TAX_EXEMPT_IND),1,1) AS RS_TAX_EXEMPT_IND
    ,AUD__TP_RESPONSE_MESSAGE.RS_FLAT_SALES_TAX_AMT_PD AS RS_FLAT_SALES_TAX_AMT_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_PCT_SALES_TAX_AMT_PD AS RS_PCT_SALES_TAX_AMT_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_PCT_SALES_TAX_RATE_PD AS RS_PCT_SALES_TAX_RATE_PD
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_PCT_SALES_TAX_BASIS_PD),1,2) AS RS_PCT_SALES_TAX_BASIS_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_INCENTIVE_FEE_PD AS RS_INCENTIVE_FEE_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_PROF_SERVICE_FEE_PD AS RS_PROF_SERVICE_FEE_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_TOTAL_AMT_PD AS RS_TOTAL_AMT_PD
    ,AUD__TP_RESPONSE_MESSAGE.RS_BASIS_OF_REIMBRSMT_DET AS RS_BASIS_OF_REIMBRSMT_DET
    ,AUD__TP_RESPONSE_MESSAGE.RS_AMT_ATTR_TO_SALES_TAX AS RS_AMT_ATTR_TO_SALES_TAX
    ,AUD__TP_RESPONSE_MESSAGE.RS_ACCUMULATED_DEDUCT_AMT AS RS_ACCUMULATED_DEDUCT_AMT
    ,AUD__TP_RESPONSE_MESSAGE.RS_REMAINING_DEDUCT_AMT AS RS_REMAINING_DEDUCT_AMT
    ,AUD__TP_RESPONSE_MESSAGE.RS_REMAINING_BENEFIT_AMT AS RS_REMAINING_BENEFIT_AMT
    ,AUD__TP_RESPONSE_MESSAGE.RS_AMT_APPLIED_TO_PER_DEDUCT AS RS_AMT_APPLIED_TO_PER_DEDUCT
    ,AUD__TP_RESPONSE_MESSAGE.RS_AMT_OF_COPAY AS RS_AMT_OF_COPAY
    ,AUD__TP_RESPONSE_MESSAGE.RS_AMT_ATTRIB_TO_PROD_SELECT AS RS_AMT_ATTRIB_TO_PROD_SELECT
    ,AUD__TP_RESPONSE_MESSAGE.RS_AMT_EXCEED_PER_BENEFIT_MAX AS RS_AMT_EXCEED_PER_BENEFIT_MAX
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_BASIS_OF_CALC_DISP_FEE),1,2) AS RS_BASIS_OF_CALC_DISP_FEE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_BASIS_OF_CALC_COPAY),1,2) AS RS_BASIS_OF_CALC_COPAY
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_BASIS_OF_CALC_FLT_SALES_TAX),1,2) AS RS_BASIS_OF_CALC_FLT_SALES_TAX
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.RS_BASIS_OF_CALC_PCT_SALES_TAX),1,2) AS RS_BASIS_OF_CALC_PCT_SALES_TAX
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_DISPENSE_FEE AS RS_ACTUAL_DISPENSE_FEE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.ACTUAL_TAX_EXEMPT_CODE),1,10) AS RS_ACTUAL_TAX_EXEMPT_CODE
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_FLAT_SALES_TAX_AMT AS RS_ACTUAL_FLAT_SALES_TAX_AMT
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_SALES_TAX_PERCENT AS RS_ACTUAL_SALES_TAX_PERCENT
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_SALES_TAX_RATE AS RS_ACTUAL_SALES_TAX_RATE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__TP_RESPONSE_MESSAGE.ACTUAL_SALES_TAX_BASIS),1,10) AS RS_ACTUAL_SALES_TAX_BASIS
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_INCENTIVE_AMT AS RS_ACTUAL_INCENTIVE_AMT
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_OTHER_AMT AS RS_ACTUAL_OTHER_AMT
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_SALES_TAX_AMT AS RS_ACTUAL_SALES_TAX_AMT
    ,AUD__TP_RESPONSE_MESSAGE.ACTUAL_COPAY_AMT AS RS_ACTUAL_COPAY_AMT
    ,AUD__TP_RESPONSE_MESSAGE.PROCESSOR_FEE_AMT AS RS_PROCESSOR_FEE_AMT
    ,AUD__TP_RESPONSE_MESSAGE.PATIENT_SALES_TAX_AMOUNT AS RS_PATIENT_SALES_TAX_AMOUNT
    ,AUD__TP_RESPONSE_MESSAGE.PLAN_SALES_TAX_AMOUNT AS RS_PLAN_SALES_TAX_AMOUNT
    ,AUD__TP_RESPONSE_MESSAGE.COINSURANCE_AMT AS RS_COINSURANCE_AMT
    ,DW__SHIPMENT_FACT.SHIPMENT_NUM AS SHIP_NUM
    ,TO_NUMBER(DW__SHIPMENT_FACT_FACILITY.FD_FACILITY_ID) AS SHIP_STORE_NUM
    ,DW__SHIPMENT_FACT.PD_PATIENT_KEY AS SHIP_PD_PATIENT_KEY
    ,DW__SHIPMENT_FACT.PAD_KEY AS SHIP_PAD_KEY
    ,(CASE WHEN DW__SHIPMENT_FACT.SHIP_DATE_KEY = 0 THEN NULL ELSE DW__SHIPMENT_FACT.SHIP_DATE_KEY END) AS SHIP_DATE
    ,(CASE WHEN DW__SHIPMENT_FACT.SHIP_DATE_KEY = 0 THEN NULL
           ELSE ROUND(((TO_DATE(TO_CHAR(DW__SHIPMENT_FACT.SHIP_DATE_KEY),'YYYYMMDD') + ((DW__SHIPMENT_FACT.SHIP_TIME_KEY - 2)/86400)) - TO_DATE('20350101','YYYYMMDD')),6)
      END) AS SHIP_DATETIME
    ,(CASE WHEN DW__SHIPMENT_FACT.ORIG_EXPECT_DELIVERY_DATE_KEY = 0 THEN NULL ELSE DW__SHIPMENT_FACT.ORIG_EXPECT_DELIVERY_DATE_KEY END) AS SHIP_ORIG_EXP_DELIV_DATE
    ,(CASE WHEN DW__SHIPMENT_FACT.ORIG_EXPECT_DELIVERY_DATE_KEY = 0 THEN NULL
           ELSE ROUND(((TO_DATE(TO_CHAR(DW__SHIPMENT_FACT.ORIG_EXPECT_DELIVERY_DATE_KEY),'YYYYMMDD') + ((DW__SHIPMENT_FACT.ORIG_EXPECT_DELIVERY_TIME_KEY - 2)/86400)) - TO_DATE('20350101','YYYYMMDD')),6)
      END) AS SHIP_ORIG_EXP_DELIV_DATETIME
    ,(CASE WHEN DW__SHIPMENT_FACT.EXPECTED_DELIVERY_DATE_KEY = 0 THEN NULL ELSE DW__SHIPMENT_FACT.EXPECTED_DELIVERY_DATE_KEY END) AS SHIP_EXP_DELIV_DATE
    ,(CASE WHEN DW__SHIPMENT_FACT.EXPECTED_DELIVERY_DATE_KEY = 0 THEN NULL
           ELSE ROUND(((TO_DATE(TO_CHAR(DW__SHIPMENT_FACT.EXPECTED_DELIVERY_DATE_KEY),'YYYYMMDD') + ((DW__SHIPMENT_FACT.EXPECTED_DELIVERY_TIME_KEY - 2)/86400)) - TO_DATE('20350101','YYYYMMDD')),6)
      END) AS SHIP_EXP_DELIV_DATETIME
    ,DW__SHIPMENT_FACT.FACILITY_ORDER_NUMBER AS SHIP_FACILITY_ORDER_NUMBER
    ,DW__SHIPMENT_FACT.SHIP_ITEM_COUNT
    ,DW__SHIPMENT_FACT.PACKAGE_COUNT AS SHIP_PACKAGE_COUNT
    ,DW__SHIPMENT_FACT.DEA_CLASS AS SHIP_DEA_CLASS
    ,DW__SHIPMENT_FACT.REFRIGERATION AS SHIP_REFRIGERATION
    ,DW__SHIPMENT_FACT.WEIGHT AS SHIP_WEIGHT
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DW__SHIPMENT_FACT.WEIGHT_UNITS),1,10) AS SHIP_WEIGHT_UNITS
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(DW__SHIPMENT_FACT.TRACKING_NUMBER),1,100) AS SHIP_TRACKING_NUMBER
    ,DW__SHIPMENT_FACT.SHIP_HANDLE_FEE
    ,DW__SHIPMENT_FACT.COURIER_SHIP_CHARGE AS SHIP_COURIER_CHARGE
    ,DW__SHIPMENT_FACT.IS_SHIPPING_COMPLETE AS SHIP_IS_COMPLETE
    ,DW__COURIER_SHIPMENT_TYPE_ORIG.SHIPPING_METHOD_DESC AS SHIP_ORIG_METHOD
    ,DW__COURIER_SHIPMENT_TYPE.SHIPPING_METHOD_DESC AS SHIP_METHOD
    ,DW__COURIER_SHIPMENT_TYPE_ORIG.COURIER_NAME AS SHIP_ORIG_COURIER_NAME
    ,DW__COURIER_SHIPMENT_TYPE.COURIER_NAME AS SHIP_COURIER_NAME
    ,DW__DELIVERY_METHOD_TYPE.DM_DELIVERY_METHOD_DESC AS SHIP_DELIVERY_METHOD
	,AUD__ORDER_RECORD.IS_SIGNATURE_REQUIRED AS SIG_REQUIRED
    
    --NEW FIELDS ARE BELOW HERE
	,AUD__FILL_FACT.IS_CHANGE_STATUS --VARCHAR2(2)
    ,AUD__FILL_STATE.ITEM_SEQ --NUMBER(18)

    ,ROUND((AUD__RX_FILL.DISPENSE_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_DISPENSE_DATE --DATE
    ,AUD__RX_FILL.DAYS_SUPPLY AS RXF_DAYS_SUPPLY --NUMBER(9,3)
    ,AUD__RX_FILL.QTY_DISPENSED AS RXF_QTY_DISPENSED --NUMBER(13,3)
    ,AUD__RX_FILL.METRIC_QTY_DISPENSED AS RXF_METRIC_QTY_DISPENSED --NUMBER(13,5)
    ,AUD__RX_FILL.INTENDED_QTY_DISPENSED AS RXF_INTENDED_QTY_DISPENSED --NUMBER(13,3)
    ,AUD__RX_FILL.INTENDED_DAYS_SUPPLY AS RXF_INTENDED_DAYS_SUPPLY --NUMBER(9,3)
    ,AUD__RX_FILL.IS_CENTRAL_FILL AS RXF_IS_CENTRAL_FILL --CHAR(1)
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__RX_FILL.SELECTED_UPC),1,20) AS RXF_SELECTED_UPC --VARCHAR2(20)
    ,ROUND((AUD__RX_FILL.RELEASED_TO_PATIENT_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_RTP_DATE --DATE
    ,ROUND((AUD__RX_FILL.READY_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS RXF_READY_DATE --DATE
    ,AUD__RX_FILL.IS_340B AS RXF_IS_340B --CHAR(1)
    ,AUD__RX_FILL.IS_CASH AS RXF_IS_CASH --CHAR(1)
    ,AUD__RX_FILL.SKIP_PRE_VER_CODE AS RXF_SKIP_PRE_VER_CODE --NUMBER(2)

    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.ACTUAL_SHIPPING_METHOD),1,100) AS ADS_ACTUAL_SHIPPING_METHOD --VARCHAR2(100)
    ,AUD__ADS_RESPONSE.ACTUAL_SHIP_CHARGE AS ADS_ACTUAL_SHIP_CHARGE --NUMBER(12,2)
    ,ROUND((AUD__ADS_RESPONSE.ACTUAL_SHIP_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_ACTUAL_SHIP_DATE --DATE
    ,ROUND((AUD__ADS_RESPONSE.ESTIMATED_DELIVERY_DATE - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_ESTIMATED_DELIVERY_DATE --DATE
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.TOTE_LICENSE_PLATE),1,50) AS ADS_TOTE_LICENSE_PLATE --VARCHAR2(50)
    ,ROUND((TO_DATE(AUD__ADS_RESPONSE.MANIFEST_SYS_EST_DELIVERY_DATE,'MM/DD/YYYY HH:MI AM') - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_MANIFEST_DELIVERY_DATE --VARCHAR2(50)
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.EXCEPTION_TEXT),1,250) AS ADS_EXCEPTION_TEXT --VARCHAR2(250)
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.EXTERNAL_ORDER_NUMBER),1,12) AS ADS_EXTERNAL_ORDER_NUMBER --VARCHAR2(12)
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.REJECT_CODE),1,10) AS ADS_REJECT_CODE --VARCHAR2(10)
    ,AUD__ADS_RESPONSE.QTY_DISPENSED AS ADS_QTY_DISPENSED --QTY_PICKED --NUMBER(13,3)
    ,AUD__ADS_RESPONSE.NUMBER_OF_VIALS AS ADS_NUMBER_OF_VIALS --NUMBER(3)
    ,AUD__ADS_RESPONSE.PACKAGE_SIZE AS ADS_PACKAGE_SIZE --NUMBER(13,3)
    ,ROUND((AUD__ADS_RESPONSE.DATE_COMPLETED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_COMPLETED --DATE
    ,ROUND((AUD__ADS_RESPONSE.DATE_FILLED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_FILLED --DATE
    ,AUD__ADS_RESPONSE.NDC_REQUESTED AS ADS_NDC_REQUESTED --VARCHAR2(13)
    ,AUD__ADS_RESPONSE.NDC_DISPENSED AS ADS_NDC_DISPENSED --VARCHAR2(13)
    ,SUBSTR(WEGMANS.CLEAN_STRING_FORTENUP(AUD__ADS_RESPONSE.QC_INITIALS),1,3) AS ADS_QC_INITIALS --VARCHAR2(3)
    ,AUD__ADS_RESPONSE.IS_EASY_OPEN_CAP AS ADS_IS_EASY_OPEN_CAP --CHAR(1)
    ,AUD__ADS_RESPONSE.STATUS AS ADS_STATUS_CODE --VARCHAR2(10)
    ,(CASE AUD__ADS_RESPONSE.STATUS
           WHEN 'A' THEN 'RX ACCEPTED - FILLING AT CF FACILITY'
           WHEN 'H' THEN 'ORDER SHIPPED'
           WHEN 'P' THEN 'COMPLETE - FILLED AT STORE'
           WHEN 'R' THEN 'RX REJECTED BY CFD'
           WHEN 'V' THEN 'RECEIVED AT STORE'
           WHEN 'C' THEN 'ORDER CANCELLED'
           WHEN 'E' THEN 'ERROR IN PROCESSING RESPONSE'
           WHEN 'F' THEN 'REFUSED CANCEL'
           ELSE NULL    
      END) AS ADS_STATUS_DESC --VARCHAR2(36)
    ,ROUND((AUD__ADS_RESPONSE.DATE_UPDATED - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATE_UPDATED --DATE
    ,ROUND((AUD__ADS_RESPONSE.DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS ADS_DATESTAMP --DATE
    
    ,ROUND((AUD__MANIFEST_ITEM.CHECK_OUT_DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_CHECK_OUT_DATESTAMP --DATE
    ,ROUND((AUD__MANIFEST_ITEM.CHECK_IN_DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_CHECK_IN_DATESTAMP --DATE
    ,ROUND((AUD__MANIFEST_ITEM.DATESTAMP - TO_DATE('20350101','YYYYMMDD')),6) AS MAN_DATESTAMP --DATE
    ,AUD__MANIFEST_ITEM.IS_PULLED_BACK AS MAN_IS_PULLED_BACK --CHAR(1)

    ,RANK() OVER (PARTITION BY
                       AUD__FILL_FACT.FILL_STATE_CHG_TS
                      ,AUD__FILL_FACT.FILL_STATE_CODE
                      ,AUD__FILL_FACT.FILL_STATE_KEY
                      ,AUD__ITEM.ORDER_NUM
                      ,AUD__ITEM.ITEM_SEQ
                  ORDER BY
                       AUD__ADS_RESPONSE.EFF_START_DATE DESC
                      ,ROW_NUMBER() OVER (ORDER BY AUD__ADS_RESPONSE.EFF_START_DATE) DESC
                      ,AUD__MANIFEST_ITEM.EFF_START_DATE DESC
                      ,AUD__MANIFEST_ITEM.ROWID DESC
                 ) AS CENTRALFILLRANK

    ,(CASE WHEN AUD__PRICE_CALC_RESULT.FILL_STATE_PRICE_NUM = AUD__FILL_STATE.FILL_STATE_PRICE_NUM
           THEN 1 ELSE 0 END) AS EQUAL_FILL_STATE_PRICE_NUM
    ,(CASE WHEN AUD__PRICE_CALC_RESULT2.FILL_STATE_PRICE_NUM = AUD__FILL_STATE.FILL_STATE_PRICE_NUM
           THEN 1 ELSE 0 END) AS EQUAL_FILL_STATE_PRICE_NUM2
    ,(CASE WHEN DW__TP_PATIENT.PD_PATIENT_KEY = DW__SHIPMENT_FACT.PD_PATIENT_KEY
           THEN 1 ELSE 0 END) AS EQUAL_PD_PATIENT_KEY

FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_FACT AUD__FILL_FACT
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__FACILITY
        ON DW__FACILITY.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
       AND DW__FACILITY.FD_IS_PPI_ENABLED = 'Y'
     INNER JOIN (
         SELECT FD_VALUE, FD_FACILITY_NUM FROM (
         SELECT FD_VALUE, FD_FACILITY_NUM,
             RANK() OVER (PARTITION BY FD_FACILITY_NUM
                          ORDER BY FD_NUM_UPDATES DESC) AS NPI_RANK
         FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID
         WHERE FD_TYPE = 'F08'
         ) WHERE NPI_RANK = 1
        ) DW__FACILITY_ID
        ON DW__FACILITY_ID.FD_FACILITY_NUM = AUD__FILL_FACT.FACILITY_NUM
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.FILL_STATE AUD__FILL_STATE
        ON AUD__FILL_STATE.H_LEVEL = AUD__FILL_FACT.FILL_STATE_KEY
       AND AUD__FILL_STATE.RX_RECORD_NUM = AUD__FILL_FACT.RX_RECORD_NUM
       AND AUD__FILL_STATE.RX_FILL_SEQ = AUD__FILL_FACT.RX_FILL_SEQ
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT DW__PRODUCT
        ON DW__PRODUCT.PRD_PRODUCT_NUM = AUD__FILL_FACT.DISPENSED_PROD_NUM
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DW__DRUG
        ON DW__DRUG.DRUG_NUM = AUD__FILL_FACT.DISPENSED_DRUG_NUM
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER DW__PRESCRIBER
        ON DW__PRESCRIBER.PRS_PRESCRIBER_NUM = AUD__FILL_FACT.PRESCRIBER_NUM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ADDRESS DW__PRESCRIBER_ADDRESS
        ON DW__PRESCRIBER_ADDRESS.PADR_PRESCRIBER_ADDRESS_NUM = AUD__FILL_FACT.PRESCRIBER_ADDRESS_NUM
     --INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT AUD__PATIENT
     --   ON AUD__PATIENT.PATIENT_NUM = AUD__FILL_FACT.PATIENT_NUM
     --  AND AUD__PATIENT.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     --LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS AUD__PATIENT_ADDRESS
     --   ON AUD__PATIENT_ADDRESS.PATIENT_NUM = AUD__FILL_FACT.PATIENT_NUM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT DW__TP_PATIENT
        ON DW__TP_PATIENT.TPD_TP_PATIENT_NUM = AUD__FILL_FACT.TP_PATIENT_NUM
       AND DW__TP_PATIENT.TPD_EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_MESSAGE AUD__TP_MESSAGE
        ON AUD__TP_MESSAGE.H_LEVEL = AUD__FILL_FACT.TP_MESSAGE_KEY
       AND AUD__TP_MESSAGE.TP_ITEM_CLAIM_NUM = AUD__FILL_FACT.TP_ITEM_CLAIM_NUM
       AND AUD__TP_MESSAGE.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.MEDICAL_CONDITION DW__MEDICAL_CONDITION
        ON DW__MEDICAL_CONDITION.MCD_MED_CONDITION_NUM = AUD__FILL_FACT.MEDICAL_CONDITION_NUM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN DW__TP_PLAN
        ON DW__TP_PLAN.TPLD_PLAN_NUM = AUD__FILL_FACT.TP_PLAN_NUM
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_PRIOR_AUTH AUD__TP_PRIOR_AUTH
        ON AUD__TP_PRIOR_AUTH.TP_PRIOR_AUTH_NUM = AUD__FILL_FACT.TP_PRIOR_AUTH_NUM
       AND AUD__TP_PRIOR_AUTH.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_PROCESSOR_DESTINATION AUD__TP_PROCESSOR_DESTINATION
        ON AUD__TP_PROCESSOR_DESTINATION.TP_PROCESSOR_DESTINATION_SEQ = AUD__FILL_FACT.TP_PROCESSOR_DEST_NUM
       AND AUD__TP_PROCESSOR_DESTINATION.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_ITEM_CLAIM AUD__TP_ITEM_CLAIM
        ON AUD__TP_ITEM_CLAIM.TP_ITEM_CLAIM_NUM = AUD__FILL_FACT.TP_ITEM_CLAIM_NUM
       AND AUD__TP_ITEM_CLAIM.H_LEVEL = AUD__FILL_FACT.TP_ITEM_CLAIM_KEY
       AND AUD__TP_ITEM_CLAIM.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_REQUEST_MESSAGE AUD__TP_REQUEST_MESSAGE
        ON AUD__TP_REQUEST_MESSAGE.TP_MESSAGE_NUM = AUD__TP_MESSAGE.TP_MESSAGE_NUM
       AND AUD__TP_REQUEST_MESSAGE.H_LEVEL = AUD__TP_MESSAGE.H_LEVEL
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.TP_RESPONSE_MESSAGE AUD__TP_RESPONSE_MESSAGE
        ON AUD__TP_RESPONSE_MESSAGE.TP_MESSAGE_NUM = AUD__TP_MESSAGE.TP_MESSAGE_NUM
       AND AUD__TP_RESPONSE_MESSAGE.H_LEVEL = AUD__TP_MESSAGE.H_LEVEL
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PRICE_CALC_RESULT AUD__PRICE_CALC_RESULT
        ON AUD__PRICE_CALC_RESULT.H_LEVEL = AUD__FILL_FACT.CURRENT_CLAIM_KEY
     LEFT OUTER JOIN 
        --{AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PRICE_CALC_RESULT
        (SELECT H_LEVEL, TP_PLAN_AMOUNT_PAID, FILL_STATE_PRICE_NUM
         FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PRICE_CALC_RESULT) AUD__PRICE_CALC_RESULT2
        ON AUD__PRICE_CALC_RESULT2.H_LEVEL = AUD__FILL_FACT.CURRENT_KEY
--       AND AUD__PRICE_CALC_RESULT2.FILL_STATE_PRICE_NUM = AUD__FILL_STATE.FILL_STATE_PRICE_NUM
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM AUD__ITEM
        ON AUD__ITEM.RX_RECORD_NUM = AUD__FILL_FACT.RX_RECORD_NUM
       AND AUD__ITEM.RX_FILL_SEQ = AUD__FILL_FACT.RX_FILL_SEQ
       AND AUD__ITEM.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
       AND AUD__ITEM.H_TYPE != 'D'
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ORDER_RECORD AUD__ORDER_RECORD
         ON AUD__ORDER_RECORD.ORDER_NUM = AUD__ITEM.ORDER_NUM
        AND AUD__ORDER_RECORD.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT DW__PATIENT
         ON DW__PATIENT.PD_PATIENT_NUM = AUD__FILL_FACT.PATIENT_NUM
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.SHIPMENT_FACT DW__SHIPMENT_FACT
         ON DW__SHIPMENT_FACT.ORDER_NUM = AUD__ITEM.ORDER_NUM
        AND DW__SHIPMENT_FACT.PD_PATIENT_KEY = DW__PATIENT.PD_PATIENT_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COURIER_SHIPMENT_TYPE DW__COURIER_SHIPMENT_TYPE
         ON DW__COURIER_SHIPMENT_TYPE.COURIER_SHIPMENT_KEY = DW__SHIPMENT_FACT.COURIER_SHIPMENT_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.COURIER_SHIPMENT_TYPE DW__COURIER_SHIPMENT_TYPE_ORIG
         ON DW__COURIER_SHIPMENT_TYPE_ORIG.COURIER_SHIPMENT_KEY = DW__SHIPMENT_FACT.ORIG_COURIER_SHIPMENT_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DELIVERY_METHOD_TYPE DW__DELIVERY_METHOD_TYPE
         ON DW__DELIVERY_METHOD_TYPE.DM_DELIVERY_METHOD_KEY = DW__SHIPMENT_FACT.DM_DELIVERY_METHOD_KEY
     LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY DW__SHIPMENT_FACT_FACILITY
        ON DW__SHIPMENT_FACT_FACILITY.FD_FACILITY_KEY = DW__SHIPMENT_FACT.FD_FACILITY_KEY
       AND DW__SHIPMENT_FACT_FACILITY.FD_IS_PPI_ENABLED = 'Y'
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_FILL AUD__RX_FILL
        ON AUD__RX_FILL.RX_RECORD_NUM = AUD__ITEM.RX_RECORD_NUM
       AND AUD__RX_FILL.RX_FILL_SEQ = AUD__ITEM.RX_FILL_SEQ
       AND AUD__RX_FILL.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ADS_RESPONSE AUD__ADS_RESPONSE
        ON AUD__ADS_RESPONSE.ORDER_NUM = AUD__ITEM.ORDER_NUM
       AND AUD__ADS_RESPONSE.ITEM_SEQ = AUD__ITEM.ITEM_SEQ
       AND AUD__ADS_RESPONSE.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.MANIFEST_ITEM AUD__MANIFEST_ITEM
        ON AUD__MANIFEST_ITEM.ORDER_NUM = AUD__ITEM.ORDER_NUM
       AND AUD__MANIFEST_ITEM.ITEM_SEQ = AUD__ITEM.ITEM_SEQ
       AND AUD__MANIFEST_ITEM.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
    WHERE AUD__FILL_FACT.FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 1) 
                                               AND (:RUNDATE - 1 + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
  )
  WHERE CENTRALFILLRANK = 1
)
WHERE MALARKEYRANK = 1
ORDER BY
     STORE_NUM
    ,RX_NUM_TXT
    ,REFILL_NUM
    ,PARTIAL_FILL_SEQ
    ,SPLIT_BILLING_CODE
    ,FILL_STATE_CHG_TS
    ,FILL_STATE_CODE
    ,RX_RECORD_NUM
    ,RX_FILL_SEQ
    ,ORDER_NUM
    ,ITEM_SEQ