SELECT DISTINCT (:RunDate - 1) "DATE_OF_SERVICE",
        VENDOR.VENDOR_NAME "SUPPLIER_NAME",
        PRICE_CAT.VENDOR_PRODUCT_ID "VENDOR_ITEM_NUMBER",
        LPAD(SUBSTR(DRUG_NDC::TEXT, 1, 5), 5, '0') || '-' ||
			  LPAD(SUBSTR(DRUG_NDC::TEXT, 6, 4), 4, '0') || '-' ||
			  LPAD(SUBSTR(DRUG_NDC::TEXT, 10, 2), 2, '0') "NDC",
        TO_CHAR(DRUG.DRUG_NDC) "NDC_WO",
        DRUG.DRUG_LABEL_NAME "DRUG_NAME",
        DRUG.DRUG_DOSAGE_FORM "DRUG_FORM",
        DRUG.DRUG_DEA_CLASS "DEA_CLASS",
        DRUG.DRUG_STRENGTH "STRENGTH",
        DRUG.DRUG_STRENGTH_UNITS "STRENGTH_UNIT",
        DRUG.DRUG_GNN "GENERIC_NAME",
        DRUG.DRUG_PACKAGE_SIZE "PACK_SIZE",
        DRUG.DRUG_IS_MAINT_DRUG "IS_MAINT_DRUG",
        PRODUCT.PRD_IS_GENERIC "SDGI",
        DRUG.DRUG_GCN "GCN",
        DRUG.DRUG_GCN_SEQ "GCN_SEQ_NUM",
        DRUG.DRUG_LABELER "DRUG_MANUFACTURER",
        DRUG.DRUG_ORANGE_BOOK_CODE "ORANGE_BOOK_CODE",
        PRICE_CAT.UNIT_PRICE "PACK_PRICE",
        ROUND(PRICE_CAT.UNIT_PRICE/DRUG.DRUG_PACKAGE_SIZE,3) "PRICE_PER_UNIT",
        PRICE_CAT.UNIT_PRICE_DATE "UNIT_PRICE_DATE",
        PRICE_CAT.PURCHASE_INCREMENT "PURCH_INCR",
        PRICE_CAT.PKG_SIZE "PKG_SIZE_INCR",
        PRICE_CAT.STATUS "STATUS",
        PRICE_CAT.EFFECTIVE_START_DATE "EFF_START_DATE"

FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR_PRICE_CATALOG PRICE_CAT

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.VENDOR VENDOR
ON VENDOR.VENDOR_KEY = PRICE_CAT.VENDOR_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
ON DRUG.DRUG_KEY = PRICE_CAT.DRUG_KEY

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRODUCT
ON PRODUCT.PRD_PRODUCT_KEY = PRICE_CAT.PRD_PRODUCT_KEY

WHERE PRICE_CAT.VENDOR_KEY IN (19617, 19616,29018,29019,2,1,29518,30019)
AND PRICE_CAT.EFFECTIVE_END_DATE = TO_DATE('2999-12-31','YYYY-MM-DD')

ORDER BY VENDOR.VENDOR_NAME,PRICE_CAT.STATUS,DRUG.DRUG_LABEL_NAME
