SELECT DISTINCT AUDPG.PATIENT_NUM "PATIENT_NUM",
        PATIENT.CREATE_DATE "PT_CREATE_DATE",
        FAC.FD_FACILITY_ID "CREATE_STORE_NUM",
        AUDPG.DATESTAMP "PT_TAGGED_DATE",
        AUDPG.EFF_START_DATE "PT_INGROUP_START",
        AUDPG.EFF_END_DATE "PT_INGROUP_END",
        AUDPG.GROUP_NUM "GROUP_NUM",
        DWG.GRP_NAME "GROUP_NAME",
        DWG.GRP_DESCRIPTION "GROUP_DESC",
        DWG.GRP_TYPE "GROUP_STATUS",
        DWG.GRP_IS_ACTIVE "GROUP_IS_ACTIVE",
        DWG.GRP_CREATE_DATE "GROUP_CREATE_DT",
        DWG.DW_LAST_UPDATE_DT "GROUP_LAST_UPDATED"

FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT_GROUP AUDPG

LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PATIENT PATIENT
ON PATIENT.PATIENT_NUM = AUDPG.PATIENT_NUM
AND PATIENT.EFF_END_DATE = TO_DATE('2999-12-31','YYYY-MM-DD')

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.GROUPS DWG
ON AUDPG.GROUP_NUM = DWG.GRP_GROUP_NUM

LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
ON PATIENT.CREATE_FACILITY_NUM = FAC.FD_FACILITY_NUM

WHERE AUDPG.DATESTAMP BETWEEN (:RUNDATE - 1)
  AND ((:RUNDATE - 1) + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')