SELECT 
     DISTINCT
     TO_NUMBER(FAC.FD_FACILITY_ID) AS STORE_NUM
    ,CTR.CC_TRANS_GATEWAY_CLIENT_ID AS MERCHANT_ID
    ,CTR.CC_TRANS_COMMAND_TYPE
    ,CASE WHEN (   CTRS.CC_TRANS_PROCESSOR_TRANS_DATE IS NULL
                OR CTRS.CC_TRANS_PROCESSOR_TRANS_TIME IS NULL)
               THEN ROUND(((:RUNDATE - 1) - TO_DATE('20350101','YYYYMMDD')),6)
          ELSE ROUND((TO_DATE(CTRS.CC_TRANS_PROCESSOR_TRANS_DATE || ' ' || CTRS.CC_TRANS_PROCESSOR_TRANS_TIME,'YYYY.MM.DD HH24:MI:SS') - TO_DATE('20350101','YYYYMMDD')),6)
     END AS TRANSACTION_DATETIME
    ,CASE WHEN CTRS.CC_TRANS_PROCESSOR_TRANS_DATE IS NULL
               THEN TO_NUMBER(TO_CHAR((:RUNDATE - 1)::DATE,'YYYYMMDD'))
          ELSE TO_NUMBER(REGEXP_REPLACE(CTRS.CC_TRANS_PROCESSOR_TRANS_DATE,'\.',''))
     END AS TRANSACTION_DATE
    ,CTRS.CC_TRANS_REQUEST_NUM
    ,CTRS.CC_TRANS_PAYMENT_MEDIA
    ,CTRS.CC_TRANS_PAYMENT_TYPE
    ,CTRS.CC_TRANS_STATUS_MSG
    ,CTRS.CC_TRANS_STATUS_CODE
    ,CTRS.CC_TRANS_PROCESSOR_TRANS_NUM
    ,CTRS.CC_TRANS_REFERENCE_NUM
    ,RPAD(TRIM(CTRS.CC_TRANS_AUTHORIZATION_CODE),6) AS CC_TRANS_AUTHORIZATION_CODE
    ,CTRS.CC_TRANS_AVS_CODE
    ,CASE CTR.CC_TRANS_COMMAND_TYPE
          WHEN 'CREDIT' THEN CTRS.CC_TRANS_CC_AMOUNT * -1
          WHEN 'REVERSAL' THEN CTRS.CC_TRANS_CC_AMOUNT * -1
          ELSE CTRS.CC_TRANS_CC_AMOUNT
     END AS AUTHORIZATION_AMOUNT
    ,CASE CTR.CC_TRANS_COMMAND_TYPE
          WHEN 'CREDIT' THEN CTR.CC_TRANS_CC_AMOUNT * -1
          WHEN 'REVERSAL' THEN CTR.CC_TRANS_CC_AMOUNT * -1
          ELSE CTR.CC_TRANS_CC_AMOUNT
     END AS TRANSACTION_AMOUNT
    ,OAMCC.LAST4_PAN AS CC_LAST4
    ,TO_NUMBER(TO_CHAR(OAMCC.EXPIRATION_DATE::DATE,'YYYYMMDD')) AS CC_EXPIRE_DATE     
FROM {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CC_TRANS_RESPONSE CTRS
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CC_TRANS_REQUEST CTR
         ON CTR.CC_TRANS_REQUEST_NUM = CTRS.CC_TRANS_REQUEST_NUM 
        AND CTR.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
        AND CTR.CC_TRANS_REQUEST_TYPE != 'IPCRB_ADMIN'
     LEFT JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT_GROUP_LIST PGL
         ON CTR.CC_TRANS_ERX_PAYMENT_NUM = PGL.PAYMENT_NUM
        AND PGL.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD') 
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM I
         ON I.PAYMENT_GROUP_NUM = PGL.PAYMENT_GROUP_NUM
        AND I.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ORDER_RECORD O
         ON O.ORDER_NUM = I.ORDER_NUM
        AND O.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX RX
         ON RX.RX_RECORD_NUM = I.RX_RECORD_NUM
        AND RX.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.RX_FILL RF
         ON RF.RX_FILL_SEQ = I.RX_FILL_SEQ
        AND RF.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     INNER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.PAYMENT PAY
         ON PAY.PAYMENT_NUM = PGL.PAYMENT_NUM
        AND PAY.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ACCOUNT_MEMBER_CREDIT_CARD OAMCC
         ON PAY.ACCOUNT_MEMBER_CREDIT_CARD_NUM = OAMCC.ACCOUNT_MEMBER_CREDIT_CARD_NUM
        AND OAMCC.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.CREDIT_CARD_TYPE CCT
         ON CCT.CREDIT_CARD_TYPE_NUM = OAMCC.CREDIT_CARD_TYPE_NUM
        AND CCT.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PAYMENT_TYPE PT
         ON PT.PAYMENT_TYPE_NUM = PAY.PAYMENT_TYPE_NUM
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PAT
         ON PAT.PD_PATIENT_NUM = RX.PATIENT_NUM
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD
         ON PRD.PRD_PRODUCT_NUM = I.PRODUCT_NUM
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
         ON DRUG.DRUG_NUM = PRD.PRD_DRUG_NUM
     LEFT JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
         ON FAC.FD_FACILITY_NUM = O.ORDER_OWNER_FACILITY_NUM
        AND FAC.FD_FACILITY_ID != '299'
WHERE CTRS.EFF_START_DATE BETWEEN (:RUNDATE - 1) AND (:RUNDATE + 1)
  AND CTRS.EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
  AND CTR.CC_TRANS_COMMAND_TYPE || '' IS NOT NULL
  AND FAC.FD_FACILITY_ID || '' IS NOT NULL
  AND (
          (    CTRS.CC_TRANS_PROCESSOR_TRANS_DATE IS NULL
           AND CTRS.DATESTAMP BETWEEN (:RUNDATE - 1) AND :RUNDATE
          )
       OR
          (    CTRS.CC_TRANS_PROCESSOR_TRANS_DATE IS NOT NULL
           AND CC_TRANS_PROCESSOR_TRANS_TIME IS NOT NULL
           AND TO_DATE(CTRS.CC_TRANS_PROCESSOR_TRANS_DATE || ' ' || CC_TRANS_PROCESSOR_TRANS_TIME,'YYYY.MM.DD HH24:MI:SS')
               BETWEEN (:RUNDATE - 1) AND :RUNDATE
          )
      )