SELECT
   FIELD01
  ,FIELD02
  ,FIELD03
  ,FIELD04
  ,FIELD05
  ,FIELD06
  ,FIELD07
  ,FIELD08
  ,FIELD09
  ,FIELD10
  ,FIELD11
  ,FIELD12
  ,FIELD13
  ,FIELD14
  ,FIELD15
  ,FIELD16
  ,FIELD17
  ,FIELD18
  ,FIELD19
  ,FIELD20
  ,FIELD21
  ,FIELD22
  ,FIELD23
  ,FIELD24
  ,FIELD25
  ,FIELD26
  ,FIELD27
  ,FIELD28
  ,FIELD29
  ,FIELD30
  ,FIELD31
  ,FIELD32
  ,FIELD33
  ,FIELD34
  ,FIELD35
  ,FIELD36
  ,FIELD37
  ,FIELD38
  ,FIELD39
  ,FIELD40
  ,FIELD41
  ,FIELD42
  ,FIELD43
  ,FIELD44
  ,FIELD45
  ,FIELD46
  ,FIELD47
  ,FIELD48
  ,FIELD49
  ,FIELD50
  ,FIELD51
  ,FIELD52
  ,FIELD53
  ,FIELD54
  ,FIELD55
  ,FIELD56
  ,FIELD57
  ,FIELD58
  ,FIELD59
  ,FIELD60
  ,FIELD61
  ,FIELD62
  ,FIELD63
  ,FIELD64
  ,FIELD65
  ,FIELD66
  ,FIELD67
  ,FIELD68
  ,FIELD69
  ,FIELD70
  ,FIELD71
  ,FIELD72
  ,FIELD73
  ,FIELD74
  ,FIELD75
  ,FIELD76
  ,FIELD77
  ,FIELD78
  ,FIELD79
  ,FIELD80
  ,FIELD81
  ,FIELD82
  ,FIELD83
  ,FIELD84
  ,FIELD85
  ,FIELD86
  ,FIELD87
  ,FIELD88
  ,FIELD89
  ,FIELD90
  ,FIELD91
  ,FIELD92
  ,FIELD93
  ,FIELD94
  ,FIELD95
  ,FIELD96
  ,FIELD97
  ,FIELD98
  ,FIELD99
  ,FIELD100
  ,FIELD101
  ,FIELD102
  ,FIELD103
  ,FIELD104
  ,FIELD105
  ,FIELD106
  ,FIELD107
  ,FIELD108
 FROM (
		 SELECT
			 CAST(SET_TO_FIXED_WIDTH(FIELD01, 2, 'L') AS CHAR(2 CHAR)) AS FIELD01
			,CAST(SET_TO_FIXED_WIDTH(FIELD02, 1, 'L') AS CHAR(1 CHAR)) AS FIELD02
			,CAST(SET_TO_FIXED_WIDTH(FIELD03, 8, 'L') AS CHAR(8 CHAR)) AS FIELD03
			,CAST(SET_TO_FIXED_WIDTH(FIELD04, 6, 'L') AS CHAR(6 CHAR)) AS FIELD04
			,CAST(SET_TO_FIXED_WIDTH(FIELD05, 15, 'L') AS CHAR(15 CHAR)) AS FIELD05
			,CAST(SET_TO_FIXED_WIDTH(FIELD06, 10, 'L') AS CHAR(10 CHAR)) AS FIELD06
			,CAST(SET_TO_FIXED_WIDTH(FIELD07, 6, 'L') AS CHAR(6 CHAR)) AS FIELD07
			,CAST(SET_TO_FIXED_WIDTH(FIELD08, 15, 'L') AS CHAR(15 CHAR)) AS FIELD08
			,CAST(SET_TO_FIXED_WIDTH(FIELD09, 8, 'L') AS CHAR(8 CHAR)) AS FIELD09
			,CAST(SET_TO_FIXED_WIDTH(FIELD10, 1, 'R') AS CHAR(1 CHAR)) AS FIELD10
			,CAST(SET_TO_FIXED_WIDTH(FIELD11, 1, 'R') AS CHAR(1 CHAR)) AS FIELD11
			,CAST(SET_TO_FIXED_WIDTH(FIELD12, 2, 'R') AS CHAR(2 CHAR)) AS FIELD12
			,CAST(SET_TO_FIXED_WIDTH(FIELD13, 2, 'R') AS CHAR(2 CHAR)) AS FIELD13
			,CAST(SET_TO_FIXED_WIDTH(FIELD14, 1, 'R') AS CHAR(1 CHAR)) AS FIELD14
			,CAST(SET_TO_FIXED_WIDTH(FIELD15, 8, 'L') AS CHAR(8 CHAR)) AS FIELD15
			,CAST(SET_TO_FIXED_WIDTH(FIELD16, 3, 'L') AS CHAR(3 CHAR)) AS FIELD16
			,CAST(SET_TO_FIXED_WIDTH(FIELD17, 3, 'R') AS CHAR(3 CHAR)) AS FIELD17
			,CAST(SET_TO_FIXED_WIDTH(FIELD18, 10, 'L') AS CHAR(10 CHAR)) AS FIELD18
			,CAST(SET_TO_FIXED_WIDTH(FIELD19, 7, 'L') AS CHAR(7 CHAR)) AS FIELD19
			,CAST(SET_TO_FIXED_WIDTH(FIELD20, 2, 'R') AS CHAR(2 CHAR)) AS FIELD20
			,CAST(SET_TO_FIXED_WIDTH(FIELD21, 10, 'R') AS CHAR(10 CHAR)) AS FIELD21
			,CAST(SET_TO_FIXED_WIDTH(FIELD22, 3, 'R') AS CHAR(3 CHAR)) AS FIELD22
			,CAST(SET_TO_FIXED_WIDTH(FIELD23, 1, 'R') AS CHAR(1 CHAR)) AS FIELD23
			,CAST(SET_TO_FIXED_WIDTH(FIELD24, 19, 'L') AS CHAR(19 CHAR)) AS FIELD24
			,CAST(SET_TO_FIXED_WIDTH(FIELD25, 2, 'L') AS CHAR(2 CHAR)) AS FIELD25
			,CAST(SET_TO_FIXED_WIDTH(FIELD26, 1, 'L') AS CHAR(1 CHAR)) AS FIELD26
			,CAST(SET_TO_FIXED_WIDTH(FIELD27, 8, 'R') AS CHAR(8 CHAR)) AS FIELD27
			,CAST(SET_TO_FIXED_WIDTH(FIELD28, 8, 'R') AS CHAR(8 CHAR)) AS FIELD28
			,CAST(SET_TO_FIXED_WIDTH(FIELD29, 9, 'L') AS CHAR(9 CHAR)) AS FIELD29
			,CAST(SET_TO_FIXED_WIDTH(FIELD30, 6, 'L') AS CHAR(6 CHAR)) AS FIELD30
			,CAST(SET_TO_FIXED_WIDTH(FIELD31, 2, 'L') AS CHAR(2 CHAR)) AS FIELD31
			,CAST(SET_TO_FIXED_WIDTH(FIELD32, 8, 'R') AS CHAR(8 CHAR)) AS FIELD32
			,CAST(SET_TO_FIXED_WIDTH(FIELD33, 8, 'R') AS CHAR(8 CHAR)) AS FIELD33
			,CAST(SET_TO_FIXED_WIDTH(FIELD34, 8, 'L') AS CHAR(8 CHAR)) AS FIELD34
			,CAST(SET_TO_FIXED_WIDTH(FIELD35, 2, 'R') AS CHAR(2 CHAR)) AS FIELD35
			,CAST(SET_TO_FIXED_WIDTH(FIELD36, 2, 'R') AS CHAR(2 CHAR)) AS FIELD36
			,CAST(SET_TO_FIXED_WIDTH(FIELD37, 11, 'R') AS CHAR(11 CHAR)) AS FIELD37
			,CAST(SET_TO_FIXED_WIDTH(FIELD38, 2, 'R') AS CHAR(2 CHAR)) AS FIELD38
			,CAST(SET_TO_FIXED_WIDTH(FIELD39, 1, 'R') AS CHAR(1 CHAR)) AS FIELD39
			,CAST(SET_TO_FIXED_WIDTH(FIELD40, 2, 'R') AS CHAR(2 CHAR)) AS FIELD40
			,CAST(SET_TO_FIXED_WIDTH(FIELD41, 15, 'L') AS CHAR(15 CHAR)) AS FIELD41
			,CAST(SET_TO_FIXED_WIDTH(FIELD42, 2, 'L') AS CHAR(2 CHAR)) AS FIELD42
			,CAST(SET_TO_FIXED_WIDTH(FIELD43, 2, 'L') AS CHAR(2 CHAR)) AS FIELD43
			,CAST(SET_TO_FIXED_WIDTH(FIELD44, 15, 'L') AS CHAR(15 CHAR)) AS FIELD44
			,CAST(SET_TO_FIXED_WIDTH(FIELD45, 2, 'L') AS CHAR(2 CHAR)) AS FIELD45
			,CAST(SET_TO_FIXED_WIDTH(FIELD46, 1, 'R') AS CHAR(1 CHAR)) AS FIELD46
			,CAST(SET_TO_FIXED_WIDTH(FIELD47, 8, 'R') AS CHAR(8 CHAR)) AS FIELD47
			,CAST(SET_TO_FIXED_WIDTH(FIELD48, 15, 'L') AS CHAR(15 CHAR)) AS FIELD48
			,CAST(SET_TO_FIXED_WIDTH(FIELD49, 1, 'R') AS CHAR(1 CHAR)) AS FIELD49
			,CAST(SET_TO_FIXED_WIDTH(FIELD50, 8, 'R') AS CHAR(8 CHAR)) AS FIELD50
			,CAST(SET_TO_FIXED_WIDTH(FIELD51, 8, 'R') AS CHAR(8 CHAR)) AS FIELD51
			,CAST(SET_TO_FIXED_WIDTH(FIELD52, 8, 'L') AS CHAR(8 CHAR)) AS FIELD52
			,CAST(SET_TO_FIXED_WIDTH(FIELD53, 30, 'L') AS CHAR(30 CHAR)) AS FIELD53
			,CAST(SET_TO_FIXED_WIDTH(FIELD54, 8, 'R') AS CHAR(8 CHAR)) AS FIELD54
			,CAST(SET_TO_FIXED_WIDTH(FIELD55, 2, 'L') AS CHAR(2 CHAR)) AS FIELD55
			,CAST(SET_TO_FIXED_WIDTH(FIELD56, 2, 'L') AS CHAR(2 CHAR)) AS FIELD56
			,CAST(SET_TO_FIXED_WIDTH(FIELD57, 2, 'L') AS CHAR(2 CHAR)) AS FIELD57
			,CAST(SET_TO_FIXED_WIDTH(FIELD58, 8, 'L') AS CHAR(8 CHAR)) AS FIELD58
			,CAST(SET_TO_FIXED_WIDTH(FIELD59, 15, 'L') AS CHAR(15 CHAR)) AS FIELD59
			,CAST(SET_TO_FIXED_WIDTH(FIELD60, 2, 'L') AS CHAR(2 CHAR)) AS FIELD60
			,CAST(SET_TO_FIXED_WIDTH(FIELD61, 19, 'L') AS CHAR(19 CHAR)) AS FIELD61
			,CAST(SET_TO_FIXED_WIDTH(FIELD62, 2, 'L') AS CHAR(2 CHAR)) AS FIELD62
			,CAST(SET_TO_FIXED_WIDTH(FIELD63, 10, 'R') AS CHAR(10 CHAR)) AS FIELD63
			,CAST(SET_TO_FIXED_WIDTH(FIELD64, 2, 'L') AS CHAR(2 CHAR)) AS FIELD64
			,CAST(SET_TO_FIXED_WIDTH(FIELD65, 8, 'R') AS CHAR(8 CHAR)) AS FIELD65
			,CAST(SET_TO_FIXED_WIDTH(FIELD66, 8, 'R') AS CHAR(8 CHAR)) AS FIELD66
			,CAST(SET_TO_FIXED_WIDTH(FIELD67, 8, 'R') AS CHAR(8 CHAR)) AS FIELD67
			,CAST(SET_TO_FIXED_WIDTH(FIELD68, 8, 'R') AS CHAR(8 CHAR)) AS FIELD68
			,CAST(SET_TO_FIXED_WIDTH(FIELD69, 8, 'R') AS CHAR(8 CHAR)) AS FIELD69
			,CAST(SET_TO_FIXED_WIDTH(FIELD70, 3, 'L') AS CHAR(3 CHAR)) AS FIELD70
			,CAST(SET_TO_FIXED_WIDTH(FIELD71, 3, 'L') AS CHAR(3 CHAR)) AS FIELD71
			,CAST(SET_TO_FIXED_WIDTH(FIELD72, 3, 'L') AS CHAR(3 CHAR)) AS FIELD72
			,CAST(SET_TO_FIXED_WIDTH(FIELD73, 8, 'R') AS CHAR(8 CHAR)) AS FIELD73
			,CAST(SET_TO_FIXED_WIDTH(FIELD74, 8, 'R') AS CHAR(8 CHAR)) AS FIELD74
			,CAST(SET_TO_FIXED_WIDTH(FIELD75, 8, 'R') AS CHAR(8 CHAR)) AS FIELD75
			,CAST(SET_TO_FIXED_WIDTH(FIELD76, 30, 'L') AS CHAR(30 CHAR)) AS FIELD76
			,CAST(SET_TO_FIXED_WIDTH(FIELD77, 8, 'R') AS CHAR(8 CHAR)) AS FIELD77
			,CAST(SET_TO_FIXED_WIDTH(FIELD78, 8, 'R') AS CHAR(8 CHAR)) AS FIELD78
			,CAST(SET_TO_FIXED_WIDTH(FIELD79, 8, 'R') AS CHAR(8 CHAR)) AS FIELD79
			,CAST(SET_TO_FIXED_WIDTH(FIELD80, 8, 'R') AS CHAR(8 CHAR)) AS FIELD80
			,CAST(SET_TO_FIXED_WIDTH(FIELD81, 8, 'R') AS CHAR(8 CHAR)) AS FIELD81
			,CAST(SET_TO_FIXED_WIDTH(FIELD82, 2, 'R') AS CHAR(2 CHAR)) AS FIELD82
			,CAST(SET_TO_FIXED_WIDTH(FIELD83, 8, 'R') AS CHAR(8 CHAR)) AS FIELD83
			,CAST(SET_TO_FIXED_WIDTH(FIELD84, 8, 'L') AS CHAR(8 CHAR)) AS FIELD84
			,CAST(SET_TO_FIXED_WIDTH(FIELD85, 7, 'L') AS CHAR(7 CHAR)) AS FIELD85
			,CAST(SET_TO_FIXED_WIDTH(FIELD86, 8, 'L') AS CHAR(8 CHAR)) AS FIELD86
			,CAST(SET_TO_FIXED_WIDTH(FIELD87, 15, 'L') AS CHAR(15 CHAR)) AS FIELD87
			,CAST(SET_TO_FIXED_WIDTH(FIELD88, 5, 'R') AS CHAR(5 CHAR)) AS FIELD88
			,CAST(SET_TO_FIXED_WIDTH(FIELD89, 32, 'L') AS CHAR(32 CHAR)) AS FIELD89
			,CAST(SET_TO_FIXED_WIDTH(FIELD90, 1, 'L') AS CHAR(1 CHAR)) AS FIELD90
			,CAST(SET_TO_FIXED_WIDTH(FIELD91, 31, 'L') AS CHAR(31 CHAR)) AS FIELD91
			,CAST(SET_TO_FIXED_WIDTH(FIELD92, 15, 'R') AS CHAR(15 CHAR)) AS FIELD92
			,CAST(SET_TO_FIXED_WIDTH(FIELD93, 1, 'L') AS CHAR(1 CHAR)) AS FIELD93
			,CAST(SET_TO_FIXED_WIDTH(FIELD94, 10, 'L') AS CHAR(10 CHAR)) AS FIELD94
			,CAST(SET_TO_FIXED_WIDTH(FIELD95, 1, 'L') AS CHAR(1 CHAR)) AS FIELD95
			,CAST(SET_TO_FIXED_WIDTH(FIELD96, 15, 'L') AS CHAR(15 CHAR)) AS FIELD96
			,CAST(SET_TO_FIXED_WIDTH(FIELD97, 2, 'L') AS CHAR(2 CHAR)) AS FIELD97
			,CAST(SET_TO_FIXED_WIDTH(FIELD98, 5, 'L') AS CHAR(5 CHAR)) AS FIELD98
			,CAST(SET_TO_FIXED_WIDTH(FIELD99, 2, 'L') AS CHAR(2 CHAR)) AS FIELD99
			,CAST(SET_TO_FIXED_WIDTH(FIELD100, 11, 'L') AS CHAR(11 CHAR)) AS FIELD100
			,CAST(SET_TO_FIXED_WIDTH(FIELD101, 20, 'L') AS CHAR(20 CHAR)) AS FIELD101
			,CAST(SET_TO_FIXED_WIDTH(FIELD102, 30, 'L') AS CHAR(30 CHAR)) AS FIELD102
			,CAST(SET_TO_FIXED_WIDTH(FIELD103, 5, 'R') AS CHAR(5 CHAR)) AS FIELD103
			,CAST(SET_TO_FIXED_WIDTH(FIELD104, 9, 'L') AS CHAR(9 CHAR)) AS FIELD104
			,CAST(SET_TO_FIXED_WIDTH(FIELD105, 8, 'L') AS CHAR(8 CHAR)) AS FIELD105
			,CAST(SET_TO_FIXED_WIDTH(FIELD106, 1, 'L') AS CHAR(1 CHAR)) AS FIELD106
			,CAST(SET_TO_FIXED_WIDTH(FIELD107, 10, 'L') AS CHAR(10 CHAR)) AS FIELD107
			,CAST(SET_TO_FIXED_WIDTH(FIELD108, 1, 'L') AS CHAR(1 CHAR)) AS FIELD108
			,FF_FILL_STATE_CHG_TS
		FROM (
			  SELECT
				  '5X' AS FIELD01 --VERSION/RELEASE NUMBER
				 ,(CASE WHEN FF.FILL_STATE_CODE = 14 THEN 'C'
						WHEN FF.FILL_STATE_CODE = 16 THEN 'R'
						ELSE ' '
				   END) AS FIELD02 --RECORD TYPE
				 ,TO_CHAR(FF.ADJUDICATION_DATE::DATE,'YYYYMMDD') AS FIELD03 --DATE AUTHORIZED
				 ,TO_CHAR(FF.ADJUDICATION_DATE::DATE, 'HH24MISS') AS FIELD04 --TIME AUTHORIZED
				 ,FAC_ID.FD_VALUE AS FIELD05 --SERVICE PROVIDER ID
				 ,TPPD.PROCESSOR_CONTROL_NUMBER AS FIELD06 --PROCESSOR CONTROL NUMBER
				 ,TPPD.BIN_NUMBER AS FIELD07 --BIN NUMBER
				 ,TPP.TPD_BENEFIT_GROUP_ID AS FIELD08 --GROUP ID
				 ,(CASE WHEN PAT_ADD.BIRTH_DATE IS NULL THEN '        '
						ELSE TO_CHAR(PAT_ADD.BIRTH_DATE::DATE,'YYYYMMDD')
				   END) AS FIELD09 --DATE OF BIRTH
				 ,(CASE WHEN PAT_ADD.GENDER = 'M' THEN '1'
						WHEN PAT_ADD.GENDER = 'F' THEN '2'
						ELSE '0'
				   END) AS FIELD10 --PATIENT GENDER CODE
				 ,TO_CHAR(NVL(TPP.TPD_RELATIONSHIP_NUM,0)) AS FIELD11 --PATIENT RELATIONSHIP CODE
				 ,TO_CHAR(NVL(TPP.TPD_PATIENT_LOCATION,0)) AS FIELD12 --PATIENT LOCATION CODE
				 ,TO_CHAR(NVL(FF.OTHER_COVERAGE_CODE_NUM,0)) AS FIELD13 --OTHER COVERAGE CODE
				 ,TO_CHAR(NVL(TPP.TPD_ELIGIBILITY_CLARIF_NUM,0)) AS FIELD14 --ELIGIBILITY CLARIFICATION CODE
				 ,(CASE WHEN FF.DATE_OF_SERVICE IS NULL THEN '        '
						ELSE TO_CHAR(FF.DATE_OF_SERVICE::DATE,'YYYYMMDD')
				   END) AS FIELD15 --DATE OF SERVICE
				 ,TPP.TPD_HOME_PLAN AS FIELD16 --HOME PLAN
				 ,(CASE WHEN PAT_ADD.ZIP IS NULL THEN '   '
						ELSE SUBSTR(PAT_ADD.ZIP,1,3)
				   END) AS FIELD17 --PATIENT ZIP CODE
				 ,SUBSTR(TP.TPLD_PLAN_CODE, 1, 3) AS FIELD18 --CARRIER ID
				 ,'       ' AS FIELD19 --FILLER
				 ,TO_CHAR(FF.REFILL_NUM) AS FIELD20 --FILL NUMBER
				 ,TO_CHAR((FF.QTY_DISPENSED * 1000)) AS FIELD21 --QUANTITY DISPENSED
				 ,TO_CHAR(FF.DAYS_SUPPLY) AS FIELD22 --DAYS SUPPLY
				 ,(CASE WHEN PROD.PRD_IS_COMPOUND = 'Y' THEN '2'
						ELSE '1'
				   END) AS FIELD23 --COMPOUND CODE
				 ,DRUG.DRUG_NDC AS FIELD24 --PRODUCT/SERVICE ID
				 ,'03' AS FIELD25 --PRODUCT/SERVICE ID QUALIFIER
				 ,NVL(FF.DAW_CODE,'0') AS FIELD26 --DAW PRODUCT SELECTION CODE
				,TO_CHAR((CASE WHEN SUBSTR(TP.TPLD_PLAN_CODE, 4, 9) IN (
						'TREMVCH'
						,'TREMLIN'
						,'TREMND'
						,'STEL90V'
						,'STEL90'
						,'STEL90N'
						,'STEL45V'
						,'STEL45'
						,'STEL45N'
						,'SIMP50V'
						,'SIMP50'
						,'SIMP50N'
						,'SIMP100V'
						,'SIMP100'
						,'SIMP100N'
						,'JVR'
						,'JLR'
						,'EPAON'
						,'EPAOR'
						,'PAR'
						,'OVF'
						,'OVR'
						,'OVND'
						,'ZFF'
						,'ZYR')
					THEN 0
					ELSE FF.DISPENSED_QTY_AWP END)*100) AS FIELD27 --INGREDIENT COST SUBMITTED (AWP)
				 ,'        ' AS FIELD28 --FLAT SALES TAX AMT SUBMITTED
				 ,FF.PRESCRIBER_ID_DEA AS FIELD29 --PRESCRIBER ID / DEA#
				 ,'      ' AS FIELD30 --FILLER
				 ,'  ' AS FIELD31 --FILLER
				 ,TO_CHAR((CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN (FF.DISPENSING_FEE_AMOUNT * 100)
								ELSE (NVL(FF.TB_DISPENSING_FEE_AMOUNT, FF.TC_DISPENSING_FEE_AMOUNT) * 100)
						   END)) AS FIELD32 --DISPENSING FEE SUBMITTED
				 ,TO_CHAR((CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN (FF.FINAL_PRICE * 100)
								ELSE (NVL(FF.TB_FINAL_PRICE, FF.TC_FINAL_PRICE) * 100)
						   END)) AS FIELD33 --GROSS AMT DUE
				 ,TO_CHAR(FF.PRESCRIBED_DATE::DATE,'YYYYMMDD') AS FIELD34 --DATE PRESCRIPTION WAS WRITTEN
				 ,TO_CHAR(FF.REFILLS_AUTHORIZED) AS FIELD35 --NUMBER OF REFILLS AUTHORIZED
				 ,TO_CHAR(TPPA.AUTH_TYPE_NUM) AS FIELD36 --PRIOR AUTHORIZATION TYPE CODE
				 ,TPPA.AUTHORIZATION_NUMBER AS FIELD37 --PRIOR AUTH NUMBER SUBMITTED
				 ,'  ' AS FIELD38 --LEVEL OF SERVICE
				 ,FF.RX_ORIGIN_CODE AS FIELD39 --PRESCRIPTION ORIGIN CODE
				 ,TO_CHAR(FF.SUBMISSION_CLARIF_NUM) AS FIELD40 --SUBMISSION CLARIFICATION CODE
				 ,CASE WHEN FAC.FD_FACILITY_ID = '198' THEN '5804819'
				  ELSE FAC.FD_NCPDP_PROVIDER_ID END AS FIELD41 --PRIMARY CARE PROVIDER ID
				 ,'07' AS FIELD42 --PRIMARY CARE PROVIDER ID QUALIFIER
				 ,TO_CHAR((CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN FF.BASIS_OF_COST
								ELSE NVL(FF.TB_BASIS_OF_COST, FF.TC_BASIS_OF_COST)
						   END)) AS FIELD43 --BASIS OF COST DETERMINATION
				 ,MED_COND.MCD_FRMTTD_COND_REF_NUM AS FIELD44 --DIAGNOSIS CODE
				 ,(CASE WHEN MED_COND.MCD_FRMTTD_COND_REF_NUM IS NOT NULL THEN '01'
						ELSE '  '
				   END) AS FIELD45 --DIAGNOSIS CODE QUALIFIER
				 ,(CASE WHEN ((PROD.PRD_PRODUCT_SCHEDULE = 'OTC') OR (PROD.PRD_PRODUCT_SCHEDULE IS NULL AND DRUG.DRUG_DRUG_CLASS = 'O')) THEN '4'
						 WHEN PROD.PRD_IS_GENERIC = 1 THEN '3'
						 ELSE '1' 
					END) AS FIELD46 --DRUG TYPE
				 ,TO_CHAR((FF.TOTAL_UANDC * 100)) AS FIELD47 --USUAL AND CUSTOMARY CHARGE
				 ,PRES.PRS_LAST_NAME AS FIELD48 --PRESCRIBER LAST NAME
				 ,DRUG.DRUG_IS_UNIT_DOSE AS FIELD49 --UNIT DOSE INDICATOR
				 ,'0' AS FIELD50 --OTHER PAYER AMOUNT PAID
				 ,TO_CHAR((CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN (FF.PATIENT_PAY_AMOUNT * 100)
								ELSE (NVL(FF.TB_PATIENT_PAY_AMOUNT, FF.TC_PATIENT_PAY_AMOUNT) * 100)
						   END)) AS FIELD51 --PATIENT PAID AMOUNT PAID
				 ,TO_CHAR(TPWCC.TWED_DATE_OF_INJURY::DATE,'YYYYMMDD') AS FIELD52 --DATE OF INJURY
				 ,TPWCC.TWED_CLAIM_REFERENCE_ID AS FIELD53 --CLAIM/REFERENCE ID
				 ,TO_CHAR( (NVL(FF.INCENTIVE_FEE_AMOUNT,0) * 100) ) AS FIELD54 --INCENTIVE AMT SUBMITTED
				 ,' ' AS FIELD55 --REASON FOR SERVICE CODE
				 ,' ' AS FIELD56 --PROFESSIONAL SERVICE CODE
				 ,FF.DUR_RESULT_SERVICE_CD AS FIELD57 --RESULT OF SERVICE CODE
				 ,' ' AS FIELD58 --OTHER PAYER DATE
				 ,FAC.FD_DEA_NUMBER AS FIELD59 --PROVIDER ID
				 ,(CASE WHEN FAC.FD_DEA_NUMBER IS NULL THEN '  '
						ELSE '01'
				   END) AS FIELD60 --PROVIDER ID QUALIFIER
				 ,WRITTEN_DRUG.DRUG_NDC AS FIELD61 --ORIGINALLY PRESCRIBED PRODUCT
				 ,'03' AS FIELD62 --ORIGINALLY PRESCRIBED PRODUCT ID QUALIFIER
				 ,TO_CHAR((FF.ORIGINAL_PRODUCT_QTY * 1000)) AS FIELD63 --ORIGINALLY PRESCRIBED QUANTITY
				 ,DRUG.DRUG_PACKAGE_UNITS AS FIELD64 --UNIT OF MEASURE 
				 ,TO_CHAR(((CASE WHEN     NVL(FF.PATIENT_PAY_AMOUNT,0) < 1
									  AND FAC.FD_FACILITY_ID IN ('198','199') 
									  AND DRUG.DRUG_NDC IN (
											   '50458057760' --XARELTO 2.5 MG TABLET
											  ,'50458058030' --XARELTO 10 MG TABLET      
											  ,'50458057830' --XARELTO 15 MG TABLET      
											  ,'50458057930' --XARELTO 20 MG TABLET      
										  )
									  THEN 1
								 ELSE NVL(FF.PATIENT_PAY_AMOUNT,0)
							END) * 100)) AS FIELD65 --PATIENT PAY AMOUNT
				 ,TO_CHAR((FF.TOTAL_COST * 100)) AS FIELD66 --INGERDIENT COST PAID
				 ,TO_CHAR((FF.TOTAL_FEE * 100)) AS FIELD67 --DISPENSING FEE PAID
				 ,TO_CHAR((FF.TP_TAX_FLAT_AMOUNT * 100)) AS FIELD68 --FLAT SALES TAX AMOUNT PAID
				 ,TO_CHAR(((CASE WHEN     NVL(FF.TP_PLAN_AMOUNT_PAID,0) < 1
									  AND FAC.FD_FACILITY_ID IN ('198','199')
									  AND DRUG.DRUG_NDC IN (
											   '50458057760' --XARELTO 2.5 MG TABLET
											  ,'50458058030' --XARELTO 10 MG TABLET      
											  ,'50458057830' --XARELTO 15 MG TABLET      
											  ,'50458057930' --XARELTO 20 MG TABLET      
										  )
									  THEN 1
								 ELSE (CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN NVL(FF.PATIENT_PAY_AMOUNT,0)
											ELSE NVL(FF.TP_PLAN_AMOUNT_PAID,0)
									   END)
							END) * 100)) AS FIELD69 --TOTAL AMOUNT PAID
				 ,'   ' AS FIELD70 --REJECT DATA REJECT REASON 1
				 ,'   ' AS FIELD71 --REJECT DATA REJECT REASON 2
				 ,'   ' AS FIELD72 --REJECT DATA REJECT REASON 3
				 ,'        ' AS FIELD73 --ACCUMULATED DEDUCTION AMOUNT
				 ,'        ' AS FIELD74 --REMAINING DEDUCTION AMOUNT
				 ,'        ' AS FIELD75 --REMAINING BENEFIT AMOUNT
				 ,DRUG.DRUG_GNN AS FIELD76 --PRODUCT GENERIC NAME
				 ,'        ' AS FIELD77 --AMOUNT APPLIED TO PERIODIC DEDUCTABLE
				 ,TO_CHAR((FF.TOTAL_COPAY * 100)) AS FIELD78 --AMOUNT OF COPAY/COINSURANCE
				 ,'        ' AS FIELD79 --AMOUNT ATTRIBUTED TO PRODUCT SELECTION
				 ,'        ' AS FIELD80 --AMOUNT EXCEEDING PERIODIC BENEFIT
				 ,TO_CHAR((NVL(FF.INCENTIVE_FEE_AMOUNT,0) * 100)) AS FIELD81 --INCENTIVE AMOUNT PAID
				 ,TO_CHAR(FF.BASIS_OF_COST) AS FIELD82 --BASIS FOR REIM DETERMINATION
				 ,'        '  AS FIELD83 --AMOUNT ATTRIBUTED TO SALES TAX
				 ,SUBSTR(TP.TPLD_PLAN_CODE, 4, 10) AS FIELD84 --PLAN ID
				 ,CASE WHEN FAC.FD_FACILITY_ID = '198' THEN '5804819'
				  ELSE FAC.FD_NCPDP_PROVIDER_ID END AS FIELD85 --NCPDP PROVIDER NUMBER
				 ,TP.TPLD_PLAN_NAME AS FIELD86 --PLAN SHORT NAME
				 ,TPPR.NAME AS FIELD87 --PROCESSOR NAME
				 ,FAC.FD_ZIPCODE AS FIELD88 --PHARMACY ZIP CODE
				 ,PAT_ADD.LAST_NAME AS FIELD89 --PATIENT LAST NAME
				 ,(CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN 'C'
						WHEN FF.EXTERNAL_BILLING_INDICATOR IS NULL THEN 'T'
						ELSE 'P'
				   END) AS FIELD90 --CLAIM TYPE
				 ,PAT_ADD.FIRST_NAME AS FIELD91 --PATIENT FIRST NAME
				 ,FF.RX_NUMBER AS FIELD92 --PRESCRIPTION/SERVICE REFERENCE NO
				 ,(CASE WHEN NVL(FF.TP_PLAN_NUM,0) = 0 THEN '1'
						WHEN TP.TPLD_IS_MEDICAID_PLAN = 'Y' THEN '2'
						ELSE '3'
				   END) AS FIELD93 --IMS PAYMENT TYPE
				 ,PRES.PRS_FIRST_NAME AS FIELD94 --PRESCRIBER FIRST NAME
				 ,PRES.PRS_MIDDLE_NAME AS FIELD95 --PRESCRIBER MIDDLE INITIAL
				 ,PRES_ADD.PADR_CITY AS FIELD96 --PRESCRIBER CITY
				 ,FF.PRESCRIBER_STATE AS FIELD97 --PRESCRIBER STATE
				 ,FF.PRESCRIBER_ZIP AS FIELD98 --PRESCRIBER ZIP CODE
				 ,(CASE WHEN FF.SPLIT_BILLING_CODE = '3' THEN ' 2'
						WHEN FF.SPLIT_BILLING_CODE = '2' THEN ' 1'
						WHEN FF.SPLIT_BILLING_CODE = '1' THEN ' 0'
						WHEN FF.SPLIT_BILLING_CODE = '0' THEN ' 0'
						ELSE '  '
				   END) AS FIELD99 --COORDINATION OF BENEFITS COUNTER          
				 ,'           ' AS FIELD100 --DE-IDENTIFIED PATIENT CODE         
				 ,FF.CARDHOLDER_ID AS FIELD101 --PATIENT CARDHOLDER ID
				 ,PAT_ADD.ADDRESS1 AS FIELD102 --PATIENT STREET ADDRESS
				 ,PAT_ADD.ZIP AS FIELD103 --PATIENT ZIP - ENCRYPTED
				 ,SUBSTR(TP.TPLD_PLAN_CODE, 4, 9) AS FIELD104 --IMS PLAN CODE
				 ,TO_CHAR(FF.FILL_STATE_CHG_TS::DATE,'YYYYMMDD') AS FIELD105 --DATE DELIVERED/FULFILLED
				 ,FF.SHORT_FILL_STATUS AS FIELD106 --PARTIAL FILL STATUS
				 ,FF.PRESCRIBER_ID_NPI AS FIELD107 --PRESCRIBER NPI NUMBER
				 ,(CASE WHEN I.TARGET_CF_FACILITY_NUM IS NULL THEN 'N' ELSE 'Y' END) AS FIELD108 --CENTRAL FILL FLAG (IF APPLICABLE)
				 ,FF.FILL_STATE_CHG_TS AS FF_FILL_STATE_CHG_TS
				FROM FILL_FACT FF
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY FAC
						 ON FAC.FD_FACILITY_NUM = FF.FACILITY_NUM
						AND FAC.FD_IS_ACTIVE = 'Y'
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FAC_ID
						 ON FAC_ID.FD_FACILITY_KEY = FF.FACILITY_NUM
						AND FAC_ID.FD_TYPE = 'F08'
					 INNER JOIN PATIENT_ADDRESS PAT_ADD
						 ON PAT_ADD.PATIENT_NUM = FF.PATIENT_NUM
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES
						 ON PRES.PRS_PRESCRIBER_NUM = FF.PRESCRIBER_NUM
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ADDRESS PRES_ADD
						 ON PRES_ADD.PADR_PRESCRIBER_ADDRESS_NUM = FF.PRESCRIBER_ADDRESS_NUM
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PROD
						 ON PROD.PRD_PRODUCT_NUM = FF.DISPENSED_PROD_NUM
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG DRUG
						 ON DRUG.DRUG_NUM = FF.DISPENSED_DRUG_NUM
					 INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG WRITTEN_DRUG
						 ON WRITTEN_DRUG.DRUG_NUM = FF.WRITTEN_DRUG_NUM
					 LEFT OUTER JOIN {AUD}.ERXAUD_PLS_ARCHIVE_VIEW.ITEM I
						 ON I.RX_RECORD_NUM = FF.RX_RECORD_NUM
						AND I.RX_FILL_SEQ = FF.RX_FILL_SEQ
						AND I.EFF_END_DATE = TO_DATE('12/31/2999', 'MM/DD/YYYY')
						AND I.H_TYPE <> 'D'
					 LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TP
						 ON TP.TPLD_PLAN_NUM = FF.TP_PLAN_NUM
					 LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPP
						 ON TPP.TPD_TP_PATIENT_NUM = FF.TP_PATIENT_NUM
						AND TPP.TPD_EFF_END_DATE = TO_DATE('2999-12-31', 'YYYY-MM-DD')
					 LEFT OUTER JOIN TP_PROCESSOR_DESTINATION TPPD
						 ON TPPD.TP_PROCESSOR_DESTINATION_SEQ = FF.TP_PROCESSOR_DEST_NUM
						AND TPPD.EFF_END_DATE = TO_DATE('2999-12-31', 'YYYY-MM-DD')
					 LEFT OUTER JOIN TP_PROCESSOR TPPR
						 ON TPPR.TP_PROCESSOR_NUM = FF.TP_PROCESSOR_NUM
						AND TPPR.EFF_END_DATE = TO_DATE('2999-12-31', 'YYYY-MM-DD')
					 LEFT OUTER JOIN TP_PRIOR_AUTH TPPA
						 ON TPPA.TP_PRIOR_AUTH_NUM = FF.TP_PRIOR_AUTH_NUM
						AND TPPA.EFF_END_DATE = TO_DATE('2999-12-31', 'YYYY-MM-DD')
					 LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_WORKERS_COMP TPWCC
						 ON TPWCC.TWED_KEY = FF.TP_WORK_COMP_NUM
					 LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.MEDICAL_CONDITION MED_COND
						 ON MED_COND.MCD_KEY = FF.MEDICAL_CONDITION_NUM
			   WHERE FF.IS_SAME_DAY_REVERSAL = 'N'
				 AND FF.FILL_STATE_CODE IN (14, 16)
				 AND NVL(FF.IS_BAR,'N')= 'N'
			 )
      )
 WHERE FF_FILL_STATE_CHG_TS BETWEEN (:RUNDATE - 1)
   AND ((:RUNDATE - 1) + INTERVAL '23 HOURS, 59 MINUTES, 59 SECONDS')
 ORDER BY FIELD85, FIELD92