SELECT
     FID.FD_VALUE AS NPI
    ,F.FD_FACILITY_NAME AS PHARMACYNAME
    ,F.FD_ADDRESS1 AS ADDRESSLINE1
    ,F.FD_ADDRESS2 AS ADDRESSLINE2
    ,F.FD_CITY AS CITY
    ,F.FD_STATE_CODE AS STATE
    ,F.FD_ZIPCODE AS ZIPCODE
    ,F.FD_PHONE1 AS STOREPHONE
    ,F.FD_FAX_NUMBER AS FAXPHONE
    ,NULL AS PAIDSEARCHRADIUS
    ,NULL AS BANNER
FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F
     INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FID
        ON FID.FD_FACILITY_KEY = F.FD_FACILITY_KEY
       AND FID.FD_TYPE = 'F08'
ORDER BY F.FD_FACILITY_NAME