SELECT
     1 AS VERSION
    ,PD_PATIENT_NUM AS CLIENTPATIENTID
    ,NULL AS LASTNAME
    ,NULL AS FIRSTNAME
    ,NVL(GENDER,'O') AS GENDER
    ,NULL AS ADDRESSLINE1
    ,NULL AS ADDRESSLINE2
    ,NULL AS CITY
    ,NULL AS STATE
    ,PAD_ZIP AS ZIPCODE
    ,TO_CHAR(PD_BIRTH_DATE::DATE,'YYYY-MM-DD') AS DOB
    ,NULL AS EMAIL
    ,NULL AS PHONE
    ,NULL AS PHONETYPE
    ,NULL AS LANGUAGE
    ,DRUG_NDC AS NDC
    ,NVL(INTENDED_QTY_DISPENSED,0) AS QTY
    ,NVL(INTENDED_DAYS_SUPPLY,0) AS DAYSSUPPLY
    ,DRUG_LABEL_NAME AS PRODUCTNAME
    ,SOLD_DATE_KEY AS FILLDATE
    ,REFILL_NUM AS FILLNUM
    ,NVL(TOTAL_REFILLS_ALLOWED,0) AS AUTHORIZEDREFILLS
    ,FD_VALUE AS NPI
    ,NULL AS MEDICARECONTRACTID
    ,NULL AS MEDICAREPLANID
    ,NULL AS BIN
    ,NULL AS PCN
    ,NULL AS GROUPID
    ,NULL AS PLAN
    ,PID_ID_TEXT AS PRESCRIBERNPI
    ,NULL AS MEDICARED
    ,NULL AS MEDICAREID
FROM ( 
	  SELECT
		   P.PD_PATIENT_NUM
		  ,PD.GENDER
		  ,PA.PAD_ZIP
          ,P.PD_BIRTH_DATE
		  ,D.DRUG_NDC
		  ,FF.INTENDED_QTY_DISPENSED
		  ,FF.INTENDED_DAYS_SUPPLY
		  ,D.DRUG_LABEL_NAME
		  ,FF.READY_DATE_KEY
		  ,FF.SOLD_DATE_KEY
          ,FF.REFILL_NUM
          ,FF.TOTAL_REFILLS_ALLOWED
          ,FID.FD_VALUE
          ,PRES_NPI.PID_ID_TEXT
		  ,RANK() OVER (PARTITION BY P.PD_PATIENT_NUM, D.DRUG_LABEL_NAME, D.DRUG_STRENGTH
				  ORDER BY FF.DISPENSED_DATE_KEY DESC
						  ,FF.DISPENSED_TIME_KEY --PARTIAL FILLS WILL HAVE SAME DISPENSED_DATE_KEY, BUT 
						  ,FF.DISPENSED_DATE_KEY              --EARLIEST DISPENSED_TIME_KEY WILL HAVE ACCURATE INTENDED_QTY_DISPENSED AND INTENDED_DAYS_SUPPLY
		   ) AS LATESTNDCRANK
		  ,RANK() OVER (PARTITION BY P.PD_PATIENT_NUM 
				  ORDER BY (CASE WHEN (PA.PAD_USAGE = 8 OR PA.PAD_ADDRESS_USAGE = 8) THEN 1 ELSE (PA.PAD_USAGE + 10) END)
						   ,PA.DW_CREATED_DT DESC
		   ) AS ADDRESSRANK
          ,RANK() OVER (PARTITION BY FF.FILL_FACT_KEY, PRES_NPI.PRS_PRESCRIBER_KEY
                        ORDER BY
                             PRES_NPI.DW_LAST_UPDATE_DT DESC
           ) AS PRESCRIBERNPIRANK
	  FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT P
		   INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_ADDRESS PA
			 ON PA.PD_PATIENT_KEY = P.PD_PATIENT_KEY
			AND PA.PAD_EFF_END_DATE = TO_DATE('29991231','YYYYMMDD')
		   INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF 
			 ON FF.PD_PATIENT_KEY = P.PD_PATIENT_KEY
		   INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F
			 ON F.FD_FACILITY_KEY = FF.FD_FACILITY_KEY
           INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY_ID FID
             ON FID.FD_FACILITY_KEY = F.FD_FACILITY_NUM
            AND FID.FD_TYPE = 'F08'
		   INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D
			 ON D.DRUG_KEY = FF.DISPENSED_DRUG_KEY
           LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT_DEMOGRAPHIC PD
             ON PD.PATIENT_DEMOGRAPHIC_KEY = FF.PATIENT_DEMOGRAPHIC_KEY
           LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES
             ON PRES.PRS_PRESCRIBER_NUM = P.PD_PRESCRIBER_NUM
           LEFT OUTER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_IDS PRES_NPI
             ON PRES_NPI.PRS_PRESCRIBER_KEY = PRES.PRS_PRESCRIBER_KEY
            AND PRES_NPI.PIT_KEY = 509 --SEE {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER_ID_TYPE.PIT_ID_DESCRIPTION = 'NATIONAL PROVIDER IDENTIFIER (NPI)'
            AND PRES_NPI.PID_STATUS = 'A'
	  WHERE P.PD_STATUS = 'A'
        AND P.PD_SPECIES_NAME IS NULL
        AND P.PD_BIRTH_DATE <= TO_DATE(TO_CHAR((TO_NUMBER(TO_CHAR(:RUNDATE::DATE,'YYYY')) - 64)) || TO_CHAR(:RUNDATE,'MMDD'),'YYYYMMDD')
        AND FF.SOLD_DATE_KEY = TO_NUMBER(TO_CHAR((:RUNDATE - 1),'YYYYMMDD'))
   )
WHERE LATESTNDCRANK = 1
  AND ADDRESSRANK = 1
  AND PRESCRIBERNPIRANK = 1