SELECT FACILITY_ID_NUM, RX_NUM, DATE_FILLED, PATIENT_LAST_NAME, PATIENT_FIRST_NAME, CARDHOLDER_ID, PATIENT_DOB, DRUG_NDC_NUM, DRUG_NAME, QTY_DRUG_DISPENSED, TX_PRICE, PATIENT_PAY, ADJ_AMT, THIRD_PARTY_NAME, THIRD_PARTY_CODE, SPLIT_BILL_INDICATOR, PRESCRIBER_NAME, DATE_SOLD, CLAIM_NUM 
FROM (
      SELECT      F.FD_FACILITY_ID AS FACILITY_ID_NUM,
                  FF.RX_NUMBER AS RX_NUM,
                  TO_CHAR(DD.CAL_DATE::DATE, 'MM/DD/YYYY') AS DATE_FILLED,
                  PAT.PD_LAST_NAME AS PATIENT_LAST_NAME,
                  PAT.PD_FIRST_NAME AS PATIENT_FIRST_NAME,
                  TPAT.TPD_CARDHOLDER_ID AS CARDHOLDER_ID,
                  TO_CHAR(PAT.PD_BIRTH_DATE::DATE, 'MM/DD/YYYY') AS PATIENT_DOB,
                  D.DRUG_NDC_MFG || '-' || D.DRUG_NDC_PRODUCT || '-' || D.DRUG_NDC_SIZE AS DRUG_NDC_NUM,
                  PRD.PRD_NAME AS DRUG_NAME,
                  CEIL(FF.QTY_DISPENSED) AS QTY_DRUG_DISPENSED,
                  (NVL(FPF.NON_COVERED_AMT, 0.00) + NVL(FPF.ACTUAL_PAID_AMT, 0)) AS TX_PRICE,
                   NVL(FPF.NON_COVERED_AMT, 0.00) AS PATIENT_PAY,
                   NVL(FPF.ACTUAL_PAID_AMT, 0.00) AS ADJ_AMT,
                   TPP.TPLD_PLAN_NAME AS THIRD_PARTY_NAME,
                   TPP.TPLD_PLAN_CODE AS THIRD_PARTY_CODE,
                   DECODE(FF.IS_COB,'Y','1','0') AS SPLIT_BILL_INDICATOR,
                   DECODE(PRES.PRS_MIDDLE_NAME, NULL,
                          PRES.PRS_LAST_NAME || ', ' || PRES.PRS_FIRST_NAME,
                          PRES.PRS_LAST_NAME || ', ' || PRES.PRS_FIRST_NAME || ' ' || PRES.PRS_MIDDLE_NAME) AS PRESCRIBER_NAME
                   ,DD2.CAL_DATE AS DATE_SOLD       
                   ,TWC.TWED_TP_WRKRS_CMP_CLM_NUM AS CLAIM_NUM
                   ,DD2.CAL_YEAR_MONTH_NAME
                   ,FF.CANCEL_DATE_KEY
     FROM {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_FACT FF
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FILL_PRICING_FACT FPF ON (FF.PRIMARY_TPLD_PLAN_KEY = FPF.TPLD_PLAN_KEY AND FF.ADJUDICATION_GROUP_NUM = FPF.ADJUDICATION_GROUP_NUM)
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PLAN TPP ON FPF.TPLD_PLAN_KEY = TPP.TPLD_PLAN_KEY AND TPP.TPLD_PLAN_CODE IN ('OTHWFMWC', 'WEGCOMP', 'WEGCOMP1')
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.FACILITY F ON FF.FD_FACILITY_KEY = F.FD_FACILITY_KEY
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DD ON FPF.DATE_OF_SERVICE_DATE_KEY = DD.DATE_KEY
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PATIENT PAT ON FF.PD_PATIENT_KEY = PAT.PD_PATIENT_KEY
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_PATIENT TPAT ON FPF.TPD_KEY = TPAT.TPD_KEY AND TPAT.TPD_TP_PLAN_NUM = TPP.TPLD_PLAN_NUM
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DRUG D ON FF.DISPENSED_DRUG_KEY = D.DRUG_KEY
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRESCRIBER PRES ON FF.PRS_PRESCRIBER_KEY = PRES.PRS_PRESCRIBER_KEY
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.PRODUCT PRD ON FF.DISPENSED_PRD_PRODUCT_KEY = PRD.PRD_PRODUCT_KEY              
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.TP_WORKERS_COMP TWC ON TWC.TWED_KEY = FPF.TWED_KEY 
          INNER JOIN {DW}.ERXDW_PLS_ARCHIVE_VIEW.DATE_DIM DD2 ON FPF.SOLD_DATE_KEY = DD2.DATE_KEY
     )
WHERE CAL_YEAR_MONTH_NAME = TO_CHAR((TO_DATE(TO_CHAR(:RUNDATE::DATE,'YYYYMM') || '01','YYYYMMDD') - 1),'YYYY-MM')
  AND CANCEL_DATE_KEY = 0 -- EXCLUDE REVERSALS