SELECT D.DRUG_NDC_MFG || '-' || D.DRUG_NDC_PRODUCT || '-' || D.DRUG_NDC_SIZE "NDC"
, D.DRUG_BRAND_NAME "DRUG_NAME"
, D.DRUG_LABELER "MANUFACTURER"
, D.DRUG_NDC_MFG "MFR_NUM"
, D.DRUG_STRENGTH "STRENGTH"
, D.DRUG_STRENGTH_UNITS "STRENGTH_UNITS"
, D.DRUG_IS_UNIT_DOSE "UNIT_DOSE_FLAG"
, D.DRUG_IS_UNIT_OF_USE "UNIT_OF_USE_FLAG"
, D.DRUG_PACKAGE_QUANTITY "PACKAGE_QTY"
, D.DRUG_PACKAGE_SIZE "PACK_SIZE"
, D.DRUG_INNER_PACKAGE "INNER_PACK"
, D.DRUG_OUTER_PACKAGE "OUTER_PACK"
, D.DRUG_CASE_SIZE "CASE_SIZE"
, D.DRUG_PACKAGE_UNITS "UNIT"
, P.PRD_DISPENSING_UNITS "DISPENSING_UNITS"
, D.DRUG_SHIPPER
, D.DRUG_PACKAGE_DESC "PACK_DESC"
, D.DRUG_NUM "ORDER_NUM"
, D.DRUG_PREVIOUS_NDC "PREV_NDC"
, D.DRUG_REPLACEMENT_NDC "REPLACEMENT_NDC"
, P.PRD_SOURCE_INDICATOR "PROD_SOURCE_IND"
, D.DRUG_IS_PROVIDER_DRUG "FDB_ADDED"
, TO_CHAR(D.DRUG_DATE_OF_ADD,'MM/DD/YYYY') "DATE_ADDED"
, TO_CHAR(D.DRUG_OBSOLETE_DATE,'MM/DD/YYYY') "OBSOLETE_DATE"
, TO_CHAR(P.PRD_DEACTIVATE_DATE,'MM/DD/YYYY HH:MI:SS AM') "DEACTIVATE_DATE"
, TO_CHAR(D.DRUG_LAST_PROVIDER_UPDATE,'MM/DD/YYYY') "LAST_PROVIDER_UPDATE"
, D.DRUG_IS_MAINT_DRUG "MAINTENANCE_DRUG_FLAG"
, D.DRUG_GNN "GENERIC_NAME"
, D.DRUG_GCN "GCN"
, D.DRUG_GCN_SEQ "GCN_SEQ_NUM"
, D.DRUG_UPC
, P.PRD_IS_GENERIC "SDGI"
, P.IS_GENERIC_OVERRIDE "SDGI_OVERRIDE"
, P.PRD_PRODUCT_SCHEDULE "DRUG_SCHEDULE"
, D.DRUG_DEA_CLASS "DEA_CLASS"
, P.PRD_IS_PRICE_MAINTAINED "PRICE_MAINTAINED"
, (SELECT SUBSTR(PG.GROUP_NAME, 1, 1)
FROM TREXONE_DW_DATA.PRODUCT_GROUP PG
WHERE PG.PRODUCT_NUM = P.PRD_PRODUCT_NUM
AND PG.MEMBER_STATUS = 'Active'
AND PG.GROUP_NUM IN (1000012,1000013,1000014,1000015,1000016,1000017,1000018,1000019,1000020,1000021, --Include Deciles 0-9
1000000,1000001,1000002,1000003,1000004,1000005,1000006,1000007,1000008,1000009) --and Deciles A-J ONLY
AND ROWNUM < 2) "DECILE"
, D.DRUG_AHFS "AHFS_THERAP_CLASS"
, D.DRUG_AHFS_DESCRIPTION "AHFS_THER_CLASS_DES_SHORT"
, D.DRUG_GC3 "AHFS_THER_CLASS_DES_LONG"
, D.DRUG_VERB "SIG_VERB"
, P.PRD_VERB_OVERRIDE "SIG_VERB_OVERRIDE"
, D.DRUG_ROUTE "SIG_ROUTE"
, SUBSTR(P.PRD_ROUTE_OVERRIDE, 1, 10) "SIG_ROUTE_OVERRIDE"
, D.DRUG_UNIT_LOW "SIG_UNIT"
, P.PRD_UNIT_OVERRIDE "SIG_UNIT_OVERRIDE"
, D.DRUG_DOSAGE_FORM "DOSAGE_FORM"
, D.DRUG_HCFA_DESI "DESI_INDICATOR"
, D.DRUG_ORANGE_BOOK_CODE "ORANGE_BOOK_CODE"
, P.PRD_HCFA_FDA_THERA_EQU_CODE "ORANGE_BOOK_CODE_OVERRIDE"
, P.PRD_DEFAULT_DAW_CODE "DEFAULT_DAW"
, P.PRD_IS_WAREHOUSED "WAREHOUSE_FLAG"
, D.DRUG_INNOVATOR "ORIGINATOR_INNOVATOR"
, P.PRD_IS_ERP_CANDIDATE "ENHANCED_REFILL_OPTIONAL"
, P.PRD_IS_GEN_PCK_SZ_RESTRICTED "GEN_SUB_PACK_RESTRICTION"
, P.PRD_MINIMUM_DISPENSE_QTY "MIN_DISP_QTY"
, PCFB.COST "BBAWP"
, P.PRD_DISTRIBUTOR "DISTRIBUTOR"
, P.PRD_HCPC_BBA_PRICE "BBAWP_OVERRIDE"
, P.PRD_IS_COMPOUND "COMPOUND_FLAG"
, P.PRD_ALTERNATE_LABEL_NAME "ALTERNATE_LABEL"
, P.PRD_IS_BLOCKED "BLOCKED_PRODUCT_FLAG"
-- Use decodes to pull the appropriate cost fields using the following order of precedence:
-- REPACKCON, CON, NET, USERDEF
, (D.DRUG_PACKAGE_SIZE * DECODE(NVL(PCFR.COST, 0), 0, DECODE(NVL(PCFC.COST, 0), 0, DECODE(NVL(PCFN.COST, 0), 0, NVL(PCFU.COST, 0), PCFN.COST), PCFC.COST), PCFR.COST)) "COST"
, DECODE(NVL(PCFR.COST, 0), 0, DECODE(NVL(PCFC.COST, 0), 0, DECODE(NVL(PCFN.COST, 0), 0, NVL(USERDEF.IS_MANUALLY_MAINTAINED, ''), NET.IS_MANUALLY_MAINTAINED), CON.IS_MANUALLY_MAINTAINED), REPACKCON.IS_MANUALLY_MAINTAINED) "COST_MANUALLY_MAINTAINED"
, DECODE(NVL(PCFR.COST, 0), 0, DECODE(NVL(PCFC.COST, 0), 0, DECODE(NVL(PCFN.COST, 0), 0, NVL(USERDEF.PERCENT_MODIFIER, 0), NET.PERCENT_MODIFIER), CON.PERCENT_MODIFIER), REPACKCON.PERCENT_MODIFIER) "PERCENT_MODIFIER"
, TO_CHAR((DECODE(NVL(PCFR.COST, 0), 0, DECODE(NVL(PCFC.COST, 0), 0, DECODE(NVL(PCFN.COST, 0), 0, NVL(USERDEF.EFFECTIVE_DATE, ''), NET.EFFECTIVE_DATE), CON.EFFECTIVE_DATE), REPACKCON.EFFECTIVE_DATE)),'MM/DD/YYYY HH:MI:SS AM') "COST_BASIS_EFF_DATE"
, (SELECT SUBSTR(PG.GROUP_NAME, 1, 1)
FROM TREXONE_DW_DATA.PRODUCT_GROUP PG
WHERE PG.PRODUCT_NUM = P.PRD_PRODUCT_NUM
AND PG.MEMBER_STATUS = 'Active'
AND PG.GROUP_NUM IN (1000010, 1000011) -- S (Scan OTC)
AND ROWNUM < 2) "OTC_TYPE"
, DECODE(NVL(PCFR.COST, 0), 0, DECODE(NVL(PCFC.COST, 0), 0, DECODE(NVL(PCFN.COST, 0), 0, NVL(PCFU.COST, 0), PCFN.COST), PCFC.COST), PCFR.COST) "UNIT_COST"
FROM TREXONE_DW_DATA.PRODUCT P
INNER JOIN TREXONE_DW_DATA.DRUG D ON (D.DRUG_NUM = P.PRD_DRUG_NUM)
-- Retrieve the max product_cost_basis_key for each cost type for the product. These will be used to retrieve
-- the data fields from the product_cost_basis table and are necessary because there is sometimes more than
-- one active record for a given product and cost type
LEFT OUTER JOIN
(SELECT PCB.PRD_PRODUCT_KEY,
MAX(DECODE(CB.COST_BASIS_NUM, 1000000, PCB.PRODUCT_COST_BASIS_KEY, 0)) KEYREPACKCON, -- 1000000 = REPACKCON - MCKESSON REPACKAGED CON
MAX(DECODE(CB.COST_BASIS_NUM, 1007, PCB.PRODUCT_COST_BASIS_KEY, 0)) KEYCON, -- 1007 = CON - CON (contract price)
MAX(DECODE(CB.COST_BASIS_NUM, 1001, PCB.PRODUCT_COST_BASIS_KEY, 0)) KEYNET, -- 1001 = NET - NET (net item price)
MAX(DECODE(CB.COST_BASIS_NUM, 1000001, PCB.PRODUCT_COST_BASIS_KEY, 0)) KEYUSERDEF, -- 1000001 = USER_DEF. - WEGMANS USER DEFINED COST
MAX(DECODE(CB.COST_BASIS_NUM, 1009, PCB.PRODUCT_COST_BASIS_KEY, 0)) KEYBBAWP -- 1009 = AWP - AWP (average wholesale price)
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS PCB
INNER JOIN TREXONE_DW_DATA.COST_BASIS CB ON (CB.COST_BASIS_KEY = PCB.COST_BASIS_KEY
AND SYSDATE BETWEEN CB.EFF_START_DATE AND CB.EFF_END_DATE)
WHERE SYSDATE BETWEEN PCB.EFFECTIVE_DATE AND NVL(PCB.TERMINATION_DATE, '31-DEC-2999')
AND CB.COST_BASIS_NUM IN (1000000, 1007, 1001, 1000001, 1009)
GROUP BY PCB.PRD_PRODUCT_KEY) PCBMAXKEYS ON (PCBMAXKEYS.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY)
-- Retrieve cost-related fields for REPACKCON cost type
LEFT OUTER JOIN
(SELECT PERCENT_MODIFIER, IS_MANUALLY_MAINTAINED, COST_BASIS_SOURCE_KEY, PRODUCT_COST_BASIS_KEY, EFFECTIVE_DATE
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS) REPACKCON ON (REPACKCON.PRODUCT_COST_BASIS_KEY = PCBMAXKEYS.KEYREPACKCON)
-- Retrieve cost-related fields for CON cost type
LEFT OUTER JOIN
(SELECT PERCENT_MODIFIER, IS_MANUALLY_MAINTAINED, COST_BASIS_SOURCE_KEY, PRODUCT_COST_BASIS_KEY, EFFECTIVE_DATE
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS) CON ON (CON.PRODUCT_COST_BASIS_KEY = PCBMAXKEYS.KEYCON)
-- Retrieve cost-related fields for NET cost type
LEFT OUTER JOIN
(SELECT PERCENT_MODIFIER, IS_MANUALLY_MAINTAINED, COST_BASIS_SOURCE_KEY, PRODUCT_COST_BASIS_KEY, EFFECTIVE_DATE
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS) NET ON (NET.PRODUCT_COST_BASIS_KEY = PCBMAXKEYS.KEYNET)
-- Retrieve cost-related fields for USERDEF cost type
LEFT OUTER JOIN
(SELECT PERCENT_MODIFIER, IS_MANUALLY_MAINTAINED, COST_BASIS_SOURCE_KEY, PRODUCT_COST_BASIS_KEY, EFFECTIVE_DATE
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS) USERDEF ON (USERDEF.PRODUCT_COST_BASIS_KEY = PCBMAXKEYS.KEYUSERDEF)
-- Retrieve cost-related fields for BBAWP cost type
LEFT OUTER JOIN
(SELECT COST_BASIS_SOURCE_KEY, PRODUCT_COST_BASIS_KEY
FROM TREXONE_DW_DATA.PRODUCT_COST_BASIS) BBAWP ON (BBAWP.PRODUCT_COST_BASIS_KEY = PCBMAXKEYS.KEYBBAWP)
-- Retrieve the max cost_basis_source_value_num for each cost type for the product. These will be used to retrieve
-- the data fields from the product_cost_fact table and are necessary because there is sometimes more than
-- one active record for a given product and cost type
LEFT OUTER JOIN -- REPACKCON
(SELECT PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY, MAX(COST_BASIS_SOURCE_VALUE_NUM) COST_BASIS_SOURCE_VALUE_NUM
FROM TREXONE_DW_DATA.PRODUCT_COST_FACT
WHERE SYSDATE BETWEEN EFFECTIVE_DATE AND NVL(TERMINATION_DATE, '31-DEC-2999')
GROUP BY PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY) PCFKEYREPACKCON
ON (PCFKEYREPACKCON.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFKEYREPACKCON.COST_BASIS_SOURCE_KEY = REPACKCON.COST_BASIS_SOURCE_KEY)
LEFT OUTER JOIN -- CON
(SELECT PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY, MAX(COST_BASIS_SOURCE_VALUE_NUM) COST_BASIS_SOURCE_VALUE_NUM
FROM TREXONE_DW_DATA.PRODUCT_COST_FACT
WHERE SYSDATE BETWEEN EFFECTIVE_DATE AND NVL(TERMINATION_DATE, '31-DEC-2999')
GROUP BY PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY) PCFKEYCON
ON (PCFKEYCON.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFKEYCON.COST_BASIS_SOURCE_KEY = CON.COST_BASIS_SOURCE_KEY)
LEFT OUTER JOIN -- NET
(SELECT PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY, MAX(COST_BASIS_SOURCE_VALUE_NUM) COST_BASIS_SOURCE_VALUE_NUM
FROM TREXONE_DW_DATA.PRODUCT_COST_FACT
WHERE SYSDATE BETWEEN EFFECTIVE_DATE AND NVL(TERMINATION_DATE, '31-DEC-2999')
GROUP BY PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY) PCFKEYNET
ON (PCFKEYNET.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFKEYNET.COST_BASIS_SOURCE_KEY = NET.COST_BASIS_SOURCE_KEY)
LEFT OUTER JOIN -- USERDEF
(SELECT PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY, MAX(COST_BASIS_SOURCE_VALUE_NUM) COST_BASIS_SOURCE_VALUE_NUM
FROM TREXONE_DW_DATA.PRODUCT_COST_FACT
WHERE SYSDATE BETWEEN EFFECTIVE_DATE AND NVL(TERMINATION_DATE, '31-DEC-2999')
GROUP BY PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY) PCFKEYUSERDEF
ON (PCFKEYUSERDEF.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFKEYUSERDEF.COST_BASIS_SOURCE_KEY = USERDEF.COST_BASIS_SOURCE_KEY)
LEFT OUTER JOIN -- BBAWP
(SELECT PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY, MAX(COST_BASIS_SOURCE_VALUE_NUM) COST_BASIS_SOURCE_VALUE_NUM
FROM TREXONE_DW_DATA.PRODUCT_COST_FACT
WHERE SYSDATE BETWEEN EFFECTIVE_DATE AND NVL(TERMINATION_DATE, '31-DEC-2999')
GROUP BY PRD_PRODUCT_KEY, COST_BASIS_SOURCE_KEY) PCFKEYBBAWP
ON (PCFKEYBBAWP.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFKEYBBAWP.COST_BASIS_SOURCE_KEY = BBAWP.COST_BASIS_SOURCE_KEY)
-- Retrieve REPACKCON cost record
LEFT OUTER JOIN TREXONE_DW_DATA.PRODUCT_COST_FACT PCFR ON (PCFR.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFR.COST_BASIS_SOURCE_VALUE_NUM = PCFKEYREPACKCON.COST_BASIS_SOURCE_VALUE_NUM
AND SYSDATE BETWEEN PCFR.EFFECTIVE_DATE AND NVL(PCFR.TERMINATION_DATE, '31-DEC-2999'))
-- Retrieve CON cost record
LEFT OUTER JOIN TREXONE_DW_DATA.PRODUCT_COST_FACT PCFC ON (PCFC.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFC.COST_BASIS_SOURCE_VALUE_NUM = PCFKEYCON.COST_BASIS_SOURCE_VALUE_NUM
AND SYSDATE BETWEEN PCFC.EFFECTIVE_DATE AND NVL(PCFC.TERMINATION_DATE, '31-DEC-2999'))
-- Retrieve NET cost record
LEFT OUTER JOIN TREXONE_DW_DATA.PRODUCT_COST_FACT PCFN ON (PCFN.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFN.COST_BASIS_SOURCE_VALUE_NUM = PCFKEYNET.COST_BASIS_SOURCE_VALUE_NUM
AND SYSDATE BETWEEN PCFN.EFFECTIVE_DATE AND NVL(PCFN.TERMINATION_DATE, '31-DEC-2999'))
-- Retrieve USERDEF cost record
LEFT OUTER JOIN TREXONE_DW_DATA.PRODUCT_COST_FACT PCFU ON (PCFU.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFU.COST_BASIS_SOURCE_VALUE_NUM = PCFKEYUSERDEF.COST_BASIS_SOURCE_VALUE_NUM
AND SYSDATE BETWEEN PCFU.EFFECTIVE_DATE AND NVL(PCFU.TERMINATION_DATE, '31-DEC-2999'))
-- Retrieve BBAWP cost record
LEFT OUTER JOIN TREXONE_DW_DATA.PRODUCT_COST_FACT PCFB ON (PCFB.PRD_PRODUCT_KEY = P.PRD_PRODUCT_KEY
AND PCFB.COST_BASIS_SOURCE_VALUE_NUM = PCFKEYBBAWP.COST_BASIS_SOURCE_VALUE_NUM
AND SYSDATE BETWEEN PCFB.EFFECTIVE_DATE AND NVL(PCFB.TERMINATION_DATE, '31-DEC-2999'))
-- 07/27/2011 Adding the following exclusions per John Culhane, Dave Perlman, and Judy Stuff to prevent
-- issues with duplicates in the rx.drug table load:
-- Obsolete/Deactivated more than 2 years ago, blocked products, corporately added products that
-- have been deactivated, and NDC 99999-9999-99
WHERE NVL(D.DRUG_OBSOLETE_DATE, '31-DEC-2999') > (SYSDATE - 730)
AND NVL(P.PRD_DEACTIVATE_DATE, '31-DEC-2999') > (SYSDATE - 730)
AND NVL(P.PRD_IS_BLOCKED, 'N') <> 'Y'
AND NOT(P.PRD_DEACTIVATE_DATE IS NOT NULL AND P.PRD_SOURCE_INDICATOR = 'Corporate')
AND D.DRUG_NDC_MFG || D.DRUG_NDC_PRODUCT || D.DRUG_NDC_SIZE <> '99999999999'
-- Manufacturer exclusion list provided by John Culhane
-- AND ROWNUM <= 110000
-- AND D.DRUG_BRAND_NAME is not null
--AND (D.DRUG_NDC_MFG = '00000' AND D.DRUG_NDC_PRODUCT = '0000') --AND D.DRUG_NDC_SIZE = '00')
AND D.DRUG_NDC_MFG NOT IN (
00247,
00363,
00440,
00490,
00615,
11917,
12280,
16590,
16881,
19458,
21140,
21695,
23490,
24385,
33358,
34575,
35356,
37205,
40986,
49002,
49614,
49999,
50428,
51655,
52959,
53265,
54569,
54868,
55045,
55289,
55887,
57866,
58016,
58864,
63874,
65243,
66116,
66267,
66336,
67544,
68016,
68030,
68071,
68094,
68115,
68258,
68387,
91899
)
ORDER BY D.DRUG_BRAND_NAME