BEGIN
    DELETE FROM WEGMANS.SALE
	WHERE SALE_DATE BETWEEN (:RunDate - 1) AND (:RunDate - 1 + INTERVAL '23:59:59' HOUR TO SECOND);
	
    DELETE FROM WEGMANS.POSTRANSACTION
	WHERE SOLD_DATE BETWEEN (:RunDate - 1) AND (:RunDate - 1 + INTERVAL '23:59:59' HOUR TO SECOND);

	COMMIT;
END;