DECLARE
    TYPE tSTORE_NUMBER IS TABLE OF WEGMANS.SALE.STORE_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tTRANSACTION_NUMBER IS TABLE OF WEGMANS.SALE.TRANSACTION_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tOPERATOR_NUMBER IS TABLE OF WEGMANS.SALE.OPERATOR_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tTERMINAL_NUMBER IS TABLE OF WEGMANS.SALE.TERMINAL_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tSALE_DATE IS TABLE OF WEGMANS.SALE.SALE_DATE%type INDEX BY BINARY_INTEGER;
    TYPE tRX_NUMBER IS TABLE OF WEGMANS.SALE.RX_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tREFILL_NUMBER IS TABLE OF WEGMANS.SALE.REFILL_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tPARTIAL_FILL_SEQ_NUMBER IS TABLE OF WEGMANS.SALE.PARTIAL_FILL_SEQ_NUMBER%type INDEX BY BINARY_INTEGER;
    TYPE tTRANSACTION_TYPE IS TABLE OF WEGMANS.SALE.TRANSACTION_TYPE%type INDEX BY BINARY_INTEGER;
    TYPE tRX_PRICE IS TABLE OF WEGMANS.SALE.RX_PRICE%type INDEX BY BINARY_INTEGER;
    TYPE tINSURANCE_PAY IS TABLE OF WEGMANS.SALE.INSURANCE_PAY%type INDEX BY BINARY_INTEGER;
    TYPE tCUSTOMER_PAY IS TABLE OF WEGMANS.SALE.CUSTOMER_PAY%type INDEX BY BINARY_INTEGER;
    --TYPE tMAIL_FLAG IS TABLE OF WEGMANS.SALE.MAIL_FLAG%type INDEX BY BINARY_INTEGER;

    vSTORE_NUMBER    tSTORE_NUMBER;
    vTRANSACTION_NUMBER    tTRANSACTION_NUMBER;
    vOPERATOR_NUMBER    tOPERATOR_NUMBER;
    vTERMINAL_NUMBER    tTERMINAL_NUMBER;
    vSALE_DATE    tSALE_DATE;
    vRX_NUMBER    tRX_NUMBER;
    vREFILL_NUMBER    tREFILL_NUMBER;
    vPARTIAL_FILL_SEQ_NUMBER    tPARTIAL_FILL_SEQ_NUMBER;
    vTRANSACTION_TYPE    tTRANSACTION_TYPE;
    vRX_PRICE    tRX_PRICE;
    vINSURANCE_PAY    tINSURANCE_PAY;
    vCUSTOMER_PAY    tCUSTOMER_PAY;
    --vMAIL_FLAG    tMAIL_FLAG;
BEGIN
    vSTORE_NUMBER := :pSTORE_NUMBER;
    vTRANSACTION_NUMBER := :pTRANSACTION_NUMBER;
    vOPERATOR_NUMBER := :pOPERATOR_NUMBER;
    vTERMINAL_NUMBER := :pTERMINAL_NUMBER;
    vSALE_DATE := :pSALE_DATE;
    vRX_NUMBER := :pRX_NUMBER;
    vREFILL_NUMBER := :pREFILL_NUMBER;
    vPARTIAL_FILL_SEQ_NUMBER := :pPARTIAL_FILL_SEQ_NUMBER;
    vTRANSACTION_TYPE := :pTRANSACTION_TYPE;
    vRX_PRICE := :pRX_PRICE;
    vINSURANCE_PAY := :pINSURANCE_PAY;
    vCUSTOMER_PAY := :pCUSTOMER_PAY;
    --vMAIL_FLAG := :pMAIL_FLAG;

    FORALL i IN vSTORE_NUMBER.first..vSTORE_NUMBER.last 
        INSERT INTO WEGMANS.SALE (
		     STORE_NUMBER
            ,TRANSACTION_NUMBER
            ,OPERATOR_NUMBER
            ,TERMINAL_NUMBER
            ,SALE_DATE
            ,RX_NUMBER
            ,REFILL_NUMBER
            ,PARTIAL_FILL_SEQ_NUMBER
            ,TRANSACTION_TYPE
            ,RX_PRICE
            ,INSURANCE_PAY
            ,CUSTOMER_PAY
            --,MAIL_FLAG
        ) VALUES (
		     vSTORE_NUMBER(i)
            ,vTRANSACTION_NUMBER(i)
            ,vOPERATOR_NUMBER(i)
            ,vTERMINAL_NUMBER(i)
            ,vSALE_DATE(i)
            ,vRX_NUMBER(i)
            ,vREFILL_NUMBER(i)
            ,vPARTIAL_FILL_SEQ_NUMBER(i)
            ,vTRANSACTION_TYPE(i)
            ,vRX_PRICE(i)
            ,vINSURANCE_PAY(i)
            ,vCUSTOMER_PAY(i)
            --,vMAIL_FLAG(i)
        );
    COMMIT;
END;
