SET SERVEROUTPUT ON
DECLARE
    v_dev_pharm_members_csv    VARCHAR2(1000 CHAR);
    v_other_members_csv        VARCHAR2(1000 CHAR);
    v_grant_or_revoke          VARCHAR2(6 CHAR);
    v_plsql                    VARCHAR(2000 CHAR);
BEGIN
    v_dev_pharm_members_csv := 'EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI';
    v_other_members_csv := 'EXT_ESCIBILIA,EXT_MROSILIO';
    v_grant_or_revoke := 'GRANT'; --'GRANT' or 'REVOKE'

    ----GRANTS FOR DEVELOPERS:
    --TABLES (not including VIEWs because complex issues from inheritance):
    FOR t IN (
        SELECT Distinct owner, table_name
        FROM all_tab_columns
        WHERE owner = 'WEGMANS'
          --Comment out the next four lines to include VIEWs.
          AND (owner, table_name) NOT IN (
                  SELECT av.owner, av.view_name
                  FROM all_views av
              )
        ORDER BY owner, table_name
    )
    LOOP
        v_plsql := v_grant_or_revoke || ' SELECT,UPDATE,INSERT,DELETE ON WEGMANS.' || t.table_name || ' TO ' || v_dev_pharm_members_csv;
        DBMS_OUTPUT.PUT_LINE('plsql=' || v_plsql);
        EXECUTE IMMEDIATE v_plsql;
        DBMS_OUTPUT.PUT_LINE('...ran on [' || To_Char(sysdate,'YYYYMMDD HH24:MI:SS' || '].'));
    END LOOP;

    ----GRANTS FOR DEVELOPERS:
    --PACKAGES, PROCEDURES, FUNCTIONS
    FOR p IN (
        SELECT Distinct owner, object_name
        FROM all_procedures
        WHERE owner = 'WEGMANS'
        ORDER BY owner, object_name
    )
    LOOP
        v_plsql := v_grant_or_revoke || ' EXECUTE ON WEGMANS.' || p.object_name || ' TO ' || v_dev_pharm_members_csv;
        DBMS_OUTPUT.PUT_LINE('plsql=' || v_plsql);
        EXECUTE IMMEDIATE v_plsql;
        DBMS_OUTPUT.PUT_LINE('...ran on [' || To_Char(sysdate,'YYYYMMDD HH24:MI:SS' || '].'));
    END LOOP;
    

    ----GRANTS FOR OTHERS:
    --Just a few specific FUNCTIONS used in queries to format output.
    FOR f IN (
        SELECT 'WEGMANS.CLEAN_STRING_FORTENUP' AS object_name FROM dual
        union all
        SELECT 'WEGMANS.KEEP_ONLY_ALPHANUMERIC' AS object_name FROM dual
        union all
        SELECT 'WEGMANS.SET_TO_FIXED_WIDTH' AS object_name FROM dual
    )
    LOOP
        v_plsql := v_grant_or_revoke || ' EXECUTE ON ' || f.object_name || ' TO ' || v_other_members_csv;
        DBMS_OUTPUT.PUT_LINE('plsql=' || v_plsql);
        EXECUTE IMMEDIATE v_plsql;
        DBMS_OUTPUT.PUT_LINE('...ran on [' || To_Char(sysdate,'YYYYMMDD HH24:MI:SS' || '].'));
    END LOOP;
END;
/

/* BELOW is the output from running this code on 7/19/2022 in Production McKesson Oracle DW:

plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_1572760 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_1595416 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_1629405 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_27155281 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_35896776 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_35896793 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.AQUA_EXPLAIN_35906781 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.ASTUTE_SUCCESSFULLY_LOADED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.ASTUTE_SUCCESSFULLY_LOADED_TST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CF_BASE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CF_TEMP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CF_TEMP2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CF_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.COLORADO_TICKET TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CPS_EARNED_TIME_RULE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CPS_EARNED_TIME_RULE_HISTORY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CRM_DRUG_CONFIG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.CYCLECOUNTGCNS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.ERXDRUGMOVEMENT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FACILITY_STOP_TIMES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FILL_FACT_30_DUPS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FILL_FACT_DUPS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FILL_FACT_SANS_DUPS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FILL_FACT_SJ_DEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FIND_PAN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.FIX_PAN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.IMS_BIN_004336_PCN_MCAIDADV TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.INVENTORY_REPORTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.INVENTORY_REPORTS2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.INV_INFO TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.INV_INFO_BCK TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.LASH_DISPENSE_NDC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.LASH_PATIENT_ID_OVERRIDE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.MEDICARE_PATIENT_POOL_PART TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_CFORDERRXSEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_CFORDERRXSEL_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_CISNDC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_CPS_INTERVALS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_CPS_TOTALS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_NDCPSA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_OMNISYS_CLAIM TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_BACKFILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_BACKFILL_ALLDATES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_RPL_PARTIAL1 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_RPL_PARTIAL2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_SALES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PHAT_TRANSACTION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_PS780PROJ TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_SMART_CLAIM TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_SMART_CLAIM_RERUNS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_SMART_CLAIM_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_TPCSFSEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_TPCSFSEL_MISSING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_TPCSFSEL_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_TPINMARSEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PERM_TPINMARSEL_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PHAT_FIX_PARTIALS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PHAT_FIX_PARTIALS_BAK TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PLAN_TABLE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.POSTRANSACTION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.POSTRANSACTION_BACKFILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PROMOS_PATIENT_KEYS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PS780PROJ_MCKESSON TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PS780PROJ_SAVE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PS780PROJ_STAGE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PS780PROJ_STAGE_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PS780PROJ_STAGE_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.PSA_SQL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.P_FILL_STATE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.P_TEMP_LABSCHEDDET_DW TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.RECALLS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.REPORT_ACTIVITY_LOG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.RXSMARTOPBLACKLISTNDCS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SALE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SCRIPTS_LOGGING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SENT_TO_SURE_SCRIPTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SERVICELEVEL_OPT_FOA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOPBLACKLISTGCNS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOPPREFERRED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOP_BLACKLISTGCN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOP_DAILYDRUGMOVEMENT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOP_DAILYDRUGMVMTROLLUP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMARTOP_PREFERREDNDC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:49].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_FRESH_NEWS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_INC605995 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_LASH_CSTATUS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_PORTAL_ACCOUNTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_STC_IMMUNIZATIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_TREMFYA_NO_DISPENSE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_GROUP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_STEP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_STEP_CLEAN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_STEP_CLEAN2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_STEP_EXCEPTIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SMC_WORKFLOW_STEP_EXCEPTIONS2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SPECIALTY_199 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SPECIALTY_199_3DRUGS_ONLY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SPECIALTY_GCN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SQL_SESSIONS_LOG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SQL_SESSIONS_LOG_OLD TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.STATE_ABBREVIATION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.STC_COVID_EXCLUSION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.STC_IMMUNIZATIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.STC_IMMUNIZATIONS_NEW TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.SURE_SCRIPTS_REJECT_CODES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_ACQUISITION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_AREACODE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_AUTOFILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_AUTO_FILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_CASHSALES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_CFOPTOUT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_CFSIG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_DEBUG_REBILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_DRUGRECALL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_FACILITY_ID TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_GEI TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_IMS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_INVENTORY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_IVR TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LABSCHEDDET TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LABSCHEDDET_2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LABSCHEDDET_DW TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LABSCHED_GROUPED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LABSCHED_TIME TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_LOWGROSS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_MCK_LAB2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_MCK_LABOR TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_MISSING_ADDR TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_NDCPSA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PATIENT_INFO TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PAT_RX_COUNTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PHAT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PRICING_TRANSACTIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PS780PROJ TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_PS780PROJRPLMNT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_REBILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_ROLES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_ROLES2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_RXPERF TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_RXTOTALS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_SIG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_TPAUDIT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_TPCSFSEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_TPCSF_CATCHUP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_GROUP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_STEP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_STEP_CLEAN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_STEP_CLEAN2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_STEP_EXCEPTIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEMP_WORKFLOW_STEP_EXCEPTIONS2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.THIRD_PARTY_CLAIMS_STAGING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TMPMULTIPLEDEA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TMP_CFORDERFEEDOCT05 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TMP_CFORDERFEEDSEP30 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TNP_CFORDERFEED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TOAD_PLAN_SQL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TOAD_PLAN_TABLE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.TPCSF_INPUT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.VTRACKS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.WCBINV TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.WEGMANS_LAST_LOAD_SEQ TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.XARELTO_NDC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT SELECT,UPDATE,INSERT,DELETE ON WEGMANS.XARELTO_PLAN_CODE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.CLEAN_STRING_FORTENUP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.CMA_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.CPS_MEASURE_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.CREATEDATESEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.FORMAT_WLB_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.FORMAT_WLB_PKGRSTEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.GET_DATE_KEY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.GET_INFO_FOR_MATCHING_PATIENT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.GET_MATCHING_PATIENTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.GET_NALOXONE_MA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.HOME_DELIVERY_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.INVENTORY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.KEEP_ONLY_ALPHANUMERIC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.LOG_SQL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.MCK_LABOR TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.MEDICARE_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.OLD_GET_PRICING_INFO TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.PHARMACY_PATIENT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.PRICING_TRANSACTIONS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.REPORTING_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SANTE_ATEB_MASTER_DATA_FEED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ACQUISITION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ATEB_DECEASED_PATIENTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ATEB_MASTER_DATA_FEED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ATEB_MASTER_DATA_FEED2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_AUTOREFILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_AUTO_FILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CASHTPSALES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CFORDERRXFEED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CFSIG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CFTEMP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CF_OPTOUT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CF_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CF_TWOSTAGE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CF_TWOSTAGE_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CII TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_COUNSELING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_COUNSELING_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_CS_TWOSTAGE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_DAILY_DRUG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_DRUG_DECILE_PULL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_DRUG_RECALLS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ETL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ETLSTATUS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ETLSTATUS_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_GEI TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_HIPAA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IMS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IMS090310 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IMS_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INMAR_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INMAR_RPL2 TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INMAR_TWOSTAGE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INMAR_TWOSTAGE_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INMAR_TWOSTAGE_TST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INVENTORY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_INVENTORY_MCKESSON TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IVR_OUTBOUND_CALLING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IVR_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IVR_TOTALS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_IVR_Test TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_LAB_SCHED_DET TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_LAB_SCHED_RERUN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_LOWGROSS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_MAIL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_NDC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_OMNISYS_CLAIM TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PATIENT_ADDRESS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PATIENT_RX_COUNTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_BACKFILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_BACKFILL_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_SALES TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_SAMPLE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PHAT_TRANSACTION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_POSREBILL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_POSREBILL_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PRESCRIBER TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PRICING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PROJECTION_DAILY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_PROJECTION_DAILY_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_QUALITY_DROPOUTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_RGISWCBSEL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_RGISWCBSEL_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_RTS_EXCEPTION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_RX_PERF TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_SALES_VARIANCE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_SMART_CLAIM TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_SMART_CLAIM_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_SPECIALTY TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_STOREUTILS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_STORE_SYNC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_TEMPAREACODE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_TPAUDIT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_TPAUDIT_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_USERUTIL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_UTIL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_UTIL_DEB TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_VERISPAN TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_VOICEPORT_FEED TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WCB TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WCB_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WCB_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WORKCOMP TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WORKCOMP_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WORKLOAD_BALANCING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_WORKLOAD_BALANCINGRSTEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SCRIPTS_ZERO_DRUGMOVEMENT TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SEARCH_MATCHING_PATIENTS TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SET_TO_FIXED_WIDTH TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SLEEP_PROC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMC_INMAR_TWOSTAGE TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMC_RTS_EXCEPTION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMC_STC_IMMUNIZATIONS_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMC_WORKLOAD_BALANCING TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMW_MAIL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SMW_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.STC_IMMUNIZATIONS_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.STORENBR_CONVERSION TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SURESCRIPTS_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SURESCRIPTS_PKG_OLD TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SURESCRIPTS_PKG_RPL TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SURESCRIPTS_PKG_SEND_EXTRA TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SURESCRIPTS_PKG_TEST TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.TEST_PRC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.TEST_PROC TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.THIRD_PARTY_CLAIMS_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.TURN_AROUND_TIME_PKG TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.WEGMANS_INV_INFO TO EXT_BOATMAN,EXT_CMCCARTHY,EXT_JONEILL,EXT_RSCHWAN,EXT_SCRINO,EXT_SNALLIANNAN,EXT_SRANI
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.CLEAN_STRING_FORTENUP TO EXT_ESCIBILIA,EXT_MROSILIO
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.KEEP_ONLY_ALPHANUMERIC TO EXT_ESCIBILIA,EXT_MROSILIO
...ran on [20220719 11:25:50].
plsql=GRANT EXECUTE ON WEGMANS.SET_TO_FIXED_WIDTH TO EXT_ESCIBILIA,EXT_MROSILIO
...ran on [20220719 11:25:50].


PL/SQL procedure successfully completed.



*/
