SELECT
     RUN_DATE AS RunDate
    ,BENEFIT_GROUP_ID AS GroupInsuranceNumber
    ,date_of_service AS FromFillDate
    ,DAW_CODE AS DispenseAsWritten 
    ,DAYS_SUPPLY AS DaysSupply
    ,dispensed_drug_num AS DispensedDrugNumber
    ,DISPENSED_QTY_AWP AS AverageWholesalePriceCost
    ,facility_num AS FacilityNumber
    ,FILL_STATE_CHG_TS AS FillFactFillStateTimestamp
    ,fill_state_code AS FillFactFillStateCode
    ,fill_state_key AS FillFactFillStateKey
    ,fill_state_price_num AS FillFactFillStatePriceNumber
    ,final_price AS FinalPrice
    ,INCENTIVE_FEE_AMOUNT AS IncentiveAmountPaid
    ,internal_fill_id AS FillFactInternalFillId
    ,is_same_day_reversal AS IsSameDayReversal
    ,medical_condition_num AS MedicalConditionNumber
    ,ORIGINAL_PRODUCT_QTY AS QuantityWritten
    ,partial_fill_seq AS PartialFillSequence
    ,patient_num AS PatientAccountNumber
    ,PATIENT_PAY_AMOUNT AS PatientPayAmount
    ,PRESCRIBED_DATE AS WrittenDate
    ,prescriber_address_num AS PrescriberAddressNumber
    ,PRESCRIBER_ID_NPI AS PrescriberNationalProviderId
    ,prescriber_num AS PrescriberNumber
    ,PRESCRIBER_STATE AS PrescriberState
    ,PRESCRIBER_ZIP AS PrescriberZipcode
    ,QTY_DISPENSED AS MetricQuantityDispensed
    ,REFILL_NUM AS RefillNumber
    ,REFILLS_AUTHORIZED AS NumberOfRefillsAuthorized
    ,REFILLS_REMAINING AS NumberOfRefillsRemaining
    ,rx_fill_seq AS FillFactFillSequence
    ,rx_number AS PrescriptionNumber
    ,RX_ORIGIN_CODE AS OriginCode
    ,rx_record_num AS FillFactRecordNumber
    ,short_fill_status AS ShortFillStatus
    ,split_billing_code AS SplitFillNumber
    ,TLOG_SEQUENCE_NUM AS HostTransactionNumber
    ,TOTAL_COST AS IngredientCostSubmitted
    ,TOTAL_FEE AS TotalFee
    ,total_uandc AS TotalUsualAndCustomary
    ,TOTAL_USER_DEFINED AS AcquisitionCost
    ,tp_curr_patient_pay_amount AS ThirdPartyCurrentPatientPay
    ,tp_curr_total_cost AS ThirdPartyCurrentTotalCost
    ,TP_CURR_TOTAL_FEE AS ThirdPartyCurrentTotalFee
    ,tp_item_claim_key AS ThirdPartyItemClaimKey
    ,tp_item_claim_num AS ThirdPartyItemClaimNumber
    ,tp_message_key AS ThirdPartyMessageKey
    ,tp_patient_num AS ThirdPartyPatientNumber
    ,TP_PLAN_AMOUNT_PAID AS ThirdPartyPlanAmountPaid
    ,tp_plan_num AS ThirdPartyPlanNumber
    ,tp_prior_auth_num AS ThirdPartyPriorAuthorization
    ,tp_processor_dest_num AS ThirdPartyProcessorDestination
    ,transaction_code AS TransactionCode
    ,fs_fill_state_chg_ts AS FillStateFillStateTimestamp
    ,fs_fill_state_code AS FillStateFillStateCode
    ,fs_rx_fill_seq AS FillStateFillSequnce
    ,fs_rx_record_num AS FillStateRecordNumber
    ,INGREDIENT_NDC1 AS CompoundNDCDispensed1
    ,INGREDIENT_NDC2 AS CompoundNDCDispensed2
    ,INGREDIENT_NDC3 AS CompoundNDCDispensed3
    ,INGREDIENT_NDC4 AS CompoundNDCDispensed4
    ,INGREDIENT_NDC5 AS CompoundNDCDispensed5
    ,INGREDIENT_NDC6 AS CompoundNDCDispensed6
    ,INGREDIENT_PRICE1 AS CompoundIngredientDrugCost1
    ,INGREDIENT_PRICE2 AS CompoundIngredientDrugCost2
    ,INGREDIENT_PRICE3 AS CompoundIngredientDrugCost3
    ,INGREDIENT_PRICE4 AS CompoundIngredientDrugCost4
    ,INGREDIENT_PRICE5 AS CompoundIngredientDrugCost5
    ,INGREDIENT_PRICE6 AS CompoundIngredientDrugCost6
    ,INGREDIENT_QTY1 AS CompoundDispensedQuantity1
    ,INGREDIENT_QTY2 AS CompoundDispensedQuantity2
    ,INGREDIENT_QTY3 AS CompoundDispensedQuantity3
    ,INGREDIENT_QTY4 AS CompoundDispensedQuantity4
    ,INGREDIENT_QTY5 AS CompoundDispensedQuantity5
    ,INGREDIENT_QTY6 AS CompoundDispensedQuantity6
    ,P_GENDER AS PatientGender
    ,PA_GENDER AS CardholderGender
    ,STATE AS CardholderState
    ,ZIP AS CardholderPostalCode
    ,AUTHORIZATION_NUMBER AS AuthorizationNumber
    ,EMERGENCY_CONDITION_CODE AS IsEmergencyFill
    ,external_billing_indicator AS ExternalBillingIndicator
    ,h_level AS ThirdPartyMessageTableHLevel
    ,tp_message_num AS ThirdPartyMessageTableMessage
    ,BIN_NUMBER AS BankingIdentificationNumber
    ,PROCESSOR_CONTROL_NUMBER AS ProcessorControlNumber
    ,RS_BASIS_OF_REIMBRSMT_DET AS BasisOfReimbursement
    ,RS_NETWRK_REIMBURSEMENT_ID AS NetworkId
    ,drug_gcn_seq AS GenericCodeNumber 
    ,DRUG_IS_MAINT_DRUG AS IsMaintenanceDrug
    ,DRUG_NDC AS SubmittedNationalDrugCode 
    ,DRUG_PACKAGE_SIZE AS DrugPackSize
    ,DRUG_STRENGTH AS Strength
    ,DRUG_STRENGTH_UNITS AS Unit
    ,FD_FACILITY_ID AS OriginatingStoreId
    ,FD_NCPDP_PROVIDER_ID AS ProviderId
    ,MCD_FRMTTD_COND_REF_NUM AS DiagnosisCode1
    ,prd_is_compound AS IsCompoundCode
    ,prd_is_generic AS IsGeneric
    ,PRD_IS_PRICE_MAINTAINED AS IsPreferredDrug
    ,PRD_NAME AS DispensedDrugName
    ,prd_package_size AS ProductPackSize
    ,PD_PATIENT_KEY AS PatientKey
    ,TPD_CARDHOLDER_ID AS CardholderId
    ,tpd_cardholder_patient_num AS CardholderPatientNumber
    ,tpd_relationship_num AS PatientRelationshipCode
    ,tpd_tp_plan_num AS ThirdPartyPatientPlanNumber
    ,tpld_plan_code AS PlanCode
    ,request_message AS RequestMessage
    ,is_senior AS IsSenior
    ,lookup_transmission_date AS LookupTransmissionDate
    ,lookup_first_adjudicated_date AS LookupFirstAdjudicatedDate
    ,lookup_first_dispense_date AS LookupFirstDispenseDate
    ,lookup_qty_dispensed AS LookupQtyDispensed
    ,lookup_days_supply AS LookupDaysSupply
    ,lookup_acquisition_cost AS LookupAcquisitionCost
    ,lookup_cf_store_indicator AS CentralFillStoreIndicator

    ,PRS_PRESCRIBER_KEY
    ,PRS_PRESCRIBER_NUM
    ,PADR_KEY
FROM WEGMANS.THIRD_PARTY_CLAIMS_STAGING 
WHERE RUN_DATE = :RunDate