
SELECT 
	To_Number(FACILITY.FD_FACILITY_ID) "store_num",
	To_Number(REGEXP_REPLACE(payment.RX_NUMBER,'[^0-9]+','')) "rx_num",
	payment.REFILL_NUM "refill_num",
	payment.FACILITY_ORDER_NUMBER "order_num",
	PATIENT.PD_PATIENT_NUM "patient_num",
	CASE WHEN PAYMENT.COMPLETION_DATE_KEY = 0 THEN NULL ELSE PAYMENT.COMPLETION_DATE_KEY END "payment_date",
	CASE WHEN PAYMENT.COMPLETION_DATE_KEY = 0 THEN NULL
		 ELSE Round(((To_date(To_Char(PAYMENT.COMPLETION_DATE_KEY),'YYYYMMDD') + ((PAYMENT.COMPLETION_TIME_KEY - 2)/86400)) - To_Date('20350101','YYYYMMDD')),6)
	END "payment_datetime",
	PAYMENT.PAYMENT_AMOUNT "payment_amount",
	CASE WHEN SHIPfact.SHIP_DATE_KEY = 0 THEN NULL ELSE SHIPfact.SHIP_DATE_KEY END "ship_date",
	SHIPfact.SHIP_HANDLE_FEE "ship_fee",
	drug.DRUG_NDC "ndc_wo",
	WEGMANS.Clean_String_ForTenUp(drug.DRUG_LABEL_NAME) "drug_name",
	PAYMENT.PAYMENT_NUM "payment_num",
	PAYMENT.REVERSAL_PAYMENT_NUM "revpayment_num",
	CASE WHEN PAYMENT.HEALTH_CARD_DESIGNATION = 'FSA' THEN 1 ELSE 0 END "is_fsa",
	CASE WHEN PAYMENT.PAYMENT_TYPE_KEY = 7 THEN 1 ELSE 0 END "is_refund",
	CCRESPONSE.CC_TRANS_PAYMENT_TYPE "cc_type",
	TO_CHAR(PAYMENT.LAST4_PAN,'0000') "cc_last4",
	CASE WHEN PAYMENT.EXPIRATION_DATE_KEY = 0 THEN NULL ELSE PAYMENT.EXPIRATION_DATE_KEY END "cc_expire_date",
	CCRESPONSE.CC_TRANS_REFERENCE_NUM "vantiv_ref_num",
	CCRESPONSE.CC_TRANS_AUTHORIZATION_CODE "vantiv_auth_code",
	CASE Payment.PAYMENT_SOURCE
	  WHEN 'U' THEN 'User Entered'
	  WHEN 'R' THEN 'CC Response'
	  ELSE NULL
	END "payment_source",
	paytype.PAYMENT_TYPE_NAME "payment_type",
	PAYMENT.QTY_DISPENSED "qty_dispensed",
	CASE WHEN PAYMENT.IS_CENTRAL_FILL_MAIL = 'Y' THEN 'CF Mail'
		 WHEN PAYMENT.IS_STORE_MAIL= 'Y' THEN 'Store Mail'
		 ELSE NULL
	END "cfstore_mail",
	payment.RX_FILL_SEQ "rx_fill_seq",
	PAYMENT.ORDER_NUM "dw_order_num",
	payment.ITEM_SEQ "item seq"
FROM TREXONE_DW_DATA.PAYMENT_FACT payment
  LEFT OUTER JOIN TREXONE_DW_DATA.FACILITY facility
    ON payment.FD_FACILITY_KEY = facility.FD_FACILITY_KEY
  LEFT JOIN TREXONE_DW_DATA.DRUG drug
    ON payment.DRUG_KEY = drug.DRUG_KEY
  LEFT OUTER JOIN TREXONE_DW_DATA.PATIENT patient
    ON payment.PD_PATIENT_KEY = patient.PD_PATIENT_KEY
  LEFT OUTER JOIN TREXONE_AUD_DATA.CC_TRANS_REQUEST ccrequest
    ON payment.PAYMENT_NUM = ccrequest.CC_TRANS_ERX_PAYMENT_NUM
   AND ccrequest.CC_TRANS_SUBMISSION_STATUS != 'D'
   AND CCREQUEST.CC_TRANS_COMMAND_TYPE != 'PRE_AUTH'
   AND ccrequest.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
   AND CCREQUEST.EFF_START_DATE >= (Trunc(:RunDate) - 1)
  LEFT OUTER JOIN TREXONE_AUD_DATA.CC_TRANS_RESPONSE ccresponse
    ON ccrequest.CC_TRANS_REQUEST_NUM = ccresponse.CC_TRANS_REQUEST_NUM
   AND CCRESPONSE.EFF_END_DATE = TO_DATE('12/31/2999','MM/DD/YYYY')
   AND ccresponse.EFF_START_DATE >= (Trunc(:RunDate) - 1)
  LEFT OUTER JOIN TREXONE_DW_DATA.PAYMENT_TYPE PAYTYPE
    ON PAYMENT.PAYMENT_TYPE_KEY = PAYTYPE.PAYMENT_TYPE_KEY
  LEFT JOIN TREXONE_DW_DATA.SHIPMENT_FACT SHIPFACT
    ON payment.ORDER_NUM = shipfact.ORDER_NUM
   AND shipfact.pd_patient_key = payment.pd_patient_key
WHERE PAYMENT.COMPLETION_DATE_KEY = To_Number(To_Char((:RunDate - 1), 'YYYYMMDD'))
--Files to 1010data must be one run date per file.
  AND PAYMENT.IS_ACTIVE = 'Y'