parameters:
  - name: primaryResourceGroup
    type: string

  - name: secondaryResourceGroup
    type: string
  
  - name: azureServiceConnectionId
    type: string

  - name: appRegistrationName
    type: string

  - name: appOwnersGroup
    type: object

  - name: frontDoorFriendlyUri
    type: string

jobs:
- job: DeployAad
  displayName: 4. Deploy Aad
  dependsOn: 
  - DeployPrimaryFunction
  - DeploySecondaryFunction
  - DeployFrontDoor

  variables:
    identifierUri: https://${{ parameters.frontDoorFriendlyUri }}
    replyUrl: $(identifierUri)/.auth/login/aad/callback
    primaryFunctionAppName: $[ dependencies.DeployPrimaryFunction.outputs['ArmTemplateOutputs.functionAppName'] ]
    secondaryFunctionAppName: $[ dependencies.DeploySecondaryFunction.outputs['ArmTemplateOutputs.functionAppName'] ]

  pool:
    vmImage: windows-latest

  steps:
    - checkout: none

    - download: current
      displayName: Download Artifacts
      artifact: armTemplates 

    - template: steps/deploy.aadApp.yml@azure_pipeline_templates
      parameters:
        displayName: '${{ parameters.appRegistrationName }}'
        identifierUris:
        - $(identifierUri)
        replyUrls: $(replyUrl)
        homepage: 
        requiredResourceAccesses: |
          [{
            "resourceAppId": "00000002-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
                "type": "Scope"
                }
            ]
          }]
        azServiceConnectionId: '${{ parameters.azureServiceConnectionId }}'
        oauth2AllowIdTokenImplicitFlow: true
        oauth2AllowImplicitFlow: true
        owners:  '${{ parameters.appOwnersGroup }}'
        administrators: '${{ parameters.appOwnersGroup }}' #TODO: appRoles need to have all the roles your system needs; id is unique guid
        appRoles: |
          [{
              "allowedMemberTypes": [
                  "Application"
              ],
              "description": "CMM System that call the service to write data",
              "displayName": "Cmm.Writer",
              "id": "f19c0674-92fc-4866-90bb-dcf614e7c8d0",
              "isEnabled": true,
              "lang": null,
              "origin": "Application",
              "value": "Cmm.Writer"
          }]