parameters:
  - name: resourceGroup
    type: string

  - name: region
    type: string
  
  - name: azureServiceConnectionId
    type: string

  - name: environment
    type: string
    default: Development
    values:
    - Production
    - Staging
    - Development
  
  - name: infrastructureJobName
    type: string
  
  - name: jobName
    type: string
  
  - name: displayName
    type: string

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  dependsOn: 
    - DeployPrimaryFunction
    - DeploySecondaryFunction
    - DeployAppInsightsActionGroups
  condition: eq('${{ parameters.environment }}', 'Production')

  variables:
    appInsightsId: $[ dependencies.${{ parameters.infrastructureJobName }}.outputs['ArmTemplateOutputs.appInsightsId'] ]
    appInsightsName: $[ dependencies.${{ parameters.infrastructureJobName }}.outputs['ArmTemplateOutputs.appInsightsName'] ]
    actionGroupAllSevsEmail: $[ dependencies.DeployAppInsightsActionGroups.outputs['ArmTemplateOutputs.actionGroupAllSevsEmail'] ]
    actionGroupSEV1Alert: $[ dependencies.DeployAppInsightsActionGroups.outputs['ArmTemplateOutputs.actionGroupSEV1Alert'] ]

  pool:
    vmImage: windows-latest

  steps:
    - checkout: none

    - download: current
      displayName: Download Artifacts
      artifact: armTemplates     

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment: Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnectionId }}'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.region }}'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/armTemplates/.azure/environment/deployalerts.json' #TODO: Change to your location
        overrideParameters: >-
           -alertName "CMM Astute Proxy Error"
           -alertScope ["$(appInsightsId)"]
           -actionGroups [ 
              {"actionGroupId":"$(actionGroupAllSevsEmail)", "webHookProperties":{}}, 
              {"actionGroupId":"$(actionGroupSEV1Alert)", "webHookProperties":{}} 
            ]
        deploymentMode: 'Incremental'
        deploymentOutputs: armOutputs