parameters:
  - name: region
    type: string
  
  - name: resourceGroup
    type: string
  
  - name: functionName
    type: string
  
  - name: azureServiceConnectionId
    type: string

  - name: environment
    type: string
    default: Development
    values:
    - Production
    - Staging
    - Development
  
  - name: jobName
    type: string
  
  - name: displayName
    type: string
  
  - name: disableSpecialtyDrugsPatientStatusUpdate
    type: string
  
  - name: frontDoorIdentifierUri
    type: string

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}

  dependsOn: 
    - DeployStorageAccount

  variables:
    storageAccountConnectionString: $[ dependencies.DeployStorageAccount.outputs['ArmTemplateOutputs.storageAccountConnectionString'] ]

  pool:
    vmImage: windows-latest

  steps:
    - checkout: none

    - download: current
      displayName: Download Artifacts
      artifact: armTemplates   

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment: Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnectionId }}'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.region }}'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/armTemplates/.azure/environment/deployfunction.json' #TODO: Change to your location
        overrideParameters: >-
          -functionAppName ${{ parameters.functionName }}
          -functionHostingEnvironment ${{ parameters.environment }}
          -cmmStorageAccountConnectionString "$(storageAccountConnectionString)"
          -cmmBaseUrl "$(AppCmmClient__BaseUrl)"
          -cmmUsername "$(AppCmmClient__Username)"
          -cmmPassword "$(AppCmmClient__Password)"
          -astuteAddressUrl "$(AppAstuteClient__AddressUrl)"
          -astuteCaseStreamUrl "$(AppAstuteClient__CaseStreamUrl)"
          -astuteCaseUrl "$(AppAstuteClient__CaseUrl)"
          -astuteUsername "$(AppAstuteClientSecurity__Username)"
          -astutePassword "$(AppAstuteClientSecurity__Password)"
          -disableSpecialtyDrugsPatientStatusUpdate ${{ parameters.disableSpecialtyDrugsPatientStatusUpdate }} 
          -frontDoorIdentifierUri "${{ parameters.frontDoorIdentifierUri }}"
          -specialtyDrugsPatientStatusUpdateTimerTrigger "$(SpecialtyDrugsPatientStatusUpdateTimerTrigger)"
        deploymentMode: 'Incremental'
        deploymentOutputs: armOutputs

    - pwsh: |
        $var=ConvertFrom-Json $env:armOutputs

        $functionAppName=$var.functionAppName.value
        $functionAppDefaultHostName=$var.functionAppDefaultHostName.value
        $appInsightsKey=$var.appInsightsKey.value
        $appInsightsId=$var.appInsightsId.value
        $appInsightsName=$var.appInsightsName.value
        $storageAccountName=$var.storageAccountName.value

        Write-Host $appInsightsId

        Write-Host "##vso[task.setvariable variable=functionAppName;isOutput=true]$functionAppName"
        Write-Host "##vso[task.setvariable variable=functionAppDefaultHostName;isOutput=true]$functionAppDefaultHostName"
        Write-Host "##vso[task.setvariable variable=storageAccountName;isOutput=true]$storageAccountName"
        Write-Host "##vso[task.setvariable variable=appInsightsKey;isOutput=true]$appInsightsKey" 
        Write-Host "##vso[task.setvariable variable=appInsightsId;isOutput=true]$appInsightsId" 
        Write-Host "##vso[task.setvariable variable=appInsightsName;isOutput=true]$appInsightsName" 
      name: ArmTemplateOutputs