parameters:
  - name: region
    type: string
  
  - name: resourceGroup
    type: string
  
  - name: azureServiceConnectionId
    type: string
  
  - name: infrastructureJobName
    type: string
  
  - name: jobName
    type: string
  
  - name: displayName
    type: string

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  dependsOn: 
  - DeployPrimaryFunction
  - DeploySecondaryFunction
  - DeployFrontDoor
  - DeployAad

  variables:
    functionAppName: $[ dependencies.${{ parameters.infrastructureJobName }}.outputs['ArmTemplateOutputs.functionAppName'] ]

  pool:
    vmImage: windows-latest

  steps:
    - checkout: none

    - download: current
      displayName: Download Function App Artifacts
      artifact: function-app  

    - task: AzureFunctionApp@1
      displayName: 'Deploy FunctionApp'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnectionId }}'
        appName: $(functionAppName)
        package: $(Pipeline.Workspace)/function-app/Wegmans.RX.Cmm.AzureFunctions.zip #TODO :Change to your ZIP
        deploymentMethod: runFromPackage