parameters:
  - name: resourceGroup
    type: string

  - name: region
    type: string
  
  - name: azureServiceConnectionId
    type: string

  - name: environment
    type: string
    default: Development
    values:
    - Production
    - Staging
    - Development

jobs:
- job: DeployAppInsightsActionGroups
  displayName: 1. Deploy App Insights Action Groups
  condition: eq('${{ parameters.environment }}', 'Production')

  pool:
    vmImage: windows-latest

  steps:
    - checkout: none

    - download: current
      displayName: Download Artifacts
      artifact: armTemplates

    - template: steps/itsm/provision.subscriptionKey.yml@azure_pipeline_templates
      parameters:
        azServiceConnectionId: '${{ parameters.azureServiceConnectionId }}'
        production: true

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment: Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnectionId }}'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.region }}'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/armTemplates/.azure/environment/deployactiongroups.json'
        overrideParameters: -ITSM_SubscriptionKey $(ItsmApiSubscription.Key)
        deploymentMode: 'Incremental'
        deploymentOutputs: armOutputs

    - pwsh: |
        $var=ConvertFrom-Json $env:armOutputs

        $actionGroupAllSevsEmail=$var.actionGroupAllSevsEmail.value
        $actionGroupSEV1Alert=$var.actionGroupSEV1Alert.value

        Write-Host "##vso[task.setvariable variable=actionGroupAllSevsEmail;isOutput=true]$actionGroupAllSevsEmail"
        Write-Host "##vso[task.setvariable variable=actionGroupSEV1Alert;isOutput=true]$actionGroupSEV1Alert"
      name: ArmTemplateOutputs