parameters:
  - name: primaryRegion
    type: string

  - name: primaryResourceGroup
    type: string

  - name: primaryFunctionName
    type: string

  - name: secondaryRegion
    type: string

  - name: secondaryResourceGroup
    type: string

  - name: secondaryFunctionName
    type: string

  - name: frontDoorResourceGroup
    type: string
  
  - name: azureServiceConnectionId
    type: string
    
  - name: frontDoorName
    type: string
    
  - name: frontDoorFriendlyUri
    type: string
  
  - name: cmmGlobalResourceGroup
    type: string
  
  - name: storageAccountName
    type: string

  - name: environment
    type: string
    default: Development
    values:
    - Production
    - Staging
    - Development

  - name: appRegistrationName
    type: string
  
  - name: disableSpecialtyDrugsPatientStatusUpdate
    type: string

jobs: 
    - template: ./deploy-storage-account.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: ${{ parameters.cmmGlobalResourceGroup }} #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        storageAccountName: '${{ parameters.storageAccountName }}'

    - template: ./deploy-action-groups.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: ${{ parameters.cmmGlobalResourceGroup }} #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        environment: '${{ parameters.environment }}'

    - template: ./deploy-function.yml
      parameters: 
        region: '${{ parameters.primaryRegion }}'
        resourceGroup: '${{ parameters.primaryResourceGroup }}' #TODO: Change
        functionName: '${{ parameters.primaryFunctionName }}'
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        environment: '${{ parameters.environment }}'
        jobName: 'DeployPrimaryFunction'
        displayName: '2. Deploy Primary Function'
        disableSpecialtyDrugsPatientStatusUpdate: ${{ parameters.disableSpecialtyDrugsPatientStatusUpdate }}
        frontDoorIdentifierUri: https://${{ parameters.frontDoorFriendlyUri }}

    - template: ./deploy-function.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: '${{ parameters.secondaryResourceGroup }}' #TODO: Change
        functionName: '${{ parameters.secondaryFunctionName }}'
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        environment: '${{ parameters.environment }}'
        jobName: 'DeploySecondaryFunction'
        displayName: '2. Deploy Secondary Function'
        disableSpecialtyDrugsPatientStatusUpdate: 'true'
        frontDoorIdentifierUri: https://${{ parameters.frontDoorFriendlyUri }}

    - template: ./deploy-alerts.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: ${{ parameters.primaryResourceGroup }} #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        environment: '${{ parameters.environment }}'
        infrastructureJobName: 'DeployPrimaryFunction'
        jobName: 'DeployPrimaryAlerts'
        displayName: '3. Deploy Primary App Insights Alerts'

    - template: ./deploy-alerts.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: ${{ parameters.secondaryResourceGroup }} #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        environment: '${{ parameters.environment }}'
        infrastructureJobName: 'DeploySecondaryFunction'
        jobName: 'DeploySecondaryAlerts'
        displayName: '3. Deploy Secondary App Insights Alerts'

    - template: ./deploy-front-door.yml
      parameters: 
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: ${{ parameters.frontDoorResourceGroup }} #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        frontDoorName: '${{ parameters.frontDoorName }}'  
        frontDoorFriendlyUrl: '${{ parameters.frontDoorFriendlyUri }}'

    - template: ./deploy-aad.yml
      parameters: 
        primaryResourceGroup: '${{ parameters.primaryResourceGroup }}' #TODO: Change
        secondaryResourceGroup: '${{ parameters.secondaryResourceGroup }}' #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        appRegistrationName: '${{ parameters.appRegistrationName }}' #TODO: Change
        appOwnersGroup: 
          - aca0594b-0faa-4222-8fb1-4c7620af1553 #AAD Group: Azure - Pharmacy Team TODO: Change to your
        frontDoorFriendlyUri: '${{ parameters.frontDoorFriendlyUri }}'

    - template: ./deploy-system.yml
      parameters:
        region: '${{ parameters.primaryRegion }}'
        resourceGroup: '${{ parameters.primaryResourceGroup }}' #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        infrastructureJobName: 'DeployPrimaryFunction'
        jobName: 'DeployPrimarySystem'
        displayName: '5. Deploy Primary System'

    - template: ./deploy-system.yml
      parameters:
        region: '${{ parameters.secondaryRegion }}'
        resourceGroup: '${{ parameters.secondaryResourceGroup }}' #TODO: Change
        azureServiceConnectionId: '${{ parameters.azureServiceConnectionId }}' #TODO: Change
        infrastructureJobName: 'DeploySecondaryFunction'
        jobName: 'DeploySecondarySystem'
        displayName: '5. Deploy Secondary System'