//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStreamServiceWrapper
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/", ConfigurationName="CaseStreamServiceWrapper.ICaseStreamService")]
    public interface ICaseStreamService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.AstuteSolutions.com/integration/2010/04/ICaseStreamService/UploadF" +
            "ile", ReplyAction="http://schemas.AstuteSolutions.com/integration/2010/04/ICaseStreamService/UploadF" +
            "ileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CaseStreamServiceWrapper.FileResponse> UploadFileAsync(CaseStreamServiceWrapper.FileRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
    public enum FileMethodType
    {
        
        /// <remarks/>
        Upload,
        
        /// <remarks/>
        UploadAutoName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
    public enum FilePathType
    {
        
        /// <remarks/>
        Attachments,
        
        /// <remarks/>
        InfoCenter,
        
        /// <remarks/>
        Letters,
        
        /// <remarks/>
        StandardLetters,
        
        /// <remarks/>
        Enclosures,
        
        /// <remarks/>
        Fulfillment,
        
        /// <remarks/>
        Logs,
        
        /// <remarks/>
        Temp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
    public enum ValidState
    {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileRequest", WrapperNamespace="http://schemas.AstuteSolutions.com/integration/2010/04/", IsWrapped=true)]
    public partial class FileRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string ID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public CaseStreamServiceWrapper.FileMethodType Method;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string Overwrite;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string Prefix;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public CaseStreamServiceWrapper.FilePathType ServerPath;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string SourceFileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string UserLanguageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string UserName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/")]
        public string company_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileRequest()
        {
        }
        
        public FileRequest(string FileSize, string ID, CaseStreamServiceWrapper.FileMethodType Method, string Overwrite, string Password, string Prefix, CaseStreamServiceWrapper.FilePathType ServerPath, string SourceFileName, string UserLanguageID, string UserName, string company_id, System.IO.Stream FileByteStream)
        {
            this.FileSize = FileSize;
            this.ID = ID;
            this.Method = Method;
            this.Overwrite = Overwrite;
            this.Password = Password;
            this.Prefix = Prefix;
            this.ServerPath = ServerPath;
            this.SourceFileName = SourceFileName;
            this.UserLanguageID = UserLanguageID;
            this.UserName = UserName;
            this.company_id = company_id;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileResponse", WrapperNamespace="http://schemas.AstuteSolutions.com/integration/2010/04/", IsWrapped=true)]
    public partial class FileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/", Order=0)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/", Order=1)]
        public int FileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.AstuteSolutions.com/integration/2010/04/", Order=2)]
        public CaseStreamServiceWrapper.ValidState Valid;
        
        public FileResponse()
        {
        }
        
        public FileResponse(string FileName, int FileSize, CaseStreamServiceWrapper.ValidState Valid)
        {
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.Valid = Valid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ICaseStreamServiceChannel : CaseStreamServiceWrapper.ICaseStreamService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CaseStreamServiceClient : System.ServiceModel.ClientBase<CaseStreamServiceWrapper.ICaseStreamService>, CaseStreamServiceWrapper.ICaseStreamService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CaseStreamServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CaseStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), CaseStreamServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaseStreamServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CaseStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaseStreamServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CaseStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaseStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CaseStreamServiceWrapper.FileResponse> UploadFileAsync(CaseStreamServiceWrapper.FileRequest request)
        {
            return base.Channel.UploadFileAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICaseStreamService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICaseStreamService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICaseStreamService))
            {
                return new System.ServiceModel.EndpointAddress("https://americasep24.myastutesolutions.com/WegmansPharmaAIS/CaseStreamService.svc" +
                        "");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICaseStreamService1))
            {
                return new System.ServiceModel.EndpointAddress("https://americasep24.myastutesolutions.com/WegmansPharmaAIS/CaseStreamService.svc" +
                        "/XML");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICaseStreamService,
            
            BasicHttpBinding_ICaseStreamService1,
        }
    }
}
